[
  {
    "qtext": "Find the missing number from the given responses. <br /> <br>45      16      4<br>18      11      -3<br>31      2      1<br>46      20      ?",
    "a": "(A)4",
    "b": "(B)8",
    "c": "(C)12",
    "d": "(D)-4",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "If in a code language TEACHER is written as ACEEHRT, then how can INDIA be written in that code?",
    "a": "(A)ADINI",
    "b": "(B)INIDA",
    "c": "(C)ADIIN",
    "d": "(D)ADNII",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "Which number is wrong in the following series ? <br /> <br />10, 38, 68, 130, 222, 350.",
    "a": "(A)68",
    "b": "(B)350",
    "c": "(C)130",
    "d": "(D)38",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "If a means ‘plus’, b means ‘minus’, c means ‘multiplied by’ and d means 'divided by', then<br /><br />18 c 14 a 6 b 16 d 4 = ?",
    "a": "(A)63",
    "b": "(B)254",
    "c": "(C)288",
    "d": "(D)1208",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "If the 25th of August in a year is Thursday, the number of mondays in that month is",
    "a": "(A)4",
    "b": "(B)5",
    "c": "(C)3",
    "d": "(D)Cannot say",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "Nithya is Sam's sister. Mogan is Sam's Father. Selvan is Rajan's Son. Rajan is Mogan's brother. How is Nithya related to Selvan?",
    "a": "(A)Daughter",
    "b": "(B)Sister",
    "c": "(C)Cousin",
    "d": "(D)Wife",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "In a group of 50 people, Ram's position from the bottom is 19 and Gopal is 2 ranks ahead of Ram, then how many people are there before Gopal ?",
    "a": "(A)29",
    "b": "(B)30",
    "c": "(C)34",
    "d": "(D)31",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "A, B, C, D, E, F, G, H and I are sitting around a circle facing the centre. D is third to the left of H who is second to the left of B. A is fourth to the left of E who is second to the right of D. C is third to the right of H. I is not an immediate neighbour of D. G is not an immediate neighbour of E. Then, which of the following are the neighbours of B ?",
    "a": "(A)IH",
    "b": "(B)CA",
    "c": "(C)IC",
    "d": "(D)None of these",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "A is 40 m South-West of B. C is 40 m South-East of B. Then, C is in which direction of 'A'?",
    "a": "(A)West",
    "b": "(B)East",
    "c": "(C)North-East",
    "d": "(D)South",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "Select the related word/letters/ numbers from the given alternatives.<br />Fog : Visibility : : AIDS : ?",
    "a": "(A)Health",
    "b": "(B)Resistance",
    "c": "(C)Death",
    "d": "(D)Virus",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "Select the related word/letters/ numbers from the given alternatives.<br />INDIA : (3, 2) :: WOMEN : ? ?",
    "a": "(A)(4, 3)",
    "b": "(B)(3, 2)",
    "c": "(C)(2, 1)",
    "d": "(D)(2, 3)",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "Select the related word/letters/ numbers from the given alternatives.<br /> 942 : 28 : : 161 : ?",
    "a": "(A)6",
    "b": "(B)2",
    "c": "(C)63",
    "d": "(D)0",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "How many triangles are there in the following figure? <br />",
    "a": "(A)19",
    "b": "(B)17",
    "c": "(C)14",
    "d": "(D)None of these",
    "correct": "A",
    "img": "https://github.com/hotdudehvfun/allquestions/blob/master/images/image2.JPG?raw=true",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "How many '3's are there in the following sequence which are neither preceded by 6 nor immediately followed by 9?<br />936639593789163963",
    "a": "(A)1",
    "b": "(B)2",
    "c": "(C)4",
    "d": "(D)None of these",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "During 9:00 AM to 2:00 PM, how many times both the hands make an angle of 90° ?",
    "a": "(A)10",
    "b": "(B)9",
    "c": "(C)8",
    "d": "(D)12",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "Study the two different positions of a cube given below with dots from 1 to 6 marked on its faces. When 3 dots is at the bottom, what will be at the top? <br />",
    "a": "(A)2 dots",
    "b": "(B)3 dots",
    "c": "(C)4 dots",
    "d": "(D)6 dots",
    "correct": "D",
    "img": "https://github.com/hotdudehvfun/allquestions/blob/master/images/image3.png?raw=true",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "A series is given, with one term missing. Choose the correct alternative from the given ones that will complete the series<br> X5C, U8F, ? , O17L, L23O",
    "a": "(A)R12I",
    "b": "(B)P12I",
    "c": "(C)R10K",
    "d": "(D)K10I",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "A series is given, with one term missing. Choose the correct alternative from the given ones that will complete the series<br> 1799, ? , 59, 14 , 4 , 1.5",
    "a": "(A)299",
    "b": "(B)874",
    "c": "(C)828",
    "d": "(D)624",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "Which one set of letters when sequentially placed at the gaps in the given letter series shall complete it?<br />a _ bb _ c _&nbsp;aab _&nbsp;bc _&nbsp;caaa _",
    "a": "(A)acacba",
    "b": "(B)acabca",
    "c": "(C)acabbc",
    "d": "(D)abcaac",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "Find the odd number/letters/ word pair from the given responses.",
    "a": "(A)Orange",
    "b": "(B)Yellow",
    "c": "(C)Green",
    "d": "(D)Pink",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "Find the odd number/letters/ word pair from the given responses.",
    "a": "(A)EHRK",
    "b": "(B)PCTI",
    "c": "(C)QKBJ",
    "d": "(D)DVRS",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "27 small cubes of equal size are alligned in such a way that a bigger cube could be formed. Now five faces of this big cube are painted with red colour and remaining faces are left unpainted. Then how many cubes are there which have no face painted ?",
    "a": "(A)2",
    "b": "(B)4",
    "c": "(C)1",
    "d": "(D)6",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "<strong>Directions: Some statements are given, followed by some conclusions. You have to consider the statements to be true even if they seem to be at variance from commonly known facts. You have to decide which of the given conclusions, if any, follows from the given statements.</strong> <br /><strong>Statement:</strong>  <br />(i)Some dogs are hens. <br />(ii) Some cats are dogs. <br /><strong>Conclusions :</strong><strong> </strong> <br />(i) Some hens are not cats. <br />(ii) Some dogs are cats",
    "a": "(A)Only conclusion I follows.",
    "b": "(B)Only conclusion II follows.",
    "c": "(C)Both conclusion I and II follow.",
    "d": "(D)None of these.",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "<strong>Directions: Some statements are given, followed by some conclusions. You have to consider the statements to be true even if they seem to be at variance from commonly known facts. You have to decide which of the given conclusions, if any, follows from the given statements.</strong> <br /> <br /><strong>Statement:</strong>  <br />Video libraries are flourishing very much these days. <br /><strong>Conclusions :</strong><strong> </strong> <br />(i) People in general have got a video craze. <br />(ii) It is much cheaper to see as many movies as one likes on videos rather than going to the Cinema hall.",
    "a": "(A)Only conclusion I follows.",
    "b": "(B)Only conclusion II follows.",
    "c": "(C)Both conclusion I and II follow.",
    "d": "(D)None of these.",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(General Intelligence and Reasoning)"
  },
  {
    "qtext": "x=<u><big>√4 + √3</big></u><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<big>√4 - √3</big><br>Find the value of:<br><big>x+</big><u><big>1</big></u><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<big>x</big>",
    "a": "(A)12",
    "b": "(B)18",
    "c": "(C)16",
    "d": "(D)14",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "If 7x<sup>2</sup>-8x-7=0 then<br>Find the value of:<br>x<sup>2</sup>+<u><big>1</big></u><br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;x<sup>2</sup>",
    "a": "(A)2<sup> <u><big>14</big></u></sup><br>&nbsp;&nbsp;<sup> <big>49</big></sup>",
    "b": "(B)3<sup> <u><big>16</big></u></sup><br>&nbsp;&nbsp;<sup> <big>49</big></sup>",
    "c": "(C)2<sup> <u><big>18</big></u></sup><br>&nbsp;&nbsp;<sup> <big>49</big></sup>",
    "d": "(D)3<sup> <u><big>15</big></u></sup><br>&nbsp;&nbsp;<sup> <big>49</big></sup>",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "Find the value of:<br><br><u>  &nbsp;&nbsp;cos²P&nbsp;</u>+<u>  &nbsp;&nbsp;1+sinP&nbsp;&nbsp;</u>-<u>  &nbsp;&nbsp;cosP&nbsp;&nbsp;</u><br>1+sinP&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;cosP &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;1-sinP",
    "a": "(A)0",
    "b": "(B)1",
    "c": "(C)sinP",
    "d": "(D)-1",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "In an examination, the average marks were found to be 50. For deducting marks due to computational errors, the average marks of 100 candidates were changed from 80 to 50, hence the net average marks came down to 40. The total number of candidates, who appeared in the examination, was –",
    "a": "(A)200",
    "b": "(B)400",
    "c": "(C)300",
    "d": "(D)150",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "A tank is normally filled in 10 hrs but it takes 2 hrs longer to fill because of a leak in its bottom. If the cistern is full, in how many hours will the leak empty it?",
    "a": "(A)50 hrs",
    "b": "(B)60 hrs",
    "c": "(C)70 hrs",
    "d": "(D)80 hrs",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "Deepti sells a pen to vrinda at a gain of 30% and vrinda sells it to chitra at gain of 20% and chitra sells it to vandana at a gain of 12.5%. If Vandana pays ₹ 17.55, what did the pen cost to Deepti?",
    "a": "(A)₹ 10",
    "b": "(B)₹ 12",
    "c": "(C)₹ 13",
    "d": "(D)₹ 14",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "The area of an equilateral triangle, inscribed in a cricle is 16√3cm<sup>2</sup>. The area of the circle in terms of π will be-",
    "a": "(A)3<sup>1</sup>/<sub>21</sub>  πcm<sup>2</sup>",
    "b": "(B)13πcm<sup>2</sup>",
    "c": "(C)18<sup>1</sup>/<sub>3</sub>  πcm<sup>2</sup>",
    "d": "(D)21<sup>1</sup>/<sub>3</sub>  πcm<sup>2</sup>",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "The measure of each of two opposite angles of a rhombus is 60° and the measure of one of its sides is 15 cm. The length of its smaller diagonal is-",
    "a": "(A)15 cm",
    "b": "(B)15√3cm",
    "c": "(C)10√2",
    "d": "(D)12√3",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "A boy was asked to find the value of <sup>4</sup>/<sub>7</sub> of a sum of money. Instead of multiplying the sum by <sup>4</sup>/<sub>7</sub>, he divided it by <sup>4</sup>/<sub>7</sub>, then his answer exceeded by ₹66. Find the sum of money.",
    "a": "(A)₹ 160",
    "b": "(B)₹ 72",
    "c": "(C)₹ 46",
    "d": "(D)₹ 56",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "A boat travels from A to B along the current and from B to A against the current in 4 hrs. If the speed of the boat in still water is 5km/hr, then what is the distance between A and B ?",
    "a": "(A)10 km",
    "b": "(B)8 km",
    "c": "(C)12 km",
    "d": "(D)Data insufficient",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "In an examination, 48 % of the candidates failed in Hindi and 42 % failed in Social Science. If 14 % failed in both the subjects, then the percentage of candidates who passed in both the subjects is –",
    "a": "(A)23 %",
    "b": "(B)24 %",
    "c": "(C)22 %",
    "d": "(D)27 %",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "A and B together can complete a work in 5 days. They start working together but, after 3 days B left the work. If the work is completed after 3 more days, B alone could do the work in –",
    "a": "(A)12 days",
    "b": "(B)15 days",
    "c": "(C)13 days",
    "d": "(D)14 days",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "If a = 33, b = 32, c = 31, then find the value of a<sup>3</sup>+b<sup>3</sup>+c<sup>3</sup> -3abc",
    "a": "(A)0",
    "b": "(B)216",
    "c": "(C)288",
    "d": "(D)192",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "The volume of a solid hemispherical object is 10472 cm<sup>3</sup>. its total surface area is –",
    "a": "(A)2757.008 cm<sup>2</sup>",
    "b": "(B)2775.008 cm<sup>2</sup>",
    "c": "(C)2575.008 cm<sup>2</sup>",
    "d": "(D)2600.008 cm<sup>2</sup>",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "ABCD is a rhombus whose three vertices A, D and C lie on a circle while the 4<sup>th</sup> vertex B lies on its centre. If the area of rhombus is 8√3cm<sup>2</sup><br> Find the radius of the circle.",
    "a": "(A)6 cm",
    "b": "(B)8 cm",
    "c": "(C)2 cm",
    "d": "(D)4 cm",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "From a cliff 120 m above the shore of a sea, the angle of depression of a ship is 60°. Find the distance from the ship to a point on the shore directly below the observer.",
    "a": "(A)40√2m",
    "b": "(B)40√3m",
    "c": "(C)60√3m",
    "d": "(D)30√2m",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "At what rate per annum will a sum of money become 9 times of itself in two years, if the interest is compounded annually ?",
    "a": "(A)100 %",
    "b": "(B)200 %",
    "c": "(C)125 %",
    "d": "(D)50 %",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "ABC is a triangle. the bisectors of the interior angle ∠B and the exterior angle at ∠C intersect at D. If ∠BDC = 30°, then ∠A is – ",
    "a": "(A)60°",
    "b": "(B)80°",
    "c": "(C)30°",
    "d": "(D)40°",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "If the simple interest and the true discount on certain sum of money are ₹ 42 and ₹ 40 respectively, then find the sum.",
    "a": "(A)₹ 840",
    "b": "(B)₹ 820",
    "c": "(C)₹ 860",
    "d": "(D)₹ 850",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "₹ 952 is divided among A, B and C in such a way that the ratio of amounts of A and B is 3 : 4 and that of B and C is 2 : 5. find the amounts (in rupees) received by each in alphabetic order.",
    "a": "(A)₹ 224, ₹ 560, ₹ 168",
    "b": "(B)₹ 168, ₹ 560, ₹ 224",
    "c": "(C)₹ 560, ₹ 224, ₹ 168",
    "d": "(D)₹ 168, ₹ 224, ₹ 560",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "ABCD is a cyclic quadrilateral, in which AB and DC are produced to meet at P. If ∠ADC = 80° and ∠DAB = 20°, then the ∠PBC – ∠PCB = ?",
    "a": "(A)60°",
    "b": "(B)80°",
    "c": "(C)70°",
    "d": "(D)130°",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "Manipur tea and Darjeeling tea are ₹ 29 and ₹ 23 per kg respectively. In what ratio both should be mixed so as to gain 40% by selling the mixture at ₹ 35 per kg ?",
    "a": "(A)1 : 2",
    "b": "(B)3 :1",
    "c": "(C)2 : 1",
    "d": "(D)2 : 3",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "A boat goes 8 kms an hour in still water, but takes twice as much time in going the same distance against the current. The speed of the current (in km/hr) is –",
    "a": "(A)2 km/hr",
    "b": "(B)4 km/hr",
    "c": "(C)3 km/hr",
    "d": "(D)5 km/hr",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(QUANTITATIVE APTITUDE)"
  },
  {
    "qtext": "On which of the following Governor General was impeachment imposed ?",
    "a": "(A)Warren Hastings",
    "b": "(B)Lord Clive",
    "c": "(C)Lord Cornwallis",
    "d": "(D)Lord wellesley",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Structural Unemployment arises due to –",
    "a": "(A)Deflationary conditions",
    "b": "(B)Heavy Industry Bias",
    "c": "(C)Shortage of raw material",
    "d": "(D)Inadequate productive capacity",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "The sub-unit of DNA is known as –",
    "a": "(A)Nucleotide",
    "b": "(B)Nucleosome",
    "c": "(C)Nucleoside",
    "d": "(D)Polypeptide",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Saline and alkaline soils in India are also called as –",
    "a": "(A)Regur",
    "b": "(B)Bangar",
    "c": "(C)Kallar",
    "d": "(D)Khadar",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Debenture holders of company are its –",
    "a": "(A)Share holders",
    "b": "(B)Creditors",
    "c": "(C)Debtors",
    "d": "(D)Directors",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Iodized salt is beneficial for –",
    "a": "(A)lowering of blood pressure",
    "b": "(B)prevention of dehydration",
    "c": "(C)thyroid function",
    "d": "(D)salivary glands",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Ramsar Convention is related to the preservation of which of the following ?",
    "a": "(A)Wetlands",
    "b": "(B)Forest lands",
    "c": "(C)Mines",
    "d": "(D)Carbon Emission",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Article 25 of the Indian Constitution is related to –",
    "a": "(A)The right to equality",
    "b": "(B)The right to property",
    "c": "(C)The right to religion",
    "d": "(D)The security of the minorities",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "A speculator who sells stocks for gain, in order to buy back when price falls, is called –",
    "a": "(A)Bull",
    "b": "(B)Bear",
    "c": "(C)Boar",
    "d": "(D)Bison",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "The 'Ratha Temple's in Mahabalipuram were built by ?",
    "a": "(A)The Cholas",
    "b": "(B)The Pallavas",
    "c": "(C)The Chedis",
    "d": "(D)The Chalukyas",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "\"The Bermuda Triangle\" is located in the –",
    "a": "(A)North–Western Altantic Ocean",
    "b": "(B)South-Eastern Altantic",
    "c": "(C)North Pacific Ocean",
    "d": "(D)South Indian Ocean",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "After which of the following movements was Gandhiji given the title 'Mahatma' ?",
    "a": "(A)Champaran Movement",
    "b": "(B)Rowlatt Act",
    "c": "(C)Non-Cooperation Movement",
    "d": "(D)Quit - India Movement",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "The demand for necessities is –",
    "a": "(A)perfectly inelastic",
    "b": "(B)inelastic",
    "c": "(C)perfectly elastic",
    "d": "(D)elastic",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "'Chilgoza' is obtained from the seeds of a species of ?",
    "a": "(A)Pine",
    "b": "(B)Palm",
    "c": "(C)Cycus",
    "d": "(D)Deodar",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Bones are pneumatic in –",
    "a": "(A)Fishes",
    "b": "(B)Amphibians",
    "c": "(C)Reptiles",
    "d": "(D)Birds",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "The smallest unit of length is –",
    "a": "(A)Micron",
    "b": "(B)Nanometre",
    "c": "(C)Angstrom",
    "d": "(D)Fermimetre",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "The radio-isotope used to detect blood clots in the circulatory system is –",
    "a": "(A)Arsenic-74",
    "b": "(B)Cobalt-60",
    "c": "(C)I-131",
    "d": "(D)Sodium-24",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Which enzyme converts proteins into peptides ?",
    "a": "(A)Pepsin",
    "b": "(B)Trypsin",
    "c": "(C)Erepsin",
    "d": "(D)Enterokinase",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Stagflation refers to a situation which is characterised by –",
    "a": "(A)deflation and rising unemployment",
    "b": "(B)inflation and rising employment",
    "c": "(C)inflation and rising unemployment",
    "d": "(D)stagnant employment and deflation",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Which of the following high dignitaries, who is not a member of the Parliament, has the right to address it?",
    "a": "(A)The Attorney General of India",
    "b": "(B)The Solicitor General of India",
    "c": "(C)The Chief Election Commissioner of India",
    "d": "(D)The Chief Justice of India",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "The balance of payments of a country is in equilibrium when the –",
    "a": "(A)demand for the domestic currency is equal to its supply",
    "b": "(B)demand for the domestic currency is the highest",
    "c": "(C)demand for the domestic currency is the lowest",
    "d": "(D)demand as well as supply of the domestic currency are the highest",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Should cars have bumpers that collapse under impact ?",
    "a": "(A)Yes, since the offending car should get damaged and pay for the mistake",
    "b": "(B)No, since it would be very expensive to get the car repaired",
    "c": "(C)No, since the colliding car would then ram into the occupants and kill them",
    "d": "(D)Yes, since they help to absorb the&nbsp;impact of a collision and keep the occupants safe",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "What is the principle of a 'Life Jacket' ?",
    "a": "(A)It provides oxygen to a drowning person",
    "b": "(B)It increases the volume of the person to keep him afloat",
    "c": "(C)It decreases the volume of the person to keep him afloat",
    "d": "(D)The person can sit on it like a raft",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Lance Naik Hanumanthappa Koppad belonged to which regiment ?",
    "a": "(A)Dogra Regiment",
    "b": "(B)Madras Regiment",
    "c": "(C)Rajput Regiment",
    "d": "(D)Jat Regiment",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Recently which place has India got in the MTCR ?",
    "a": "(A)35<sup>th</sup>",
    "b": "(B)36<sup>th</sup>",
    "c": "(C)34<sup>th</sup>",
    "d": "(D)33<sup>th</sup>",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(GENERAL AWARENESS)"
  },
  {
    "qtext": "Find out in which part of the given sentence has an Error. <br>If we work (A)/ slow and steady (B)/ we can finish by noon. (C)/ No error (D)",
    "a": "(A)A",
    "b": "(B)B",
    "c": "(C)C",
    "d": "(D)D",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Find out in which part of the given sentence has an Error. <br>Many a passenger (A)/ have been (B)/ taken to the hospital. (C) No error (D)",
    "a": "(A)A",
    "b": "(B)B",
    "c": "(C)C",
    "d": "(D)D",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Find out in which part of the given sentence has an Error. <br>If you can't remember his (A)/ number you had better (B)/ to look it up. (C) No error (D)",
    "a": "(A)A",
    "b": "(B)B",
    "c": "(C)C",
    "d": "(D)D",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the correct alternative out of the four.<br>As he could not execute the work properly, he had no option _____ to leave the organization",
    "a": "(A)than",
    "b": "(B)as",
    "c": "(C)but",
    "d": "(D)except",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the correct alternative out of the four.<br>The Government aims _____ rehabilitating the affected victims in the calamity.",
    "a": "(A)t",
    "b": "(B)for",
    "c": "(C)about",
    "d": "(D)at",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the correct alternative out of the four.<br>The unemployment problem, as _____ is not severe among the educated women",
    "a": "(A)perceived",
    "b": "(B)conceived",
    "c": "(C)thought",
    "d": "(D)solved",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the correct alternative out of the four.<br> The police have <u>so far succeeded in recovering</u> only a part of the stolen property.",
    "a": "(A)thus far succeeded for recover",
    "b": "(B)so far succeed in the recovery of",
    "c": "(C)as far as succeeded in recovery of",
    "d": "(D)no improvement",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the correct alternative out of the four.<br>The easiest <u>of the thing to do</u> is to ask the address to the postman.",
    "a": "(A)of the things to do",
    "b": "(B)among the things did ",
    "c": "(C)of all the things done",
    "d": "(D)no improvement",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the correct alternative out of the four.<br>Why <u>should the candidates</u> be afraid of English Language is not clear.",
    "a": "(A)the candidates should be",
    "b": "(B)do the candidates be",
    "c": "(C)should be the candidates",
    "d": "(D)no improvement",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the one which best expresses the meaning of the given word<br>Earnestly",
    "a": "(A)hopefully",
    "b": "(B)regretfully",
    "c": "(C)sincerely",
    "d": "(D)regularly",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the one which best expresses the meaning of the given word<br>Witty",
    "a": "(A)whispering",
    "b": "(B)astonishing",
    "c": "(C)amusing",
    "d": "(D)approaching",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the option opposite in meaning to the given word <br> Venerate",
    "a": "(A)abuse",
    "b": "(B)defame",
    "c": "(C)accuse",
    "d": "(D)criticise",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the option opposite in meaning to the given word <br>Capacious",
    "a": "(A)foolish",
    "b": "(B)caring",
    "c": "(C)limited",
    "d": "(D)changeable",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the  correctly spelt word.",
    "a": "(A)Messenger",
    "b": "(B)Messanger",
    "c": "(C)Massenger",
    "d": "(D)Massanger",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the one which can be substituted for the given words/sentences.<br>A square peg in a round hole –",
    "a": "(A)an impossible task",
    "b": "(B)a scheme that never work",
    "c": "(C)a person unsuited to the position he fills",
    "d": "(D)none of these",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the one which can be substituted for the given words/sentences.<br>To worship the rising sun –",
    "a": "(A)to honour the promising sun",
    "b": "(B)to indulge in flattery",
    "c": "(C)to welcome the coming events",
    "d": "(D)to honour a man who is coming into office",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the one which can be substituted for the given words/sentences.<br>The story does not hold water –",
    "a": "(A)does not deserve appreciation",
    "b": "(B)not correct or true",
    "c": "(C)cannot be told",
    "d": "(D)cannot be valued",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the one which can be substituted for the given words/sentences.<br>List of headings of the business to be transacted at a meeting –",
    "a": "(A)Proceedings",
    "b": "(B)Excerpts",
    "c": "(C)Agenda",
    "d": "(D)Schedule",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the alternative which best expresses the meaning of the Idiom/Phrase<br>Opposed to great or sudden change –",
    "a": "(A)Conservative",
    "b": "(B)Evolutionary",
    "c": "(C)Revolutionary",
    "d": "(D)Static",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "Choose the alternative which best expresses the meaning of the Idiom/Phrase<br>Land so surrounded by water as to be almost an island –",
    "a": "(A)Isthmus",
    "b": "(B)Lagoon",
    "c": "(C)Archipelago",
    "d": "(D)Peninsula",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "<strong>PASSAGE-1</strong> <br /> Probably there was more unity and harmony in the human personality in the old days, though this was at a lower level, than today except for certain individuals who were obviously of a very high type. During this long age of transition, through which humanity has been passing we have managed to break up that unity, but have not so far succeeded in finding another. We cling still to the ways of dogmatic religion, adhere to outworn practices and beliefs, and yet talk and presume to live in terms of the scientific method. Perhaps science has been too narrow in its approach to life and has ignored many vital aspects of it, and hence it could not provide a suitable basis for a new unity and harmony. Perhaps it is gradually broadening this basis now and we shall achieve a new harmony for the human personality on a much higher level than the previous one. But the problem is a more difficult and complex one now. It was perhaps easier to develop some kind of a harmonious personality in the restricted spheres of ancient and medieval times. In that little world of town and village, with fixed concepts of social organisation and behaviour, the individual and group lived their self-contained lives, protected, as a rule, from outer storms.</p><br> The modern man has not achieved a proper inner stability because",
    "a": "(A)he is still in a state of bewilderment",
    "b": "(B)he is dogmatic in his outlook",
    "c": "(C)he refuses to adopt a scientific outlook",
    "d": "(D)he cannot give up his superstitions",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "<strong>PASSAGE-1</strong> <br /> Probably there was more unity and harmony in the human personality in the old days, though this was at a lower level, than today except for certain individuals who were obviously of a very high type. During this long age of transition, through which humanity has been passing we have managed to break up that unity, but have not so far succeeded in finding another. We cling still to the ways of dogmatic religion, adhere to outworn practices and beliefs, and yet talk and presume to live in terms of the scientific method. Perhaps science has been too narrow in its approach to life and has ignored many vital aspects of it, and hence it could not provide a suitable basis for a new unity and harmony. Perhaps it is gradually broadening this basis now and we shall achieve a new harmony for the human personality on a much higher level than the previous one. But the problem is a more difficult and complex one now. It was perhaps easier to develop some kind of a harmonious personality in the restricted spheres of ancient and medieval times. In that little world of town and village, with fixed concepts of social organisation and behaviour, the individual and group lived their self-contained lives, protected, as a rule, from outer storms. </p><br>According to the author, human personality in the past was—",
    "a": "(A)seriously limited",
    "b": "(B)fully developed",
    "c": "(C)well-integrated",
    "d": "(D)well-rounded but flawed in part",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "<strong>PASSAGE-1</strong> <br /> Probably there was more unity and harmony in the human personality in the old days, though this was at a lower level, than today except for certain individuals who were obviously of a very high type. During this long age of transition, through which humanity has been passing we have managed to break up that unity, but have not so far succeeded in finding another. We cling still to the ways of dogmatic religion, adhere to outworn practices and beliefs, and yet talk and presume to live in terms of the scientific method. Perhaps science has been too narrow in its approach to life and has ignored many vital aspects of it, and hence it could not provide a suitable basis for a new unity and harmony. Perhaps it is gradually broadening this basis now and we shall achieve a new harmony for the human personality on a much higher level than the previous one. But the problem is a more difficult and complex one now. It was perhaps easier to develop some kind of a harmonious personality in the restricted spheres of ancient and medieval times. In that little world of town and village, with fixed concepts of social organisation and behaviour, the individual and group lived their self-contained lives, protected, as a rule, from outer storms. <br /><br />On the whole, the author’s attitude to the future may be summed up as one of—",
    "a": "(A)scientific scepticism",
    "b": "(B)stoic resignation",
    "c": "(C)cautious optimist",
    "d": "(D)naive enthusiasm",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "<strong>PASSAGE-1</strong> <br /> Probably there was more unity and harmony in the human personality in the old days, though this was at a lower level, than today except for certain individuals who were obviously of a very high type. During this long age of transition, through which humanity has been passing we have managed to break up that unity, but have not so far succeeded in finding another. We cling still to the ways of dogmatic religion, adhere to outworn practices and beliefs, and yet talk and presume to live in terms of the scientific method. Perhaps science has been too narrow in its approach to life and has ignored many vital aspects of it, and hence it could not provide a suitable basis for a new unity and harmony. Perhaps it is gradually broadening this basis now and we shall achieve a new harmony for the human personality on a much higher level than the previous one. But the problem is a more difficult and complex one now. It was perhaps easier to develop some kind of a harmonious personality in the restricted spheres of ancient and medieval times. In that little world of town and village, with fixed concepts of social organisation and behaviour, the individual and group lived their self-contained lives, protected, as a rule, from outer storms. </p><br>According to the author, science is now—",
    "a": "(A)broadening our horizons",
    "b": "(B)shedding its old methods in dealing with life",
    "c": "(C)opening up new vistas in human personality",
    "d": "(D)holding out a bright future for man",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  },
  {
    "qtext": "<strong>PASSAGE-1</strong> <br />  Probably there was more unity and harmony in the human personality in the old days, though this was at a lower level, than today except for certain individuals who were obviously of a very high type. During this long age of transition, through which humanity has been passing we have managed to break up that unity, but have not so far succeeded in finding another. We cling still to the ways of dogmatic religion, adhere to outworn practices and beliefs, and yet talk and presume to live in terms of the scientific method. Perhaps science has been too narrow in its approach to life and has ignored many vital aspects of it, and hence it could not provide a suitable basis for a new unity and harmony. Perhaps it is gradually broadening this basis now and we shall achieve a new harmony for the human personality on a much higher level than the previous one. But the problem is a more difficult and complex one now. It was perhaps easier to develop some kind of a harmonious personality in the restricted spheres of ancient and medieval times. In that little world of town and village, with fixed concepts of social organisation and behaviour, the individual and group lived their self-contained lives, protected, as a rule, from outer storms. </p><br>According to the author old societies provided men—",
    "a": "(A)a limited world-view",
    "b": "(B)a well-developed community sense",
    "c": "(C)restricted opportunities",
    "d": "(D)sound religious convictions",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(ENGLISH LANGUAGE)"
  }
]
