[
  {
    "qtext": "There are 5 persons between A and B. There are 8 persons between B and C. If 3 persons are ahead of C and 21 persons are behind A, then find the maximum and minimum number of persons in the row.",
    "a": "(A)40 and 28",
    "b": "(B)28 and 40",
    "c": "(C)38 and 25",
    "d": "(D)None of these",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Find the missing number from the given responses",
    "a": "(A)20",
    "b": "(B)26",
    "c": "(C)27",
    "d": "(D)32",
    "correct": "B",
    "img": "http://campusquizkybv.blob.core.windows.net/paramountitemimages/636042764835418079_9387570.PNG",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In a certain code language 'MADRAS' is written as '–1'. How would  'DELHI' be written in that code language ?",
    "a": "(A)3",
    "b": "(B)–3",
    "c": "(C)4",
    "d": "(D)–5",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "At what time between 3 pm and 4 pm will both the hands of a clock overlap each other?",
    "a": "(A)4 minutes past 3",
    "b": "(B)30 minutes past 3",
    "c": "(C)16<sup>4</sup>&frasl;<sub>11</sub>",
    "d": "(D)None of these",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mala starts moving towards East. In what order should she turn so that she moves towards South ?",
    "a": "(A)Right, Right, Right",
    "b": "(B)Lift, Left, Right",
    "c": "(C)Left, Left, Left",
    "d": "(D)None of these",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Find the odd letter/ word pair from the given responses.",
    "a": "(A)Mahanadi",
    "b": "(B)Cauvery",
    "c": "(C)Narmada",
    "d": "(D)Krishna",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Find the odd letter/ word pair from the given responses.",
    "a": "(A)DEB",
    "b": "(B)RTP",
    "c": "(C)HIF",
    "d": "(D)NOL",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Which one set of letters when sequentially placed at the gaps in the given letter series shall complete it ? <br> aa _ aabb _ b _ aa _ aabb _ bb",
    "a": "(A)bbbba",
    "b": "(B)aabbb",
    "c": "(C)babba",
    "d": "(D)bbbaa",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Arrange the following words as per order in the dictionary<br>1.Zephyr<br>2.Zodiac<br>3.Zoonomy<br>4.Zenith<br>5.Zig Zag",
    "a": "(A)2, 4, 3, 5, 1",
    "b": "(B)4, 2, 1, 3, 5",
    "c": "(C)4, 1, 5, 2, 3",
    "d": "(D)5, 3, 2, 4, 1",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Which of the following statements is true?",
    "a": "(A)All government employees are clerks.",
    "b": "(B)Some government employees are graduates as well as clerks and urban as well.",
    "c": "(C)All government employees are graduates.",
    "d": "(D)All clerks are government employees but not graduates.",
    "correct": "B",
    "img": "https://github.com/hotdudehvfun/allquestions/blob/master/images/image1.png?raw=true",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "From the given alternatives, select the word which cannot be formed using the letters of the given word.<br>DISCRIMINATION",
    "a": "(A)CRIME",
    "b": "(B)MANSION",
    "c": "(C)ACTION",
    "d": "(D)SCAN",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "'Vipul' is taller than 'Hans'. 'Hans' is taller than Anand. 'Alok' is taller than 'Ashok'. 'Ashok' is taller than 'Hans'. Who is the tallest ?",
    "a": "(A)Alok",
    "b": "(B)Vipul",
    "c": "(C)Ashok",
    "d": "(D)Cannot be determined",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Five men, sitting in a circle and facing the centre, are playing cards. Mukund is to the left of Rajesh. Vijay is to the right of Anil and sits between Anil and Nagesh.<br> Tell who is to the right of Nagesh.",
    "a": "(A)Mukund",
    "b": "(B)Anil",
    "c": "(C)Rajesh",
    "d": "(D)Vijay",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Choose the correct order of mathematical notations which will replace * in the following equation and balance the given equation– <br> 15 * 24 * 3 * 6 * 17",
    "a": "(A)+ × - +",
    "b": "(B)– ÷ + =",
    "c": "(C)+ ÷ – =",
    "d": "(D)+ × = ÷",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "A man said to a woman, \"The sister of the husband of your mother is my aunt\". How is the woman related to that man ?",
    "a": "(A)Mother",
    "b": "(B)Sister",
    "c": "(C)Anut",
    "d": "(D)Daughter",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Some statements are given, followed by some conclusions. You have to consider the statements to be true even if they seem to be at variance from commonly known facts. You have to decide which of the given conclusions, if any, follows from the given statements. <br> Statement: <br> All tents are cabins. <br> All cabins are houses <br> Conclusions <br>I All tents are houses. <br>II All houses are tents.",
    "a": "(A)Only conclusion I follows.",
    "b": "(B)Only conclusion II follows.",
    "c": "(C)Both conclusion I and II follow.",
    "d": "(D)None of these.",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Some statements are given, followed by some conclusions. You have to consider the statements to be true even if they seem to be at variance from commonly known facts. You have to decide which of the given conclusions, if any, follows from the given statements. <br>Statement <br>A bad person can manipulate the meaning of religious-texts for his own purpose. <br>Conclusions <br>I Persons with impure conscience work egotistically. <br> II Actual wisdom is obtained from religious-texts.",
    "a": "(A)Only conclusion I follows.",
    "b": "(B)Only conclusion II follows.",
    "c": "(C)Both conclusion I and II follow.",
    "d": "(D)None of these.",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Select the related word/letters/ number from the given alternatives <br> Tortoise : Amphibian : : Chimpanzee : ?",
    "a": "(A)Mamnal",
    "b": "(B)Amphibain",
    "c": "(C)Canivorous",
    "d": "(D)Omnivorous",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Select the related word/letters/ number from the given alternatives.<br>2 : 12 : : 8 : ?",
    "a": "(A)128",
    "b": "(B)576",
    "c": "(C)396",
    "d": "(D)18",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Select the related word/letters/ number from the given alternatives.<br> ZaDc : BcFe : : RsFe : ?",
    "a": "(A)TuEh",
    "b": "(B)TuHg",
    "c": "(C)ToHg",
    "d": "(D)TuGh",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In questions no. 22 to 23, a series is given, with one term missing. Choose the correct alternative from the given ones that will complete the series. <br />0, 6, 24, 60, 120, 210, ?",
    "a": "(A)236",
    "b": "(B)336",
    "c": "(C)346",
    "d": "(D)226",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": " : In questions no. 22 to 23, a series is given, with one term missing. Choose the correct alternative from the given ones that will complete the series. <br> A A B A B C A B C D A B C D E A B C D E F A B C D E F ?",
    "a": "(A)A",
    "b": "(B)C",
    "c": "(C)H",
    "d": "(D)G",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": ": In the question given below, one question and below it two statements I and II are given. The data given in the statements is sufficient to answer the question or not. Read  the statements and give answer. If <br> I. Z is to the south of Y. <br/>II. M is to the west of Z and to the south of X. <br>Pillar X is in which direction with respect to Pillar Y ?",
    "a": "(A)Neither I nor II is sufficient.",
    "b": "(B)Only either I or II is sufficient.",
    "c": "(C)Only II is sufficient",
    "d": "(D)Both are sufficient",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "A person distributes his pens among 5 friends A, B, C, D and E in the ratio <sup>1</sup>&frasl;<sub>2</sub>:<sup>1</sup>&frasl;<sub>3</sub>:<sup>1</sup>&frasl;<sub>4</sub>:<sup>1</sup>&frasl;<sub>5</sub>:<sup>1</sup>&frasl;<sub>6</sub>: then what will be the minimum number of pens that the person has?",
    "a": "(A)57",
    "b": "(B)87",
    "c": "(C)67",
    "d": "(D)77",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "Two pipes,  A and B can fill a tank in 16 and 20 minutes respectively. If both are opened   together and at the end of 4 minutes, pipe A is closed, how long will the pipe B take to fill&nbsp;the remaining part of the tank?",
    "a": "(A)11 minutes",
    "b": "(B)13 minutes",
    "c": "(C)16 minutes",
    "d": "(D)9 minutes",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "The Rajdhani Express travels first 280 km in 3 hours and next 310 km in 4 hours. Find its average speed for the entire journey.",
    "a": "(A)84<sup>1</sup>&frasl;<sub>7</sub>",
    "b": "(B)84<sup>2</sup>&frasl;<sub>7</sub>",
    "c": "(C)84<sup>3</sup>&frasl;<sub>7</sub>",
    "d": "(D)84<sup>4</sup>&frasl;<sub>7</sub>",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "A sum is invested at a certain annual rate of simple interest for 4 years. Had it been invested at 5% higher rate, it would have got ₹355 more. What is the sum?",
    "a": "(A)₹1700",
    "b": "(B)₹1745",
    "c": "(C)₹1775",
    "d": "(D)₹1755",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "A man borrows₹3000 at 10% compound rate of interest. At the end of each year he pays back ₹1000. How much amount should he pay at the end of the third year to clear all his dues?",
    "a": "(A)₹1530",
    "b": "(B)₹1683",
    "c": "(C)₹1663",
    "d": "(D)₹1563",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "If the area of a trapezium is 209 sq. m and the lengths of its parallel sides are 13 m and 9 m respectively, then the distance between the parallel sides is –",
    "a": "(A)17 m",
    "b": "(B)21 m",
    "c": "(C)19 m",
    "d": "(D)23 m",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "The number of sides in a regular polygon is 12. The value of its each interior angle is –",
    "a": "(A)144°",
    "b": "(B)150°",
    "c": "(C)154°",
    "d": "(D)160°",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "If two numbers 2963 and 1312 are divided by a three digit number N, giving the same remainder in each case, then the sum of the digits of number N is –",
    "a": "(A)8",
    "b": "(B)11",
    "c": "(C)9",
    "d": "(D)10",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "The marked price of a shirt and a trouser are in the ratio 2 : 3. The shopkeeper gives 30% discount on the shirt. If the total discount is 20%. Then, the discount offered on the trouser is –",
    "a": "(A)12<sup>1</sup>&frasl;<sub>2</sub>",
    "b": "(B)33<sup>1</sup>&frasl;<sub>3</sub>",
    "c": "(C)13<sup>1</sup>&frasl;<sub>3</sub>>",
    "d": "(D)37<sup>1</sup>&frasl;<supub>2</sub>",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "The ratio of number of boys and girls in a school is 2 : 3. If 30% of the boys and 50% of the girls are scholarship holders, then what is the pecentage of those students who do not get scholarship?",
    "a": "(A)42%",
    "b": "(B)58%",
    "c": "(C)46%",
    "d": "(D)54%",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "A can finish a work in 30 days working 16 hours a day. B can finish the same work in&nbsp; <sup>40</sup>&frasl;<sub>3</sub> days working 18 hours a day.&nbsp;find in how many days A and B together can finish the same work,&nbsp;if A and B work 20 hours a day?",
    "a": "(A)2 days",
    "b": "(B)8 days",
    "c": "(C)4 days",
    "d": "(D)10 days",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "Two cars start at the same time from a point and move along two roads intersecting at right angles to each other. their speeds are 54 km/hr and 72 km/hr respectively. After 10 seconds, the distance between them will be –",
    "a": "(A)150 m",
    "b": "(B)350 m",
    "c": "(C)200 m",
    "d": "(D)250 m",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "From a point on a bridge across a river, the angles of depression of the banks are 30° and 45°, respectively. If the bridge is at a height of 3 m above the bank, find the width of the river.",
    "a": "(A)3(√3+1)",
    "b": "(B)3(√3-1)",
    "c": "(C)3(√3+3)",
    "d": "(D)3(√3-3)",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "PR is a tangent at a point Q on a circle, in which O is the centre and its radius is 8 cm. <br />if OR = 16 cm and OP = 10 cm, then the length of PR is –",
    "a": "(A)18 cm",
    "b": "(B)19 cm",
    "c": "(C)19.8 cm",
    "d": "(D)21.86 cm",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "The batting average of a cricket player for 30 innings is 40 runs. His highest score exceeds his lowest score by 100 runs. <br />If these two innings are not included, the average of the remaining 28 innings is 38 runs. The lowest score of the players is –",
    "a": "(A)12",
    "b": "(B)15",
    "c": "(C)18",
    "d": "(D)20",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "A fruit seller buys 700 oranges at the rate of 100 oranges for ₹500 and 500 oranges of another variety at the rate of 100 oranges for ₹700 and sells them at ₹84 per dozen. The profit percent is –",
    "a": "(A)20%",
    "b": "(B)40%",
    "c": "(C)30%",
    "d": "(D)10%",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "Some small spheres of radius 1.4 cm are dropped in a cylindrical vessel which contains some water. These small spheres are fully immersed in water. If the radius of the vessel be 28 cm and water rises by 3.5 cm, then how many small spheres were dropped into the vessel ?",
    "a": "(A)600",
    "b": "(B)500",
    "c": "(C)750",
    "d": "(D)900",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "(Quantative Aptitude)"
  },
  {
    "qtext": "The viceroy of India at the time of the Jallianwala Bagh massacre was –",
    "a": "(A)Lord Curzon",
    "b": "(B)Lord Irwin",
    "c": "(C)Lord Rippon",
    "d": "(D)Lord Chelmsford",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "A person can contest panchayat elections if he completes the age of –",
    "a": "(A)25 years",
    "b": "(B)30 years",
    "c": "(C)21 years",
    "d": "(D)18 years",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The lowest taxonomics category in universal usage is –",
    "a": "(A)Genus",
    "b": "(B)Order",
    "c": "(C)Species",
    "d": "(D)Class",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The circle that divides the day from night on the globe is called –",
    "a": "(A)Circle of illumination",
    "b": "(B)Orbital plane",
    "c": "(C)Equinox",
    "d": "(D)Equator",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Any factor of production can earn economic-rent, when its supply will be –",
    "a": "(A)Perfectly elastic",
    "b": "(B)Perfectly inelastic",
    "c": "(C)Elastic in nature",
    "d": "(D)All of the above",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Catalyst is a substance which –",
    "a": "(A)increases the rate of the reaction",
    "b": "(B)decreases the rate of reaction",
    "c": "(C)has no action on the rate of the reaction",
    "d": "(D)none of these",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Who is the author of the book 'MS : A Life in Music' ?",
    "a": "(A)U.K. Ananthamurthy",
    "b": "(B)T.J.S. George",
    "c": "(C)Elana Ferrante",
    "d": "(D)Perumal Murgan",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The Vice-President of India can be relieved by the –",
    "a": "(A)Rajya Sabha",
    "b": "(B)Lok Sabha",
    "c": "(C)Rajya Sabha & Lok Sabha&nbsp",
    "d": "(D)Election Commission",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "According to Keynes, business cycles are due to variation in the rate of investment&nbsp;caused by fluctuations in the –",
    "a": "(A)Marginal efficiency of capital",
    "b": "(B)Marginal propensity to save&nbsp",
    "c": "(C)Marginal propensity to consumption",
    "d": "(D)Marginal efficiency to investment",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The first European President of Indian National Congress was –",
    "a": "(A)Alfred Web",
    "b": "(B)A.O. Hume",
    "c": "(C)Waderbern",
    "d": "(D)George Yule",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The river Betwa meets with –",
    "a": "(A)The Ganga",
    "b": "(B)The Yamuna",
    "c": "(C)The Brahmaputra",
    "d": "(D)The Son",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The Lucknow Pact was concluded between the –",
    "a": "(A)Congress & British Government",
    "b": "(B)Congress & Muslim League",
    "c": "(C)Muslim League and British Government",
    "d": "(D)None of these",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The 'Slack Season' in the Indian Economy is –",
    "a": "(A)March - April",
    "b": "(B)September – December",
    "c": "(C)January - June",
    "d": "(D)February - April",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Turpentine oil is obtained from –",
    "a": "(A)Pinus",
    "b": "(B)Cedarwood",
    "c": "(C)Herb",
    "d": "(D)Petroleum",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "In a human body what is the number of&nbsp;cervical vertebrae?",
    "a": "(A)5",
    "b": "(B)7",
    "c": "(C)8",
    "d": "(D)12",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "In MRI machine, which one of the following is used ?",
    "a": "(A)Sound wave",
    "b": "(B)X-ray",
    "c": "(C)Ultra-sound wave",
    "d": "(D)Magnetic wave",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The acid rain destroys vegetations because it contains –",
    "a": "(A)nitric acid",
    "b": "(B)ozone",
    "c": "(C)carbon monoxide",
    "d": "(D)sulphuric acid",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Toxicology is related to the study of –",
    "a": "(A)viruses",
    "b": "(B)bacteria",
    "c": "(C)diseases",
    "d": "(D)poisons",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "If the supply curve is a straight line&nbsp;passing through the origin, then the price elasticity of supply will be –",
    "a": "(A)less than unity",
    "b": "(B)infinitely large",
    "c": "(C)greater than unity",
    "d": "(D)equal to unity",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Triple vaccine is administered to a new born child to immunize it against –",
    "a": "(A)whooping cough, tetanus and measles",
    "b": "(B)whooping cough, tetanus and diphtheria",
    "c": "(C)tetanus, diphtheria, measles and rubella",
    "d": "(D)tetanus, diphtheria, small pox and rubella",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Which term is not related to banking ?",
    "a": "(A)C.R.R.",
    "b": "(B)N.E.E.R.",
    "c": "(C)S.L.R.",
    "d": "(D)Fixed Deposits",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "For a person having hypermetropia, the near point is –",
    "a": "(A)greater than 25 cm",
    "b": "(B)greater than 50 cm",
    "c": "(C)less than 25 cm",
    "d": "(D)infinity",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "On holding a piece of wood under&nbsp;water, the upthrust on it will be –",
    "a": "(A)equal to the weight of the wood",
    "b": "(B)less than weight of the wood&nbsp",
    "c": "(C)more than weight of the wood",
    "d": "(D)zero",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Who has been appointed as the new Executive Director of RBI ?",
    "a": "(A)Deedak Singhal",
    "b": "(B)Sudarshan Sen",
    "c": "(C)Meena Hemchandra",
    "d": "(D)Milind Sharma",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Which country will host the 2016 BRICS Anti- Narcotics Heads Meet ?",
    "a": "(A)Russia",
    "b": "(B)India",
    "c": "(C)Brazil",
    "d": "(D)China",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "<span><b>Direction :</b></span><span><b> In Question nos. 76 to 78, some part of the sentences have errors and some are correct. Find out which part of a sentence has an error and blacken corresponding to the appropriate letter (A), (B), (C) and (D). If a sentence is free from error, blacken corresponding to 'No error' in the Answer Sheet.</b></span><br /><br />We have (A)/ to vacate (B)/ the five first single rooms. (C)/ No error (D)",
    "a": "(A)A",
    "b": "(B)B",
    "c": "(C)C",
    "d": "(D)D",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b>Direction :</b></span><span><b> In Question nos. 76 to 78, some part of the sentences have errors and some are correct. Find out which part of a sentence has an error and blacken corresponding to the appropriate letter (A), (B), (C) and (D). If a sentence is free from error, blacken the oval corresponding to 'No error' in the Answer Sheet.</b></span><br /><br />Buxar is (A)/ further from (B)/ Kolkata than Patna is. (C)/ No error (D)",
    "a": "(A)A",
    "b": "(B)B",
    "c": "(C)C",
    "d": "(D)D",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b>Direction :</b></span><span><b> In Question nos. 76 to 78, some part of the sentences have errors and some are correct. Find out which part of a sentence has an error and blacken corresponding to the appropriate letter (A), (B), (C) and (D). If a sentence is free from error, blacken the oval corresponding to 'No error' in t</b></span><span><b>he Answer Sheet.</b></span><br /><br />The student (A)/ rose a problem (B)/ in the class. (C)/ No error (D)",
    "a": "(A)A",
    "b": "(B)B",
    "c": "(C)C",
    "d": "(D)D",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<strong> :</strong><strong> In Question nos. 79 to 81, sentences given with blanks are to be filled in with an appropriate word. Four alternatives are suggested for each question. Choose the correct alternative out of the four and indicate it by blackening the </strong><strong>appropriate in</strong><strong> the Answer Sheet.</strong> <br /> <br />If you do not _____, all your monthly expenses would exceed your income.",
    "a": "(A)economise",
    "b": "(B)spend",
    "c": "(C)save",
    "d": "(D)splurge",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b> :</b></span><span><b> In Question nos. 79 to 81, sentences given with blanks are to be filled in with an appropriate word. Four alternatives are suggested for each question. Choose the correct alternative out of the four and indicate it by blackening the appropriate in the Answer Sheet.</b></span><br /><br />He had taken the shocking news quietly, neither _____ fate nor uttering any word of bitterness.",
    "a": "(A)submitting to",
    "b": "(B)railing against",
    "c": "(C)conspiring with&nbsp",
    "d": "(D)dissenting from",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b> :</b></span><span><b> In Question nos. 79 to 81, sentences given with blanks are to be filled in with an appropriate word. Four alternatives are suggested for each question. Choose the correct alternative out of the four and indicate it by blackening the appropriate in the Answer Sheet.</b></span>&nbsp;&nbsp;&nbsp;&nbsp;<br /><br />Kicking the bucket is a humorous _____ for dying.",
    "a": "(A)dictum",
    "b": "(B)incantation",
    "c": "(C)euphemism",
    "d": "(D)addendum",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b>Direction: In Question nos. 82 to 84, a sentence/ a part of the sentence is underlined. Below are given alternatives to the underlined part at (A), (B), (C) which may improve the sentence. Choose the correct alternative. In case no improvement is needed your answer is (D). Mark your answer in the Answer Sheet.</b></span><br /><br />Teachers and parents alike should realise that to&nbsp;<span><u>say a particular child is better than the other is doing a great injustice to both the children.</u></span>",
    "a": "(A)say a particular child is better than the other is doing a great injustice to the former",
    "b": "(B)say a particular child is better than the other is doing a great injustice to both of them",
    "c": "(C)say a particular child is better than the other is to do a great injustice to both the children&nbsp",
    "d": "(D)no improvement&nbsp",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "</span><span><b>Direction: In Question nos. 82 to 84, a sentence/ a part of the sentence is underlined. Below are given alternatives to the underlined part at (A), (B), (C) which may improve the sentence. Choose the correct alternative. In case no improvement is needed your answer is (D). Mark your answer in the</b></span><span><b>&nbsp;</b></span>Answer Sheet.<br /><br />He sailed for New York on Monday,&nbsp;<span><u>arriving there on Saturday for the much-awaited inauguration of the new hospital.</u></span>",
    "a": "(A)and arrived there on Saturday for the much-awaited inauguration of the new hospital",
    "b": "(B)arriving there on Saturday for the inauguration of the much-awaited new hospital",
    "c": "(C)arriving there for the inauguration of the much-awaited new hospital on Saturday.",
    "d": "(D)no improvement&nbsp",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b>Direction: In Question nos. 82 to 84, a sentence/ a part of the sentence is underlined. Below are given alternatives to the underlined part at (A), (B), (C) which may improve the sentence. Choose the correct alternative. In case no improvement is needed your answer is (D). Mark your answer in the Answer Sheet.</b></span><br />After trying to convince him for a long time, I realised that&nbsp;<span><u>he was one of those people who never listens to reason</u></span>.",
    "a": "(A)he was one of those people who never listen to reason",
    "b": "(B)he was one of those people who never listen to reasoning",
    "c": "(C)he is one of those people who never listen to reason",
    "d": "(D)no improvement",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b> :</b></span><span><b> In Question nos. 85 to 86 out of the four alternatives, choose the one which best expresses the meaning of the given word and mark it in the Answer Sheet.</b></span> <br /> <br />Hauteur",
    "a": "(A)Arrogance",
    "b": "(B)Fashion",
    "c": "(C)Hatred",
    "d": "(D)Crop",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<strong> :</strong><strong> In Question nos. 85 to 86 out of the four alternatives, choose the one which best expresses the meaning of the given word and mark it in the Answer Sheet.</strong> <br /> <br />Discursive",
    "a": "(A)Rambling",
    "b": "(B)Impolite",
    "c": "(C)Neglectful",
    "d": "(D)Methodical",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b> :</b></span><span><b> In question nos. 87 to 88, choose the option opposite in meaning to the given word and mark it in the Answer Sheet.</b></span> <br /> <br />Dour&nbsp",
    "a": "(A)active",
    "b": "(B)young",
    "c": "(C)radical",
    "d": "(D)cheerful",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b> :</b></span><span><b> In question nos. 87 to 88, choose the option opposite in meaning to the given word and mark it in the Answer Sheet.</b></span> <br /> <br />Wrath",
    "a": "(A)delight",
    "b": "(B)solace",
    "c": "(C)cheerful",
    "d": "(D)peace",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<strong> :</strong><strong> In question no. 89, four words are given, out of which only one word is correctly spelt. Find the correctly spelt word and mark your answer in the Answer Sheet.",
    "a": "(A)Millionaire",
    "b": "(B)Millunare",
    "c": "(C)Millionere",
    "d": "(D)Millionaer",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b>Direction :</b></span><span><b> In Question nos. 90 to 92, four alternatives are given for the Idiom/Phrase underlined in the sentence. Choose the alternative which best expresses the meaning of the Idiom/Phrase and mark it in the Answer Sheet.</b></span><br /><br />Whenever I meet him he&nbsp;<span><b>pulls a long face.</b></span><span><b>&nbsp;</b></span",
    "a": "(A)looks cheerful",
    "b": "(B)looks angry",
    "c": "(C)looks indifferent",
    "d": "(D)looks gloomy",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b>Direction :</b></span><span><b> In Question nos. 90 to 92, four alternatives are given for the Idiom/Phrase underlined in the sentence. Choose the alternative which best expresses the meaning of the Idiom/Phrase and mark it in the Answer Sheet.</b></span><br /><br />People usually take promises made on the eve of&nbsp;<span><b>elections with a grain of salt.</b></span><span><b>&nbsp;</b></span",
    "a": "(A)with total disbelief",
    "b": "(B)wholeheartedly",
    "c": "(C)with some reservation",
    "d": "(D)seriously",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b>Direction :</b></span><span><b> In Question nos. 90 to 92, four alternatives are given for the Idiom/Phrase underlined in the sentence. Choose the alternative which best expresses the meaning of the Idiom/Phrase and mark it in the Answer Sheet.</b></span><br /><br />Let's listen to him, he seems to be having&nbsp;<span><b>something up his sleeve.</b></span><span><b>&nbsp;</b></span",
    "a": "(A)a secret plan",
    "b": "(B)a grand idea",
    "c": "(C)something&nbsp;important",
    "d": "(D)a profitable plan",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b> :</b></span><span><b> In Question nos. 93 to 95, out of the four alternatives, choose the one which can be substituted for the given words/sentences and indicate it by blackening the appropriate&nbsp;</b></span><span><b>in the Answer Sheet.&nbsp;</b></span><br /><br />A group of three powerful people –",
    "a": "(A)Trio",
    "b": "(B)Tritium",
    "c": "(C)Trivet",
    "d": "(D)Triumvirate",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b> :</b></span><span><b> In Question nos. 93 to 95, out of the four alternatives, choose the one which can be substituted for the given words/sentences and indicate it by blackening the appropriate in the Answer Sheet.&nbsp;</b></span><br /><br />To write under a different name –",
    "a": "(A)Anonymous",
    "b": "(B)Biography",
    "c": "(C)Pseudonym",
    "d": "(D)Masquerade",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b> :</b></span><span><b> In Question nos. 93 to 95, out of the four alternatives, choose the one which can be substituted for the given words/sentences and indicate it by blackening the appropriate in the Answer Sheet.&nbsp;</b></span><br /><br />Constant effort to achieve something –",
    "a": "(A)Perseverance",
    "b": "(B)Vigour",
    "c": "(C)Attempt&nbsp",
    "d": "(D)Enthusiasm&nbsp",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b>Direction :</b></span><span><b> In Question nos. 96 to 100, you have a brief passage with 5 questions each.  Read the passages carefully and choose the best answer to each question out of the four alternatives and mark it by blackening the appropriate in the Answer Sheet.</b></span><br /><span><b>PASSAGE-1</b></span><br />&nbsp;&nbsp;&nbsp;&nbsp;Many Sociologists have argued that there is a functional relationship between education and economic system. They point to the fact that mass formal education began in industrial society and is an established part of all industrial societies. They note that the expansion of the economies of industrial societies is accompanied by a corresponding expansion of their educational systems. They explain this correspondence in terms of the needs of industry for skilled and trained manpower, needs which are met by the educational system, thus, the provision of mass elementary education in Britain in 1870 can be seen as a response to the needs of industry for a literate and numerate work-force at a time when industrial processes were becoming more, complex and the demand for technical skills was steadily&nbsp;growing.<br /><br />The author argues that—",
    "a": "(A)formal education can be traced to industrial society",
    "b": "(B)industrial society is responsible for expansion of education at the mass level",
    "c": "(C)industrial society gave rise to vocational education",
    "d": "(D)industrial society changed the pattern of education",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b>Direction :</b></span><span><b> In Question nos. 96 to 100, you have a brief passage with 5 questions each.  Read the passages carefully and choose the best answer to each question out of the four alternatives and mark it by blackening the appropriate in the Answer Sheet.</b></span><br /><span><b>PASSAGE-1</b></span><br />&nbsp;&nbsp;&nbsp;&nbsp;Many Sociologists have argued that there is a functional relationship between education and economic system. They point to the fact that mass formal education began in industrial society and is an established part of all industrial societies. They note that the expansion of the economies of industrial societies is accompanied by a corresponding expansion of their educational systems. They explain this correspondence in terms of the needs of industry for skilled and trained manpower, needs which are met by the educational system, thus, the provision of mass elementary education in Britain in 1870 can be seen as a response to the needs of industry for a literate and numerate work-force at a time when industrial processes were becoming more, complex and the demand for technical skills was steadily growing.<br /><br />The Sociologists referred to in the passage say that the relationship between industry and<br />elementary education was one—",
    "a": "(A)based on mutual need",
    "b": "(B)based entirely on the need of the industry",
    "c": "(C)based entirely on economic need",
    "d": "(D)based on some inexplicable historical forces",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b>Direction :</b></span><span><b> In Question nos. 96 to 100, you have a brief passage with 5 questions each.  Read the passages carefully and choose the best answer to each question out of the four alternatives and mark it by blackening the appropriate in the Answer Sheet.</b></span><br /><span><b>PASSAGE-1</b></span><br />&nbsp;&nbsp;&nbsp;&nbsp;Many Sociologists have argued that there is a functional relationship between education and economic system. They point to the fact that mass formal education began in industrial society and is an established part of all industrial societies. They note that the expansion of the economies of industrial societies is accompanied by a corresponding expansion of their educational systems. They explain this correspondence in terms of the needs of industry for skilled and trained manpower, needs which are met by the educational system, thus, the provision of mass elementary education in Britain in 1870 can be seen as a response to the needs of industry for a literate and numerate work-force at a time when industrial processes were becoming more, complex and the demand for technical skills was steadily growing.<br /><br />By ‘functional relationship’ is meant—",
    "a": "(A)a short-term relationship",
    "b": "(B)practical and utilitarian relationship&nbsp",
    "c": "(C)temporary arrangement&nbsp",
    "d": "(D)close and unbreakable relationship",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<span><b>Direction :</b></span><span><b> In Question nos. 96 to 100, you have a brief passage with 5 questions each.  Read the passages carefully and choose the best answer to each question out of the four alternatives and mark it by blackening the appropriate in the Answer Sheet.</b></span><br /><span><b>PASSAGE-1</b></span><br />&nbsp;&nbsp;&nbsp;&nbsp;Many Sociologists have argued that there is a functional relationship between education and economic system. They point to the fact that mass formal education began in industrial society and is an established part of all industrial societies. They note that the expansion of the economies of industrial societies is accompanied by a corresponding expansion of their educational systems. They explain this correspondence in terms of the needs of industry for skilled and trained manpower, needs which are met by the educational system, thus, the provision of mass elementary education in Britain in 1870 can be seen as a response to the needs of industry for a literate and numerate work-force at a time when industrial processes were becoming more, complex and the demand for technical skills was steadily growing.<br /><br />The industry needs a literate work-force because—",
    "a": "(A)its expansion needs sound learning",
    "b": "(B)it relies heavily on expertise",
    "c": "(C)it promotes a competitive spirit",
    "d": "(D)its operations need intricate technical knowledge",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "English"
  },
  {
    "qtext": "<strong>Direction :</strong><strong> In Question nos. 96 to 100, you have a brief passage with 5 questions each. Read the passages carefully and choose the best answer to each question out of the four alternatives and mark it by blackening the appropriate in the Answer Sheet.</strong> <br /><strong>PASSAGE-1</strong> <br /> Many Sociologists have argued that there is a functional relationship between education and economic system. They point to the fact that mass formal education began in industrial society and is an established part of all industrial societies. They note that the expansion of the economies of industrial societies is accompanied by a corresponding expansion of their educational systems. They explain this correspondence in terms of the needs of industry for skilled and trained manpower, needs which are met by the educational system, thus, the provision of mass elementary education in Britain in 1870 can be seen as a response to the needs of industry for a literate and numerate work-force at a time when industrial processes were becoming more, complex and the demand for technical skills was steadily growing. <br /> <br />The observations of the Sociologists are based on a study of—",
    "a": "(A)the statistical data available in a historical context",
    "b": "(B)economic system of the 19th century",
    "c": "(C)the correlation between industry and education in a historical context",
    "d": "(D)growth of industry in the 19th century",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "English"
  }
]
