{
"data":[{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nENORMOUS",
    "a": "A. Soft",
    "b": "B. Average",
    "c": "C. Tiny",
    "d": "D. Weak",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCOMMISSIONED",
    "a": "A. Started",
    "b": "B. Closed",
    "c": "C. Finished",
    "d": "D. Terminated",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nARTIFICIAL",
    "a": "A. Red",
    "b": "B. Natural",
    "c": "C. Truthful",
    "d": "D. Solid",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEXODUS",
    "a": "A. Influx",
    "b": "B. Home-coming",
    "c": "C. Return",
    "d": "D. Restoration",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nRELINQUISH",
    "a": "A. Abdicate",
    "b": "B. Renounce",
    "c": "C. Possess",
    "d": "D. Deny",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEXPAND",
    "a": "A. Convert",
    "b": "B. Condense",
    "c": "C. Congest",
    "d": "D. Conclude",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nMORTAL",
    "a": "A. Divine",
    "b": "B. Immortal",
    "c": "C. Spiritual",
    "d": "D. Eternal",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nQUIESCENT",
    "a": "A. ACTIVE",
    "b": "B. Dormant",
    "c": "C. Weak",
    "d": "D. Unconcerned",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nOBEYING",
    "a": "A. Ordering",
    "b": "B. Following",
    "c": "C. Refusing",
    "d": "D. Contradicting",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFRAUDULENT",
    "a": "A. Candid",
    "b": "B. Direct",
    "c": "C. Forthright",
    "d": "D. Genuine",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFLAGITIOUS",
    "a": "A. Innocent",
    "b": "B. Vapid",
    "c": "C. Ignorant",
    "d": "D. Frivolous",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBELITTLE",
    "a": "A. Criticize",
    "b": "B. Flatter",
    "c": "C. Exaggerate",
    "d": "D. Adore",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSTARTLED",
    "a": "A. Amused",
    "b": "B. Relaxed",
    "c": "C. Endless",
    "d": "D. Astonished",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBUSY",
    "a": "A. Occupied",
    "b": "B. Engrossed",
    "c": "C. Relaxed",
    "d": "D. Engaged",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFRESH",
    "a": "A. Faulty",
    "b": "B. Sluggish",
    "c": "C. Disgraceful",
    "d": "D. Stale",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCULPABLE",
    "a": "A. Defendable",
    "b": "B. Blameless",
    "c": "C. Careless",
    "d": "D. Irresponsible",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nOBEYING",
    "a": "A. Ordering",
    "b": "B. Following",
    "c": "C. Refusing",
    "d": "D. Contradicting",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFRAUDULENT",
    "a": "A. Candid",
    "b": "B. Direct",
    "c": "C. Forthright",
    "d": "D. Genuine",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFLAGITIOUS",
    "a": "A. Innocent",
    "b": "B. Vapid",
    "c": "C. Ignorant",
    "d": "D. Frivolous",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBELITTLE",
    "a": "A. Criticize",
    "b": "B. Flatter",
    "c": "C. Exaggerate",
    "d": "D. Adore",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSTARTLED",
    "a": "A. Amused",
    "b": "B. Relaxed",
    "c": "C. Endless",
    "d": "D. Astonished",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBUSY",
    "a": "A. Occupied",
    "b": "B. Engrossed",
    "c": "C. Relaxed",
    "d": "D. Engaged",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFRESH",
    "a": "A. Faulty",
    "b": "B. Sluggish",
    "c": "C. Disgraceful",
    "d": "D. Stale",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCULPABLE",
    "a": "A. Defendable",
    "b": "B. Blameless",
    "c": "C. Careless",
    "d": "D. Irresponsible",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nARROGANT",
    "a": "A. Humble",
    "b": "B. Cowardly",
    "c": "C. Egotistic",
    "d": "D. Gentlemanly",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nVICTORIOUS",
    "a": "A. Defeated",
    "b": "B. Annexed",
    "c": "C. Destroyed",
    "d": "D. Vanquished",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nGRACEFUL",
    "a": "A. Rough",
    "b": "B. Expert",
    "c": "C. Miserable",
    "d": "D. Awkward",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nNADIR",
    "a": "A. Modernity",
    "b": "B. Zenith",
    "c": "C. Liberty",
    "d": "D. Progress",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEXTRAVAGANCE",
    "a": "A. Luxury",
    "b": "B. Poverty",
    "c": "C. Economical",
    "d": "D. Cheapness",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nPERTINENT",
    "a": "A. Irrational",
    "b": "B. Irregular",
    "c": "C. Insistent",
    "d": "D. Irrelevant",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nOBSCURE",
    "a": "A. Implicit",
    "b": "B. Obnoxious",
    "c": "C. Explicit",
    "d": "D. Pedantic",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nURBANE",
    "a": "A. Illiterate",
    "b": "B. Backward",
    "c": "C. Discourteous",
    "d": "D. Orthodox",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nVANITY",
    "a": "A. Pride",
    "b": "B. Humility",
    "c": "C. Conceit",
    "d": "D. Ostentatious",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nRARELY",
    "a": "A. Hardly",
    "b": "B. Definately",
    "c": "C. Frequently",
    "d": "D. Periodically",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nMALICIOUS",
    "a": "A. Kind",
    "b": "B. Boastful",
    "c": "C. Generous",
    "d": "D. Indifferent",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEPILOGUE",
    "a": "A. Dialogue",
    "b": "B. Prelude",
    "c": "C. Post script",
    "d": "D. Epigram",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCAPACIOUS",
    "a": "A. Limited",
    "b": "B. Caring",
    "c": "C. Foolish",
    "d": "D. Changeable",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCONDENSE",
    "a": "A. Expand",
    "b": "B. Distribute",
    "c": "C. Interpret",
    "d": "D. Lengthen",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nADAPTABLE",
    "a": "A. Adoptable",
    "b": "B. Flexible",
    "c": "C. Yielding",
    "d": "D. Rigid",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSACROSANCT",
    "a": "A. Irreligious",
    "b": "B. Unethical",
    "c": "C. Irreverent",
    "d": "D. Unholy",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nINDISCREET",
    "a": "A. Reliable",
    "b": "B. Honest",
    "c": "C. Prudent",
    "d": "D. Stupid",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFAMILIAR",
    "a": "A. Unpleasant",
    "b": "B. Dangerous",
    "c": "C. Friendly",
    "d": "D. Strange",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nTANGIBLE",
    "a": "A. Ethereal",
    "b": "B. Concrete",
    "c": "C. Actual",
    "d": "D. Solid",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nLOVE",
    "a": "A. Villainy",
    "b": "B. Hatred",
    "c": "C. Compulsion",
    "d": "D. Force",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFAMOUS",
    "a": "A. Disgraced",
    "b": "B. Unknown",
    "c": "C. Evil",
    "d": "D. Popular",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nABSOLUTE",
    "a": "A. Deficient",
    "b": "B. Faulty",
    "c": "C. Limited",
    "d": "D. Scarce",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFRUGAL",
    "a": "A. Copious",
    "b": "B. Extravagant",
    "c": "C. Generous",
    "d": "D. Ostentatious",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nINSIPID",
    "a": "A. Tasty",
    "b": "B. Stupid",
    "c": "C. Discreet",
    "d": "D. Feast",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nABLE",
    "a": "A. Disable",
    "b": "B. Inable",
    "c": "C. Unable",
    "d": "D. Misable",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHOSTILITY",
    "a": "A. Courtesy",
    "b": "B. Hospitality",
    "c": "C. Relationship",
    "d": "D. Friendliness",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCROWDED",
    "a": "A. Busy",
    "b": "B. Congested",
    "c": "C. Quiet",
    "d": "D. Deserted",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCOMIC",
    "a": "A. Emotional",
    "b": "B. Tragic",
    "c": "C. Fearful",
    "d": "D. Painful",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHAPLESS",
    "a": "A. Cheerful",
    "b": "B. Consistent",
    "c": "C. Fortunate",
    "d": "D. Shapely",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFLIMSY",
    "a": "A. Frail",
    "b": "B. Filthy",
    "c": "C. Firm",
    "d": "D. Flippant",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEQUANIMITY",
    "a": "A. Resentment",
    "b": "B. Dubiousness",
    "c": "C. Duplicity",
    "d": "D. Excitement",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nADDITION",
    "a": "A. Division",
    "b": "B. Enumeration",
    "c": "C. Subtraction",
    "d": "D. Multiplication",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nZENITH",
    "a": "A. Acme",
    "b": "B. Top",
    "c": "C. Nadir",
    "d": "D. Pinnacle",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nDOUBTFUL",
    "a": "A. Famous",
    "b": "B. Certain",
    "c": "C. Fixed",
    "d": "D. Important",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nPERENNIAL",
    "a": "A. Frequent",
    "b": "B. Regular",
    "c": "C. Lasting",
    "d": "D. Rare",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBENIGN",
    "a": "A. Malevolent",
    "b": "B. Soft",
    "c": "C. Friendly",
    "d": "D. Unwise",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHINDRANCE",
    "a": "A. Aid",
    "b": "B. Persuasion",
    "c": "C. Cooperation",
    "d": "D. Agreement",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEXTRICATE",
    "a": "A. Manifest",
    "b": "B. Palpable",
    "c": "C. Release",
    "d": "D. Entangle",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nREPRESS",
    "a": "A. Inhibit",
    "b": "B. Liberate",
    "c": "C. Curb",
    "d": "D. Quell",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nACQUITTED",
    "a": "A. Freed",
    "b": "B. Burdened",
    "c": "C. Convicted",
    "d": "D. Entrusted",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nPROVOCATION",
    "a": "A. Vocation",
    "b": "B. Pacification",
    "c": "C. Peace",
    "d": "D. Destruction",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSUBSERVIENT",
    "a": "A. Aggressive",
    "b": "B. Straightforward",
    "c": "C. Dignified",
    "d": "D. Supercilious",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nLEND",
    "a": "A. Borrow",
    "b": "B. Cheat",
    "c": "C. Pawn",
    "d": "D. Hire",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFAINT-HEARTED",
    "a": "A. Warm-hearted",
    "b": "B. Full-blooded",
    "c": "C. Hot-blooded",
    "d": "D. Stout-hearted",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nREMISS",
    "a": "A. Forgetful",
    "b": "B. Watchful",
    "c": "C. Dutiful",
    "d": "D. Harmful",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nTRANSPARENT",
    "a": "A. Semi-transparent",
    "b": "B. Muddy",
    "c": "C. Opaque",
    "d": "D. Dark",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHONORARY",
    "a": "A. Dishonorable",
    "b": "B. Reputed",
    "c": "C. Paid",
    "d": "D. Official",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nMETICULOUS",
    "a": "A. Mutual",
    "b": "B. Shaggy",
    "c": "C. Meretricious",
    "d": "D. Slovenly",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nLOQUACIOUS",
    "a": "A. Reticent",
    "b": "B. Talkative",
    "c": "C. Garrulous",
    "d": "D. Verbose",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCONFESS",
    "a": "A. Deny",
    "b": "B. Refuse",
    "c": "C. Contest",
    "d": "D. Contend",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nANNOY",
    "a": "A. Praise",
    "b": "B. Rejoice",
    "c": "C. Please",
    "d": "D. Reward",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nREPEL",
    "a": "A. Attend",
    "b": "B. Concentrate",
    "c": "C. Continue",
    "d": "D. Attract",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSUPPRESS",
    "a": "A. Encourage",
    "b": "B. Allow",
    "c": "C. Praise",
    "d": "D. Permit",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nNIGGARDLY",
    "a": "A. Frugal",
    "b": "B. Thrifty",
    "c": "C. Stingy",
    "d": "D. Generous",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nIMPASSE",
    "a": "A. Resurgence",
    "b": "B. Breakthrough",
    "c": "C. Continuation",
    "d": "D. Combination",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHAPHAZARD",
    "a": "A. Fortuitous",
    "b": "B. Indifferent",
    "c": "C. Deliberate",
    "d": "D. Accidental",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nDENSITY",
    "a": "A. Rarity",
    "b": "B. Intelligence",
    "c": "C. Clarity",
    "d": "D. Brightness",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nADHERENT",
    "a": "A. Detractor",
    "b": "B. Enemy",
    "c": "C. Alien",
    "d": "D. Rival",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBASE",
    "a": "A. Climax",
    "b": "B. Height",
    "c": "C. Top",
    "d": "D. Roof",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nPATCHY",
    "a": "A. Attractive",
    "b": "B. Uniform",
    "c": "C. Simple",
    "d": "D. Clear",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nENMITY",
    "a": "A. Important",
    "b": "B. Unnecessary",
    "c": "C. Friendship",
    "d": "D. Likeness",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHOLLOW",
    "a": "A. Filled",
    "b": "B. Solid",
    "c": "C. Strong",
    "d": "D. Substantial",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nVALUABLE",
    "a": "A. Invaluable",
    "b": "B. Worthless",
    "c": "C. Inferior",
    "d": "D. Lowly",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nGULLIBLE",
    "a": "A. Incredulous",
    "b": "B. Fickle",
    "c": "C. Easy",
    "d": "D. Stylish",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nINDUSTRIOUS",
    "a": "A. Indifferent",
    "b": "B. Indolent",
    "c": "C. Casual",
    "d": "D. Passive",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nAUTONOMY",
    "a": "A. Slavery",
    "b": "B. Subordination",
    "c": "C. Dependence",
    "d": "D. Submissiveness",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nALIEN",
    "a": "A. Native",
    "b": "B. Domiciled",
    "c": "C. Natural",
    "d": "D. Resident",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSYNTHETIC",
    "a": "A. Affable",
    "b": "B. Natural",
    "c": "C. Plastic",
    "d": "D. Cosmetic",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBALANCE",
    "a": "A. Disbalance",
    "b": "B. Misbalance",
    "c": "C. Debalance",
    "d": "D. Imbalance",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nLIABILITY",
    "a": "A. Property",
    "b": "B. Assets",
    "c": "C. Debt",
    "d": "D. Treasure",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nMOUNTAIN",
    "a": "A. Plain",
    "b": "B. Plateau",
    "c": "C. Precipice",
    "d": "D. Valley",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSTATIONARY",
    "a": "A. Active",
    "b": "B. Mobile",
    "c": "C. Rapid",
    "d": "D. Busy",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCONCEDE",
    "a": "A. Object",
    "b": "B. Refuse",
    "c": "C. Grant",
    "d": "D. Accede",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nVIOLENT",
    "a": "A. Humble",
    "b": "B. Harmless",
    "c": "C. Gentle",
    "d": "D. Tame",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nVIRTUOUS",
    "a": "A. Wicked",
    "b": "B. Corrupt",
    "c": "C. Vicious",
    "d": "D. Scandalous",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nGAIN",
    "a": "A. Loose",
    "b": "B. Fall",
    "c": "C. Lost",
    "d": "D. Lose",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nPRELIMINARY",
    "a": "A. Final",
    "b": "B. First",
    "c": "C. Secondary",
    "d": "D. Initial",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nDEFIANCE",
    "a": "A. Anxiety",
    "b": "B. Obedience",
    "c": "C. Suspicion",
    "d": "D. Dismay",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nENCOURAGE",
    "a": "A. Dampen",
    "b": "B. Disapprove",
    "c": "C. Discourage",
    "d": "D. Warn",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nLUCID",
    "a": "A. Glory",
    "b": "B. Noisy",
    "c": "C. Obscure",
    "d": "D. Distinct",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSTRINGENT",
    "a": "A. General",
    "b": "B. Vehement",
    "c": "C. Lenient",
    "d": "D. Magnanimous",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nMINOR",
    "a": "A. Big",
    "b": "B. Major",
    "c": "C. Tall",
    "d": "D. Heavy",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nREVEALED",
    "a": "A. Denied",
    "b": "B. Concealed",
    "c": "C. Ignored",
    "d": "D. Overlooked",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nESSENTIAL",
    "a": "A. Extra",
    "b": "B. Noughts",
    "c": "C. Minors",
    "d": "D. Trivial",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHYPOCRITICAL",
    "a": "A. Gentle",
    "b": "B. Sincere",
    "c": "C. Amiable",
    "d": "D. Dependable",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFICKLE",
    "a": "A. Courageous",
    "b": "B. Sincere",
    "c": "C. Steadfast",
    "d": "D. Humble",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},
{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>History <b>abounds</b> in instances of courage.</p>",
    "a": "A. shines",
    "b": "B. lacks",
    "c": "C. suffices",
    "d": "D. fails",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The inhabitants of the island were <b>barbarians</b>.</p>",
    "a": "A. civilized",
    "b": "B. cruel",
    "c": "C. uncivilized",
    "d": "D. bad",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The members thought that the task was <b>feasible</b>.</p>",
    "a": "A. impractical",
    "b": "B. impossible",
    "c": "C. difficult",
    "d": "D. impracticable",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p><b>crestfallen</b> he returned as he had never faced such humiliation in the whole of his life.</p>",
    "a": "A. vainglorious",
    "b": "B. indignant",
    "c": "C. triumphant",
    "d": "D. disturbed",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p><b>Feasibility</b> of the project is under study.</p>",
    "a": "A. unsuitability",
    "b": "B. cheapness",
    "c": "C. impropriety",
    "d": "D. impracticability",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The <b>incessant</b> noise of the boring machine made it difficult for us to got to sleep at night.</p>",
    "a": "A. intermittent",
    "b": "B. harsh",
    "c": "C. soft",
    "d": "D. constant",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Unsettled conditions in the land led to <b>exodus</b> of hundreds of its citizens.</p>",
    "a": "A. invasion",
    "b": "B. entry",
    "c": "C. immigration",
    "d": "D. expulsion",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Many people try to <b>resist</b> reforms in the society.</p>",
    "a": "A. fight",
    "b": "B. accept",
    "c": "C. welcome",
    "d": "D. repel",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Because of the economy drive, they very unwillingly surrendered some <b>superfluous</b> posts.</p>",
    "a": "A. important",
    "b": "B. relevant",
    "c": "C. significant",
    "d": "D. essential",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The young leader was <b>reluctant</b> to shoulder the responsibilities of ministerial office.</p>",
    "a": "A. wanting",
    "b": "B. willing",
    "c": "C. anxious",
    "d": "D. eager",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Sathish point of view was correct but his behavior with his father was quite <b>impertinent</b>.</p>",
    "a": "A. healthy",
    "b": "B. respectful",
    "c": "C. inadequate",
    "d": "D. smooth",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>This new magazine is know for its <b>comprehensive</b> coverage of news.</p>",
    "a": "A. casual",
    "b": "B. inadequate",
    "c": "C. indifferent",
    "d": "D. superficial",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>He is well known for coming up with <b>impracticable</b> solutions.</p>",
    "a": "A. easy",
    "b": "B. possible",
    "c": "C. feasible",
    "d": "D. alternate",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The managing director remarked that the secretary was an <b>asset</b> to the company.</p>",
    "a": "A. loss",
    "b": "B. liability",
    "c": "C. drag",
    "d": "D. handicap",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>You can hardly find any trace of <b>humility</b> in the man.</p>",
    "a": "A. pride",
    "b": "B. insolence",
    "c": "C. arrogance",
    "d": "D. conceit",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The plantation workers were on a <b>collision</b> course before the labor officer intervened.</p>",
    "a": "A. retaliatory",
    "b": "B. perfunctory",
    "c": "C. conciliatory",
    "d": "D. circuitous",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The result of the tournament gave them a sense of <b>elation</b>.</p>",
    "a": "A. despondency",
    "b": "B. misery",
    "c": "C. disappointment",
    "d": "D. despair",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The officer asked the clerk to <b>expedite</b> the matter.</p>",
    "a": "A. postpone",
    "b": "B. defer",
    "c": "C. adjourn",
    "d": "D. delay",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>He is extremely <b>intelligent</b> but proud.</p>",
    "a": "A. dull",
    "b": "B. weak",
    "c": "C. ignorant",
    "d": "D. simple",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>I <b>abhor</b> the ideas he sometimes expresses</p>",
    "a": "A. admire",
    "b": "B. respect",
    "c": "C. applaud",
    "d": "D. appreciate",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>They had an <b>insipid</b> conversation.</p>",
    "a": "A. lively",
    "b": "B. argumentative",
    "c": "C. loud",
    "d": "D. curious",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The habit of <b>squandering</b> money should not be encouraged.</p>",
    "a": "A. discarding",
    "b": "B. boarding",
    "c": "C. collecting",
    "d": "D. saving",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The bedroom is at the <b>rear</b> side of this house.</p>",
    "a": "A. unusual",
    "b": "B. front",
    "c": "C. upper",
    "d": "D. back",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>His critics found in the <b>overt</b> statements some hidden design.</p>",
    "a": "A. converse",
    "b": "B. pervert",
    "c": "C. covert",
    "d": "D. contrived",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>He spoke against corruption with <b>zeal</b>.</p>",
    "a": "A. indifference",
    "b": "B. calmness",
    "c": "C. despair",
    "d": "D. passiveness",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Those who views are <b>progressive</b> often meet with formidable impediments when they begin to act.</p>",
    "a": "A. revolutionary",
    "b": "B. retrograde",
    "c": "C. brave",
    "d": "D. outmoded",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Everything about him, especially his talkative nature, proclaims his <b>effeminacy</b>.</p>",
    "a": "A. aggressiveness",
    "b": "B. attractiveness",
    "c": "C. manliness",
    "d": "D. boorishness",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p><b>Adversity</b> teaches man to be humble and self-reliant.</p>",
    "a": "A. sincerity",
    "b": "B. animosity",
    "c": "C. curiosity",
    "d": "D. prosperity",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Given these constraint, we have no alternative but to suggest <b>an improvised</b> solution.</p>",
    "a": "A. a complete",
    "b": "B. a preplanned",
    "c": "C. a permanent",
    "d": "D. a proscribed",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The chairman <b>initiated</b> the proceedings with a brief speech.</p>",
    "a": "A. confused",
    "b": "B. closed",
    "c": "C. started",
    "d": "D. complicated",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>We had a <b>delectable</b> meal yesterday.</p>",
    "a": "A. heavy",
    "b": "B. unsavory",
    "c": "C. tasty",
    "d": "D. nice",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>There was something strange and <b>morbid</b> about the whole house.</p>",
    "a": "A. healthy",
    "b": "B. cheerful",
    "c": "C. insipid",
    "d": "D. appealing",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The leader was <b>pragmatic</b> in his approach to the problem facing the country.</p>",
    "a": "A. indefinite",
    "b": "B. vague",
    "c": "C. idealistic",
    "d": "D. optimistic",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Many people suffer setbacks in their career because of their inherent <b>levity</b>.</p>",
    "a": "A. seriousness",
    "b": "B. solemnity",
    "c": "C. religiosity",
    "d": "D. gravity",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The moment when jadish got order of promotion, as General Manager, was a <b>memorable</b> occasion for him and his family.</p>",
    "a": "A. passing",
    "b": "B. immemorial",
    "c": "C. forgetful",
    "d": "D. innocuous",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>They took note of <b>humility</b> of the visiting dignitary.</p>",
    "a": "A. grandeur",
    "b": "B. arrogance",
    "c": "C. friendliness",
    "d": "D. decency",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Harish displays <b>enthusiasm</b> whenever he is posed with a problem.</p>",
    "a": "A. eagerness",
    "b": "B. weakness",
    "c": "C. indifference",
    "d": "D. softness",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>I was surprised at his <b>stiff</b> attitude.</p>",
    "a": "A. courteous",
    "b": "B. flexible",
    "c": "C. soft",
    "d": "D. lively",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>It was done in a <b>haphazard</b> manner.</p>",
    "a": "A. planned",
    "b": "B. excellent",
    "c": "C. extraordinary",
    "d": "D. designed",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>He <b>abandoned</b> his family.</p>",
    "a": "A. supported",
    "b": "B. encouraged",
    "c": "C. pleased",
    "d": "D. saved",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>In a literary work <b>obscurity</b> cab be a virtue.</p>",
    "a": "A. clarity",
    "b": "B. precision",
    "c": "C. definiteness",
    "d": "D. specificity",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>It was universally characterized as a <b>progressive</b> measure.</p>",
    "a": "A. regressive",
    "b": "B. obstructive",
    "c": "C. retrograde",
    "d": "D. abhorrent",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Mala was often teased as <b>corpulent</b> by her friends.</p>",
    "a": "A. fat",
    "b": "B. belligerent",
    "c": "C. garrulous",
    "d": "D. gaunt",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>His <b>vindictive</b> nature often came up for comment among his friends.</p>",
    "a": "A. forgetful",
    "b": "B. forgiving",
    "c": "C. obedient",
    "d": "D. timid",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The minister gave a public speech on the controversial subject to <b>precipitate</b> the matter.</p>",
    "a": "A. aggravate",
    "b": "B. create",
    "c": "C. defer",
    "d": "D. push",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Poet often prefer <b>ambiguity</b> to</p>",
    "a": "A. clarity",
    "b": "B. certainty",
    "c": "C. rationality",
    "d": "D. perversity",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>In ancient India, scholars had no interest in political power or <b>material</b> growth.</p>",
    "a": "A. internal",
    "b": "B. spiritual",
    "c": "C. psychic",
    "d": "D. celestial",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The atmosphere in that desolate place looked <b>ominous</b>.</p>",
    "a": "A. pleasant",
    "b": "B. encouraging",
    "c": "C. auspicious",
    "d": "D. favorable",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Like poverty, <b>affluence</b> can sometimes create its own problems.</p>",
    "a": "A. indigence",
    "b": "B. opulence",
    "c": "C. sorrow",
    "d": "D. exuberance",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The atmosphere in the institute he had newly joined <b>congenial</b> to research.</p>",
    "a": "A. disagreeable for",
    "b": "B. inconvenient for",
    "c": "C. unpleasant for",
    "d": "D. unsuitable for",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Dinesh could manage his family satisfactory with his <b>meager</b> income.</p>",
    "a": "A. continuous",
    "b": "B. fabulous",
    "c": "C. hard",
    "d": "D. adequate",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>His short but pointed speech was <b>applauded</b> by all sections of the audience.</p>",
    "a": "A. disapproved",
    "b": "B. misunderstood",
    "c": "C. praised",
    "d": "D. welcomed",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>I thought about her a lot during the <b>following</b> months.</p>",
    "a": "A. succeeding",
    "b": "B. proceeding",
    "c": "C. preceding",
    "d": "D. receding",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>His interpretation of the poem is <b>superficial</b>.</p>",
    "a": "A. mysterious",
    "b": "B. difficult",
    "c": "C. profound",
    "d": "D. mystical",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The chairman <b>rebuked</b> the accounts for not supervising officer for not supervising the work of his subordinates.</p>",
    "a": "A. received",
    "b": "B. awarded",
    "c": "C. invited",
    "d": "D. praised",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>It is one of <b>pernicious</b> customs prevailing in the society.</p>",
    "a": "A. permanent",
    "b": "B. beneficial",
    "c": "C. parochial",
    "d": "D. dangerous",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>He was asked to <b>accelerate</b> the pace of work.</p>",
    "a": "A. supervise",
    "b": "B. slacken",
    "c": "C. control",
    "d": "D. check",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The commission took two years to go through the <b>massive</b> collection of files and documents before preparing its report.</p>",
    "a": "A. meager",
    "b": "B. heavy",
    "c": "C. light",
    "d": "D. short",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>He is the most <b>prudent</b> person. I have ever came across.</p>",
    "a": "A. shortsighted",
    "b": "B. reckless",
    "c": "C. inconsiderate",
    "d": "D. injudicious",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>According to a great philosopher <b>magnanimity</b> in a man implies many other qualities.</p>",
    "a": "A. enmity",
    "b": "B. meanness",
    "c": "C. jealousy",
    "d": "D. poverty",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>Nothing has been organised properly and confusion seems <b>inevitable</b>.</p>",
    "a": "A. inevident",
    "b": "B. inefficient",
    "c": "C. ineligible",
    "d": "D. uncertain",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>What he tells me <b>confirms</b> my ideas.</p>",
    "a": "A. strengthens",
    "b": "B. opposes",
    "c": "C. contradicts",
    "d": "D. verifies",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The actor is well known both for his <b>humility</b> and courage.</p>",
    "a": "A. pride",
    "b": "B. determination",
    "c": "C. honesty",
    "d": "D. gentleness",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The General Manager is quite <b>tactful</b> and handles the workers union very effectively.</p>",
    "a": "A. disciplined",
    "b": "B. naive",
    "c": "C. strict",
    "d": "D. loose",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The error in the newspaper article is <b>incidental</b>.</p>",
    "a": "A. intentional",
    "b": "B. conventional",
    "c": "C. usual",
    "d": "D. permissible",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The club meets on the last Thursday of every month is a <b>dilapidated</b> palace.</p>",
    "a": "A. neglected",
    "b": "B. regenerated",
    "c": "C. renovated",
    "d": "D. furnished",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>A <b>friendly</b> dog meet us at the farmgate.</p>",
    "a": "A. helpful",
    "b": "B. understanding",
    "c": "C. quiet",
    "d": "D. hostile",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>In the interest of one's own reputation one should avoid <b>ostentation</b> while entertaining friends.</p>",
    "a": "A. miserliness",
    "b": "B. simplicity",
    "c": "C. purity",
    "d": "D. innocence",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>She used to <b>disparage</b> her neighbor every now and then.</p>",
    "a": "A. please",
    "b": "B. praise",
    "c": "C. belittle",
    "d": "D. denigrate",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "Each sentences below consist of a word or a phrase which is bold. It is followed by four words or phrases. Select the word or pharse which is closes to the OPPOSITE in meaning of the bold word or phrase.\n\n<p>The story told by the teacher <b>amused</b> children in the class.</p>",
    "a": "A. frightened",
    "b": "B. jolted",
    "c": "C. astonished",
    "d": "D. saddened",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
}


]
}
