{
"data":[{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nENORMOUS",
    "a": "A. Soft",
    "b": "B. Average",
    "c": "C. Tiny",
    "d": "D. Weak",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCOMMISSIONED",
    "a": "A. Started",
    "b": "B. Closed",
    "c": "C. Finished",
    "d": "D. Terminated",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nARTIFICIAL",
    "a": "A. Red",
    "b": "B. Natural",
    "c": "C. Truthful",
    "d": "D. Solid",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEXODUS",
    "a": "A. Influx",
    "b": "B. Home-coming",
    "c": "C. Return",
    "d": "D. Restoration",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nRELINQUISH",
    "a": "A. Abdicate",
    "b": "B. Renounce",
    "c": "C. Possess",
    "d": "D. Deny",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEXPAND",
    "a": "A. Convert",
    "b": "B. Condense",
    "c": "C. Congest",
    "d": "D. Conclude",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nMORTAL",
    "a": "A. Divine",
    "b": "B. Immortal",
    "c": "C. Spiritual",
    "d": "D. Eternal",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nQUIESCENT",
    "a": "A. ACTIVE",
    "b": "B. Dormant",
    "c": "C. Weak",
    "d": "D. Unconcerned",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nOBEYING",
    "a": "A. Ordering",
    "b": "B. Following",
    "c": "C. Refusing",
    "d": "D. Contradicting",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFRAUDULENT",
    "a": "A. Candid",
    "b": "B. Direct",
    "c": "C. Forthright",
    "d": "D. Genuine",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFLAGITIOUS",
    "a": "A. Innocent",
    "b": "B. Vapid",
    "c": "C. Ignorant",
    "d": "D. Frivolous",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBELITTLE",
    "a": "A. Criticize",
    "b": "B. Flatter",
    "c": "C. Exaggerate",
    "d": "D. Adore",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSTARTLED",
    "a": "A. Amused",
    "b": "B. Relaxed",
    "c": "C. Endless",
    "d": "D. Astonished",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBUSY",
    "a": "A. Occupied",
    "b": "B. Engrossed",
    "c": "C. Relaxed",
    "d": "D. Engaged",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFRESH",
    "a": "A. Faulty",
    "b": "B. Sluggish",
    "c": "C. Disgraceful",
    "d": "D. Stale",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCULPABLE",
    "a": "A. Defendable",
    "b": "B. Blameless",
    "c": "C. Careless",
    "d": "D. Irresponsible",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nOBEYING",
    "a": "A. Ordering",
    "b": "B. Following",
    "c": "C. Refusing",
    "d": "D. Contradicting",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFRAUDULENT",
    "a": "A. Candid",
    "b": "B. Direct",
    "c": "C. Forthright",
    "d": "D. Genuine",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFLAGITIOUS",
    "a": "A. Innocent",
    "b": "B. Vapid",
    "c": "C. Ignorant",
    "d": "D. Frivolous",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBELITTLE",
    "a": "A. Criticize",
    "b": "B. Flatter",
    "c": "C. Exaggerate",
    "d": "D. Adore",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSTARTLED",
    "a": "A. Amused",
    "b": "B. Relaxed",
    "c": "C. Endless",
    "d": "D. Astonished",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBUSY",
    "a": "A. Occupied",
    "b": "B. Engrossed",
    "c": "C. Relaxed",
    "d": "D. Engaged",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFRESH",
    "a": "A. Faulty",
    "b": "B. Sluggish",
    "c": "C. Disgraceful",
    "d": "D. Stale",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCULPABLE",
    "a": "A. Defendable",
    "b": "B. Blameless",
    "c": "C. Careless",
    "d": "D. Irresponsible",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nARROGANT",
    "a": "A. Humble",
    "b": "B. Cowardly",
    "c": "C. Egotistic",
    "d": "D. Gentlemanly",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nVICTORIOUS",
    "a": "A. Defeated",
    "b": "B. Annexed",
    "c": "C. Destroyed",
    "d": "D. Vanquished",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nGRACEFUL",
    "a": "A. Rough",
    "b": "B. Expert",
    "c": "C. Miserable",
    "d": "D. Awkward",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nNADIR",
    "a": "A. Modernity",
    "b": "B. Zenith",
    "c": "C. Liberty",
    "d": "D. Progress",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEXTRAVAGANCE",
    "a": "A. Luxury",
    "b": "B. Poverty",
    "c": "C. Economical",
    "d": "D. Cheapness",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nPERTINENT",
    "a": "A. Irrational",
    "b": "B. Irregular",
    "c": "C. Insistent",
    "d": "D. Irrelevant",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nOBSCURE",
    "a": "A. Implicit",
    "b": "B. Obnoxious",
    "c": "C. Explicit",
    "d": "D. Pedantic",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nURBANE",
    "a": "A. Illiterate",
    "b": "B. Backward",
    "c": "C. Discourteous",
    "d": "D. Orthodox",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nVANITY",
    "a": "A. Pride",
    "b": "B. Humility",
    "c": "C. Conceit",
    "d": "D. Ostentatious",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nRARELY",
    "a": "A. Hardly",
    "b": "B. Definately",
    "c": "C. Frequently",
    "d": "D. Periodically",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nMALICIOUS",
    "a": "A. Kind",
    "b": "B. Boastful",
    "c": "C. Generous",
    "d": "D. Indifferent",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEPILOGUE",
    "a": "A. Dialogue",
    "b": "B. Prelude",
    "c": "C. Post script",
    "d": "D. Epigram",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCAPACIOUS",
    "a": "A. Limited",
    "b": "B. Caring",
    "c": "C. Foolish",
    "d": "D. Changeable",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCONDENSE",
    "a": "A. Expand",
    "b": "B. Distribute",
    "c": "C. Interpret",
    "d": "D. Lengthen",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nADAPTABLE",
    "a": "A. Adoptable",
    "b": "B. Flexible",
    "c": "C. Yielding",
    "d": "D. Rigid",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSACROSANCT",
    "a": "A. Irreligious",
    "b": "B. Unethical",
    "c": "C. Irreverent",
    "d": "D. Unholy",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nINDISCREET",
    "a": "A. Reliable",
    "b": "B. Honest",
    "c": "C. Prudent",
    "d": "D. Stupid",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFAMILIAR",
    "a": "A. Unpleasant",
    "b": "B. Dangerous",
    "c": "C. Friendly",
    "d": "D. Strange",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nTANGIBLE",
    "a": "A. Ethereal",
    "b": "B. Concrete",
    "c": "C. Actual",
    "d": "D. Solid",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nLOVE",
    "a": "A. Villainy",
    "b": "B. Hatred",
    "c": "C. Compulsion",
    "d": "D. Force",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFAMOUS",
    "a": "A. Disgraced",
    "b": "B. Unknown",
    "c": "C. Evil",
    "d": "D. Popular",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nABSOLUTE",
    "a": "A. Deficient",
    "b": "B. Faulty",
    "c": "C. Limited",
    "d": "D. Scarce",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFRUGAL",
    "a": "A. Copious",
    "b": "B. Extravagant",
    "c": "C. Generous",
    "d": "D. Ostentatious",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nINSIPID",
    "a": "A. Tasty",
    "b": "B. Stupid",
    "c": "C. Discreet",
    "d": "D. Feast",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nABLE",
    "a": "A. Disable",
    "b": "B. Inable",
    "c": "C. Unable",
    "d": "D. Misable",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHOSTILITY",
    "a": "A. Courtesy",
    "b": "B. Hospitality",
    "c": "C. Relationship",
    "d": "D. Friendliness",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCROWDED",
    "a": "A. Busy",
    "b": "B. Congested",
    "c": "C. Quiet",
    "d": "D. Deserted",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCOMIC",
    "a": "A. Emotional",
    "b": "B. Tragic",
    "c": "C. Fearful",
    "d": "D. Painful",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHAPLESS",
    "a": "A. Cheerful",
    "b": "B. Consistent",
    "c": "C. Fortunate",
    "d": "D. Shapely",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFLIMSY",
    "a": "A. Frail",
    "b": "B. Filthy",
    "c": "C. Firm",
    "d": "D. Flippant",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEQUANIMITY",
    "a": "A. Resentment",
    "b": "B. Dubiousness",
    "c": "C. Duplicity",
    "d": "D. Excitement",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nADDITION",
    "a": "A. Division",
    "b": "B. Enumeration",
    "c": "C. Subtraction",
    "d": "D. Multiplication",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nZENITH",
    "a": "A. Acme",
    "b": "B. Top",
    "c": "C. Nadir",
    "d": "D. Pinnacle",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nDOUBTFUL",
    "a": "A. Famous",
    "b": "B. Certain",
    "c": "C. Fixed",
    "d": "D. Important",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nPERENNIAL",
    "a": "A. Frequent",
    "b": "B. Regular",
    "c": "C. Lasting",
    "d": "D. Rare",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBENIGN",
    "a": "A. Malevolent",
    "b": "B. Soft",
    "c": "C. Friendly",
    "d": "D. Unwise",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHINDRANCE",
    "a": "A. Aid",
    "b": "B. Persuasion",
    "c": "C. Cooperation",
    "d": "D. Agreement",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nEXTRICATE",
    "a": "A. Manifest",
    "b": "B. Palpable",
    "c": "C. Release",
    "d": "D. Entangle",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nREPRESS",
    "a": "A. Inhibit",
    "b": "B. Liberate",
    "c": "C. Curb",
    "d": "D. Quell",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nACQUITTED",
    "a": "A. Freed",
    "b": "B. Burdened",
    "c": "C. Convicted",
    "d": "D. Entrusted",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nPROVOCATION",
    "a": "A. Vocation",
    "b": "B. Pacification",
    "c": "C. Peace",
    "d": "D. Destruction",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSUBSERVIENT",
    "a": "A. Aggressive",
    "b": "B. Straightforward",
    "c": "C. Dignified",
    "d": "D. Supercilious",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nLEND",
    "a": "A. Borrow",
    "b": "B. Cheat",
    "c": "C. Pawn",
    "d": "D. Hire",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFAINT-HEARTED",
    "a": "A. Warm-hearted",
    "b": "B. Full-blooded",
    "c": "C. Hot-blooded",
    "d": "D. Stout-hearted",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nREMISS",
    "a": "A. Forgetful",
    "b": "B. Watchful",
    "c": "C. Dutiful",
    "d": "D. Harmful",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nTRANSPARENT",
    "a": "A. Semi-transparent",
    "b": "B. Muddy",
    "c": "C. Opaque",
    "d": "D. Dark",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHONORARY",
    "a": "A. Dishonorable",
    "b": "B. Reputed",
    "c": "C. Paid",
    "d": "D. Official",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nMETICULOUS",
    "a": "A. Mutual",
    "b": "B. Shaggy",
    "c": "C. Meretricious",
    "d": "D. Slovenly",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nLOQUACIOUS",
    "a": "A. Reticent",
    "b": "B. Talkative",
    "c": "C. Garrulous",
    "d": "D. Verbose",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCONFESS",
    "a": "A. Deny",
    "b": "B. Refuse",
    "c": "C. Contest",
    "d": "D. Contend",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nANNOY",
    "a": "A. Praise",
    "b": "B. Rejoice",
    "c": "C. Please",
    "d": "D. Reward",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nREPEL",
    "a": "A. Attend",
    "b": "B. Concentrate",
    "c": "C. Continue",
    "d": "D. Attract",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSUPPRESS",
    "a": "A. Encourage",
    "b": "B. Allow",
    "c": "C. Praise",
    "d": "D. Permit",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nNIGGARDLY",
    "a": "A. Frugal",
    "b": "B. Thrifty",
    "c": "C. Stingy",
    "d": "D. Generous",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nIMPASSE",
    "a": "A. Resurgence",
    "b": "B. Breakthrough",
    "c": "C. Continuation",
    "d": "D. Combination",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHAPHAZARD",
    "a": "A. Fortuitous",
    "b": "B. Indifferent",
    "c": "C. Deliberate",
    "d": "D. Accidental",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nDENSITY",
    "a": "A. Rarity",
    "b": "B. Intelligence",
    "c": "C. Clarity",
    "d": "D. Brightness",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nADHERENT",
    "a": "A. Detractor",
    "b": "B. Enemy",
    "c": "C. Alien",
    "d": "D. Rival",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBASE",
    "a": "A. Climax",
    "b": "B. Height",
    "c": "C. Top",
    "d": "D. Roof",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nPATCHY",
    "a": "A. Attractive",
    "b": "B. Uniform",
    "c": "C. Simple",
    "d": "D. Clear",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nENMITY",
    "a": "A. Important",
    "b": "B. Unnecessary",
    "c": "C. Friendship",
    "d": "D. Likeness",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHOLLOW",
    "a": "A. Filled",
    "b": "B. Solid",
    "c": "C. Strong",
    "d": "D. Substantial",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nVALUABLE",
    "a": "A. Invaluable",
    "b": "B. Worthless",
    "c": "C. Inferior",
    "d": "D. Lowly",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nGULLIBLE",
    "a": "A. Incredulous",
    "b": "B. Fickle",
    "c": "C. Easy",
    "d": "D. Stylish",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nINDUSTRIOUS",
    "a": "A. Indifferent",
    "b": "B. Indolent",
    "c": "C. Casual",
    "d": "D. Passive",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nAUTONOMY",
    "a": "A. Slavery",
    "b": "B. Subordination",
    "c": "C. Dependence",
    "d": "D. Submissiveness",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nALIEN",
    "a": "A. Native",
    "b": "B. Domiciled",
    "c": "C. Natural",
    "d": "D. Resident",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSYNTHETIC",
    "a": "A. Affable",
    "b": "B. Natural",
    "c": "C. Plastic",
    "d": "D. Cosmetic",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nBALANCE",
    "a": "A. Disbalance",
    "b": "B. Misbalance",
    "c": "C. Debalance",
    "d": "D. Imbalance",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nLIABILITY",
    "a": "A. Property",
    "b": "B. Assets",
    "c": "C. Debt",
    "d": "D. Treasure",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nMOUNTAIN",
    "a": "A. Plain",
    "b": "B. Plateau",
    "c": "C. Precipice",
    "d": "D. Valley",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSTATIONARY",
    "a": "A. Active",
    "b": "B. Mobile",
    "c": "C. Rapid",
    "d": "D. Busy",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nCONCEDE",
    "a": "A. Object",
    "b": "B. Refuse",
    "c": "C. Grant",
    "d": "D. Accede",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nVIOLENT",
    "a": "A. Humble",
    "b": "B. Harmless",
    "c": "C. Gentle",
    "d": "D. Tame",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nVIRTUOUS",
    "a": "A. Wicked",
    "b": "B. Corrupt",
    "c": "C. Vicious",
    "d": "D. Scandalous",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nGAIN",
    "a": "A. Loose",
    "b": "B. Fall",
    "c": "C. Lost",
    "d": "D. Lose",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nPRELIMINARY",
    "a": "A. Final",
    "b": "B. First",
    "c": "C. Secondary",
    "d": "D. Initial",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nDEFIANCE",
    "a": "A. Anxiety",
    "b": "B. Obedience",
    "c": "C. Suspicion",
    "d": "D. Dismay",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nENCOURAGE",
    "a": "A. Dampen",
    "b": "B. Disapprove",
    "c": "C. Discourage",
    "d": "D. Warn",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nLUCID",
    "a": "A. Glory",
    "b": "B. Noisy",
    "c": "C. Obscure",
    "d": "D. Distinct",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nSTRINGENT",
    "a": "A. General",
    "b": "B. Vehement",
    "c": "C. Lenient",
    "d": "D. Magnanimous",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nMINOR",
    "a": "A. Big",
    "b": "B. Major",
    "c": "C. Tall",
    "d": "D. Heavy",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nREVEALED",
    "a": "A. Denied",
    "b": "B. Concealed",
    "c": "C. Ignored",
    "d": "D. Overlooked",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nESSENTIAL",
    "a": "A. Extra",
    "b": "B. Noughts",
    "c": "C. Minors",
    "d": "D. Trivial",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nHYPOCRITICAL",
    "a": "A. Gentle",
    "b": "B. Sincere",
    "c": "C. Amiable",
    "d": "D. Dependable",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
},{
    "qtext": "In the following questions choose the word which is the exact OPPOSITE of the given words.\n\nFICKLE",
    "a": "A. Courageous",
    "b": "B. Sincere",
    "c": "C. Steadfast",
    "d": "D. Humble",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Antonyms",
    "section": "(English)"
}]
}
