{
  "data":[
    {
        "qtext": "In the world today we make health and end in itself. We have forgotten that health is really means to enable a person to do his work and do it well. a lot of modern medicine and this includes many patients as well as many physicians pays very little attention to health but very much attention to those who imagine that they are ill. Our great concern with health is shown by the medical columns in newspapers. the health articles in popular magazines and the popularity of television programmes and all those books on medicine. We talk about health all the time. Yet for the most part the only result is more people with imaginary illness. The healthy man should not be wasting time talking about health: he should be using health for work. The work does the work that good health possible.\nModern medicine is primarily concerned with",
        "a": "(A)promotion of good health",
        "b": "(B)people suffering from imaginary illness",
        "c": "(C)people suffering from real illness",
        "d": "(D)increased efficiency in work",
        "correct": "B",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "In the world today we make health and end in itself. We have forgotten that health is really means to enable a person to do his work and do it well. a lot of modern medicine and this includes many patients as well as many physicians pays very little attention to health but very much attention to those who imagine that they are ill. Our great concern with health is shown by the medical columns in newspapers. the health articles in popular magazines and the popularity of television programmes and all those books on medicine. We talk about health all the time. Yet for the most part the only result is more people with imaginary illness. The healthy man should not be wasting time talking about health: he should be using health for work. The work does the work that good health possible.\nThe passage suggests that",
        "a": "(A)health is an end in itself",
        "b": "(B)health is blessing",
        "c": "(C)health is only means to an end",
        "d": "(D)we should not talk about health",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "In the world today we make health and end in itself. We have forgotten that health is really means to enable a person to do his work and do it well. a lot of modern medicine and this includes many patients as well as many physicians pays very little attention to health but very much attention to those who imagine that they are ill. Our great concern with health is shown by the medical columns in newspapers. the health articles in popular magazines and the popularity of television programmes and all those books on medicine. We talk about health all the time. Yet for the most part the only result is more people with imaginary illness. The healthy man should not be wasting time talking about health: he should be using health for work. The work does the work that good health possible.\nTalking about the health all time makes people",
        "a": "(A)always suffer from imaginary illness",
        "b": "(B)sometimes suffer from imaginary illness",
        "c": "(C)rarely suffer from imaginary illness",
        "d": "(D)often suffer from imaginary illness",
        "correct": "D",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "In the world today we make health and end in itself. We have forgotten that health is really means to enable a person to do his work and do it well. a lot of modern medicine and this includes many patients as well as many physicians pays very little attention to health but very much attention to those who imagine that they are ill. Our great concern with health is shown by the medical columns in newspapers. the health articles in popular magazines and the popularity of television programmes and all those books on medicine. We talk about health all the time. Yet for the most part the only result is more people with imaginary illness. The healthy man should not be wasting time talking about health: he should be using health for work. The work does the work that good health possible.\nThe passage tells us",
        "a": "(A)how medicine should be manufactured",
        "b": "(B)what healthy man should or should not do",
        "c": "(C)what television programmes should be about",
        "d": "(D)how best to imagine illness",
        "correct": "B",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "In the world today we make health and end in itself. We have forgotten that health is really means to enable a person to do his work and do it well. a lot of modern medicine and this includes many patients as well as many physicians pays very little attention to health but very much attention to those who imagine that they are ill. Our great concern with health is shown by the medical columns in newspapers. the health articles in popular magazines and the popularity of television programmes and all those books on medicine. We talk about health all the time. Yet for the most part the only result is more people with imaginary illness. The healthy man should not be wasting time talking about health: he should be using health for work. The work does the work that good health possible.\nA healthy man should be concerned with",
        "a": "(A)his work which good health makes possible",
        "b": "(B)looking after his health",
        "c": "(C)his health which makes work possible",
        "d": "(D)talking about health",
        "correct": "A",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "It is to progress in the human sciences that we must look to undo the evils which have resulted from a knowledge of physical world hastily and superficially acquired by population unconscious of the changes in themselves that the new knowledge has imperative. The road to a happier world than any known in the past lies open before us if atavistic destructive passions can be kept in leash while the necessary adaptations are made. Fears are inevitable in time, but hopes are equally rational and far more likely to bear good fruit. We must learn to think rather less of the dangers to be avoided than of the good that will lie within our grasp if we can believe in it and let it dominate our thoughts. Science, whatever unpleasant consequences it may have by the way, is in its very nature a liberator, a liberator of bondage to physical nature and in time to come, a liberator from the weight of destructive passions. We are on the threshold of utter disaster or unprecedentedly glorious achievement. No previous age has been fraught with problems so momentous; and it is to science that we must look to for a happy future.\nWhat does science liberate s from? It is liberate us from",
        "a": "(A)fears and destructive passions",
        "b": "(B)slavery to physical nature and from passions",
        "c": "(C)bondage to physical nature",
        "d": "(D)idealistic hopes of glorious future",
        "correct": "B",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "It is to progress in the human sciences that we must look to undo the evils which have resulted from a knowledge of physical world hastily and superficially acquired by population unconscious of the changes in themselves that the new knowledge has imperative. The road to a happier world than any known in the past lies open before us if atavistic destructive passions can be kept in leash while the necessary adaptations are made. Fears are inevitable in time, but hopes are equally rational and far more likely to bear good fruit. We must learn to think rather less of the dangers to be avoided than of the good that will lie within our grasp if we can believe in it and let it dominate our thoughts. Science, whatever unpleasant consequences it may have by the way, is in its very nature a liberator, a liberator of bondage to physical nature and in time to come, a liberator from the weight of destructive passions. We are on the threshold of utter disaster or unprecedentedly glorious achievement. No previous age has been fraught with problems so momentous; and it is to science that we must look to for a happy future.\nShould human sciences be developed because they will",
        "a": "(A)provide more knowledge of the physical word",
        "b": "(B)make us conscious of the changing world",
        "c": "(C)make us conscious of the changing in ourselves",
        "d": "(D)eliminate the destruction caused by a superficial knowledge of the physical world",
        "correct": "D",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "It is to progress in the human sciences that we must look to undo the evils which have resulted from a knowledge of physical world hastily and superficially acquired by population unconscious of the changes in themselves that the new knowledge has imperative. The road to a happier world than any known in the past lies open before us if atavistic destructive passions can be kept in leash while the necessary adaptations are made. Fears are inevitable in time, but hopes are equally rational and far more likely to bear good fruit. We must learn to think rather less of the dangers to be avoided than of the good that will lie within our grasp if we can believe in it and let it dominate our thoughts. Science, whatever unpleasant consequences it may have by the way, is in its very nature a liberator, a liberator of bondage to physical nature and in time to come, a liberator from the weight of destructive passions. We are on the threshold of utter disaster or unprecedentedly glorious achievement. No previous age has been fraught with problems so momentous; and it is to science that we must look to for a happy future.\nIf man's bestial yearning is controlled",
        "a": "(A)the future will be tolerable",
        "b": "(B)the future will be brighter than the present",
        "c": "(C)the present will be brighter than the future",
        "d": "(D)the present will become tolerable",
        "correct": "B",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "It is to progress in the human sciences that we must look to undo the evils which have resulted from a knowledge of physical world hastily and superficially acquired by population unconscious of the changes in themselves that the new knowledge has imperative. The road to a happier world than any known in the past lies open before us if atavistic destructive passions can be kept in leash while the necessary adaptations are made. Fears are inevitable in time, but hopes are equally rational and far more likely to bear good fruit. We must learn to think rather less of the dangers to be avoided than of the good that will lie within our grasp if we can believe in it and let it dominate our thoughts. Science, whatever unpleasant consequences it may have by the way, is in its very nature a liberator, a liberator of bondage to physical nature and in time to come, a liberator from the weight of destructive passions. We are on the threshold of utter disaster or unprecedentedly glorious achievement. No previous age has been fraught with problems so momentous; and it is to science that we must look to for a happy future.\nFears and hopes according to the author",
        "a": "(A)are closely linked with the life of modern man",
        "b": "(B)can bear fruit",
        "c": "(C)can yield good results",
        "d": "(D)are irrational",
        "correct": "A",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "It is to progress in the human sciences that we must look to undo the evils which have resulted from a knowledge of physical world hastily and superficially acquired by population unconscious of the changes in themselves that the new knowledge has imperative. The road to a happier world than any known in the past lies open before us if atavistic destructive passions can be kept in leash while the necessary adaptations are made. Fears are inevitable in time, but hopes are equally rational and far more likely to bear good fruit. We must learn to think rather less of the dangers to be avoided than of the good that will lie within our grasp if we can believe in it and let it dominate our thoughts. Science, whatever unpleasant consequences it may have by the way, is in its very nature a liberator, a liberator of bondage to physical nature and in time to come, a liberator from the weight of destructive passions. We are on the threshold of utter disaster or unprecedentedly glorious achievement. No previous age has been fraught with problems so momentous; and it is to science that we must look to for a happy future.\nTo carve out a bright future man should",
        "a": "(A)analyse dangers that lie ahead",
        "b": "(B)try to avoid dangers",
        "c": "(C)overcome fear and dangers",
        "d": "(D)cultivate a positive outlook",
        "correct": "D",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "The object underlying the rules of natural justice \\\"is to prevent miscarriage of justice\\\" ans secure \\\"fair play in action\\\" As pointed out earlier the requirement about recording of reasons for its decision by an administrative authority exercising quasi-judicial functions achieves his object by excluding changes of arbitrariness and ensuring a degree of fairness in the process of decision making. Keeping in view the expanding horizon of the principle of natural justice which govern exercise of power by administrative authorities. The rules of natural justice are not embodied rules. The extent of their application depends upon the particularly statutory framework where under jurisdication has been conferred on the administrative authority. with regard to the exercise of particular power by an administrative authority including exercise of judicial or quasi-judicial functions the legislature, while conferring the said power, may feel that it would not be in the larger public interest that the reasons for the order passed by the administrative authority be recorded in the order and be communicated to the aggrieved party and it may dispense with such a requirement.\n\"The rules of the natural justice are not embodies rules\" means that these rules",
        "a": "(A)are left deliberately vague",
        "b": "(B)cannot be satisfactorily interpreted",
        "c": "(C)are flexible",
        "d": "(D)cannot be visualised",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "The object underlying the rules of natural justice \\\"is to prevent miscarriage of justice\\\" ans secure \\\"fair play in action\\\" As pointed out earlier the requirement about recording of reasons for its decision by an administrative authority exercising quasi-judicial functions achieves his object by excluding changes of arbitrariness and ensuring a degree of fairness in the process of decision making. Keeping in view the expanding horizon of the principle of natural justice which govern exercise of power by administrative authorities. The rules of natural justice are not embodied rules. The extent of their application depends upon the particularly statutory framework where under jurisdication has been conferred on the administrative authority. with regard to the exercise of particular power by an administrative authority including exercise of judicial or quasi-judicial functions the legislature, while conferring the said power, may feel that it would not be in the larger public interest that the reasons for the order passed by the administrative authority be recorded in the order and be communicated to the aggrieved party and it may dispense with such a requirement.\nFrom the passage it is clear that it is the legislature that",
        "a": "(A)invests the administrative authority with enormous powers",
        "b": "(B)embodies rules",
        "c": "(C)has the larger interests of public welfare",
        "d": "(D)leaves administrative authority enough discretion to interpret rules",
        "correct": "A",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "The object underlying the rules of natural justice \\\"is to prevent miscarriage of justice\\\" ans secure \\\"fair play in action\\\" As pointed out earlier the requirement about recording of reasons for its decision by an administrative authority exercising quasi-judicial functions achieves his object by excluding changes of arbitrariness and ensuring a degree of fairness in the process of decision making. Keeping in view the expanding horizon of the principle of natural justice which govern exercise of power by administrative authorities. The rules of natural justice are not embodied rules. The extent of their application depends upon the particularly statutory framework where under jurisdication has been conferred on the administrative authority. with regard to the exercise of particular power by an administrative authority including exercise of judicial or quasi-judicial functions the legislature, while conferring the said power, may feel that it would not be in the larger public interest that the reasons for the order passed by the administrative authority be recorded in the order and be communicated to the aggrieved party and it may dispense with such a requirement.\nAccording to the passage, there is always a gap between",
        "a": "(A)rules of natural justice and their application",
        "b": "(B)conception of a rule and its concretisation",
        "c": "(C)demand for natural justice and its realisation",
        "d": "(D)intention and execution",
        "correct": "A",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "The object underlying the rules of natural justice \\\"is to prevent miscarriage of justice\\\" ans secure \\\"fair play in action\\\" As pointed out earlier the requirement about recording of reasons for its decision by an administrative authority exercising quasi-judicial functions achieves his object by excluding changes of arbitrariness and ensuring a degree of fairness in the process of decision making. Keeping in view the expanding horizon of the principle of natural justice which govern exercise of power by administrative authorities. The rules of natural justice are not embodied rules. The extent of their application depends upon the particularly statutory framework where under jurisdication has been conferred on the administrative authority. with regard to the exercise of particular power by an administrative authority including exercise of judicial or quasi-judicial functions the legislature, while conferring the said power, may feel that it would not be in the larger public interest that the reasons for the order passed by the administrative authority be recorded in the order and be communicated to the aggrieved party and it may dispense with such a requirement.\n\"To dispense with a requirement\" means",
        "a": "(A)to do without the demand",
        "b": "(B)to drop the charge",
        "c": "(C)to cancel all formal procedure",
        "d": "(D)to alter the provisions of the case",
        "correct": "A",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "The object underlying the rules of natural justice \\\"is to prevent miscarriage of justice\\\" ans secure \\\"fair play in action\\\" As pointed out earlier the requirement about recording of reasons for its decision by an administrative authority exercising quasi-judicial functions achieves his object by excluding changes of arbitrariness and ensuring a degree of fairness in the process of decision making. Keeping in view the expanding horizon of the principle of natural justice which govern exercise of power by administrative authorities. The rules of natural justice are not embodied rules. The extent of their application depends upon the particularly statutory framework where under jurisdication has been conferred on the administrative authority. with regard to the exercise of particular power by an administrative authority including exercise of judicial or quasi-judicial functions the legislature, while conferring the said power, may feel that it would not be in the larger public interest that the reasons for the order passed by the administrative authority be recorded in the order and be communicated to the aggrieved party and it may dispense with such a requirement.\nAccording to the passage, natural justice can be brought about by",
        "a": "(A)administrative authority remaining vigilant",
        "b": "(B)administrative authority upholding rules of natural justice",
        "c": "(C)administrative authority farming rules suitably",
        "d": "(D)administrative authority observing the rules of fair play",
        "correct": "D",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
     {
        "qtext": "The strength of the electronics industry in Japan is the Japanese ability to organise production and marketing rather than their achievements in original research. The British are generally recognised as a far more inventive collection of individuals, but never seem able to exploit what they invent. There are many examples, from the TSR Z hovercraft, high speed train and Sinclair scooter to the Triumph, BSA and Norton Motorcycle which all prove this sad rule. The Japanese were able to exploits their strengths in marketing and development many years ago, and their success was at first either not understood in the West or was dismissed as something which could have been produced only at their low price. They were sold because they were cheap copies of other people\\'s ideas churned out of a workhouse which was dedicated to hard grind above all else.\nIt is evident from the passage that the strength of a country's industry depends upon",
        "a": "(A)original research",
        "b": "(B)international cooperation",
        "c": "(C)dedicated workforce",
        "d": "(D)electronic development",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "The strength of the electronics industry in Japan is the Japanese ability to organise production and marketing rather than their achievements in original research. The British are generally recognised as a far more inventive collection of individuals, but never seem able to exploit what they invent. There are many examples, from the TSR Z hovercraft, high speed train and Sinclair scooter to the Triumph, BSA and Norton Motorcycle which all prove this sad rule. The Japanese were able to exploits their strengths in marketing and development many years ago, and their success was at first either not understood in the West or was dismissed as something which could have been produced only at their low price. They were sold because they were cheap copies of other people\\'s ideas churned out of a workhouse which was dedicated to hard grind above all else.\nThe sad rule mentioned in this passage refers to",
        "a": "(A)the inability of the Japanese to be inventive like the British",
        "b": "(B)the inability of the British to be industrious like the Japanese",
        "c": "(C)the lack of variety in Japanese inventions",
        "d": "(D)the poorer marketing ability of British",
        "correct": "D",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "The strength of the electronics industry in Japan is the Japanese ability to organise production and marketing rather than their achievements in original research. The British are generally recognised as a far more inventive collection of individuals, but never seem able to exploit what they invent. There are many examples, from the TSR Z hovercraft, high speed train and Sinclair scooter to the Triumph, BSA and Norton Motorcycle which all prove this sad rule. The Japanese were able to exploits their strengths in marketing and development many years ago, and their success was at first either not understood in the West or was dismissed as something which could have been produced only at their low price. They were sold because they were cheap copies of other people\\'s ideas churned out of a workhouse which was dedicated to hard grind above all else.\nThe TSR Z hovercraft, high speed train, Sinclair scooter etc. are the symbols of",
        "a": "(A)Japanese success",
        "b": "(B)British failure",
        "c": "(C)British success",
        "d": "(D)Japanese failure",
        "correct": "B",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "The strength of the electronics industry in Japan is the Japanese ability to organise production and marketing rather than their achievements in original research. The British are generally recognised as a far more inventive collection of individuals, but never seem able to exploit what they invent. There are many examples, from the TSR Z hovercraft, high speed train and Sinclair scooter to the Triumph, BSA and Norton Motorcycle which all prove this sad rule. The Japanese were able to exploits their strengths in marketing and development many years ago, and their success was at first either not understood in the West or was dismissed as something which could have been produced only at their low price. They were sold because they were cheap copies of other people\\'s ideas churned out of a workhouse which was dedicated to hard grind above all else.\nAccording to the passage, prosperity in industry depends upon",
        "a": "(A)productivity",
        "b": "(B)inventiveness",
        "c": "(C)marketing ability",
        "d": "(D)official patronage",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "The strength of the electronics industry in Japan is the Japanese ability to organise production and marketing rather than their achievements in original research. The British are generally recognised as a far more inventive collection of individuals, but never seem able to exploit what they invent. There are many examples, from the TSR Z hovercraft, high speed train and Sinclair scooter to the Triumph, BSA and Norton Motorcycle which all prove this sad rule. The Japanese were able to exploits their strengths in marketing and development many years ago, and their success was at first either not understood in the West or was dismissed as something which could have been produced only at their low price. They were sold because they were cheap copies of other people\\'s ideas churned out of a workhouse which was dedicated to hard grind above all else.\nThe main theme of this passage is",
        "a": "(A)electronic industry in Japan",
        "b": "(B)industrial comparison between Japan and Britain",
        "c": "(C)the role of marketing efficiency in industrial prosperity",
        "d": "(D)the importance of original research in industry",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Courage is not only the basis of virtue; it is its expression. faith, hope, charity and all the rest don\\'t become virtues until it takes courage to exercise them. There are roughly two types of courage. the first an emotional state which urges a man to risk injury or death, is physical courage. The second, more reasoning attitude which enables him to take coolly his career, happiness, his whole future or his judgement of what he thinks either right or worthwhile, is moral courage.\\nI have known many men, who had marked physical courage, but lacked moral courage. Some of them were in high places, but they failed to be great in themselves because they lacked moral courage. On the other hand I have seen men who undoubtedly possessed moral courage but were very cautious about taking physical risks. But I have never met a man with moral courage who couldn\\'t, when it was really necessary, face a situation boldly.\nA man of courage is",
        "a": "(A)cunning",
        "b": "(B)intelligent",
        "c": "(C)curious",
        "d": "(D)careful",
        "correct": "D",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Courage is not only the basis of virtue; it is its expression. faith, hope, charity and all the rest don\\'t become virtues until it takes courage to exercise them. There are roughly two types of courage. the first an emotional state which urges a man to risk injury or death, is physical courage. The second, more reasoning attitude which enables him to take coolly his career, happiness, his whole future or his judgement of what he thinks either right or worthwhile, is moral courage.\\nI have known many men, who had marked physical courage, but lacked moral courage. Some of them were in high places, but they failed to be great in themselves because they lacked moral courage. On the other hand I have seen men who undoubtedly possessed moral courage but were very cautious about taking physical risks. But I have never met a man with moral courage who couldn\\'t, when it was really necessary, face a situation boldly.\nPhysical courage is an expression of",
        "a": "(A)emotions",
        "b": "(B)deliberation",
        "c": "(C)uncertainty",
        "d": "(D)defiance",
        "correct": "A",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Courage is not only the basis of virtue; it is its expression. faith, hope, charity and all the rest don\\'t become virtues until it takes courage to exercise them. There are roughly two types of courage. the first an emotional state which urges a man to risk injury or death, is physical courage. The second, more reasoning attitude which enables him to take coolly his career, happiness, his whole future or his judgement of what he thinks either right or worthwhile, is moral courage.\\nI have known many men, who had marked physical courage, but lacked moral courage. Some of them were in high places, but they failed to be great in themselves because they lacked moral courage. On the other hand I have seen men who undoubtedly possessed moral courage but were very cautious about taking physical risks. But I have never met a man with moral courage who couldn\\'t, when it was really necessary, face a situation boldly.\nA man with moral courage can",
        "a": "(A)defy his enemies",
        "b": "(B)overcome all difficulties",
        "c": "(C)face a situation boldly",
        "d": "(D)be very pragmatic",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Courage is not only the basis of virtue; it is its expression. faith, hope, charity and all the rest don\\'t become virtues until it takes courage to exercise them. There are roughly two types of courage. the first an emotional state which urges a man to risk injury or death, is physical courage. The second, more reasoning attitude which enables him to take coolly his career, happiness, his whole future or his judgement of what he thinks either right or worthwhile, is moral courage.\\nI have known many men, who had marked physical courage, but lacked moral courage. Some of them were in high places, but they failed to be great in themselves because they lacked moral courage. On the other hand I have seen men who undoubtedly possessed moral courage but were very cautious about taking physical risks. But I have never met a man with moral courage who couldn\\'t, when it was really necessary, face a situation boldly.\nPeople with physical courage of ten lack",
        "a": "(A)mental balance",
        "b": "(B)capacity for reasoning",
        "c": "(C)emotional stability",
        "d": "(D)will to fight",
        "correct": "B",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Courage is not only the basis of virtue; it is its expression. faith, hope, charity and all the rest don\\'t become virtues until it takes courage to exercise them. There are roughly two types of courage. the first an emotional state which urges a man to risk injury or death, is physical courage. The second, more reasoning attitude which enables him to take coolly his career, happiness, his whole future or his judgement of what he thinks either right or worthwhile, is moral courage.\\nI have known many men, who had marked physical courage, but lacked moral courage. Some of them were in high places, but they failed to be great in themselves because they lacked moral courage. On the other hand I have seen men who undoubtedly possessed moral courage but were very cautious about taking physical risks. But I have never met a man with moral courage who couldn\\'t, when it was really necessary, face a situation boldly.\nAll virtues become meaningful because of",
        "a": "(A)faith",
        "b": "(B)charity",
        "c": "(C)courage",
        "d": "(D)hope",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
     {
        "qtext": "Soft bodied animals like caterpillars often fall a prey to voracious hunters like birds or reptiles. Despite having no means to \\'actively\\' defend themselves, with weapons like claws or jaws, they have nevertheless, evolved other equally effective deterrents. A particular species of the caterpillar lives at an altitude over 2.500 metres in the Himalayas. It uses prominent colour to inform would be predators of its in edibility. In the event that an inexperienced or adventurous bird did eat the caterpillar, it would probably vomit it soon after, and subsequently desist from attacking similar species in future. Though this would do the unfortunate victim no good, the species benefits. A rare example of the martyr among animals.\nThe expression \"others equally effective deterrents\" mean",
        "a": "(A)preventive weapons which have equal effect of others",
        "b": "(B)mechanism which scares everyone equally well",
        "c": "(C)preventive equipment which it is as effective as something that has been already mentioned in the passage",
        "d": "(D)deterrents that are as powerful as those the caterpillars have",
        "correct": "B",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Soft bodied animals like caterpillars often fall a prey to voracious hunters like birds or reptiles. Despite having no means to \\'actively\\' defend themselves, with weapons like claws or jaws, they have nevertheless, evolved other equally effective deterrents. A particular species of the caterpillar lives at an altitude over 2.500 metres in the Himalayas. It uses prominent colour to inform would be predators of its in edibility. In the event that an inexperienced or adventurous bird did eat the caterpillar, it would probably vomit it soon after, and subsequently desist from attacking similar species in future. Though this would do the unfortunate victim no good, the species benefits. A rare example of the martyr among animals.\nExperienced birds do not attack the Himalayan caterpillars because they are",
        "a": "(A)repulsive",
        "b": "(B)very aggressive",
        "c": "(C)inedible",
        "d": "(D)diseased",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Soft bodied animals like caterpillars often fall a prey to voracious hunters like birds or reptiles. Despite having no means to \\'actively\\' defend themselves, with weapons like claws or jaws, they have nevertheless, evolved other equally effective deterrents. A particular species of the caterpillar lives at an altitude over 2.500 metres in the Himalayas. It uses prominent colour to inform would be predators of its in edibility. In the event that an inexperienced or adventurous bird did eat the caterpillar, it would probably vomit it soon after, and subsequently desist from attacking similar species in future. Though this would do the unfortunate victim no good, the species benefits. A rare example of the martyr among animals.\nThe Himalayan caterpillar uses prominent colours to",
        "a": "(A)warn the predator",
        "b": "(B)attack the predator",
        "c": "(C)reveal itself",
        "d": "(D)defend itself",
        "correct": "A",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Soft bodied animals like caterpillars often fall a prey to voracious hunters like birds or reptiles. Despite having no means to \\'actively\\' defend themselves, with weapons like claws or jaws, they have nevertheless, evolved other equally effective deterrents. A particular species of the caterpillar lives at an altitude over 2.500 metres in the Himalayas. It uses prominent colour to inform would be predators of its in edibility. In the event that an inexperienced or adventurous bird did eat the caterpillar, it would probably vomit it soon after, and subsequently desist from attacking similar species in future. Though this would do the unfortunate victim no good, the species benefits. A rare example of the martyr among animals.\nCaterpillars cannot defend themselves because",
        "a": "(A)are passive animals",
        "b": "(B)are lazy",
        "c": "(C)cannot acquire weapons",
        "d": "(D)have no claws or jaws",
        "correct": "D",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Soft bodied animals like caterpillars often fall a prey to voracious hunters like birds or reptiles. Despite having no means to \\'actively\\' defend themselves, with weapons like claws or jaws, they have nevertheless, evolved other equally effective deterrents. A particular species of the caterpillar lives at an altitude over 2.500 metres in the Himalayas. It uses prominent colour to inform would be predators of its in edibility. In the event that an inexperienced or adventurous bird did eat the caterpillar, it would probably vomit it soon after, and subsequently desist from attacking similar species in future. Though this would do the unfortunate victim no good, the species benefits. A rare example of the martyr among animals.\nIn the context of this passage, a martyr is one who dies",
        "a": "(A)without putting up resistance",
        "b": "(B)without any gain to oneself",
        "c": "(C)while defending ones homeland",
        "d": "(D)to save others",
        "correct": "D",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Today perhaps your only association with the word \\'polio\\' is the Sabin Oral Vaccine that protects children from the disease. Fifty five years ago this was not so. The dreaded disease, which mainly affects the brain ans spinal cord, causing stiffening and weakening of muscles, crippling and paralysis - which is Why I am in a wheelchair today. If somebody had predicted, when I was born, that this would happen to me, no one would have believed it. I was seventh child in a family of four pairs of brothers and sisters, with huge 23 year gap between the first and last. I was so fair and brown haired that I looked more look like a foreigner than a Dawood Bohri. I was also considered to be the healthiest of the brood.\nIn his childhood, the narrator was",
        "a": "(A)a weakling",
        "b": "(B)very healthy",
        "c": "(C)tall and slim",
        "d": "(D)short and stout",
        "correct": "B",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Today perhaps your only association with the word \\'polio\\' is the Sabin Oral Vaccine that protects children from the disease. Fifty five years ago this was not so. The dreaded disease, which mainly affects the brain ans spinal cord, causing stiffening and weakening of muscles, crippling and paralysis - which is Why I am in a wheelchair today. If somebody had predicted, when I was born, that this would happen to me, no one would have believed it. I was seventh child in a family of four pairs of brothers and sisters, with huge 23 year gap between the first and last. I was so fair and brown haired that I looked more look like a foreigner than a Dawood Bohri. I was also considered to be the healthiest of the brood.\nIn this passage, the word 'brood' refers to",
        "a": "(A)polio victims",
        "b": "(B)foreign children",
        "c": "(C)children in the family",
        "d": "(D)Indian Children",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Today perhaps your only association with the word \\'polio\\' is the Sabin Oral Vaccine that protects children from the disease. Fifty five years ago this was not so. The dreaded disease, which mainly affects the brain ans spinal cord, causing stiffening and weakening of muscles, crippling and paralysis - which is Why I am in a wheelchair today. If somebody had predicted, when I was born, that this would happen to me, no one would have believed it. I was seventh child in a family of four pairs of brothers and sisters, with huge 23 year gap between the first and last. I was so fair and brown haired that I looked more look like a foreigner than a Dawood Bohri. I was also considered to be the healthiest of the brood.\nThe narrator was the seventh child in a family of",
        "a": "(A)8 children",
        "b": "(B)16 children",
        "c": "(C)23 children",
        "d": "(D)4 children",
        "correct": "A",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Today perhaps your only association with the word \\'polio\\' is the Sabin Oral Vaccine that protects children from the disease. Fifty five years ago this was not so. The dreaded disease, which mainly affects the brain ans spinal cord, causing stiffening and weakening of muscles, crippling and paralysis - which is Why I am in a wheelchair today. If somebody had predicted, when I was born, that this would happen to me, no one would have believed it. I was seventh child in a family of four pairs of brothers and sisters, with huge 23 year gap between the first and last. I was so fair and brown haired that I looked more look like a foreigner than a Dawood Bohri. I was also considered to be the healthiest of the brood.\nIn this passage, the narrator is a patient of",
        "a": "(A)heart disease",
        "b": "(B)polio",
        "c": "(C)paralysis",
        "d": "(D)nervous weakness",
        "correct": "B",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Today perhaps your only association with the word \\'polio\\' is the Sabin Oral Vaccine that protects children from the disease. Fifty five years ago this was not so. The dreaded disease, which mainly affects the brain ans spinal cord, causing stiffening and weakening of muscles, crippling and paralysis - which is Why I am in a wheelchair today. If somebody had predicted, when I was born, that this would happen to me, no one would have believed it. I was seventh child in a family of four pairs of brothers and sisters, with huge 23 year gap between the first and last. I was so fair and brown haired that I looked more look like a foreigner than a Dawood Bohri. I was also considered to be the healthiest of the brood.\nIn his childhood, the narrator looked \"more like a foreigner than a Dawood Bohri\" This was because he was",
        "a": "(A)a foreign child",
        "b": "(B)a very healthy boy",
        "c": "(C)tell and smart",
        "d": "(D)fair and brown haired",
        "correct": "D",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Piccadilly Circus was full of loneliness.It seethes and echoes with it. To live near it. Looking down on it is a discomforting exercise. You can\\'t feel the pulse of London here, though people expect to. To Londoners it is a maddening obstruction between one place and another, and few voluntarily linger there. The only locals are those who live off the lingerers; the lingerers are primarily sightseers, with a fair sprinkling of people hoping to draw attention to themselves - both typically from the provinces. They have come to see the heart of London and expect to see spectacle, glamour and vice.\nPiccadilly circus is",
        "a": "(A)the name of a circus company",
        "b": "(B)a lonely and resounding old building",
        "c": "(C)a centrally located area in London",
        "d": "(D)a huge heap of ruins",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Piccadilly Circus was full of loneliness.It seethes and echoes with it. To live near it. Looking down on it is a discomforting exercise. You can\\'t feel the pulse of London here, though people expect to. To Londoners it is a maddening obstruction between one place and another, and few voluntarily linger there. The only locals are those who live off the lingerers; the lingerers are primarily sightseers, with a fair sprinkling of people hoping to draw attention to themselves - both typically from the provinces. They have come to see the heart of London and expect to see spectacle, glamour and vice.\nThe passage implies that",
        "a": "(A)some Londoners love to spend their time near the Piccadilly circus",
        "b": "(B)no Londoner wants to be in Piccadilly circus",
        "c": "(C)Piccadilly circus is a hazardous place",
        "d": "(D)Piccadilly circus is place of vice",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Piccadilly Circus was full of loneliness.It seethes and echoes with it. To live near it. Looking down on it is a discomforting exercise. You can\\'t feel the pulse of London here, though people expect to. To Londoners it is a maddening obstruction between one place and another, and few voluntarily linger there. The only locals are those who live off the lingerers; the lingerers are primarily sightseers, with a fair sprinkling of people hoping to draw attention to themselves - both typically from the provinces. They have come to see the heart of London and expect to see spectacle, glamour and vice.\nAccording to this passage, people from outside London go to Piccadilly circus because it is",
        "a": "(A)a historical place",
        "b": "(B)full of glamour",
        "c": "(C)full of exciting people",
        "d": "(D)the pulse of London",
        "correct": "B",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Piccadilly Circus was full of loneliness.It seethes and echoes with it. To live near it. Looking down on it is a discomforting exercise. You can\\'t feel the pulse of London here, though people expect to. To Londoners it is a maddening obstruction between one place and another, and few voluntarily linger there. The only locals are those who live off the lingerers; the lingerers are primarily sightseers, with a fair sprinkling of people hoping to draw attention to themselves - both typically from the provinces. They have come to see the heart of London and expect to see spectacle, glamour and vice.\nFor those who live near Piccadilly circus, it is",
        "a": "(A)a very noisy place",
        "b": "(B)crowded with people",
        "c": "(C)an obstruction to traffic",
        "d": "(D)an awkward structure",
        "correct": "C",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    },
    {
        "qtext": "Piccadilly Circus was full of loneliness.It seethes and echoes with it. To live near it. Looking down on it is a discomforting exercise. You can\\'t feel the pulse of London here, though people expect to. To Londoners it is a maddening obstruction between one place and another, and few voluntarily linger there. The only locals are those who live off the lingerers; the lingerers are primarily sightseers, with a fair sprinkling of people hoping to draw attention to themselves - both typically from the provinces. They have come to see the heart of London and expect to see spectacle, glamour and vice.\nThe lingerers found in Piccadilly circus are mainly",
        "a": "(A)the citizens of London",
        "b": "(B)sightseers from provincial areas of Britain",
        "c": "(C)people who want to show off",
        "d": "(D)local idlers",
        "correct": "B",
        "img": "",
        "topic": "Comprehension",
        "section": "(English)"
    }
    
]}
