{
  "data": [
    {
      "qtext": "Rearrange the following five sentences in proper sequence so as to for a meaningful paragraph, then answer the questions given below them.\nAfter Examining him, the doctor smiled at him mischievously and took out a syringe.\nThinking that he was really sick, his father summoned the family doctor.\nThat day, Mintu wanted to take a day off from school\nImmediately, Mintu jumped up from his bed and swore the he was fine\nTherefor; he pretended to be sick and remained in bed.\n\n<p>Which sentence should come <b>third</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence so as to for a meaningful paragraph, then answer the questions given below them.\nAfter Examining him, the doctor smiled at him mischievously and took out a syringe.\nThinking that he was really sick, his father summoned the family doctor.\nThat day, Mintu wanted to take a day off from school\nImmediately, Mintu jumped up from his bed and swore the he was fine\nTherefor; he pretended to be sick and remained in bed.\n\n<p>Which sentence should come <b>last</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence so as to for a meaningful paragraph, then answer the questions given below them.\nAfter Examining him, the doctor smiled at him mischievously and took out a syringe.\nThinking that he was really sick, his father summoned the family doctor.\nThat day, Mintu wanted to take a day off from school\nImmediately, Mintu jumped up from his bed and swore the he was fine\nTherefor; he pretended to be sick and remained in bed.\n\n<p>Which sentence should come <b>fourth</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence so as to for a meaningful paragraph, then answer the questions given below them.\nAfter Examining him, the doctor smiled at him mischievously and took out a syringe.\nThinking that he was really sick, his father summoned the family doctor.\nThat day, Mintu wanted to take a day off from school\nImmediately, Mintu jumped up from his bed and swore the he was fine\nTherefor; he pretended to be sick and remained in bed.\n\n<p>Which sentence should come <b>second</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence so as to for a meaningful paragraph, then answer the questions given below them.\nAfter Examining him, the doctor smiled at him mischievously and took out a syringe.\nThinking that he was really sick, his father summoned the family doctor.\nThat day, Mintu wanted to take a day off from school\nImmediately, Mintu jumped up from his bed and swore the he was fine\nTherefor; he pretended to be sick and remained in bed.\n\n<p>Which sentence should come <b>first</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Read the following five sentences and rearrange them to make a coherent and logical paragraph. After deciding the sequence, answer the questions given below.\nIn his literacy work he spoke of that province of human life which mere intellect does not speak.\nHe has also given innocent joy to many children by his stories like 'Kabuliwalah'\nThese songs are sung not only in bengal but all over the country.\nRabindranath's great works sprang from intensity of vision and feelings.\nHe sang of beauty and heroism, nobility and charm.\n\n<p>Which sentence should come <b>fourth</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Read the following five sentences and rearrange them to make a coherent and logical paragraph. After deciding the sequence, answer the questions given below.\nIn his literacy work he spoke of that province of human life which mere intellect does not speak.\nHe has also given innocent joy to many children by his stories like 'Kabuliwalah'\nThese songs are sung not only in bengal but all over the country.\nRabindranath's great works sprang from intensity of vision and feelings.\nHe sang of beauty and heroism, nobility and charm.\n\n<p>Which sentence should come <b>third</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Read the following five sentences and rearrange them to make a coherent and logical paragraph. After deciding the sequence, answer the questions given below.\nIn his literacy work he spoke of that province of human life which mere intellect does not speak.\nHe has also given innocent joy to many children by his stories like 'Kabuliwalah'\nThese songs are sung not only in bengal but all over the country.\nRabindranath's great works sprang from intensity of vision and feelings.\nHe sang of beauty and heroism, nobility and charm.\n\n<p>Which sentence should come <b>second</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Read the following five sentences and rearrange them to make a coherent and logical paragraph. After deciding the sequence, answer the questions given below.\nIn his literacy work he spoke of that province of human life which mere intellect does not speak.\nHe has also given innocent joy to many children by his stories like 'Kabuliwalah'\nThese songs are sung not only in bengal but all over the country.\nRabindranath's great works sprang from intensity of vision and feelings.\nHe sang of beauty and heroism, nobility and charm.\n\n<p>Which sentence should come <b>fifth</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Read the following five sentences and rearrange them to make a coherent and logical paragraph. After deciding the sequence, answer the questions given below.\nIn his literacy work he spoke of that province of human life which mere intellect does not speak.\nHe has also given innocent joy to many children by his stories like 'Kabuliwalah'\nThese songs are sung not only in bengal but all over the country.\nRabindranath's great works sprang from intensity of vision and feelings.\nHe sang of beauty and heroism, nobility and charm.\n\n<p>Which sentence should come <b>first</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Read the following five sentences in the proper sequence so as to form a meaningfull paragraph, then answer the questions given below them.\nI reached office at 11 O' clock after sending the money.\nSome money had to be sent to my parents.\nAfter that, I spent almost an hour at the Post Office.\nTherefore, I went to bank to withdraw some money.\nHowever, I had no money with me.\n\n<p>Which sentence should come <b>third</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Read the following five sentences in the proper sequence so as to form a meaningfull paragraph, then answer the questions given below them.\nI reached office at 11 O' clock after sending the money.\nSome money had to be sent to my parents.\nAfter that, I spent almost an hour at the Post Office.\nTherefore, I went to bank to withdraw some money.\nHowever, I had no money with me.\n\n<p>Which sentence should come <b>first</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Read the following five sentences in the proper sequence so as to form a meaningfull paragraph, then answer the questions given below them.\nI reached office at 11 O' clock after sending the money.\nSome money had to be sent to my parents.\nAfter that, I spent almost an hour at the Post Office.\nTherefore, I went to bank to withdraw some money.\nHowever, I had no money with me.\n\n<p>Which sentence should come <b>fifth</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Read the following five sentences in the proper sequence so as to form a meaningfull paragraph, then answer the questions given below them.\nI reached office at 11 O' clock after sending the money.\nSome money had to be sent to my parents.\nAfter that, I spent almost an hour at the Post Office.\nTherefore, I went to bank to withdraw some money.\nHowever, I had no money with me.\n\n<p>Which sentence should come <b>fourth</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Read the following five sentences in the proper sequence so as to form a meaningfull paragraph, then answer the questions given below them.\nI reached office at 11 O' clock after sending the money.\nSome money had to be sent to my parents.\nAfter that, I spent almost an hour at the Post Office.\nTherefore, I went to bank to withdraw some money.\nHowever, I had no money with me.\n\n<p>Which sentence should come <b>second</b> in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIn fact, it prevent us from helping children to analyse conflict, to learn to cope with it and counter it.\nChildren have always known that there is conflict in the adult world.\nHowever, the make-believe world that 19th century rationally imposed on childhood in Europe and which we impose in an institutionalised manner through our modern education system can hardly be described as related in this regard.\nWe may therefore conclude that conflict in an institutionalised manner is not a matter of faith in children's capacities, rather, it is a lack of faith in ourselves as adults.\nFurther, psychologists tell us and story tellers have always known that the child's desire to search for order and coherence gathers strength from the knowledge of conflict.\n\n<p>Which of the following should be the <b>fourth</b> sentence in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIn fact, it prevent us from helping children to analyse conflict, to learn to cope with it and counter it.\nChildren have always known that there is conflict in the adult world.\nHowever, the make-believe world that 19th century rationally imposed on childhood in Europe and which we impose in an institutionalised manner through our modern education system can hardly be described as related in this regard.\nWe may therefore conclude that conflict in an institutionalised manner is not a matter of faith in children's capacities, rather, it is a lack of faith in ourselves as adults.\nFurther, psychologists tell us and story tellers have always known that the child's desire to search for order and coherence gathers strength from the knowledge of conflict.\n\n<p>Which of the following should be the <b>last</b> sentence in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIn fact, it prevent us from helping children to analyse conflict, to learn to cope with it and counter it.\nChildren have always known that there is conflict in the adult world.\nHowever, the make-believe world that 19th century rationally imposed on childhood in Europe and which we impose in an institutionalised manner through our modern education system can hardly be described as related in this regard.\nWe may therefore conclude that conflict in an institutionalised manner is not a matter of faith in children's capacities, rather, it is a lack of faith in ourselves as adults.\nFurther, psychologists tell us and story tellers have always known that the child's desire to search for order and coherence gathers strength from the knowledge of conflict.\n\n<p>Which of the following should be the <b>third</b> sentence in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIn fact, it prevent us from helping children to analyse conflict, to learn to cope with it and counter it.\nChildren have always known that there is conflict in the adult world.\nHowever, the make-believe world that 19th century rationally imposed on childhood in Europe and which we impose in an institutionalised manner through our modern education system can hardly be described as related in this regard.\nWe may therefore conclude that conflict in an institutionalised manner is not a matter of faith in children's capacities, rather, it is a lack of faith in ourselves as adults.\nFurther, psychologists tell us and story tellers have always known that the child's desire to search for order and coherence gathers strength from the knowledge of conflict.\n\n<p>Which of the following should be the <b>second</b> sentence in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIn fact, it prevent us from helping children to analyse conflict, to learn to cope with it and counter it.\nChildren have always known that there is conflict in the adult world.\nHowever, the make-believe world that 19th century rationally imposed on childhood in Europe and which we impose in an institutionalised manner through our modern education system can hardly be described as related in this regard.\nWe may therefore conclude that conflict in an institutionalised manner is not a matter of faith in children's capacities, rather, it is a lack of faith in ourselves as adults.\nFurther, psychologists tell us and story tellers have always known that the child's desire to search for order and coherence gathers strength from the knowledge of conflict.\n\n<p>Which of the following should be the <b>first</b> sentence in the paragraph?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA case in point is the programme involving the Sardar Sarovar Dam which would displace about 2, 00, 000 people.\nCritics decry the fact that a major development institution appears to absorb more capital than it distributes to borrowers.\nFor all its faults critics however, concede that the bank remains a relatively efficient instrument for distribution of development-aid money.\nOne of the key complaint focuses on this non-profit bank's recent \"profitability\"\nAlthough the lives of millions of people around the globe have been improved by the bank's activities, it is now under fire.\nThe bank is also being blamed for large-scale involuntary resettlement to make way for dams and other construction projects.\n\n<p>Which sentence should come <b>sixth</b> in the paragraph?</p>",
      "a": "A. 5",
      "b": "B. 4",
      "c": "C. 2",
      "d": "D. 1",
      "e": "E. 3",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA case in point is the programme involving the Sardar Sarovar Dam which would displace about 2, 00, 000 people.\nCritics decry the fact that a major development institution appears to absorb more capital than it distributes to borrowers.\nFor all its faults critics however, concede that the bank remains a relatively efficient instrument for distribution of development-aid money.\nOne of the key complaint focuses on this non-profit bank's recent \"profitability\"\nAlthough the lives of millions of people around the globe have been improved by the bank's activities, it is now under fire.\nThe bank is also being blamed for large-scale involuntary resettlement to make way for dams and other construction projects.\n\n<p>Which sentence should come <b>third</b> in the paragraph?</p>",
      "a": "A. 2",
      "b": "B. 5",
      "c": "C. 1",
      "d": "D. 4",
      "e": "E. 6",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA case in point is the programme involving the Sardar Sarovar Dam which would displace about 2, 00, 000 people.\nCritics decry the fact that a major development institution appears to absorb more capital than it distributes to borrowers.\nFor all its faults critics however, concede that the bank remains a relatively efficient instrument for distribution of development-aid money.\nOne of the key complaint focuses on this non-profit bank's recent \"profitability\"\nAlthough the lives of millions of people around the globe have been improved by the bank's activities, it is now under fire.\nThe bank is also being blamed for large-scale involuntary resettlement to make way for dams and other construction projects.\n\n<p>Which sentence should come <b>second</b> in the paragraph?</p>",
      "a": "A. 3",
      "b": "B. 1",
      "c": "C. 4",
      "d": "D. 6",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA case in point is the programme involving the Sardar Sarovar Dam which would displace about 2, 00, 000 people.\nCritics decry the fact that a major development institution appears to absorb more capital than it distributes to borrowers.\nFor all its faults critics however, concede that the bank remains a relatively efficient instrument for distribution of development-aid money.\nOne of the key complaint focuses on this non-profit bank's recent \"profitability\"\nAlthough the lives of millions of people around the globe have been improved by the bank's activities, it is now under fire.\nThe bank is also being blamed for large-scale involuntary resettlement to make way for dams and other construction projects.\n\n<p>Which sentence should come <b>fourth</b> in the paragraph?</p>",
      "a": "A. 6",
      "b": "B. 3",
      "c": "C. 5",
      "d": "D. 2",
      "e": "E. 1",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA case in point is the programme involving the Sardar Sarovar Dam which would displace about 2, 00, 000 people.\nCritics decry the fact that a major development institution appears to absorb more capital than it distributes to borrowers.\nFor all its faults critics however, concede that the bank remains a relatively efficient instrument for distribution of development-aid money.\nOne of the key complaint focuses on this non-profit bank's recent \"profitability\"\nAlthough the lives of millions of people around the globe have been improved by the bank's activities, it is now under fire.\nThe bank is also being blamed for large-scale involuntary resettlement to make way for dams and other construction projects.\n\n<p>Which sentence should come <b>first</b> in the paragraph?</p>",
      "a": "A. 4",
      "b": "B. 6",
      "c": "C. 3",
      "d": "D. 2",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nChandrakanth was shocked when he realised that the leg had lost sensation.\nwhen he tried to get up, he felt his leg was very heavy.\nHe had to lie down hopelessly, till he saw a flash light\nIt was an odd night time and hence nobody heard his voice.\nDue to sudden sprain chandrakanth fell down.\nNervous with this realisation, he called out for help.\n\n<p>Which of the following should be the <b>third</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nChandrakanth was shocked when he realised that the leg had lost sensation.\nwhen he tried to get up, he felt his leg was very heavy.\nHe had to lie down hopelessly, till he saw a flash light\nIt was an odd night time and hence nobody heard his voice.\nDue to sudden sprain chandrakanth fell down.\nNervous with this realisation, he called out for help.\n\n<p>Which of the following should be the <b>first</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nChandrakanth was shocked when he realised that the leg had lost sensation.\nwhen he tried to get up, he felt his leg was very heavy.\nHe had to lie down hopelessly, till he saw a flash light\nIt was an odd night time and hence nobody heard his voice.\nDue to sudden sprain chandrakanth fell down.\nNervous with this realisation, he called out for help.\n\n<p>Which of the following should be the <b>second</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nChandrakanth was shocked when he realised that the leg had lost sensation.\nwhen he tried to get up, he felt his leg was very heavy.\nHe had to lie down hopelessly, till he saw a flash light\nIt was an odd night time and hence nobody heard his voice.\nDue to sudden sprain chandrakanth fell down.\nNervous with this realisation, he called out for help.\n\n<p>Which of the following should be the <b>sixth</b> sentence ?</p>",
      "a": "A. 6",
      "b": "B. 5",
      "c": "C. 4",
      "d": "D. 3",
      "e": "E. 2",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nChandrakanth was shocked when he realised that the leg had lost sensation.\nwhen he tried to get up, he felt his leg was very heavy.\nHe had to lie down hopelessly, till he saw a flash light\nIt was an odd night time and hence nobody heard his voice.\nDue to sudden sprain chandrakanth fell down.\nNervous with this realisation, he called out for help.\n\n<p>Which of the following should be the <b>fourth</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 6",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nThe history of mankind is full of such fightings between communities, nations and people.\nFrom the primitive weapon of warfare, man has advanced to the modern nuclear weapons.\nEver since the dawn of civilisation man has been fighting with man.\nA modern war is scientific in character, but the effect is the same wiping human existence out of this earth.\nThe only difference now seems to be in the efficiency of the instruments used for killing each other.\n\n<p>Which of the following should be the <b>first</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nThe history of mankind is full of such fightings between communities, nations and people.\nFrom the primitive weapon of warfare, man has advanced to the modern nuclear weapons.\nEver since the dawn of civilisation man has been fighting with man.\nA modern war is scientific in character, but the effect is the same wiping human existence out of this earth.\nThe only difference now seems to be in the efficiency of the instruments used for killing each other.\n\n<p>Which of the following should be the <b>second</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nThe history of mankind is full of such fightings between communities, nations and people.\nFrom the primitive weapon of warfare, man has advanced to the modern nuclear weapons.\nEver since the dawn of civilisation man has been fighting with man.\nA modern war is scientific in character, but the effect is the same wiping human existence out of this earth.\nThe only difference now seems to be in the efficiency of the instruments used for killing each other.\n\n<p>Which of the following should be the <b>fourth</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nThe history of mankind is full of such fightings between communities, nations and people.\nFrom the primitive weapon of warfare, man has advanced to the modern nuclear weapons.\nEver since the dawn of civilisation man has been fighting with man.\nA modern war is scientific in character, but the effect is the same wiping human existence out of this earth.\nThe only difference now seems to be in the efficiency of the instruments used for killing each other.\n\n<p>Which of the following should be the <b>third</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nThe history of mankind is full of such fightings between communities, nations and people.\nFrom the primitive weapon of warfare, man has advanced to the modern nuclear weapons.\nEver since the dawn of civilisation man has been fighting with man.\nA modern war is scientific in character, but the effect is the same wiping human existence out of this earth.\nThe only difference now seems to be in the efficiency of the instruments used for killing each other.\n\n<p>Which of the following should be the <b>fifth</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIts current was very powerful and could take away big tree trunks.\nThere were some children, playing on the bank of waterway\nIn the forest of Madhubani, there is big lake.\nThe excess water started flowing forcefully through the waterway.\nOnce there was a very heavy rain because of which the lake started overflowing.\nA poor man noticed it and rushed to save them.\n\n<p>Which of the following should be the <b>third</b> sentence ?</p>",
      "a": "A. 6",
      "b": "B. 5",
      "c": "C. 4",
      "d": "D. 3",
      "e": "E. 2",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIts current was very powerful and could take away big tree trunks.\nThere were some children, playing on the bank of waterway\nIn the forest of Madhubani, there is big lake.\nThe excess water started flowing forcefully through the waterway.\nOnce there was a very heavy rain because of which the lake started overflowing.\nA poor man noticed it and rushed to save them.\n\n<p>Which of the following should be the <b>first</b> sentence ?</p>",
      "a": "A. 6",
      "b": "B. 5",
      "c": "C. 4",
      "d": "D. 3",
      "e": "E. 2",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIts current was very powerful and could take away big tree trunks.\nThere were some children, playing on the bank of waterway\nIn the forest of Madhubani, there is big lake.\nThe excess water started flowing forcefully through the waterway.\nOnce there was a very heavy rain because of which the lake started overflowing.\nA poor man noticed it and rushed to save them.\n\n<p>Which of the following should be the <b>sixth</b> sentence ?</p>",
      "a": "A. 6",
      "b": "B. 5",
      "c": "C. 4",
      "d": "D. 3",
      "e": "E. 2",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIts current was very powerful and could take away big tree trunks.\nThere were some children, playing on the bank of waterway\nIn the forest of Madhubani, there is big lake.\nThe excess water started flowing forcefully through the waterway.\nOnce there was a very heavy rain because of which the lake started overflowing.\nA poor man noticed it and rushed to save them.\n\n<p>Which of the following should be the <b>fourth</b> sentence ?</p>",
      "a": "A. 5",
      "b": "B. 4",
      "c": "C. 3",
      "d": "D. 2",
      "e": "E. 1",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIts current was very powerful and could take away big tree trunks.\nThere were some children, playing on the bank of waterway\nIn the forest of Madhubani, there is big lake.\nThe excess water started flowing forcefully through the waterway.\nOnce there was a very heavy rain because of which the lake started overflowing.\nA poor man noticed it and rushed to save them.\n\n<p>Which of the following should be the <b>second</b> sentence ?</p>",
      "a": "A. 6",
      "b": "B. 5",
      "c": "C. 4",
      "d": "D. 3",
      "e": "E. 2",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nThe means and methods they employ to deal with public pressures are also different.\nThey will make no move unless the gallery is packed.\nThe poorest are over-hesitant, evasive and preoccupied with their relationships with others.\nEnourmous difference is generally observed in the ways in which various public officials respond to public pressures.\nThe best possess understanding of forces that must be taken in to account, determination not to be swerved from the path of public interest.\nThey confront all embarrassments with a state general formula.\n\n<p>Which of the following should be the <b>first</b> sentence ?</p>",
      "a": "A. 6",
      "b": "B. 5",
      "c": "C. 4",
      "d": "D. 3",
      "e": "E. 2",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nThe means and methods they employ to deal with public pressures are also different.\nThey will make no move unless the gallery is packed.\nThe poorest are over-hesitant, evasive and preoccupied with their relationships with others.\nEnourmous difference is generally observed in the ways in which various public officials respond to public pressures.\nThe best possess understanding of forces that must be taken in to account, determination not to be swerved from the path of public interest.\nThey confront all embarrassments with a state general formula.\n\n<p>Which of the following should be the <b>sixth</b> sentence ?</p>",
      "a": "A. 2",
      "b": "B. 3",
      "c": "C. 4",
      "d": "D. 5",
      "e": "E. 6",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nThe means and methods they employ to deal with public pressures are also different.\nThey will make no move unless the gallery is packed.\nThe poorest are over-hesitant, evasive and preoccupied with their relationships with others.\nEnourmous difference is generally observed in the ways in which various public officials respond to public pressures.\nThe best possess understanding of forces that must be taken in to account, determination not to be swerved from the path of public interest.\nThey confront all embarrassments with a state general formula.\n\n<p>Which of the following should be the <b>fourth</b> sentence ?</p>",
      "a": "A. 2",
      "b": "B. 3",
      "c": "C. 4",
      "d": "D. 5",
      "e": "E. 6",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nThe means and methods they employ to deal with public pressures are also different.\nThey will make no move unless the gallery is packed.\nThe poorest are over-hesitant, evasive and preoccupied with their relationships with others.\nEnourmous difference is generally observed in the ways in which various public officials respond to public pressures.\nThe best possess understanding of forces that must be taken in to account, determination not to be swerved from the path of public interest.\nThey confront all embarrassments with a state general formula.\n\n<p>Which of the following should be the <b>third</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nThe means and methods they employ to deal with public pressures are also different.\nThey will make no move unless the gallery is packed.\nThe poorest are over-hesitant, evasive and preoccupied with their relationships with others.\nEnourmous difference is generally observed in the ways in which various public officials respond to public pressures.\nThe best possess understanding of forces that must be taken in to account, determination not to be swerved from the path of public interest.\nThey confront all embarrassments with a state general formula.\n\n<p>Which of the following should be the <b>second</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nBut, we all helped in the first few days.\nChandrapur is considered as a rural area.\nManohar was transferred to his office recently.\nInitially he was not getting adjusted to the city life.\nNow, Manohar is very proud of his colleagues.\nBefore that he was working in chandrapur branch of our office.\n\n<p>Which of the following should be the <b>sixth</b> sentence ?</p>",
      "a": "A. 3",
      "b": "B. 4",
      "c": "C. 5",
      "d": "D. 6",
      "e": "E. 1",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nBut, we all helped in the first few days.\nChandrapur is considered as a rural area.\nManohar was transferred to his office recently.\nInitially he was not getting adjusted to the city life.\nNow, Manohar is very proud of his colleagues.\nBefore that he was working in chandrapur branch of our office.\n\n<p>Which of the following should be the <b>fourth</b> sentence ?</p>",
      "a": "A. 3",
      "b": "B. 4",
      "c": "C. 5",
      "d": "D. 6",
      "e": "E. 1",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nBut, we all helped in the first few days.\nChandrapur is considered as a rural area.\nManohar was transferred to his office recently.\nInitially he was not getting adjusted to the city life.\nNow, Manohar is very proud of his colleagues.\nBefore that he was working in chandrapur branch of our office.\n\n<p>Which of the following should be the <b>third</b> sentence ?</p>",
      "a": "A. 5",
      "b": "B. 6",
      "c": "C. 1",
      "d": "D. 2",
      "e": "E. 3",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nBut, we all helped in the first few days.\nChandrapur is considered as a rural area.\nManohar was transferred to his office recently.\nInitially he was not getting adjusted to the city life.\nNow, Manohar is very proud of his colleagues.\nBefore that he was working in chandrapur branch of our office.\n\n<p>Which of the following should be the <b>second</b> sentence ?</p>",
      "a": "A. 2",
      "b": "B. 3",
      "c": "C. 4",
      "d": "D. 5",
      "e": "E. 6",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nBut, we all helped in the first few days.\nChandrapur is considered as a rural area.\nManohar was transferred to his office recently.\nInitially he was not getting adjusted to the city life.\nNow, Manohar is very proud of his colleagues.\nBefore that he was working in chandrapur branch of our office.\n\n<p>Which of the following should be the <b>first</b> sentence ?</p>",
      "a": "A. 3",
      "b": "B. 4",
      "c": "C. 5",
      "d": "D. 6",
      "e": "E. 1",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIndeed, the mutations that the family has undergone in this century have been more challenging than at any time of its evolution.\nThus, we have nuclear families, single parent families, surrogate families and global families to name just a few.\nHow these changes have reduced our world view is an interesting field of study in themselves.\nWhat we often forget is that the family as it exists today has expanded its orthodox definition to include several variations.\nEach of these has brought it own attitudes and priorities.\n\n<p>Which sentence should come <b>fourth</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIndeed, the mutations that the family has undergone in this century have been more challenging than at any time of its evolution.\nThus, we have nuclear families, single parent families, surrogate families and global families to name just a few.\nHow these changes have reduced our world view is an interesting field of study in themselves.\nWhat we often forget is that the family as it exists today has expanded its orthodox definition to include several variations.\nEach of these has brought it own attitudes and priorities.\n\n<p>Which sentence should come <b>second</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIndeed, the mutations that the family has undergone in this century have been more challenging than at any time of its evolution.\nThus, we have nuclear families, single parent families, surrogate families and global families to name just a few.\nHow these changes have reduced our world view is an interesting field of study in themselves.\nWhat we often forget is that the family as it exists today has expanded its orthodox definition to include several variations.\nEach of these has brought it own attitudes and priorities.\n\n<p>Which sentence should come <b>fifth</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIndeed, the mutations that the family has undergone in this century have been more challenging than at any time of its evolution.\nThus, we have nuclear families, single parent families, surrogate families and global families to name just a few.\nHow these changes have reduced our world view is an interesting field of study in themselves.\nWhat we often forget is that the family as it exists today has expanded its orthodox definition to include several variations.\nEach of these has brought it own attitudes and priorities.\n\n<p>Which sentence should come <b>first</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nIndeed, the mutations that the family has undergone in this century have been more challenging than at any time of its evolution.\nThus, we have nuclear families, single parent families, surrogate families and global families to name just a few.\nHow these changes have reduced our world view is an interesting field of study in themselves.\nWhat we often forget is that the family as it exists today has expanded its orthodox definition to include several variations.\nEach of these has brought it own attitudes and priorities.\n\n<p>Which sentence should come <b>third</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nBut by then it was too late to correct things.\nIt is impossible to steer such a large project to success without planning.\nHe had to standby and watch helplessly.\nThe whole scheme was destined, to fail from the beginning.\nBhaskar started realising this only towards the end.\n\n<p>Which sentence should come <b>first</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nBut by then it was too late to correct things.\nIt is impossible to steer such a large project to success without planning.\nHe had to standby and watch helplessly.\nThe whole scheme was destined, to fail from the beginning.\nBhaskar started realising this only towards the end.\n\n<p>Which sentence should come <b>fifth</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nBut by then it was too late to correct things.\nIt is impossible to steer such a large project to success without planning.\nHe had to standby and watch helplessly.\nThe whole scheme was destined, to fail from the beginning.\nBhaskar started realising this only towards the end.\n\n<p>Which sentence should come <b>third</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nBut by then it was too late to correct things.\nIt is impossible to steer such a large project to success without planning.\nHe had to standby and watch helplessly.\nThe whole scheme was destined, to fail from the beginning.\nBhaskar started realising this only towards the end.\n\n<p>Which sentence should come <b>second</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nBut by then it was too late to correct things.\nIt is impossible to steer such a large project to success without planning.\nHe had to standby and watch helplessly.\nThe whole scheme was destined, to fail from the beginning.\nBhaskar started realising this only towards the end.\n\n<p>Which sentence should come <b>fourth</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nWould you steal a software programme out of retail shop?\nThe industry on its part has formed an organisation to specially gather information, educate and drag and software pirates to courts.\nBut more than the legality, there is always a different way of looking at piracy and that is in terms of morality.\nThe Government on the other hand has initiated National Enforcements Committees.\nAs far as the issue of tackling piracy is concerned, both the industry and government have already started initiating action.\n\n<p>Which of the following should be the <b>fourth</b> sentence ?</p>",
      "a": "A. 5",
      "b": "B. 1",
      "c": "C. 2",
      "d": "D. 4",
      "e": "E. 3",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nWould you steal a software programme out of retail shop?\nThe industry on its part has formed an organisation to specially gather information, educate and drag and software pirates to courts.\nBut more than the legality, there is always a different way of looking at piracy and that is in terms of morality.\nThe Government on the other hand has initiated National Enforcements Committees.\nAs far as the issue of tackling piracy is concerned, both the industry and government have already started initiating action.\n\n<p>Which of the following should be the <b>fifth</b> sentence ?</p>",
      "a": "A. 1",
      "b": "B. 4",
      "c": "C. 3",
      "d": "D. 5",
      "e": "E. 2",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nWould you steal a software programme out of retail shop?\nThe industry on its part has formed an organisation to specially gather information, educate and drag and software pirates to courts.\nBut more than the legality, there is always a different way of looking at piracy and that is in terms of morality.\nThe Government on the other hand has initiated National Enforcements Committees.\nAs far as the issue of tackling piracy is concerned, both the industry and government have already started initiating action.\n\n<p>Which of the following should be the <b>first</b> sentence ?</p>",
      "a": "A. 3",
      "b": "B. 2",
      "c": "C. 5",
      "d": "D. 1",
      "e": "E. 4",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nWould you steal a software programme out of retail shop?\nThe industry on its part has formed an organisation to specially gather information, educate and drag and software pirates to courts.\nBut more than the legality, there is always a different way of looking at piracy and that is in terms of morality.\nThe Government on the other hand has initiated National Enforcements Committees.\nAs far as the issue of tackling piracy is concerned, both the industry and government have already started initiating action.\n\n<p>Which of the following should be the <b>third</b> sentence ?</p>",
      "a": "A. 2",
      "b": "B. 3",
      "c": "C. 1",
      "d": "D. 5",
      "e": "E. 4",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nWould you steal a software programme out of retail shop?\nThe industry on its part has formed an organisation to specially gather information, educate and drag and software pirates to courts.\nBut more than the legality, there is always a different way of looking at piracy and that is in terms of morality.\nThe Government on the other hand has initiated National Enforcements Committees.\nAs far as the issue of tackling piracy is concerned, both the industry and government have already started initiating action.\n\n<p>Which of the following should be the <b>second</b> sentence ?</p>",
      "a": "A. 4",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 1",
      "e": "E. 5",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nJohn did not have the money to buy the beautiful clip.\nAfter a while, Jane explained to John that she had sold her hair to buy a gold chain for his watch.\nAs it was Christmas, john want to give Jane a surprise present.\nWhen Jane saw it, she felt like crying.\nHe decided to present her a clip made of ivory for her long flowing hair.\nHe, therefore sold off his watch and brought home the present.\n\n<p>Which of the sentences should come <b>sixth</b> in the paragraph ?</p>",
      "a": "A. 5",
      "b": "B. 4",
      "c": "C. 1",
      "d": "D. 3",
      "e": "E. 2",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nJohn did not have the money to buy the beautiful clip.\nAfter a while, Jane explained to John that she had sold her hair to buy a gold chain for his watch.\nAs it was Christmas, john want to give Jane a surprise present.\nWhen Jane saw it, she felt like crying.\nHe decided to present her a clip made of ivory for her long flowing hair.\nHe, therefore sold off his watch and brought home the present.\n\n<p>Which of the sentences should come <b>first</b> in the paragraph ?</p>",
      "a": "A. 3",
      "b": "B. 6",
      "c": "C. 2",
      "d": "D. 5",
      "e": "E. 4",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nJohn did not have the money to buy the beautiful clip.\nAfter a while, Jane explained to John that she had sold her hair to buy a gold chain for his watch.\nAs it was Christmas, john want to give Jane a surprise present.\nWhen Jane saw it, she felt like crying.\nHe decided to present her a clip made of ivory for her long flowing hair.\nHe, therefore sold off his watch and brought home the present.\n\n<p>Which of the sentences should come <b>second</b> in the paragraph ?</p>",
      "a": "A. 6",
      "b": "B. 1",
      "c": "C. 5",
      "d": "D. 4",
      "e": "E. 3",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nJohn did not have the money to buy the beautiful clip.\nAfter a while, Jane explained to John that she had sold her hair to buy a gold chain for his watch.\nAs it was Christmas, john want to give Jane a surprise present.\nWhen Jane saw it, she felt like crying.\nHe decided to present her a clip made of ivory for her long flowing hair.\nHe, therefore sold off his watch and brought home the present.\n\n<p>Which of the sentences should come <b>third</b> in the paragraph ?</p>",
      "a": "A. 4",
      "b": "B. 5",
      "c": "C. 6",
      "d": "D. 2",
      "e": "E. 1",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nJohn did not have the money to buy the beautiful clip.\nAfter a while, Jane explained to John that she had sold her hair to buy a gold chain for his watch.\nAs it was Christmas, john want to give Jane a surprise present.\nWhen Jane saw it, she felt like crying.\nHe decided to present her a clip made of ivory for her long flowing hair.\nHe, therefore sold off his watch and brought home the present.\n\n<p>Which of the sentences should come <b>fourth</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 6",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA Study to this effects suggests that the average white-collar worker demonstrates only about 25% listening efficiency.\nHowever for trained and good listeners it is not unusual to use all the three approaches during a setting, thus improving listening efficiency.\nThere are three approaches to listening: Listening for comprehension, Listening for empathy and Listening for evaluation.\nAlthough we spend nearly half of each communication interaction listening, we do not listen well.\nEach approach has a particular emphasis that may help us to receive and process informationin different settings.\n\n<p>Which of the sentences should come <b>second</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA Study to this effects suggests that the average white-collar worker demonstrates only about 25% listening efficiency.\nHowever for trained and good listeners it is not unusual to use all the three approaches during a setting, thus improving listening efficiency.\nThere are three approaches to listening: Listening for comprehension, Listening for empathy and Listening for evaluation.\nAlthough we spend nearly half of each communication interaction listening, we do not listen well.\nEach approach has a particular emphasis that may help us to receive and process informationin different settings.\n\n<p>Which of the sentences should come <b>fourth</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA Study to this effects suggests that the average white-collar worker demonstrates only about 25% listening efficiency.\nHowever for trained and good listeners it is not unusual to use all the three approaches during a setting, thus improving listening efficiency.\nThere are three approaches to listening: Listening for comprehension, Listening for empathy and Listening for evaluation.\nAlthough we spend nearly half of each communication interaction listening, we do not listen well.\nEach approach has a particular emphasis that may help us to receive and process informationin different settings.\n\n<p>Which of the sentences should come <b>fifth</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA Study to this effects suggests that the average white-collar worker demonstrates only about 25% listening efficiency.\nHowever for trained and good listeners it is not unusual to use all the three approaches during a setting, thus improving listening efficiency.\nThere are three approaches to listening: Listening for comprehension, Listening for empathy and Listening for evaluation.\nAlthough we spend nearly half of each communication interaction listening, we do not listen well.\nEach approach has a particular emphasis that may help us to receive and process informationin different settings.\n\n<p>Which of the sentences should come <b>third</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA Study to this effects suggests that the average white-collar worker demonstrates only about 25% listening efficiency.\nHowever for trained and good listeners it is not unusual to use all the three approaches during a setting, thus improving listening efficiency.\nThere are three approaches to listening: Listening for comprehension, Listening for empathy and Listening for evaluation.\nAlthough we spend nearly half of each communication interaction listening, we do not listen well.\nEach approach has a particular emphasis that may help us to receive and process informationin different settings.\n\n<p>Which of the sentences should come <b>first</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nKiran received a call to attend the interview.\nHe applied for a new job.\nKiran was an ambitious boy.\nBut, he was not happy there.\nHis father had put him in a clerical job.\n\n<p>Which of the sentences should come <b>first</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nKiran received a call to attend the interview.\nHe applied for a new job.\nKiran was an ambitious boy.\nBut, he was not happy there.\nHis father had put him in a clerical job.\n\n<p>Which of the sentences should come <b>third</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nKiran received a call to attend the interview.\nHe applied for a new job.\nKiran was an ambitious boy.\nBut, he was not happy there.\nHis father had put him in a clerical job.\n\n<p>Which of the sentences should come <b>fourth</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nKiran received a call to attend the interview.\nHe applied for a new job.\nKiran was an ambitious boy.\nBut, he was not happy there.\nHis father had put him in a clerical job.\n\n<p>Which of the sentences should come <b>second</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following five sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nKiran received a call to attend the interview.\nHe applied for a new job.\nKiran was an ambitious boy.\nBut, he was not happy there.\nHis father had put him in a clerical job.\n\n<p>Which of the sentences should come <b>fifth</b> in the paragraph ?</p>",
      "a": "A. 1",
      "b": "B. 2",
      "c": "C. 3",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA taxi was summoned and Venu was taken to Lifeline hospital.\nWhile hurrying home from school.\nsince they did not succeed, they decided to take him to a hospital.\nWhen Venu opened his eyes, he found himself surrounded by doctors and nurses.\nSome people rushed towards him and tried to bring him to his senses.\nHe was thrown a couple of feet away and lost consciousness.\n\n<p>Which of the sentences should come <b>first</b> in the paragraph ?</p>",
      "a": "A. 4",
      "b": "B. 6",
      "c": "C. 2",
      "d": "D. 5",
      "e": "E. 3",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA taxi was summoned and Venu was taken to Lifeline hospital.\nWhile hurrying home from school.\nsince they did not succeed, they decided to take him to a hospital.\nWhen Venu opened his eyes, he found himself surrounded by doctors and nurses.\nSome people rushed towards him and tried to bring him to his senses.\nHe was thrown a couple of feet away and lost consciousness.\n\n<p>Which of the sentences should come <b>fourth</b> in the paragraph ?</p>",
      "a": "A. 3",
      "b": "B. 5",
      "c": "C. 6",
      "d": "D. 2",
      "e": "E. 1",
      "correct": "A",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA taxi was summoned and Venu was taken to Lifeline hospital.\nWhile hurrying home from school.\nsince they did not succeed, they decided to take him to a hospital.\nWhen Venu opened his eyes, he found himself surrounded by doctors and nurses.\nSome people rushed towards him and tried to bring him to his senses.\nHe was thrown a couple of feet away and lost consciousness.\n\n<p>Which of the sentences should come <b>third</b> in the paragraph ?</p>",
      "a": "A. 6",
      "b": "B. 2",
      "c": "C. 5",
      "d": "D. 1",
      "e": "E. 4",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA taxi was summoned and Venu was taken to Lifeline hospital.\nWhile hurrying home from school.\nsince they did not succeed, they decided to take him to a hospital.\nWhen Venu opened his eyes, he found himself surrounded by doctors and nurses.\nSome people rushed towards him and tried to bring him to his senses.\nHe was thrown a couple of feet away and lost consciousness.\n\n<p>Which of the sentences should come <b>second</b> in the paragraph ?</p>",
      "a": "A. 5",
      "b": "B. 1",
      "c": "C. 4",
      "d": "D. 3",
      "e": "E. 6",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "Rearrange the following six sentences in proper sequence to form a meaningful paragraph, then answer the questions given below.\nA taxi was summoned and Venu was taken to Lifeline hospital.\nWhile hurrying home from school.\nsince they did not succeed, they decided to take him to a hospital.\nWhen Venu opened his eyes, he found himself surrounded by doctors and nurses.\nSome people rushed towards him and tried to bring him to his senses.\nHe was thrown a couple of feet away and lost consciousness.\n\n<p>Which of the sentences should come <b>sixth</b> in the paragraph ?</p>",
      "a": "A. 2",
      "b": "B. 3",
      "c": "C. 1",
      "d": "D. 4",
      "e": "E. 5",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "In each question rearrange the given sentences in proper sequence to form a meaningful paragraph; then, mark the correct sequence as answer.\n<p></p><ol class=\"En-Para-Formation\">\n<li>Participation involves more than the formal sharing of decisions.</li>\n<li>Through anticipation, individuals or organisations consider trends and make plans, shielding institutions from trauma of learning by shock.</li>\n<li>Innovative learning involves both anticipation and participation.</li>\n<li>It is an attitude characterised by cooperation, dialogue and empathy.</li>\n</ol><p></p>",
      "a": "A. 2314",
      "b": "B. 1243",
      "c": "C. 4132",
      "d": "D. 3214",
      "e": "E. 1324",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "In each question rearrange the given sentences in proper sequence to form a meaningful paragraph; then, mark the correct sequence as answer.\n<p></p><ol class=\"En-Para-Formation\">\n<li>Finally the bureaucratic organisation took over from the pioneering enterprise.</li>\n<li>The 19<sup>th</sup> century was the age of entrepreneur, the self-made man.</li>\n<li>Thoughtful business administration took over from action-centred business entrepreneurship.</li>\n<li>In the 20<sup>th</sup> century the rational executive took command.</li>\n</ol><p></p>",
      "a": "A. 4213",
      "b": "B. 3124",
      "c": "C. 2431",
      "d": "D. 2341",
      "e": "E. 4213",
      "correct": "D",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "In each question rearrange the given sentences in proper sequence to form a meaningful paragraph; then, mark the correct sequence as answer.\n<p></p><ol class=\"En-Para-Formation\">\n<li>However, different rulers and governments dealt with the different groups in a compartmentalised manner.</li>\n<li>Various situtatutional and political changes have taken place over the past three and half centuries.</li>\n<li>This tendency resulted in deeply embedded fragmented South African society which became even more prominent in the period 1948 until the new commencement of the new Constitution on May 10 1994.</li>\n<li>South Africa is a racially divided society since the first European settlers arrived in 1652.</li>\n</ol><p></p>",
      "a": "A. 2413",
      "b": "B. 4213",
      "c": "C. 3124",
      "d": "D. 1342",
      "e": "E. 2134",
      "correct": "B",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "In each question rearrange the given sentences in proper sequence to form a meaningful paragraph; then, mark the correct sequence as answer.\n<p></p><ol class=\"En-Para-Formation\">\n<li>Now under liberated economy they are learning to complete domestically and globally.</li>\n<li>In India corporations until recently achieved success by avoiding competition, using protected and regulated domestic markets.</li>\n<li>The trend is irreversible.</li>\n<li>Business leaders are preparing themselves to meet competitive challenges and to avoid being swept away.</li>\n</ol><p></p>",
      "a": "A. 1243",
      "b": "B. 2431",
      "c": "C. 2413",
      "d": "D. 3421",
      "e": "E. 2143",
      "correct": "E",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    },
    {
      "qtext": "In each question rearrange the given sentences in proper sequence to form a meaningful paragraph; then, mark the correct sequence as answer.\n<p></p><ol class=\"En-Para-Formation\">\n<li>Learn a kind of tenderness towards the vanity of others.</li>\n<li>And indeed towards all their prejudices.</li>\n<li>Who make a cult of sincerity.</li>\n<li>Men accustomed to difficult negotiations.</li>\n<li>Which is infinitely shocking to these. </li>\n</ol><p></p>",
      "a": "A. 43512",
      "b": "B. 34521",
      "c": "C. 41253",
      "d": "D. 34251",
      "e": "E. 43521",
      "correct": "C",
      "img": "",
      "topic": "Paragraph Formation",
      "section": "(English)"
    }
  ]
}
