{
"data":[
  {
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Fate smiles ...... those who untiringly grapple with stark realities of life.</p>",
    "a": "A. with",
    "b": "B. over",
    "c": "C. on",
    "d": "D. round",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The miser gazed ...... at the pile of gold coins in front of him.</p>",
    "a": "A. avidly",
    "b": "B. admiringly",
    "c": "C. thoughtfully",
    "d": "D. earnestly",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Catching the earlier train will give us the ...... to do some shopping.</p>",
    "a": "A. chance",
    "b": "B. luck",
    "c": "C. possibility",
    "d": "D. occasion",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I saw a ...... of cows in the field.</p>",
    "a": "A. group",
    "b": "B. herd",
    "c": "C. swarm",
    "d": "D. flock",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The grapes are now ...... enough to be picked.</p>",
    "a": "A. ready",
    "b": "B. mature",
    "c": "C. ripe",
    "d": "D. advanced",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Success in this examination depends ...... hard work alone.</p>",
    "a": "A. at",
    "b": "B. over",
    "c": "C. for",
    "d": "D. on",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>My uncle decided to take ...... and my sister to the market.</p>",
    "a": "A. I",
    "b": "B. mine",
    "c": "C. me",
    "d": "D. myself",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>If you smuggle goods into the country, they may be ...... by the customs authority.</p>",
    "a": "A. possessed",
    "b": "B. punished",
    "c": "C. confiscated",
    "d": "D. fined",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Man does not live by ...... alone.</p>",
    "a": "A. food",
    "b": "B. bread",
    "c": "C. meals",
    "d": "D. diet",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Piyush behaves strangely at times and, therefore, nobody gets ...... with him.</p>",
    "a": "A. about",
    "b": "B. through",
    "c": "C. along",
    "d": "D. up",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Rohan and Rohit are twin brothers, but they do not look ......</p>",
    "a": "A. unique",
    "b": "B. different",
    "c": "C. likely",
    "d": "D. alike",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>To err is ...... to forgive divine.</p>",
    "a": "A. beastly",
    "b": "B. human",
    "c": "C. inhuman",
    "d": "D. natural",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The ruling party will have to put its own house ...... order.</p>",
    "a": "A. in",
    "b": "B. on",
    "c": "C. to",
    "d": "D. into",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>...... of old paintings is a job for experts.</p>",
    "a": "A. Resurrection",
    "b": "B. Retrieval",
    "c": "C. Restoration",
    "d": "D. Resumption",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>During Diwali the shops are ...... of people.</p>",
    "a": "A. busy",
    "b": "B. full",
    "c": "C. crowded",
    "d": "D. bubbling",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The paths of glory lead ...... to the grave.</p>",
    "a": "A. straight",
    "b": "B. but",
    "c": "C. in",
    "d": "D. directly",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The telephone ...... several times before I answered it.</p>",
    "a": "A. was ringing",
    "b": "B. has rung",
    "c": "C. had rung",
    "d": "D. would ring",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He passed the examination in the first class because he ......</p>",
    "a": "A. was hard working for it",
    "b": "B. worked hardly for it",
    "c": "C. had worked hard for it",
    "d": "D. was working hard for it",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Jawaharlal spent his childhood ...... Anand Bhawan.</p>",
    "a": "A. at",
    "b": "B. in",
    "c": "C. on",
    "d": "D. across",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>If negotiations are to prove fruitful, there must not only be sincerity on each side, but there must also be ...... in the sincerity of the other side.</p>",
    "a": "A. faith",
    "b": "B. belief",
    "c": "C. substance",
    "d": "D. certainty",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I hate sitting ...... him as he always smells of garlic.</p>",
    "a": "A. besides",
    "b": "B. along",
    "c": "C. at",
    "d": "D. beside",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Some regions of our country still remain ...... to the average man.</p>",
    "a": "A. inaccessible",
    "b": "B. impossible",
    "c": "C. impermeable",
    "d": "D. impenetrable",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>It ...... that Prashant will not be selected for the post</p>",
    "a": "A. feels",
    "b": "B. looks",
    "c": "C. believes",
    "d": "D. seems",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>In Bush, Saddam was up ...... more than his match.</p>",
    "a": "A. for",
    "b": "B. into",
    "c": "C. against",
    "d": "D. to",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I haven't seen you ...... a week.</p>",
    "a": "A. within",
    "b": "B. since",
    "c": "C. for",
    "d": "D. from",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I listened, but I had no idea what he was ...... about.</p>",
    "a": "A. saying",
    "b": "B. talking",
    "c": "C. telling",
    "d": "D. discussing",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The car in which the minister was traveling ...... with an accident.</p>",
    "a": "A. hit",
    "b": "B. drove",
    "c": "C. crashed",
    "d": "D. met",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The non cooperative attitude of the members can only ...... the image of the society.</p>",
    "a": "A. spoil",
    "b": "B. improve",
    "c": "C. degrade",
    "d": "D. defame",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Sonika is quite intelligent but rather ......</p>",
    "a": "A. idealistic",
    "b": "B. generous",
    "c": "C. lazy",
    "d": "D. optimistic",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>In a little-publicised deal, Pepsi, Cola has ...... the entire soft drink market in Afghanistan.</p>",
    "a": "A. occupied",
    "b": "B. conquered",
    "c": "C. swallowed",
    "d": "D. captured",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He ...... in wearing the old fashioned coat in spite of his wife's disapproval.</p>",
    "a": "A. insists",
    "b": "B. persists",
    "c": "C. desists",
    "d": "D. resists",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>She ...... a brief appearance at the end of party.</p>",
    "a": "A. put on",
    "b": "B. put in",
    "c": "C. put across",
    "d": "D. put up",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Life is to death as pleasure is to ......</p>",
    "a": "A. poverty",
    "b": "B. suffering",
    "c": "C. anguish",
    "d": "D. pain",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>This, partly, explains how the Mehta family has been able to ...... its lavish lifestyle in recent times, despite the fact that all its assets have been ......</p>",
    "a": "A. keep, removed",
    "b": "B. afford, attached",
    "c": "C. develop, liquidated",
    "d": "D. keep up, destroyed",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The machine is difficult to build ...... easy to maintain.</p>",
    "a": "A. but",
    "b": "B. and",
    "c": "C. for",
    "d": "D. if",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>If you work beyond your capacity, you will naturally feel ......</p>",
    "a": "A. drowsy",
    "b": "B. tired",
    "c": "C. confident",
    "d": "D. giddy",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>If you persists in telling lies to me I shall sue you ...... slander.</p>",
    "a": "A. to",
    "b": "B. on",
    "c": "C. for",
    "d": "D. with",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>His father-in-law ...... him up in business.</p>",
    "a": "A. put",
    "b": "B. made",
    "c": "C. set",
    "d": "D. built",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>...... works of reference are valuable as Encyclopedia, Brittanica.</p>",
    "a": "A. A few",
    "b": "B. Few",
    "c": "C. The few",
    "d": "D. Fewer",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>This book is quite similar ......</p>",
    "a": "A. with the \"Treasure Island\"",
    "b": "B. of that film we saw at school",
    "c": "C. to the one I read last week",
    "d": "D. than a story told by our teacher",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>If our friends are not able to take us in their car, we must make ...... arrangements to go to the airport.</p>",
    "a": "A. alternative",
    "b": "B. another",
    "c": "C. alternate",
    "d": "D. possible",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>A crescendo of metallic thuds arose from the market, where the iron-smiths were ...... the pieces of metals.</p>",
    "a": "A. flattening",
    "b": "B. striking",
    "c": "C. hammering",
    "d": "D. thrashing",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I haven't eaten an apple ...... a long while.</p>",
    "a": "A. from",
    "b": "B. since",
    "c": "C. for",
    "d": "D. until",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The parliament invested the new organisation ...... judicial authority.</p>",
    "a": "A. by",
    "b": "B. with",
    "c": "C. from",
    "d": "D. through",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Owing to the power cut in the area, factories are being forced to ...... men</p>",
    "a": "A. throw away",
    "b": "B. send off",
    "c": "C. put off",
    "d": "D. lay off",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Man must ...... to stop pollution.</p>",
    "a": "A. act",
    "b": "B. perform",
    "c": "C. operate",
    "d": "D. behave",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He was sent to the prison for his ......</p>",
    "a": "A. sin",
    "b": "B. vice",
    "c": "C. crime",
    "d": "D. guilt",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The answer was written ...... blue ink.</p>",
    "a": "A. with",
    "b": "B. by",
    "c": "C. in",
    "d": "D. on",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Many ...... decisions were taken at the meeting.</p>",
    "a": "A. hectic",
    "b": "B. historic",
    "c": "C. historical",
    "d": "D. histrionic",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Those who persist in the endeavor at long last triumph ...... the odds of life.</p>",
    "a": "A. over",
    "b": "B. on",
    "c": "C. upon",
    "d": "D. about",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>In the modern materialistic society, the only aim of people appears to be ...... money by fair means or foul.</p>",
    "a": "A. print",
    "b": "B. produce",
    "c": "C. acquire",
    "d": "D. extort",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>What is the ...... for an air letter?</p>",
    "a": "A. fare",
    "b": "B. value",
    "c": "C. postage",
    "d": "D. stamp",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He became enamored ...... her grace when he first saw her dance.</p>",
    "a": "A. with",
    "b": "B. of",
    "c": "C. by",
    "d": "D. in",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Rama was so badly injured that he needed ...... care in the hospital.</p>",
    "a": "A. extensive",
    "b": "B. little",
    "c": "C. deep",
    "d": "D. intensive",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>You cannot devise a method which ...... all possibility of errors.</p>",
    "a": "A. excludes",
    "b": "B. includes",
    "c": "C. avoids",
    "d": "D. ignores",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Many areas of the city were ...... into darkness for several hours.</p>",
    "a": "A. spread",
    "b": "B. plunged",
    "c": "C. merged",
    "d": "D. deep",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Find the ...... that accompany these cartoons.</p>",
    "a": "A. topics",
    "b": "B. titles",
    "c": "C. captions",
    "d": "D. headings",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I don't really know how to ...... the problem.</p>",
    "a": "A. tackle",
    "b": "B. cope",
    "c": "C. draw",
    "d": "D. erase",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The English schemed to continue their rule in India by playing off one community ...... the other.</p>",
    "a": "A. before",
    "b": "B. upon",
    "c": "C. against",
    "d": "D. with",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The passengers were afraid, but the captain ...... them that there was no danger.</p>",
    "a": "A. promised",
    "b": "B. assured",
    "c": "C. advised",
    "d": "D. counselled",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The family gave father a gold watch on the ...... of his fiftieth birthday.</p>",
    "a": "A. time",
    "b": "B. event",
    "c": "C. occasion",
    "d": "D. celebration",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The park ...... as far as the river.</p>",
    "a": "A. extends",
    "b": "B. advances",
    "c": "C. enlarges",
    "d": "D. emerges",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Many of the advances of civilisation have been conceived by young people just on the ...... of adulthood</p>",
    "a": "A. boundary",
    "b": "B. threshold",
    "c": "C. peak",
    "d": "D. horizon",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Arti pulled a long ...... when she was told that she could not go to Agra.</p>",
    "a": "A. mouth",
    "b": "B. skirt",
    "c": "C. face",
    "d": "D. hand",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Brothers must live in harmony. They must never fall ......</p>",
    "a": "A. off",
    "b": "B. out",
    "c": "C. apart",
    "d": "D. away",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I was astounded at his ...... lack of knowledge about the Continent of Africa.</p>",
    "a": "A. abundant",
    "b": "B. colossal",
    "c": "C. huge",
    "d": "D. great",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Ayesha always ...... the permission of her father before going for movies.</p>",
    "a": "A. seeking",
    "b": "B. seeks",
    "c": "C. sought",
    "d": "D. seeker",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He felt no ...... as he plunged the knife into her back.</p>",
    "a": "A. qualms",
    "b": "B. scruple",
    "c": "C. conscience",
    "d": "D. morals",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>You haven't had your lunch yet, ...... you?</p>",
    "a": "A. are",
    "b": "B. aren't",
    "c": "C. have",
    "d": "D. haven't",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The manner in which bombs exploded in five trains with in a short span of time suggests that it is a part of a ......</p>",
    "a": "A. game",
    "b": "B. conspiracy",
    "c": "C. villainy",
    "d": "D. sabotage",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Wheat ...... carbohydrates, vitamins, proteins, and dietary fibre in our daily diet.</p>",
    "a": "A. has",
    "b": "B. gives",
    "c": "C. yields",
    "d": "D. provides",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The waiter hasn't brought the coffee ...... I've been here an hour already.</p>",
    "a": "A. till",
    "b": "B. up",
    "c": "C. yet",
    "d": "D. still",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>In our zeal for progress we should not ...... executive with more power.</p>",
    "a": "A. avoid",
    "b": "B. give",
    "c": "C. enhance",
    "d": "D. arm",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>You've only three months to complete the course, Don't give ...... now.</p>",
    "a": "A. out",
    "b": "B. away",
    "c": "C. up",
    "d": "D. off",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The traveler slept under the ...... shade of banyan tree.</p>",
    "a": "A. cold",
    "b": "B. cool",
    "c": "C. cooling",
    "d": "D. dark",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>She has an aversion ...... taking even onion and garlic.</p>",
    "a": "A. with",
    "b": "B. at",
    "c": "C. against",
    "d": "D. to",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The river overflowed its ...... and flooded the area.</p>",
    "a": "A. edges",
    "b": "B. fronts",
    "c": "C. limits",
    "d": "D. banks",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>...... The arrival of the police, nobody went near the victim.</p>",
    "a": "A. Unless",
    "b": "B. Although",
    "c": "C. Even",
    "d": "D. Till",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>When I was a child, I ......to school everyday instead going by cycle.</p>",
    "a": "A. had walked",
    "b": "B. walked",
    "c": "C. have walked",
    "d": "D. have been walking",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Farida sings very well and ...... does salim.</p>",
    "a": "A. even",
    "b": "B. too",
    "c": "C. also",
    "d": "D. so",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The old Nature versus ...... debate regarding crime continues even today.</p>",
    "a": "A. Man",
    "b": "B. Universe",
    "c": "C. Culture",
    "d": "D. Nurture",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The Sun ...... at six this morning.</p>",
    "a": "A. raised",
    "b": "B. rose",
    "c": "C. arose",
    "d": "D. aroused",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>That rule is applicable ...... every one.</p>",
    "a": "A. to",
    "b": "B. for",
    "c": "C. about",
    "d": "D. with",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Her parents will never give their ...... to so much an unsuitable match.</p>",
    "a": "A. acquiescence",
    "b": "B. consent",
    "c": "C. agreement",
    "d": "D. willingness",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He tried to ...... himself against a horde of ruffians.</p>",
    "a": "A. collect",
    "b": "B. save",
    "c": "C. support",
    "d": "D. defend",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>According to corporate circles data is pushing through the merger to create financially ...... company in the processed foods business, the group's thrust area for the 1990's</p>",
    "a": "A. acceptable",
    "b": "B. powerful",
    "c": "C. leading",
    "d": "D. straight",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Indeed, all over the world, more and more people are ...... coffee.</p>",
    "a": "A. wanting",
    "b": "B. drinking",
    "c": "C. liking",
    "d": "D. partaking",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Like any other country India has its ...... share of superstitions.</p>",
    "a": "A. proper",
    "b": "B. abundant",
    "c": "C. fair",
    "d": "D. peculiar",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The new education policy provides a useful ...... for the planners to remove illiteracy.</p>",
    "a": "A. breakup",
    "b": "B. breakthrough",
    "c": "C. breakaway",
    "d": "D. break-in",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>People who ...... on horses usually lose in the end.</p>",
    "a": "A. gamble",
    "b": "B. play",
    "c": "C. risk",
    "d": "D. place",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>About twenty clerks were made ...... when the banks introduced computers.</p>",
    "a": "A. dispensable",
    "b": "B. redundant",
    "c": "C. expandable",
    "d": "D. obsolete",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>After the rain the weather ...... and the sun came out.</p>",
    "a": "A. cleared out",
    "b": "B. cleared up",
    "c": "C. cleared away",
    "d": "D. cleared off",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The building comprises ...... sixty rooms.</p>",
    "a": "A. of",
    "b": "B. onto",
    "c": "C. by",
    "d": "D. no preposition needed",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Namrata was found to ...... the required qualifications for the job.</p>",
    "a": "A. contain",
    "b": "B. disclose",
    "c": "C. posses",
    "d": "D. acquire",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Government buildings are ...... on the Republic day.</p>",
    "a": "A. enlightened",
    "b": "B. lightened",
    "c": "C. illuminated",
    "d": "D. glowed",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>we had ...... wonderful time at the party last night.</p>",
    "a": "A. such a",
    "b": "B. so",
    "c": "C. such",
    "d": "D. very",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>An employment advertisement should ...... the number of vacancies.</p>",
    "a": "A. provide",
    "b": "B. specify",
    "c": "C. contain",
    "d": "D. declare",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>When varun left the cocktail party he was as ...... as a judge.</p>",
    "a": "A. sober",
    "b": "B. drunk",
    "c": "C. brave",
    "d": "D. wise",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The criminal seems to have acted in ...... the three others.</p>",
    "a": "A. collusion",
    "b": "B. coalition",
    "c": "C. collision",
    "d": "D. cohesion",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Soft minded individuals are ...... to embrace all kinds superstitions.</p>",
    "a": "A. disposed",
    "b": "B. eager",
    "c": "C. reluctant",
    "d": "D. prone",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The stenographer is very efficient. He is ...... to his firm.</p>",
    "a": "A. a boon",
    "b": "B. a credit",
    "c": "C. a blessing",
    "d": "D. an asset",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>However, the group's long-term strategy is to ...... on core sector business connected with infrastructure and energy.</p>",
    "a": "A. breed",
    "b": "B. develop",
    "c": "C. concentrate",
    "d": "D. depend",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The man came in a van to ...... the television set.</p>",
    "a": "A. mend",
    "b": "B. reform",
    "c": "C. correct",
    "d": "D. alter",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Nobody can ...... me to do anything which I do not want to do.</p>",
    "a": "A. encourage",
    "b": "B. request",
    "c": "C. oppose",
    "d": "D. compel",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>A sanguine outlook is associated with the ......</p>",
    "a": "A. rationalist",
    "b": "B. socialist",
    "c": "C. philanthropist",
    "d": "D. optimist",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>His conduct is bad, and his honesty is not ...... suspicion.</p>",
    "a": "A. above",
    "b": "B. beyond",
    "c": "C. under",
    "d": "D. in",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>It is 14 years since i ...... him.</p>",
    "a": "A. have seen",
    "b": "B. had seen",
    "c": "C. saw",
    "d": "D. see",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>It being an ...... issue, it is not correct to introduce questions of morality in to the debate.</p>",
    "a": "A. moral",
    "b": "B. immoral",
    "c": "C. amoral",
    "d": "D. irrelevant",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Natwarlal ...... them all for a ride by producing false documents.</p>",
    "a": "A. took",
    "b": "B. cheated",
    "c": "C. kept",
    "d": "D. let",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>True brevity ...... in saying only what needs to be said.</p>",
    "a": "A. consists",
    "b": "B. depicts",
    "c": "C. portrays",
    "d": "D. resides",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Health is too important to be ......</p>",
    "a": "A. discarded",
    "b": "B. despised",
    "c": "C. detested",
    "d": "D. neglected",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>In hot weather I like lying in the ...... of a tree.</p>",
    "a": "A. shade",
    "b": "B. shelter",
    "c": "C. protection",
    "d": "D. shadow",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>It was indeed unreasonable ...... him to leave this job and start business.</p>",
    "a": "A. in",
    "b": "B. with",
    "c": "C. upon",
    "d": "D. of",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>One major ...... between the Election Commission and the Union Government related to the powers of the former in respect of the deployment of central police forces at places where are elections is held.</p>",
    "a": "A. irritant",
    "b": "B. conflict",
    "c": "C. pain",
    "d": "D. culprit",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>We shall not to be able to use your ability in court unless we can find someone to ...... to statements.</p>",
    "a": "A. corroborate",
    "b": "B. avouch",
    "c": "C. verify",
    "d": "D. approve",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He is too dull ...... this problem.</p>",
    "a": "A. solving",
    "b": "B. to solving",
    "c": "C. to solve",
    "d": "D. solves",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He is the person who is ...... to blame.</p>",
    "a": "A. mostly",
    "b": "B. sure",
    "c": "C. most",
    "d": "D. bound",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>We had to pay more taxi fare because the driver brought us by a ...... route.</p>",
    "a": "A. circular",
    "b": "B. circumscribed",
    "c": "C. longest",
    "d": "D. circuitous",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He was accused ...... stealing his aunt's necklace.</p>",
    "a": "A. for",
    "b": "B. with",
    "c": "C. of",
    "d": "D. on",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He knew everything better than anybody else, and it was an affront to his ...... vanity that you should disagree with him.</p>",
    "a": "A. overstrung",
    "b": "B. overweening",
    "c": "C. overwhelming",
    "d": "D. overwrought",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>It's very kind of you to ...... to speak at the meeting.</p>",
    "a": "A. accept",
    "b": "B. agree",
    "c": "C. comply",
    "d": "D. concur",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Pakistan lost a ...... wicket just when they seemed to be doing so well, and that led to their eventual defeat.</p>",
    "a": "A. critical",
    "b": "B. crucial",
    "c": "C. sensitive",
    "d": "D. providential",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Sita's heart ...... at the sight of the beautiful diamond necklace.</p>",
    "a": "A. leapt",
    "b": "B. stopped",
    "c": "C. slowed",
    "d": "D. ran",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He lives near a lovely ...... of countryside.</p>",
    "a": "A. length",
    "b": "B. piece",
    "c": "C. section",
    "d": "D. stretch",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Ambition is one of those ......which are never satisfied.</p>",
    "a": "A. ideas",
    "b": "B. fancies",
    "c": "C. passions",
    "d": "D. feeds",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He is a person of sound character and ...... disposition.</p>",
    "a": "A. beneficent",
    "b": "B. morous",
    "c": "C. amiable",
    "d": "D. amicable",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>If I take a state roadways bus, I'll get late, ...... ?</p>",
    "a": "A. isn't it",
    "b": "B. won't I",
    "c": "C. will I",
    "d": "D. is it",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>In high school many of us never realised  the importance that grammar would ...... in later life.</p>",
    "a": "A. figure",
    "b": "B. portray",
    "c": "C. play",
    "d": "D. exercise",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>In a changing and ...... unstructured business environment, creativity and innovation are being ...... demanded of executives.</p>",
    "a": "A. highly, extremely",
    "b": "B. progressively, increasingly",
    "c": "C. increasingly, moderately",
    "d": "D. excessively, rapidly",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>On account of the dearth of grass on the arid plains the cattle became ......</p>",
    "a": "A. flippant",
    "b": "B. jubilant",
    "c": "C. agitated",
    "d": "D. emaciated",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>A woman came in with a baby who, she said, ...... a safety pin.</p>",
    "a": "A. was just swallowing",
    "b": "B. swallowed",
    "c": "C. had just swallowed",
    "d": "D. just swallowed",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The Hubble Space Telescope will search for planets around the stars, a key to the ...... extraterrestrial life, and examine interstellar dust and gases out of which stars are born.</p>",
    "a": "A. perception",
    "b": "B. discovery",
    "c": "C. enquiry",
    "d": "D. quest",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>She ...... Rs 80 out of the bank every Friday.</p>",
    "a": "A. obtains",
    "b": "B. draws",
    "c": "C. pulls",
    "d": "D. extracts",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The American ...... presented his credentials to the President of India.</p>",
    "a": "A. adviser",
    "b": "B. ambassador",
    "c": "C. delegate",
    "d": "D. representative",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Once he has signed the agreement, he won't be able to ......</p>",
    "a": "A. back up",
    "b": "B. back in",
    "c": "C. back at",
    "d": "D. back out",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>It was difficult to remove my feet as it had got stuck ...... in the mud.</p>",
    "a": "A. fairly",
    "b": "B. greatly",
    "c": "C. widely",
    "d": "D. firmly",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He is a very careful person, he never takes side but remains ......</p>",
    "a": "A. impartial",
    "b": "B. unbiased",
    "c": "C. neutral",
    "d": "D. prejudiced",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>West Bengal ...... plentiful rainfall and is consequently a very green part of the country.</p>",
    "a": "A. misses",
    "b": "B. receives",
    "c": "C. expects",
    "d": "D. regrets",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>this brand of TV is quite inferior ...... that one.</p>",
    "a": "A. than",
    "b": "B. to",
    "c": "C. with",
    "d": "D. over",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>It is not what you say that ...... but what you do</p>",
    "a": "A. matches",
    "b": "B. implies",
    "c": "C. matters",
    "d": "D. moves",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>'Please' and 'Thank you' are the little courtesies by which we keep the ...... of life oiled and running smoothly.</p>",
    "a": "A. path",
    "b": "B. machine",
    "c": "C. garden",
    "d": "D. river",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I put ...... the light and slept.</p>",
    "a": "A. up",
    "b": "B. down",
    "c": "C. in",
    "d": "D. out",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>...... all intents and purposes, the manager is the master of the firm.</p>",
    "a": "A. in",
    "b": "B. upon",
    "c": "C. with",
    "d": "D. to",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The pilot had been warned about the storm, before he ......</p>",
    "a": "A. took away",
    "b": "B. took up",
    "c": "C. took over",
    "d": "D. took off",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Hardly had he arrived ...... it started raining.</p>",
    "a": "A. before",
    "b": "B. when",
    "c": "C. than",
    "d": "D. after",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I ...... a car to be absolutely necessary these days.</p>",
    "a": "A. consider",
    "b": "B. regard",
    "c": "C. think",
    "d": "D. agree",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Besides other provisions, that shopkeeper deals ...... cosmetics.</p>",
    "a": "A. with",
    "b": "B. in",
    "c": "C. at",
    "d": "D. for",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Leave a two inch ...... on each page for the teacher's remarks.</p>",
    "a": "A. border",
    "b": "B. margin",
    "c": "C. blank",
    "d": "D. gap",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The team was well trained and strong, but somehow their ...... was low.</p>",
    "a": "A. feeling",
    "b": "B. moral",
    "c": "C. consciousness",
    "d": "D. morale",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The lovers were meeting each other secretly, but their ...... affair was soon known to everyone.</p>",
    "a": "A. clandestine",
    "b": "B. covert",
    "c": "C. unknown",
    "d": "D. candid",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The king ...... the rebel.</p>",
    "a": "A. excused",
    "b": "B. forgave",
    "c": "C. pardoned",
    "d": "D. none of these",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I shall call ...... you tomorrow.</p>",
    "a": "A. at",
    "b": "B. on",
    "c": "C. with",
    "d": "D. by",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>She ...... from the crowd because of her height and flaming red hair.</p>",
    "a": "A. stood out",
    "b": "B. stood off",
    "c": "C. stood up",
    "d": "D. stood by",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>In a large cities people are cut ...... from nature.</p>",
    "a": "A. away",
    "b": "B. off",
    "c": "C. out",
    "d": "D. down",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The more your action and thought are allied and ...... the happier you grow.</p>",
    "a": "A. diverget",
    "b": "B. unravelled",
    "c": "C. integrated",
    "d": "D. invincible",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>We had a ...... of warm weather in February.</p>",
    "a": "A. time",
    "b": "B. spell",
    "c": "C. length",
    "d": "D. phase",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Physically we are now all neighbors, but psychologically. we are ...... to each other.</p>",
    "a": "A. primitives",
    "b": "B. complimentary",
    "c": "C. strangers",
    "d": "D. cowards",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>When their examinations are over, the children gleefully ...... the books they had been reading.</p>",
    "a": "A. shelve",
    "b": "B. sidetrack",
    "c": "C. overthrew",
    "d": "D. abandon",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Chintu is ...... small to start playing cricket now.</p>",
    "a": "A. very",
    "b": "B. much",
    "c": "C. too",
    "d": "D. more",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The thief ...... all the money.</p>",
    "a": "A. made up",
    "b": "B. made off with",
    "c": "C. mode do with",
    "d": "D. made good",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The luggage was ...... heavy for him to lift</p>",
    "a": "A. much",
    "b": "B. as",
    "c": "C. so",
    "d": "D. too",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Walking at 3'o clock, I heard the ...... of thunder.</p>",
    "a": "A. crackle",
    "b": "B. rumble",
    "c": "C. ripple",
    "d": "D. clank",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>A stone that goes on rolling ...... no moss.</p>",
    "a": "A. collects",
    "b": "B. gets",
    "c": "C. gathers",
    "d": "D. accumulates",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The earth is at present in great danger of becoming uninhabitable because of ...... environmental pollution which is going on at an incredible rapid pace.</p>",
    "a": "A. gigantic",
    "b": "B. inhuman",
    "c": "C. stupendous",
    "d": "D. colossal",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Moreover, a fact finding mission ...... by BSN to India in January this year strongly recommended that the French group should go it alone, and not hand over ...... to an Indian Partner.</p>",
    "a": "A. organised, papers",
    "b": "B. constituted, authority",
    "c": "C. sponsored, power",
    "d": "D. dispatched, control",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>There is a keen ...... in each trade.</p>",
    "a": "A. contest",
    "b": "B. comparison",
    "c": "C. competition",
    "d": "D. cooperation",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Now, the management graduate can expect to have a prosperous life on a ...... income without having to depend on finding a place in family busiess having to tend the paternal estates.</p>",
    "a": "A. professional",
    "b": "B. regular",
    "c": "C. meaningful",
    "d": "D. dependable",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The boy fell ...... bicycle.</p>",
    "a": "A. of",
    "b": "B. off",
    "c": "C. from",
    "d": "D. under",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The French ...... reputed to have a very good sense of humour.</p>",
    "a": "A. is",
    "b": "B. was",
    "c": "C. are",
    "d": "D. will be",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Johny, where are you? ...... up this tree.</p>",
    "a": "A. There I am",
    "b": "B. There am I",
    "c": "C. Here am I",
    "d": "D. Here I am",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>That the poor in our country, are happy is</p>",
    "a": "A. a dream",
    "b": "B. a vision",
    "c": "C. an ideal",
    "d": "D. an illusion",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The robbers were arrested and ...... prison yesterday.</p>",
    "a": "A. brought into",
    "b": "B. brought to",
    "c": "C. taken into",
    "d": "D. taken to",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The cinema ...... a welcome escape from cramped and dull city life and the Indians are avid movie-goers.</p>",
    "a": "A. depicts",
    "b": "B. highlights",
    "c": "C. follows",
    "d": "D. offers",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I shall take revenge ...... you.</p>",
    "a": "A. from",
    "b": "B. with",
    "c": "C. on",
    "d": "D. at",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>This book is a useful ...... to our library.</p>",
    "a": "A. discovery",
    "b": "B. asset",
    "c": "C. addition",
    "d": "D. arrival",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The boy was cured ...... typhoid.</p>",
    "a": "A. from",
    "b": "B. of",
    "c": "C. for",
    "d": "D. through",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The communalist represents the ...... of everything noble that we have inherited from our culture and history.</p>",
    "a": "A. antithesis",
    "b": "B. antidote",
    "c": "C. immorality",
    "d": "D. antagonism",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He is so ...... to light that he never leaves the house without sunglasses.</p>",
    "a": "A. insensitive",
    "b": "B. sensitive",
    "c": "C. afraid",
    "d": "D. immune",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The ...... of the Minister's statement cannot be verified by people who have no access to official records.</p>",
    "a": "A. veracity",
    "b": "B. verbosity",
    "c": "C. ambiguity",
    "d": "D. validity",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>But the introductory fee does not stop after the initial handshake, brokers have to ...... it up after each transaction.</p>",
    "a": "A. bring",
    "b": "B. cough",
    "c": "C. boost",
    "d": "D. give",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Colgate has also set an ambitious aim of ......on 8% value shared of tooth paste market by then end of first years.</p>",
    "a": "A. cornering",
    "b": "B. soliciting",
    "c": "C. disturbing",
    "d": "D. keeping",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>...... a failure of some traffic lights, traffic is moving very slowly.</p>",
    "a": "A. Owing",
    "b": "B. Due to",
    "c": "C. Because",
    "d": "D. Since",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>The battalion operating from the mountain was able to ...... three enemy divisons.</p>",
    "a": "A. tie up",
    "b": "B. tie down",
    "c": "C. tie on",
    "d": "D. tie with",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I purposely ...... meet you during my last visit to Kashmir.</p>",
    "a": "A. didn't",
    "b": "B. won't",
    "c": "C. hadn't",
    "d": "D. wouldn't",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I have read one novel by Premchand. I want to read ...... novel by him.</p>",
    "a": "A. other",
    "b": "B. another",
    "c": "C. all",
    "d": "D. few",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>A man remains narrow minded, self compliance and ignorant unless he visits other people and ...... from them.</p>",
    "a": "A. earns",
    "b": "B. borrows",
    "c": "C. learns",
    "d": "D. hears",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>My father ...... down for a nap.</p>",
    "a": "A. lays",
    "b": "B. laid",
    "c": "C. lain",
    "d": "D. lie",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>I think they allow their children too much ......</p>",
    "a": "A. liberality",
    "b": "B. latitude",
    "c": "C. lassitude",
    "d": "D. levity",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Once you suspect a person of double dealing, you ought to keep him at arm's ......</p>",
    "a": "A. distance",
    "b": "B. length",
    "c": "C. aim",
    "d": "D. width",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Affix a revenue stamp and put your signature ...... it.</p>",
    "a": "A. on",
    "b": "B. upo",
    "c": "C. above",
    "d": "D. over",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>My first lesson ...... forgiveness came from my mother.</p>",
    "a": "A. upon",
    "b": "B. about",
    "c": "C. in",
    "d": "D. on",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>At one point, it looked as if an area of agreement would ...... specially over the issue of productivity linked wages.</p>",
    "a": "A. develop",
    "b": "B. come out",
    "c": "C. emerge",
    "d": "D. grow",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>Do you know ......?</p>",
    "a": "A. where she comes from",
    "b": "B. where does she come from",
    "c": "C. where from she comes",
    "d": "D. from where does she come",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>God is ......</p>",
    "a": "A. graceful",
    "b": "B. gracious",
    "c": "C. grateful",
    "d": "D. greatful",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
},{
    "qtext": "Choose best word from the given words to fill in the blank.\n<p>He is so ...... that he immediately believe my story of ghosts.</p>",
    "a": "A. innocent",
    "b": "B. credulous",
    "c": "C. vociferous",
    "d": "D. credible",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Selecting Words",
    "section": "(English)"
}


]}
