{
  "data":[
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Chauffeure",
        "b": "(B)Chauffeor",
        "c": "(C)Chauffeur",
        "d": "(D)Chaeuffeur",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Chlorophyll",
        "b": "(B)Chlorophyl",
        "c": "(C)Chlorophell",
        "d": "(D)Chlorophill",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Commissionner",
        "b": "(B)Commissioner",
        "c": "(C)Comissioner",
        "d": "(D)Commisioner",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Carnivorus",
        "b": "(B)Carnivrous",
        "c": "(C)Carnevorous",
        "d": "(D)Carnivorous",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Collosal",
        "b": "(B)Colossal",
        "c": "(C)Colosal",
        "d": "(D)Colosale",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Commendant",
        "b": "(B)Commandent",
        "c": "(C)Commandant",
        "d": "(D)Comandant",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Cumpassion",
        "b": "(B)Compassion",
        "c": "(C)Compasion",
        "d": "(D)Compastion",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Cunvenience",
        "b": "(B)Convenience",
        "c": "(C)Convinience",
        "d": "(D)Convenence",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Corrooboration",
        "b": "(B)Corroboraetion",
        "c": "(C)Coroboration",
        "d": "(D)Corroboration",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Daniel",
        "b": "(B)Danile",
        "c": "(C)Daneil",
        "d": "(D)Danniel",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Detiriorate",
        "b": "(B)Detereorate",
        "c": "(C)Deteriorate",
        "d": "(D)Daeteriorate",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Daibites",
        "b": "(B)Diabites",
        "c": "(C)Daibetes",
        "d": "(D)Diabetes",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Diaphragm",
        "b": "(B)Daiphragm",
        "c": "(C)Diaphrgm",
        "d": "(D)Diaphragam",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Diarrhoae",
        "b": "(B)Diarhoea",
        "c": "(C)Dearrhoea",
        "d": "(D)Diarrhoea",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Desciplinary",
        "b": "(B)Disciplinary",
        "c": "(C)Disceplinary",
        "d": "(D)Disciplenary",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Dysentery",
        "b": "(B)Dysintery",
        "c": "(C)Dysentiry",
        "d": "(D)Dysentary",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Dyispepsia",
        "b": "(B)Dyspepsea",
        "c": "(C)Dyspepsia",
        "d": "(D)Dyspipsia",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Eczima",
        "b": "(B)Ecgema",
        "c": "(C)Eczema",
        "d": "(D)Ecczema",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Enveronment",
        "b": "(B)Envirenment",
        "c": "(C)Enviroment",
        "d": "(D)Environment",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Equilibrium",
        "b": "(B)Equellibrium",
        "c": "(C)Equillibrium",
        "d": "(D)Equillibreum",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Eucaliptus",
        "b": "(B)Eucelyptus",
        "c": "(C)Eucalyptus",
        "d": "(D)Eucaleptus",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Ecclesiastec",
        "b": "(B)Ecclisiastic",
        "c": "(C)Eclesiastic",
        "d": "(D)Ecclesiastic",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Emancipattion",
        "b": "(B)Emancipation",
        "c": "(C)Emencipation",
        "d": "(D)Emancepation",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Emberrassment",
        "b": "(B)Embarassment",
        "c": "(C)Embarrassment",
        "d": "(D)Embarrasment",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Equivecation",
        "b": "(B)Equivocation",
        "c": "(C)Equivacation",
        "d": "(D)Equevocation",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Eradication",
        "b": "(B)Eradecation",
        "c": "(C)Eraedication",
        "d": "(D)Eardication",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Espionege",
        "b": "(B)Eespionage",
        "c": "(C)Espionage",
        "d": "(D)Espeonage",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Etiquette",
        "b": "(B)Etiquatte",
        "c": "(C)Etiquete",
        "d": "(D)Etequette",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Exonaration",
        "b": "(B)Exsoneration",
        "c": "(C)Exoneration",
        "d": "(D)Exoniration",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Expedient",
        "b": "(B)Exspedient",
        "c": "(C)Expediant",
        "d": "(D)Expedeent",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Fahrenheit",
        "b": "(B)Fahrenhiet",
        "c": "(C)Faahrenheit",
        "d": "(D)Fahennheit",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Ferreous",
        "b": "(B)Ferrous",
        "c": "(C)Firrous",
        "d": "(D)Ferous",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Fermenttation",
        "b": "(B)Fermintation",
        "c": "(C)Fermentation",
        "d": "(D)Farmentation",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Garruelous",
        "b": "(B)Garrulious",
        "c": "(C)Garulous",
        "d": "(D)Garrulous",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Gonorrhea",
        "b": "(B)Gonurrhoea",
        "c": "(C)Gonorhoea",
        "d": "(D)Gonorrhoea",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Grasshoppar",
        "b": "(B)Grasshopper",
        "c": "(C)Grashopper",
        "d": "(D)Grasshoper",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Garrition",
        "b": "(B)Garison",
        "c": "(C)Garreson",
        "d": "(D)Garrison",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Girraffe",
        "b": "(B)Geraffe",
        "c": "(C)Giraffe",
        "d": "(D)Girafe",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Grandeur",
        "b": "(B)Grander",
        "c": "(C)Granduer",
        "d": "(D)Grandiur",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Ginaecology",
        "b": "(B)Gynaecolgy",
        "c": "(C)Gyneacology",
        "d": "(D)Gynaecology",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Harmonim",
        "b": "(B)Harmoneum",
        "c": "(C)Harmonium",
        "d": "(D)Harrmonium",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Heamoglobin",
        "b": "(B)Haemoglobin",
        "c": "(C)Haeimoglobin",
        "d": "(D)Haemogloben",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Haemorrhge",
        "b": "(B)Haemorhage",
        "c": "(C)Haemorrhage",
        "d": "(D)Haimorrhage",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Harppon",
        "b": "(B)Harppoon",
        "c": "(C)Harpon",
        "d": "(D)Harpoon",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Heridiatary",
        "b": "(B)Hereditary",
        "c": "(C)Hirediatary",
        "d": "(D)Heredeatary",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Heterodx",
        "b": "(B)Hetreodox",
        "c": "(C)Heterodox",
        "d": "(D)Hiterodox",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Hippopottamus",
        "b": "(B)Heppopotamus",
        "c": "(C)Hipopotamus",
        "d": "(D)Hippopotamus",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Herbivorus",
        "b": "(B)Herbivorous",
        "c": "(C)Hervivorous",
        "d": "(D)Hirbivorous",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Hardman",
        "b": "(B)Hardsman",
        "c": "(C)Herdman",
        "d": "(D)Herdsman",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Hygiene",
        "b": "(B)Hygene",
        "c": "(C)Higiene",
        "d": "(D)Hygine",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Hypermetorpia",
        "b": "(B)Hypermetreopia",
        "c": "(C)Hypermitropia",
        "d": "(D)Hypermetropia",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) erratic",
        "b": "2) diligent",
        "c": "3) evence",
        "d": "4) diabolical",
        "e": "5) All are correct",
        "correct": "3",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) diaspora",
        "b": "2) debility",
        "c": "3) delirious",
        "d": "4) debut",
        "e": "5) All are correct",
        "correct": "5",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) naivete",
        "b": "2) nuance",
        "c": "3) peian",
        "d": "4) progeny",
        "e": "5) All are correct",
        "correct": "3",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) nee",
        "b": "2) pecilate",
        "c": "3) peevish",
        "d": "4) niche",
        "e": "5) All are correct",
        "correct": "2",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) mete",
        "b": "2) muzzle",
        "c": "3) juggle",
        "d": "4) jaicose",
        "e": "5) All are correct",
        "correct": "4",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) maltreat",
        "b": "2) mayhem",
        "c": "3) lustre",
        "d": "4) leway",
        "e": "5) All are correct",
        "correct": "4",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) handy",
        "b": "2) impugn",
        "c": "3) hiccup",
        "d": "4) goery",
        "e": "5) All are correct",
        "correct": "4",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) ensconce",
        "b": "2) exacerbate",
        "c": "3) gruff",
        "d": "4) grudge",
        "e": "5) All are correct",
        "correct": "5",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) exorcist",
        "b": "2) feitish",
        "c": "3) fervid",
        "d": "4) gamut",
        "e": "5) All are correct",
        "correct": "2",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) doleful",
        "b": "2) diatribe",
        "c": "3) detente",
        "d": "4) doyan",
        "e": "5) All are correct",
        "correct": "4",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) Fauna",
        "b": "2) facsimile",
        "c": "3) epilogue",
        "d": "4) alamanac",
        "e": "5) All are correct",
        "correct": "4",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) virtuoso",
        "b": "2) lunar",
        "c": "3) axiom",
        "d": "4) potable",
        "e": "5) All are correct",
        "correct": "5",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) martyr",
        "b": "2) heretic",
        "c": "3) polyglot",
        "d": "4) coquete",
        "e": "5) All are correct",
        "correct": "4",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) divergent",
        "b": "2) symbolic",
        "c": "3) chauveinist",
        "d": "4) solidarity",
        "e": "5) All are correct",
        "correct": "3",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) egregious",
        "b": "2) uttering",
        "c": "3) patrirchal",
        "d": "4) pronouncements",
        "e": "5) All are correct",
        "correct": "3",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) asunder",
        "b": "2) elaborate",
        "c": "3) irevocable",
        "d": "4) sanction",
        "e": "5) All are correct",
        "correct": "3",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) canibal",
        "b": "2) struck",
        "c": "3) arbitration",
        "d": "4) implicitly",
        "e": "5) All are correct",
        "correct": "1",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) debonair",
        "b": "2) emigrant",
        "c": "3) itinerant",
        "d": "4) swashbuckler",
        "e": "5) All are correct",
        "correct": "5",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) decanter",
        "b": "2) creche",
        "c": "3) plebiscite",
        "d": "4) regelia",
        "e": "5) All are correct",
        "correct": "4",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) sensual",
        "b": "2) rein",
        "c": "3) prey",
        "d": "4) beatific",
        "e": "5) All are correct",
        "correct": "5",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) veneal",
        "b": "2) arena",
        "c": "3) cloakroom",
        "d": "4) cage",
        "e": "5) All are correct",
        "correct": "1",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) eatable",
        "b": "2) almanac",
        "c": "3) teetotaller",
        "d": "4) uxorious",
        "e": "5) All are correct",
        "correct": "5",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) convent",
        "b": "2) sanaterium",
        "c": "3) salutatorian",
        "d": "4) tannery",
        "e": "5) All are correct",
        "correct": "2",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) aresenal",
        "b": "2) apiary",
        "c": "3) aviary",
        "d": "4) aquarium",
        "e": "5) All are correct",
        "correct": "1",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) delegate",
        "b": "2) soporific",
        "c": "3) regalia",
        "d": "4) kenel",
        "e": "5) All are correct",
        "correct": "4",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) thearchy",
        "b": "2) autocracy",
        "c": "3) prestigious",
        "d": "4) compere",
        "e": "5) All are correct",
        "correct": "1",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) potable",
        "b": "2) facsimile",
        "c": "3) crusade",
        "d": "4) pedantic",
        "e": "5) All are correct",
        "correct": "5",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) cleque",
        "b": "2) bevy",
        "c": "3) brood",
        "d": "4) brace",
        "e": "5) All are correct",
        "correct": "1",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) barrage",
        "b": "2) stream",
        "c": "3) posse",
        "d": "4) bolley",
        "e": "5) All are correct",
        "correct": "5",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) eugenics",
        "b": "2) rhetoric",
        "c": "3) homophobia",
        "d": "4) ortheopy",
        "e": "5) All are correct",
        "correct": "5",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) reputation",
        "b": "2) revelation",
        "c": "3) appreciate",
        "d": "4) reimburuse",
        "e": "5) All are correct",
        "correct": "4",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) Elaborate",
        "b": "2) Collapse",
        "c": "3) Anecdote",
        "d": "4) remuneraition",
        "e": "5) All are correct",
        "correct": "4",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) subjugete",
        "b": "2) Tenacious",
        "c": "3) Contaminate",
        "d": "4) Speculate",
        "e": "5) All are correct",
        "correct": "1",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) tame",
        "b": "2) uncertain",
        "c": "3) prehistric",
        "d": "4) Conceive",
        "e": "5) All are correct",
        "correct": "3",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) Rival",
        "b": "2) fasty",
        "c": "3) competitor",
        "d": "4) appearance",
        "e": "5) All are correct",
        "correct": "2",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) demytify",
        "b": "2) Abridged",
        "c": "3) redundant",
        "d": "4) concise",
        "e": "5) All are correct",
        "correct": "1",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) somewhat",
        "b": "2) Elegant",
        "c": "3) falsfier",
        "d": "4) unrefined",
        "e": "5) All are correct",
        "correct": "3",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) Incursion",
        "b": "2) Indecerous",
        "c": "3) Nadir",
        "d": "4) passable",
        "e": "5) All are correct",
        "correct": "2",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"Which of the following spelling incorrect in the given context ?",
        "a": "1) Alongside",
        "b": "2) Adjacent",
        "c": "3) remote",
        "d": "4) Clientele",
        "e": "5) All are correct",
        "correct": "5",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext":"1) Repentant",
        "a": "2) Skimpy",
        "b": "3) Sparse",
        "c": "4) Sloth",
        "d": "5) All are correct",
        "e": "5",
        "correct": "5",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    }
]
  
}
