{
  "data":[
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Chauffeure",
        "b": "(B)Chauffeor",
        "c": "(C)Chauffeur",
        "d": "(D)Chaeuffeur",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Chlorophyll",
        "b": "(B)Chlorophyl",
        "c": "(C)Chlorophell",
        "d": "(D)Chlorophill",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Commissionner",
        "b": "(B)Commissioner",
        "c": "(C)Comissioner",
        "d": "(D)Commisioner",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Carnivorus",
        "b": "(B)Carnivrous",
        "c": "(C)Carnevorous",
        "d": "(D)Carnivorous",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Collosal",
        "b": "(B)Colossal",
        "c": "(C)Colosal",
        "d": "(D)Colosale",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Commendant",
        "b": "(B)Commandent",
        "c": "(C)Commandant",
        "d": "(D)Comandant",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Cumpassion",
        "b": "(B)Compassion",
        "c": "(C)Compasion",
        "d": "(D)Compastion",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Cunvenience",
        "b": "(B)Convenience",
        "c": "(C)Convinience",
        "d": "(D)Convenence",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Corrooboration",
        "b": "(B)Corroboraetion",
        "c": "(C)Coroboration",
        "d": "(D)Corroboration",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Daniel",
        "b": "(B)Danile",
        "c": "(C)Daneil",
        "d": "(D)Danniel",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Detiriorate",
        "b": "(B)Detereorate",
        "c": "(C)Deteriorate",
        "d": "(D)Daeteriorate",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Daibites",
        "b": "(B)Diabites",
        "c": "(C)Daibetes",
        "d": "(D)Diabetes",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Diaphragm",
        "b": "(B)Daiphragm",
        "c": "(C)Diaphrgm",
        "d": "(D)Diaphragam",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Diarrhoae",
        "b": "(B)Diarhoea",
        "c": "(C)Dearrhoea",
        "d": "(D)Diarrhoea",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Desciplinary",
        "b": "(B)Disciplinary",
        "c": "(C)Disceplinary",
        "d": "(D)Disciplenary",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Dysentery",
        "b": "(B)Dysintery",
        "c": "(C)Dysentiry",
        "d": "(D)Dysentary",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Dyispepsia",
        "b": "(B)Dyspepsea",
        "c": "(C)Dyspepsia",
        "d": "(D)Dyspipsia",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": "Spelling test - find correct spelling :",
        "a": "(A)Eczima",
        "b": "(B)Ecgema",
        "c": "(C)Eczema",
        "d": "(D)Ecczema",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Enveronment",
        "b": "(B)Envirenment",
        "c": "(C)Enviroment",
        "d": "(D)Environment",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Equilibrium",
        "b": "(B)Equellibrium",
        "c": "(C)Equillibrium",
        "d": "(D)Equillibreum",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Eucaliptus",
        "b": "(B)Eucelyptus",
        "c": "(C)Eucalyptus",
        "d": "(D)Eucaleptus",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Ecclesiastec",
        "b": "(B)Ecclisiastic",
        "c": "(C)Eclesiastic",
        "d": "(D)Ecclesiastic",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Emancipattion",
        "b": "(B)Emancipation",
        "c": "(C)Emencipation",
        "d": "(D)Emancepation",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Emberrassment",
        "b": "(B)Embarassment",
        "c": "(C)Embarrassment",
        "d": "(D)Embarrasment",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Equivecation",
        "b": "(B)Equivocation",
        "c": "(C)Equivacation",
        "d": "(D)Equevocation",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Eradication",
        "b": "(B)Eradecation",
        "c": "(C)Eraedication",
        "d": "(D)Eardication",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Espionege",
        "b": "(B)Eespionage",
        "c": "(C)Espionage",
        "d": "(D)Espeonage",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Etiquette",
        "b": "(B)Etiquatte",
        "c": "(C)Etiquete",
        "d": "(D)Etequette",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Exonaration",
        "b": "(B)Exsoneration",
        "c": "(C)Exoneration",
        "d": "(D)Exoniration",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Expedient",
        "b": "(B)Exspedient",
        "c": "(C)Expediant",
        "d": "(D)Expedeent",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Fahrenheit",
        "b": "(B)Fahrenhiet",
        "c": "(C)Faahrenheit",
        "d": "(D)Fahennheit",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Ferreous",
        "b": "(B)Ferrous",
        "c": "(C)Firrous",
        "d": "(D)Ferous",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Fermenttation",
        "b": "(B)Fermintation",
        "c": "(C)Fermentation",
        "d": "(D)Farmentation",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Garruelous",
        "b": "(B)Garrulious",
        "c": "(C)Garulous",
        "d": "(D)Garrulous",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Gonorrhea",
        "b": "(B)Gonurrhoea",
        "c": "(C)Gonorhoea",
        "d": "(D)Gonorrhoea",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Grasshoppar",
        "b": "(B)Grasshopper",
        "c": "(C)Grashopper",
        "d": "(D)Grasshoper",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Garrition",
        "b": "(B)Garison",
        "c": "(C)Garreson",
        "d": "(D)Garrison",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Girraffe",
        "b": "(B)Geraffe",
        "c": "(C)Giraffe",
        "d": "(D)Girafe",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Grandeur",
        "b": "(B)Grander",
        "c": "(C)Granduer",
        "d": "(D)Grandiur",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Ginaecology",
        "b": "(B)Gynaecolgy",
        "c": "(C)Gyneacology",
        "d": "(D)Gynaecology",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Harmonim",
        "b": "(B)Harmoneum",
        "c": "(C)Harmonium",
        "d": "(D)Harrmonium",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Heamoglobin",
        "b": "(B)Haemoglobin",
        "c": "(C)Haeimoglobin",
        "d": "(D)Haemogloben",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Haemorrhge",
        "b": "(B)Haemorhage",
        "c": "(C)Haemorrhage",
        "d": "(D)Haimorrhage",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Harppon",
        "b": "(B)Harppoon",
        "c": "(C)Harpon",
        "d": "(D)Harpoon",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Heridiatary",
        "b": "(B)Hereditary",
        "c": "(C)Hirediatary",
        "d": "(D)Heredeatary",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Heterodx",
        "b": "(B)Hetreodox",
        "c": "(C)Heterodox",
        "d": "(D)Hiterodox",
        "correct": "C",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Hippopottamus",
        "b": "(B)Heppopotamus",
        "c": "(C)Hipopotamus",
        "d": "(D)Hippopotamus",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Herbivorus",
        "b": "(B)Herbivorous",
        "c": "(C)Hervivorous",
        "d": "(D)Hirbivorous",
        "correct": "B",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Hardman",
        "b": "(B)Hardsman",
        "c": "(C)Herdman",
        "d": "(D)Herdsman",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Hygiene",
        "b": "(B)Hygene",
        "c": "(C)Higiene",
        "d": "(D)Hygine",
        "correct": "A",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    },
    {
        "qtext": " Spelling test - find correct spelling :",
        "a": "(A)Hypermetorpia",
        "b": "(B)Hypermetreopia",
        "c": "(C)Hypermitropia",
        "d": "(D)Hypermetropia",
        "correct": "D",
        "img": "",
        "topic": "Spellings",
        "section": "(English)"
    }
]
  
}
