{
"data":[
  {
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>CORPULENT</p>",
    "a": "A. Lean",
    "b": "B. Gaunt",
    "c": "C. Emaciated",
    "d": "D. Obese",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>BRIEF</p>",
    "a": "A. Limited",
    "b": "B. Small",
    "c": "C. Little",
    "d": "D. Short",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>EMBEZZLE</p>",
    "a": "A. Misappropriate",
    "b": "B. Balance",
    "c": "C. Remunerate",
    "d": "D. Clear",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>VENT</p>",
    "a": "A. Opening",
    "b": "B. Stodge",
    "c": "C. End",
    "d": "D. Past tense of go",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>AUGUST</p>",
    "a": "A. Common",
    "b": "B. Ridiculous",
    "c": "C. Dignified",
    "d": "D. Petty",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>CANNY</p>",
    "a": "A. Obstinate",
    "b": "B. Handsome",
    "c": "C. Clever",
    "d": "D. Stout",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>ALERT</p>",
    "a": "A. Energetic",
    "b": "B. Observant",
    "c": "C. Intelligent",
    "d": "D. Watchful",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>WARRIOR</p>",
    "a": "A. Soldier",
    "b": "B. Sailor",
    "c": "C. Pirate",
    "d": "D. Spy",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>DISTANT</p>",
    "a": "A. Far",
    "b": "B. Removed",
    "c": "C. Reserved",
    "d": "D. Separate",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>ADVERSITY </p>",
    "a": "A. Failure",
    "b": "B. Helplessness",
    "c": "C. Misfortune",
    "d": "D. Crisis",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>FAKE</p>",
    "a": "A. Original",
    "b": "B. Imitation",
    "c": "C. Trustworthy",
    "d": "D. Loyal",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>INDICT</p>",
    "a": "A. Condemn",
    "b": "B. Reprimand",
    "c": "C. Accuse",
    "d": "D. Allege",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>STRINGENT</p>",
    "a": "A. Dry",
    "b": "B. Strained",
    "c": "C. Rigorous",
    "d": "D. Shrill",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>LAMENT</p>",
    "a": "A. Complain",
    "b": "B. Comment",
    "c": "C. Condone",
    "d": "D. Console",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>HESITATED</p>",
    "a": "A. Stopped",
    "b": "B. Paused",
    "c": "C. Slowed",
    "d": "D. Postponed",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>RESCUE</p>",
    "a": "A. Command",
    "b": "B. Help",
    "c": "C. Defence",
    "d": "D. Safety",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>ATTEMPT</p>",
    "a": "A. Serve",
    "b": "B. Explore",
    "c": "C. Try",
    "d": "D. Explain",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>FORAY</p>",
    "a": "A. Maraud",
    "b": "B. Contest",
    "c": "C. Ranger",
    "d": "D. Intuition",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>RECKLESS</p>",
    "a": "A. Courageous",
    "b": "B. Rash",
    "c": "C. Bold",
    "d": "D. Daring",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>CONSEQUENCES</p>",
    "a": "A. Results",
    "b": "B. Conclusions",
    "c": "C. Difficulties",
    "d": "D. Applications",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>IMPROVEMENT</p>",
    "a": "A. Advancement",
    "b": "B. Betterment",
    "c": "C. Promotion",
    "d": "D. Preference",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>INEBRIATE</p>",
    "a": "A. Dreamy",
    "b": "B. Stupefied",
    "c": "C. Unsteady",
    "d": "D. Drunken",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>STERILE</p>",
    "a": "A. Barren",
    "b": "B. Arid",
    "c": "C. Childless",
    "d": "D. Dry",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>ABJECT</p>",
    "a": "A. Challenge",
    "b": "B. Miserable",
    "c": "C. Deny",
    "d": "D. Disobey",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>MOVING</p>",
    "a": "A. Taking",
    "b": "B. Toying",
    "c": "C. Shifting",
    "d": "D. Turning",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>IRONIC</p>",
    "a": "A. Inflexible",
    "b": "B. Bitter",
    "c": "C. Good-natured",
    "d": "D. Disguisedly sarcastic",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>TIMID</p>",
    "a": "A. Fast",
    "b": "B. Slow",
    "c": "C. Medium",
    "d": "D. Shy",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>EXTRICATE</p>",
    "a": "A. Pull",
    "b": "B. Free",
    "c": "C. Tie",
    "d": "D. Complicate",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>NEUTRAL</p>",
    "a": "A. Unbiased",
    "b": "B. Non-aligned",
    "c": "C. Undecided",
    "d": "D. Indifferent",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>SHALLOW</p>",
    "a": "A. Artificial",
    "b": "B. Superficial",
    "c": "C. Foolish",
    "d": "D. Worthless",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>DIVERSION</p>",
    "a": "A. Amusement",
    "b": "B. Distortion",
    "c": "C. Deviation",
    "d": "D. Bylane",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>INSOLVENT</p>",
    "a": "A. Poor",
    "b": "B. Bankrupt",
    "c": "C. Penniless",
    "d": "D. Broke",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>INEXPLICABLE</p>",
    "a": "A. Confusing",
    "b": "B. Unaccountable",
    "c": "C. Chaotic",
    "d": "D. Unconnected",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>FEEBLE</p>",
    "a": "A. Weak",
    "b": "B. Vain",
    "c": "C. Arrogant",
    "d": "D. Sick",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>TRANSIENT</p>",
    "a": "A. Transparent",
    "b": "B. Fleeting",
    "c": "C. Feeble",
    "d": "D. Fanciful",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>BARE</p>",
    "a": "A. Uncovered",
    "b": "B. Tolerate",
    "c": "C. Clear",
    "d": "D. Neat",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>REPEAL</p>",
    "a": "A. Sanction",
    "b": "B. Perpetuate",
    "c": "C. Pass",
    "d": "D. Cancel",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>SALACITY</p>",
    "a": "A. Bliss",
    "b": "B. Depression",
    "c": "C. Indecency",
    "d": "D. Recession",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>ECSTATIC</p>",
    "a": "A. Animated",
    "b": "B. Bewildered",
    "c": "C. Enraptured",
    "d": "D. Illful",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>ADMONISH</p>",
    "a": "A. Punish",
    "b": "B. Curse",
    "c": "C. Dismiss",
    "d": "D. Reprimand",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>DILIGENT</p>",
    "a": "A. Progressive",
    "b": "B. Brilliant",
    "c": "C. Inventive",
    "d": "D. Hard-working",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>PIOUS</p>",
    "a": "A. Pure",
    "b": "B. Pretentious",
    "c": "C. Clean",
    "d": "D. Devout",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>BROWSE</p>",
    "a": "A. Heal",
    "b": "B. Deceive",
    "c": "C. Examine",
    "d": "D. Strike",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>INFREQUENT</p>",
    "a": "A. Never",
    "b": "B. Usual",
    "c": "C. Rare",
    "d": "D. Sometimes",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>RESTRAINT</p>",
    "a": "A. Hindrance",
    "b": "B. Repression",
    "c": "C. Obstacle",
    "d": "D. Restriction",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>DEIFY</p>",
    "a": "A. Flatter",
    "b": "B. Challenge",
    "c": "C. Worship",
    "d": "D. Face",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>HARBINGER</p>",
    "a": "A. Messenger",
    "b": "B. Steward",
    "c": "C. Forerunner",
    "d": "D. Pilot",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>VENUE</p>",
    "a": "A. Place",
    "b": "B. Agenda",
    "c": "C. Time",
    "d": "D. Duration",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>CANDID</p>",
    "a": "A. Apparent",
    "b": "B. Explicit",
    "c": "C. Frank",
    "d": "D. Bright",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>MELD</p>",
    "a": "A. To soothe",
    "b": "B. Merge",
    "c": "C. Purchase",
    "d": "D. Glisten",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>LYNCH</p>",
    "a": "A. Hang",
    "b": "B. Madden",
    "c": "C. Kill",
    "d": "D. Shoot",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>TORTURE</p>",
    "a": "A. Torment",
    "b": "B. Chastisement",
    "c": "C. Harassment",
    "d": "D. Terror",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>ABUNDANT</p>",
    "a": "A. Ripe",
    "b": "B. Cheap",
    "c": "C. Plenty",
    "d": "D. Absent",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>ENTIRE</p>",
    "a": "A. Part",
    "b": "B. Quarter",
    "c": "C. Whole",
    "d": "D. Half",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>DESTITUTION</p>",
    "a": "A. Humility",
    "b": "B. Moderation",
    "c": "C. Poverty",
    "d": "D. Beggary",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>WRETCHED</p>",
    "a": "A. Poor",
    "b": "B. Foolish",
    "c": "C. Insane",
    "d": "D. Strained",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>INTIMIDATE</p>",
    "a": "A. To hint",
    "b": "B. Frighten",
    "c": "C. Bluff",
    "d": "D. Harass",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>CANTANKEROUS</p>",
    "a": "A. Quarrelsome",
    "b": "B. Rash",
    "c": "C. Disrespectful",
    "d": "D. Noisy",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>RANT</p>",
    "a": "A. Praise inordinately",
    "b": "B. Formalise",
    "c": "C. To preach noisily",
    "d": "D. Treat with screen",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>ZANY</p>",
    "a": "A. Clown",
    "b": "B. Pet",
    "c": "C. Thief",
    "d": "D. Magician",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>TACITURNITY</p>",
    "a": "A. Dumbness",
    "b": "B. Changeablemess",
    "c": "C. Hesitation",
    "d": "D. Reserve",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>MASSACRE</p>",
    "a": "A. Murder",
    "b": "B. Stab",
    "c": "C. Assassinate",
    "d": "D. Slaughter",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>KEN</p>",
    "a": "A. Ignorance",
    "b": "B. Witness",
    "c": "C. Trial",
    "d": "D. Knowledge",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>WARY</p>",
    "a": "A. Sad",
    "b": "B. vigilant",
    "c": "C. Distorted",
    "d": "D. Tired",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>RABBLE</p>",
    "a": "A. Mob",
    "b": "B. Noise",
    "c": "C. Roar",
    "d": "D. Rubbish",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>MAYHEM</p>",
    "a": "A. Jubilation",
    "b": "B. Havoc",
    "c": "C. Excitement",
    "d": "D. Defeat",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>PONDER</p>",
    "a": "A. Think",
    "b": "B. Evaluate",
    "c": "C. Anticipate",
    "d": "D. Increase",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>CONNOISSEUR</p>",
    "a": "A. Ignorant",
    "b": "B. Lover of art",
    "c": "C. Interpreter",
    "d": "D. Delinquent",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>SHIVER</p>",
    "a": "A. Feel",
    "b": "B. Rock",
    "c": "C. Tremble",
    "d": "D. Move",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>PRESTIGE</p>",
    "a": "A. Influence",
    "b": "B. Quality",
    "c": "C. Name",
    "d": "D. Wealth",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>STRINGENT</p>",
    "a": "A. Tense",
    "b": "B. Stringly",
    "c": "C. Strict",
    "d": "D. Causing to Shrink",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>INSOMNIA</p>",
    "a": "A. Lethargy",
    "b": "B. Sleeplessness",
    "c": "C. Drunkenness",
    "d": "D. Unconsciousness",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>LAUD</p>",
    "a": "A. Lord",
    "b": "B. Eulogy",
    "c": "C. Praise",
    "d": "D. Extolled",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>REPERCUSSION</p>",
    "a": "A. Clever reply",
    "b": "B. Recollection",
    "c": "C. Remuneration",
    "d": "D. Reaction",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>IMPROMPTU</p>",
    "a": "A. Offhand",
    "b": "B. Unimportant",
    "c": "C. Unreal",
    "d": "D. Effective",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>FRUGALITY</p>",
    "a": "A. Foolishness",
    "b": "B. Extremity",
    "c": "C. Enthusiasm",
    "d": "D. Economy",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>CORRESPONDENCE</p>",
    "a": "A. Agreements",
    "b": "B. Contracts",
    "c": "C. Documents",
    "d": "D. Letters",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>ASCEND</p>",
    "a": "A. Leap",
    "b": "B. Grow",
    "c": "C. Deviate",
    "d": "D. Mount",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>FURORE</p>",
    "a": "A. Excitement",
    "b": "B. Worry",
    "c": "C. Flux",
    "d": "D. Anteroom",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>SYNOPSIS</p>",
    "a": "A. Index",
    "b": "B. Mixture",
    "c": "C. Summary",
    "d": "D. Puzzles",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>TURN UP</p>",
    "a": "A. Land up",
    "b": "B. Show up",
    "c": "C. Crop up",
    "d": "D. Come up",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>VIGOUR</p>",
    "a": "A. Strength",
    "b": "B. Boldness",
    "c": "C. Warmth",
    "d": "D. Enthusism",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>GARNISH</p>",
    "a": "A. Paint",
    "b": "B. Garner",
    "c": "C. Adorn",
    "d": "D. Abuse",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>MENDACIOUS</p>",
    "a": "A. Full of Confidence",
    "b": "B. False",
    "c": "C. Encouraging",
    "d": "D. Provocative",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>GARRULITY</p>",
    "a": "A. Credulity",
    "b": "B. Senility",
    "c": "C. Loquaciousness",
    "d": "D. Speciousness",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>MOROSE</p>",
    "a": "A. Annoyed",
    "b": "B. Gloomy",
    "c": "C. Moody",
    "d": "D. Displeased",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>VORACIOUS</p>",
    "a": "A. Truthful",
    "b": "B. Gluttonous",
    "c": "C. Funny",
    "d": "D. Venturous",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>AWAKENED</p>",
    "a": "A. Enlightened",
    "b": "B. Realised",
    "c": "C. Shook",
    "d": "D. Waken",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>GRATIFY</p>",
    "a": "A. Appreciate",
    "b": "B. Frank",
    "c": "C. Indulge",
    "d": "D. Pacify",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>PRECARIOUS</p>",
    "a": "A. Cautious",
    "b": "B. Critical",
    "c": "C. Perilous",
    "d": "D. Brittle",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>INFAMY</p>",
    "a": "A. Dishonour",
    "b": "B. Glory",
    "c": "C. Integrity",
    "d": "D. Reputation",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>MASTERLY</p>",
    "a": "A. Crafty",
    "b": "B. Skilful",
    "c": "C. Meaningful",
    "d": "D. Cruel",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>SCINTILLATING</p>",
    "a": "A. Smouldering",
    "b": "B. Glittering",
    "c": "C. Touching",
    "d": "D. Warming",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>TEPID</p>",
    "a": "A. Hot",
    "b": "B. Warm",
    "c": "C. Cold",
    "d": "D. Boiling",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>VORACIOUS</p>",
    "a": "A. Wild",
    "b": "B. Greedy",
    "c": "C. Angry",
    "d": "D. Quick",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>UNITE</p>",
    "a": "A. Unfold",
    "b": "B. Unchain",
    "c": "C. Combine",
    "d": "D. Unhinge",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>COMBAT</p>",
    "a": "A. Conflict",
    "b": "B. Quarrel",
    "c": "C. Feud",
    "d": "D. Fight",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>REFECTORY</p>",
    "a": "A. Restaurant",
    "b": "B. Parlour",
    "c": "C. Living Room",
    "d": "D. Dining Room",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>UNCOUTH</p>",
    "a": "A. Ungraceful",
    "b": "B. Rough",
    "c": "C. Slovenly",
    "d": "D. Dirty",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>ERROR</p>",
    "a": "A. Misadventure",
    "b": "B. Misgiving",
    "c": "C. Ambiguity",
    "d": "D. Blunder",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>COMMENSURATE</p>",
    "a": "A. Measurable",
    "b": "B. Proportionate",
    "c": "C. Begining",
    "d": "D. Appropriate",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>DEBACLE</p>",
    "a": "A. Collapse",
    "b": "B. Decline",
    "c": "C. Defeat",
    "d": "D. Disgrace",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>GERMANE</p>",
    "a": "A. Responsible",
    "b": "B. Logical",
    "c": "C. Possible",
    "d": "D. Relevant",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In the following the questions choose the word which best expresses the meaning of the given word.\n\n<p>DISTINCTION</p>",
    "a": "A. Diffusion",
    "b": "B. Disagreement",
    "c": "C. Different",
    "d": "D. Degree",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},
{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>It is very difficult to <b>retain</b> all that you hear in the class.</p>",
    "a": "A. keep",
    "b": "B. recall",
    "c": "C. preserve",
    "d": "D. conserve",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The great artist life was full of <b>vicissitudes</b>.</p>",
    "a": "A. sorrows",
    "b": "B. misfortunes",
    "c": "C. changes",
    "d": "D. surprises",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>She has an <b>insatiable</b> love for music.</p>",
    "a": "A. unsatisfiable",
    "b": "B. unchanging",
    "c": "C. irreconcilable",
    "d": "D. undesirable",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The great dancer impressed the appreciative crowd by his <b>nimble</b> movements.</p>",
    "a": "A. Unrhythmic",
    "b": "B. lively",
    "c": "C. quickening",
    "d": "D. clear",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The visitor had a <b>bohemian</b> look.</p>",
    "a": "A. hostile",
    "b": "B. unconventional",
    "c": "C. sinister",
    "d": "D. unfriendly",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The bullet wound proved to be <b>fatal</b> and the soldier died immediately.</p>",
    "a": "A. grievous",
    "b": "B. dangerous",
    "c": "C. serious",
    "d": "D. deadly",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The attitude of Western countries towards the Third World Countries is rather <b>callous</b> to say the least.</p>",
    "a": "A. passive",
    "b": "B. unkind",
    "c": "C. cursed",
    "d": "D. unfeeling",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>In spite of their efforts, the team of scientists could not make much <b>headway</b> to solve the problem.</p>",
    "a": "A. progress",
    "b": "B. thinking",
    "c": "C. efforts",
    "d": "D. start",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>On scrutiny the police officer found out that the documents provided by the landlord were totally <b>fabricated</b>.</p>",
    "a": "A. forged",
    "b": "B. historical",
    "c": "C. prepared",
    "d": "D. genuine",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Lack of occupation is not necessary revealed by <b>manifest</b> idleness.</p>",
    "a": "A. easily perceived",
    "b": "B. easily acquired",
    "c": "C. easily infected",
    "d": "D. easily deflected",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The accident occurred due to his <b>lapse</b>.</p>",
    "a": "A. trick",
    "b": "B. interval",
    "c": "C. error",
    "d": "D. ignorance",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Sunlight and shadow made the landscape a <b>kaleidoscope</b> of colour.</p>",
    "a": "A. tube containing mirrors and loose pieces of coloured glass",
    "b": "B. frequently changing pattern of bright scenes",
    "c": "C. a mixture of black and white",
    "d": "D. resembling the seven colours of rainbow",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>After the <b>dismal</b> performance of the team in the series concluded yesterday, the captain offered his resignation to the president of the club.</p>",
    "a": "A. poor",
    "b": "B. sorrowful",
    "c": "C. minimum",
    "d": "D. short",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>We didn't believe in his statement, but <b>subsequent</b>  events proved that he was right.</p>",
    "a": "A. later",
    "b": "B. many",
    "c": "C. few",
    "d": "D. earlier",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The <b>pioneers</b> left a blazing trial of courage, manliness and chivalry.</p>",
    "a": "A. inventors",
    "b": "B. explorers",
    "c": "C. colonialist",
    "d": "D. settlers",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>He has a <b>propensity</b> for getting into debt.</p>",
    "a": "A. natural tendency",
    "b": "B. aptitude",
    "c": "C. characteristic",
    "d": "D. quality",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>That young is quite <b>sanguine</b> about the result of his competitive examination.</p>",
    "a": "A. depressed",
    "b": "B. pessimistic",
    "c": "C. anxious",
    "d": "D. optimistic",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>He is <b>averse</b> to the idea of holding elections now.</p>",
    "a": "A. convinced",
    "b": "B. angry",
    "c": "C. agreeable",
    "d": "D. opposed",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The thief <b>outwitted</b> the constable on some pretext and disappeared on the way to the police station.</p>",
    "a": "A. defeated",
    "b": "B. be fooled",
    "c": "C. cheated",
    "d": "D. outmanoeuvred",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Silence is <b>mandatory</b> for meditation to be effective.</p>",
    "a": "A. compulsory",
    "b": "B. necessary",
    "c": "C. required",
    "d": "D. needed",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>We should always try to maintain and promote communal <b>amity</b>.</p>",
    "a": "A. bondage",
    "b": "B. contention",
    "c": "C. friendship",
    "d": "D. understanding",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The soldier displayed <b>exceptional</b> courage and saved Major from the enemy's hand.</p>",
    "a": "A. avoidable",
    "b": "B. unusual",
    "c": "C. strange",
    "d": "D. abnormal",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Public figures should not indulge in <b>mud-slinging</b>.</p>",
    "a": "A. caricatures",
    "b": "B. mockery",
    "c": "C. slander",
    "d": "D. quarrelling",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The notice said that the meeting would begin <b> precisely</b> at 9.30 AM.</p>",
    "a": "A. approximately",
    "b": "B. exactly",
    "c": "C. accurately",
    "d": "D. concisely",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>That the plan is both inhuman and <b>preposterous</b> needs no further proof.</p>",
    "a": "A. heartless",
    "b": "B. impractical",
    "c": "C. absurd",
    "d": "D. abnormal",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The prisoner has been <b>languishing</b> in the jail for the last many years.</p>",
    "a": "A. convicted",
    "b": "B. suffering",
    "c": "C. attempting",
    "d": "D. avoiding",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>As the driver was <b>inebriated</b> he could not control the car.</p>",
    "a": "A. inexperienced",
    "b": "B. tired",
    "c": "C. befuddled",
    "d": "D. intoxicated",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>When the police questioned him, he gave very <b>incoherent</b> answer at first.</p>",
    "a": "A. irrational",
    "b": "B. inconsistent",
    "c": "C. irrelevant",
    "d": "D. irritating",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Even today many people are guided by <b>abstruse</b> moral values.</p>",
    "a": "A. dangerous",
    "b": "B. impracticable",
    "c": "C. obscure",
    "d": "D. irrational",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Instead of putting up a united front against on common enemy, the medieval states frittered away their energy in <b>internecine</b> warfare.</p>",
    "a": "A. mutually destructive",
    "b": "B. baneful",
    "c": "C. pernicious",
    "d": "D. detrimental",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Few teachers have been spared the problem of an <b>obstreperous</b> pupil in the class.</p>",
    "a": "A. sullen",
    "b": "B. unruly",
    "c": "C. lazy",
    "d": "D. awkward",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The story is too fantastic to be <b> credible</b>.</p>",
    "a": "A. believable",
    "b": "B. false",
    "c": "C. readable",
    "d": "D. praiseworthy",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>They feel that we should be fully aware of our own <b>environment</b>.</p>",
    "a": "A. nationality",
    "b": "B. heredity",
    "c": "C. nature",
    "d": "D. surroundings",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>No one will invite her to a tea party for she is so <b>garrulous</b>.</p>",
    "a": "A. talks a lot",
    "b": "B. giggles all the time",
    "c": "C. laughs a lot",
    "d": "D. repeats gossip",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The <b>aberration</b> in the Indian Economy can be attributed to short-sightedness of its political masters.</p>",
    "a": "A. procrastination",
    "b": "B. privilege",
    "c": "C. deviation",
    "d": "D. steadfastness",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Traffic being what it is, it is <b>lamentable</b> that our roads are unable to take the load.</p>",
    "a": "A. unpardonable",
    "b": "B. deplorable",
    "c": "C. inexcusable",
    "d": "D. terrible",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>A <b>rupture</b> in the relationship of two brothers is quite apparent.</p>",
    "a": "A. break",
    "b": "B. damage",
    "c": "C. breach",
    "d": "D. gap",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>His visit to foreign countries brought about a <b>sea-change</b> in his outlook and his attitude to people.</p>",
    "a": "A. complete change",
    "b": "B. partial change",
    "c": "C. favourable change",
    "d": "D. unfavourable change",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Only those who are <b> gullible </b> take every advertisement seriously.</p>",
    "a": "A. fallible",
    "b": "B. enthusiastic",
    "c": "C. unsuspecting",
    "d": "D. unrealistic",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Whatever opinion he give is <b>sane</b></p>",
    "a": "A. rational",
    "b": "B. obscure",
    "c": "C. wild",
    "d": "D. arrogant",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The recent acts of <b>vandalism</b> in the country cannot be ignored.</p>",
    "a": "A. disturbance",
    "b": "B. ravage",
    "c": "C. provocation",
    "d": "D. violence",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>It took him a long time to <b>come round</b> after the operation.</p>",
    "a": "A. recover",
    "b": "B. walk",
    "c": "C. move",
    "d": "D. eat",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>I don't like <b>alien</b> fashions.</p>",
    "a": "A. foreign",
    "b": "B. extraneous",
    "c": "C. unusual",
    "d": "D. exotic",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Catching snakes can be <b>hazardous</b> for people untrained in the art.</p>",
    "a": "A. tricky",
    "b": "B. harmful",
    "c": "C. difficult",
    "d": "D. dangerous",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The inspector was a <b>vigilant</b> young man.</p>",
    "a": "A. intelligent",
    "b": "B. ambitious",
    "c": "C. watchful",
    "d": "D. smart",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>I wrote to him as <b>lately</b> as last week.</p>",
    "a": "A. immediately",
    "b": "B. early",
    "c": "C. recently",
    "d": "D. late",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Many species of animals have become <b>extinct</b> during the last hundred years.</p>",
    "a": "A. aggressive",
    "b": "B. non-existent",
    "c": "C. scattered",
    "d": "D. feeble.",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The tablet <b>alleviated</b> the pain, and the patient was soon feeling much better.</p>",
    "a": "A. mitigated",
    "b": "B. moderated",
    "c": "C. removed",
    "d": "D. lightened",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The International Community may begin to doubt the <b>credentials</b> of the largest democracy in the world.</p>",
    "a": "A. principles",
    "b": "B. dependability",
    "c": "C. capacity to return loans",
    "d": "D. trustworthiness",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>They were totally unaware of the <b>impending</b> disaster.</p>",
    "a": "A. threatening",
    "b": "B. imminent",
    "c": "C. terrible",
    "d": "D. possible",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The general policies will <b>relieve</b> the sufferings of the common man.</p>",
    "a": "A. alleviate",
    "b": "B. mitigate",
    "c": "C. moderate",
    "d": "D. abate",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The underworld still makes solid profit out of <b>illicit</b> liquor.</p>",
    "a": "A. indigenous",
    "b": "B. illegitimate",
    "c": "C. illegal",
    "d": "D. country",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>True religion does not require one to <b>proselytise</b> through guile or force.</p>",
    "a": "A. translate",
    "b": "B. hypnotise",
    "c": "C. attack",
    "d": "D. convert",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The small boy was able to give a <b>graphic</b> description of the thief.</p>",
    "a": "A. picture",
    "b": "B. drawing",
    "c": "C. vivid",
    "d": "D. broad",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>\" I have learnt a great deal working factories, and for a time I've never been a weaver. Here are my <b>testimonials</b>, Mr. Davis\"</p>",
    "a": "A. witnesses",
    "b": "B. testaments",
    "c": "C. tokens",
    "d": "D. credentials",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The claims of students look hollow when they <b>attribute</b> their poor performance to difficulty of examination.</p>",
    "a": "A. infer",
    "b": "B. impute",
    "c": "C. inhere",
    "d": "D. inundate",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The angry villagers have <b>lynched</b> two suspected child-lifters already.</p>",
    "a": "A. beaten up",
    "b": "B. captured",
    "c": "C. killed",
    "d": "D. mutilated",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Some people just cannot <b>compromise</b> where truth is concerned.</p>",
    "a": "A. adjust",
    "b": "B. accommodate",
    "c": "C. yield",
    "d": "D. conciliate",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>He listened of my request with <b>indifference</b>.</p>",
    "a": "A. disinterest",
    "b": "B. concern",
    "c": "C. displeasure",
    "d": "D. caution",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The soldier provided his <b>mettle</b> in the battlefield.</p>",
    "a": "A. persistence",
    "b": "B. stamina and strength",
    "c": "C. courage and endurance",
    "d": "D. heroism",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Japan has been very much <b>eulogised</b> in this book.</p>",
    "a": "A. appreciated",
    "b": "B. praised",
    "c": "C. approved",
    "d": "D. applauded",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The time I spent in the library was a most <b>rewarding</b> one.</p>",
    "a": "A. profitable",
    "b": "B. paying",
    "c": "C. serviceable",
    "d": "D. precious",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The <b>benevolence</b> of the God of Rain has seen a very successful monsoon this year too</p>",
    "a": "A. ill-will",
    "b": "B. kindness",
    "c": "C. morbidity",
    "d": "D. vision",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Whatever the <b>verdict</b> of history may be, Chaplin will occupy a unique place in its pages.</p>",
    "a": "A. judgement",
    "b": "B. voice",
    "c": "C. outcome",
    "d": "D. prediction",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Even though singing of ballads is no longer <b>lucrative</b> the Bhopas  of Rajasthan continue to sing them in order to cherish the memory of their royal warriors.</p>",
    "a": "A. tempting",
    "b": "B. attractive",
    "c": "C. profitable",
    "d": "D. honourable",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p><b>Incensed</b> by his rude behaviour, the manager suspended the worker.</p>",
    "a": "A. excited",
    "b": "B. inflamed",
    "c": "C. enraged",
    "d": "D. enthused",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The poem is written in a very <b>lucid</b> style.</p>",
    "a": "A. elaborate",
    "b": "B. clear",
    "c": "C. noble",
    "d": "D. intricate",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The base of an Indian Politicians is the group of <b>sycophants</b> around them who earn bad name for their leaders.</p>",
    "a": "A. submissive",
    "b": "B. foppish",
    "c": "C. flatterers",
    "d": "D. jarnor",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>He was wanted at the <b>outset</b> of his career.</p>",
    "a": "A. end",
    "b": "B. beginning",
    "c": "C. middle",
    "d": "D. entrance",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>When youngsters do not have good role-model to <b>emulate</b> they start searching for them amongst Sportsmen of Filmstars.</p>",
    "a": "A. imitate",
    "b": "B. modify",
    "c": "C. mollify",
    "d": "D. inhabit",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The novel was so interesting that I was <b> oblivious</b> of my surroundings.</p>",
    "a": "A. precarious",
    "b": "B. unmindful",
    "c": "C. aware",
    "d": "D. watchful",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>All the characters in this novel are <b>fictitious</b>.</p>",
    "a": "A. unbelievable",
    "b": "B. unreliable",
    "c": "C. infamous",
    "d": "D. unreal",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Everyone was listening to the news of earthquake with mounting <b>anxiety</b>.</p>",
    "a": "A. curiosity",
    "b": "B. grief",
    "c": "C. uneasiness",
    "d": "D. eagerness",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>He <b>corroborated</b> the statement of his brother.</p>",
    "a": "A. confirmed",
    "b": "B. disproved",
    "c": "C. condemned",
    "d": "D. seconded",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The prince fell in love with a <b>comely</b> young maiden.</p>",
    "a": "A. delightful",
    "b": "B. pretty",
    "c": "C. homely",
    "d": "D. elegant",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>When I look back over there wartime years I cannot help feeling that time is an inadequate and even <b>capricious</b> measure of their duration at one moment they seem so long, at another so short.</p>",
    "a": "A. misleading",
    "b": "B. whimsical",
    "c": "C. erratic",
    "d": "D. unpredictable",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Manish <b>neglected</b> to remit the fees in time and therefore had to pay a fine.</p>",
    "a": "A. refused",
    "b": "B. failed",
    "c": "C. promised",
    "d": "D. obstructed",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Some of the Asian countries have been <b>enmeshed</b> in an inescapable debt trap.</p>",
    "a": "A. entangled",
    "b": "B. hit",
    "c": "C. struck",
    "d": "D. ensured",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>She <b>baffled</b> all our attempts to find her.</p>",
    "a": "A. defeated",
    "b": "B. thwarted",
    "c": "C. foiled",
    "d": "D. circumvented",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>It is a <b>scandal</b> that the murderer was declared innocent.</p>",
    "a": "A. silly notion",
    "b": "B. talk",
    "c": "C. rumour",
    "d": "D. disgraceful action",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Everybody likes him because he is an <b>industrious</b> student.</p>",
    "a": "A. energetic",
    "b": "B. prompt",
    "c": "C. excellent",
    "d": "D. diligent",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The young man appears to be quite <b>headstrong</b>.</p>",
    "a": "A. thick-headed",
    "b": "B. obstinate",
    "c": "C. robust",
    "d": "D. witty",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>As soon as he finished his speech, there was <b>spontaneous</b> applause from the audience.</p>",
    "a": "A. well-timed",
    "b": "B. willing",
    "c": "C. instinctive",
    "d": "D. instantaneous",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The president of the party <b>deprecated</b> the move of the Government to introduce electoral reforms in a haste.</p>",
    "a": "A. welcomed",
    "b": "B. denied",
    "c": "C. protested",
    "d": "D. humiliated",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>He found a <b>lucrative</b> assignment.</p>",
    "a": "A. good",
    "b": "B. profitable",
    "c": "C. excellent",
    "d": "D. significiant",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>A person unrestrained by the rules of morality or tradition is called a <b>licentious</b> person.</p>",
    "a": "A. libertine",
    "b": "B. loafer-type",
    "c": "C. criminal",
    "d": "D. freelance",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The leader nodded his <b>approbation</b>.</p>",
    "a": "A. understanding",
    "b": "B. approval",
    "c": "C. admiration",
    "d": "D. appreciation",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>When he returned he was accompanied by a <b>sprightly</b> young girl.</p>",
    "a": "A. beautiful",
    "b": "B. lively",
    "c": "C. intelligent",
    "d": "D. sportive",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Being a member of this club, he has certain <b>rights</b>.</p>",
    "a": "A. status",
    "b": "B. truth",
    "c": "C. virtues",
    "d": "D. privileges",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>When he could not endure the cruel ragging any longer, the new recruit bravely <b>stood up to</b> all his bullying seniors.</p>",
    "a": "A. challenged",
    "b": "B. fought back",
    "c": "C. resisted",
    "d": "D. defeated",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>His style is quite <b>transparent</b>.</p>",
    "a": "A. verbose",
    "b": "B. involved",
    "c": "C. lucid",
    "d": "D. witty",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The invasion force had no artillery and was completely <b>annihilated</b>.</p>",
    "a": "A. dismembered",
    "b": "B. reduced",
    "c": "C. destroyed",
    "d": "D. split",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The courage shown by the soldiers at this moment of crisis is <b>exemplary</b>.</p>",
    "a": "A. suitable",
    "b": "B. clear",
    "c": "C. elementary",
    "d": "D. admirable",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>Swift is known in the world of letters for his <b>misogynism</b>.</p>",
    "a": "A. hate for mankind",
    "b": "B. hate for womankind",
    "c": "C. love for the reasonable",
    "d": "D. love for the womankind",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
},{
    "qtext": "In each of the sentences given below a word is printed in bold. Below it four choices are given. Pick up the one which is most nearly the same in meaning as the word printer in bold and can replaces it without altering the meaning of the sentence.\n\n<p>The <b>indiscriminate</b> demand for mass consumption goods is deplorable.</p>",
    "a": "A. desperate",
    "b": "B. undifferentiated",
    "c": "C. discreet",
    "d": "D. insensitive",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Synonyms",
    "section": "(English)"
}


]}
