[
{
    "qtext": "Grand Central Terminal, Park Avenue, New York is the world's",
    "a": "A. largest railway station",
    "b": "B. highest railway station",
    "c": "C. longest railway station",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Entomology is the science that studies",
    "a": "A. Behavior of human beings",
    "b": "B. Insects",
    "c": "C. The origin and history of technical and scientific terms",
    "d": "D. The formation of rocks",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Eritrea, which became the 182nd member of the UN in 1993, e continent of</p>",
    "a": "A. Asia",
    "b": "B. Africa",
    "c": "C. Europe",
    "d": "D. Australia",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Garampani sanctuary is located at",
    "a": "A. Junagarh, Gujarat",
    "b": "B. Diphu, Assam",
    "c": "C. Kohima, Nagaland",
    "d": "D. Gangtok, Sikkim",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "For which of the following disciplines is Nobel Prize awarded",
    "a": "A. Physics and Chemistry",
    "b": "B. Physiology or Medicine",
    "c": "C. Literature, Peace and Economics",
    "d": "D. All of the above",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Hitler party which came into power in 1933 is known as",
    "a": "A. Labour Party",
    "b": "B. Nazi Party",
    "c": "C. Ku-Klux-Klan",
    "d": "D. Democratic Party",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "FFC stands for",
    "a": "A. Foreign Finance Corporation",
    "b": "B. Film Finance Corporation",
    "c": "C. Federation of Football Council",
    "d": "D. None of the above",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Fastest shorthand writer was",
    "a": "A. Dr. G.  D. Bist",
    "b": "B. J.R.D. Tata",
    "c": "C. J.M. Tagore",
    "d": "D. Khudada Khan",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Epsom (England) is the place associated with",
    "a": "A. Horse racing",
    "b": "B. Polo",
    "c": "C. Shooting",
    "d": "D. Snooker",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "First human heart transplant operation conducted by Drd on Louis Washkansky, was conducted in</p>",
    "a": "A. 1967",
    "b": "B. 1968",
    "c": "C. 1958",
    "d": "D. 1922",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Galileo was an Italian astronomer who",
    "a": "A. developed the telescope",
    "b": "B. discovered four satellites of Jupiter",
    "c": "C. discovered that the movement of pendulum produces a regular time measurement",
    "d": "D. All of the above",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Habeas Corpus Act 1679",
    "a": "A. states that no one was to be imprisoned without a writ or warrant stating the charge against him",
    "b": "B. provided facilities to a prisoner to obtain either speedy trial or release in bail",
    "c": "C. safeguarded the personal liberties of the people against arbitrary imprisonment by the king's orders",
    "d": "D. All of the above",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Exposure to sunlight helps a person improve his health because",
    "a": "A. the infrared light kills bacteria in the body",
    "b": "B. resistance power increases",
    "c": "C. the pigment cells in the skin get stimulated and produce a healthy tan",
    "d": "D. the ultraviolet rays convert skin oil into Vitamin D",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Golf player Vijay Singh belongs to which country",
    "a": "A. USA",
    "b": "B. Fiji",
    "c": "C. India",
    "d": "D. UK",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Guarantee to an exporter that the importer of his goods y for the goods ordered by him, is known as</p>",
    "a": "A. Letter of Credit (L/C)",
    "b": "B. laissezfaire",
    "c": "C. inflation",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "First Afghan War took place in",
    "a": "A. 1839",
    "b": "B. 1843",
    "c": "C. 1833",
    "d": "D. 1848",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Gulf cooperation council was originally formed by",
    "a": "A. Bahrain, Kuwait, Oman, Qatar, Saudi Arabia and United Arab Emirates",
    "b": "B. Second World Nations",
    "c": "C. Third World Nations",
    "d": "D. Fourth World Nations",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "First China War was fought between",
    "a": "A. China and Britain",
    "b": "B. China and France",
    "c": "C. China and Egypt",
    "d": "D. China and Greek",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Dumping is",
    "a": "A. selling of goods abroad at a price well below the production cost at the home market price",
    "b": "B. the process by which the supply of a manufacture's product remains low in the domestic market, which batches him better price",
    "c": "C. prohibited by regulations of GATT",
    "d": "D. All of the above",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "For the Olympics and World Tournaments, the dimensions t are</p>",
    "a": "A. 26 m x 14 m",
    "b": "B. 28 m x 15 m",
    "c": "C. 27 m x 16 m",
    "d": "D. 28 m x 16 m",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Federation Cup, World Cup, Allywyn International Trophy p are awarded to winners of</p>",
    "a": "A. Tennis",
    "b": "B. Volleyball",
    "c": "C. Basketball",
    "d": "D. Cricket",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Each year World Red Cross and Red Crescent Day is celebrated on",
    "a": "A. May 8",
    "b": "B. May 18",
    "c": "C. June 8",
    "d": "D. June 18",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Famous sculptures depicting art of love built some time in 950 AD D are</p>",
    "a": "A. Khajuraho temples",
    "b": "B. Jama Masjid",
    "c": "C. Sun temple",
    "d": "D. Mahabalipuram temples",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Gravity setting chambers are used in industries to remove",
    "a": "A. SOx",
    "b": "B. NOx",
    "c": "C. suspended particulate matter",
    "d": "D. CO",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Guwahati High Court is the judicature of",
    "a": "A. Nagaland",
    "b": "B. Arunachal Pradesh",
    "c": "C. Assam",
    "d": "D. All of the above",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Friction can be reduced by changing from",
    "a": "A. sliding to rolling",
    "b": "B. rolling to sliding",
    "c": "C. potential energy to kinetic energy",
    "d": "D. dynamic to static",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "During eleventh Antarctic Expedition in Nov. 1991/March s installed.</p>",
    "a": "A. SODAR (SOnic Detection And Ranging)",
    "b": "B. Second Permanent Station 'Maitree'",
    "c": "C. First permanent station 'Dakshin Gangotri'",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "From the following, choose the set in which names of Secretaryf the UNO are arranged in correct chronological order?</p>",
    "a": "A. U Thant, Kurt Waldheim, Dag Hammarskjoeld, Trygve Lie.",
    "b": "B. Trygve Lie, Dag Hammarskjoeld, U Thant, Kurt Waldheim.",
    "c": "C. Trygve Lie, U Thant , Dag Hammarskjoeld, Kurt Waldheim.",
    "d": "D. U Thant, Dag Hammarskjoeld, Trygve Lie, Kurt Waldheim.",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Fire temple is the place of worship of which of the following religion",
    "a": "A. Taoism",
    "b": "B. Judaism",
    "c": "C. Zoroastrianism (Parsi Religion)",
    "d": "D. Shintoism",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Film and TV institute of India is located at",
    "a": "A. Pune (Maharashtra)",
    "b": "B. Rajkot (Gujarat)",
    "c": "C. Pimpri (Maharashtra)",
    "d": "D. Perambur (Tamilnadu)",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Georgia, Uzbekistan and Turkmenistan became the members of UNO in",
    "a": "A. 1991",
    "b": "B. 1992",
    "c": "C. 1993",
    "d": "D. 1994",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Guru Gobind Singh was",
    "a": "A. the 10th Guru of the Sikhs",
    "b": "B. founder of Khalsa, the inner council of the Sikhs in 1699",
    "c": "C. author of Dasam Granth",
    "d": "D. All the above",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Hermann Scheer (Germany) received right Livelihood Award in 1999 for",
    "a": "A. his indefatigable work for thepromotion of solar energy worldwide",
    "b": "B. his long standing efforts to end the impunity of dictators",
    "c": "C. showing that organic agriculture is a key to both environmental sustainability and food security",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Germany signed the Armistice Treaty on ____ and World War I ended",
    "a": "A. January 19, 1918",
    "b": "B. May 30, 1918",
    "c": "C. November 11, 1918",
    "d": "D. February 15, 1918",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "During World War II, when did Germany attack France",
    "a": "A. 1940",
    "b": "B. 1941",
    "c": "C. 1942",
    "d": "D. 1943",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Frederick Sanger is a twice recipient of the Nobel Prize for",
    "a": "A. Chemistry in 1958 and 1980",
    "b": "B. Physics in 1956 and 1972",
    "c": "C. Chemistry in 1954 and Peace in 1962",
    "d": "D. Physics in 1903 and Chemistry in 1911",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "The ozone layer restricts",
    "a": "A. Visible light",
    "b": "B. Infrared radiation",
    "c": "C. X-rays and gamma rays",
    "d": "D. Ultraviolet radiation",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Eugenics is the study of",
    "a": "A. altering human beings by changing their genetic components",
    "b": "B. people of European origin",
    "c": "C. different races of mankind",
    "d": "D. genetic of plants",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Euclid was",
    "a": "A. Greek mathematician",
    "b": "B. Contributor to the use of deductive principles of logic as the basis of geometry",
    "c": "C. Propounded the geometrical theorems",
    "d": "D. All of the above",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Ecology deals with",
    "a": "A. Birds",
    "b": "B. Cell formation",
    "c": "C. Relation between organisms and their environment",
    "d": "D. Tissues",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Filaria is caused by",
    "a": "A. Bacteria",
    "b": "B. Mosquito",
    "c": "C. Protozoa",
    "d": "D. Virus",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Goa Shipyard Limited (GSL) was established in",
    "a": "A. 1958",
    "b": "B. 1957",
    "c": "C. 1956",
    "d": "D. 1955",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "DRDL stands for",
    "a": "A. Defence Research and Development Laboratary",
    "b": "B. Department of Research and Development Laboratory",
    "c": "C. Differential Research and Documentation Laboratary",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Who was the first Indian Chief of Army Staff of the Indian Army ",
    "a": "A. Gen. K.M. Cariappa",
    "b": "B. Vice-Admiral R.D. Katari",
    "c": "C. Gen. Maharaja Rajendra Singhji",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "FRS stands for",
    "a": "A. Fellow Research System",
    "b": "B. Federation of Regulation Society",
    "c": "C. Fellow of Royal Society",
    "d": "D. None of the above",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Escape velocity of a rocket fired from the earth towards a velocity to get rid of the</p>",
    "a": "A. Earth's gravitational pull",
    "b": "B. Moon's gravitational pull",
    "c": "C. Centripetal force due to the earth's rotation",
    "d": "D. Pressure of the atmosphere",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "GATT (General Agreement on Tariffs and Trade) is",
    "a": "A. international agreement signed in 1947 between non-communist nations with the object of encouraging international trade unobstructed by tariff barriers",
    "b": "B. agreement which seeks to achieve its aim by arranging and encouraging bargaining with trade concessions between members",
    "c": "C. Both option A and B",
    "d": "D. None of the above",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Coral reefs in India can be found in",
    "a": "A. the coast of Orissa",
    "b": "B. Waltair",
    "c": "C. Rameshwaram",
    "d": "D. Trivandrum",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "For safety, the fuse wire used in the mains for f electricity must be made of metal having</p>",
    "a": "A. low melting point",
    "b": "B. high resistance",
    "c": "C. high melting point",
    "d": "D. low specific heat",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Golden Temple, Amritsar is India's",
    "a": "A. largest Gurdwara",
    "b": "B. oldest Gurudwara",
    "c": "C. Both option A and B are correct",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "During World War I Germany was defeated in the Battle of e western front and Romania declared war on the eastern front in the year</p>",
    "a": "A. 1914 AD",
    "b": "B. 1915 AD",
    "c": "C. 1916 AD",
    "d": "D. 1917 AD",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Heavy Water Project (Talcher) and Fertilizer plant (Paradeeps industries of</p>",
    "a": "A. Orissa",
    "b": "B. Tamil nadu",
    "c": "C. Andhra Pradesh",
    "d": "D. Kerala",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Hamid Karzai was chosen president of Afghanistan in",
    "a": "A. 2000",
    "b": "B. 2001",
    "c": "C. 2002",
    "d": "D. 2003",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Durand Cup is associated with the game of",
    "a": "A. Cricket",
    "b": "B. Football",
    "c": "C. Hockey",
    "d": "D. Volleyball",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Headquarters of UNO are situated at",
    "a": "A. New York, USA",
    "b": "B. Hague (Netherlands)",
    "c": "C. Geneva",
    "d": "D. Paris",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "First International Peace Congress was held in London in",
    "a": "A. 1564 AD",
    "b": "B. 1798 AD",
    "c": "C. 1843 AD",
    "d": "D. 1901 AD",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "For seeing objects at the surface of water from a submarine under e instrument used is</p>",
    "a": "A. kaleidoscope",
    "b": "B. periscope",
    "c": "C. spectroscope",
    "d": "D. telescope",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Dr. Zakir Hussain was",
    "a": "A. the first Muslim president of India",
    "b": "B. first vice president of India",
    "c": "C. first president of Indian National Congress",
    "d": "D. first speaker of Lok Sabha",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "G-15 is an economic grouping of",
    "a": "A. First World Nations",
    "b": "B. Second World Nations",
    "c": "C. Third World Nations",
    "d": "D. Fourth World Nations",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Fathometer is used to measure",
    "a": "A. Earthquakes",
    "b": "B. Rainfall",
    "c": "C. Ocean depth",
    "d": "D. Sound intensity",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "For galvanizing iron which of the following metals is used",
    "a": "A. Aluminium",
    "b": "B. Copper",
    "c": "C. Lead",
    "d": "D. Zinc",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Economic goods are",
    "a": "A. all commodities that are limited in quantity as compared to their demand",
    "b": "B. Commodities that is available according to their demand",
    "c": "C. Commodities that is available more as compared to demand",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "For purifying drinking water alum is used",
    "a": "A. for coagulation of mud particles",
    "b": "B. to kill bacteria",
    "c": "C. to remove salts",
    "d": "D. to remove gases",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Hockey was introduced in the Asian Games in",
    "a": "A. 1958 in Tokyo",
    "b": "B. 1962 in Jakarta",
    "c": "C. 1966 in Bangkok",
    "d": "D. 1970 in Bangkok",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "ESCAP stands for",
    "a": "A. Economic and Social Commission for Asia and Pacific",
    "b": "B. European Society Council for Africa and Pacific",
    "c": "C. Economic and Social Commission for Africa and Pacific",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Firdausi was",
    "a": "A. a poet",
    "b": "B. well known for his epic 'Shahnama'",
    "c": "C. Both option A and B",
    "d": "D. None of the above",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Himalayan Mountaineering Institute is at",
    "a": "A. Darjeeling",
    "b": "B. Dehradun",
    "c": "C. Marmago",
    "d": "D. Dispur",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Gabriel Daniel Fahrenheit was",
    "a": "A. a German Physicist",
    "b": "B. developed the mercury thermometer in 1714",
    "c": "C. devised temperature scale",
    "d": "D. All of the above",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "During the first crusade, crusaders reached Jerusalem and </p>",
    "a": "A. 1000 AD",
    "b": "B. 1099 AD",
    "c": "C. 1200 AD",
    "d": "D. 1515 AD",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Dr. Linus Carl Pauling is the only person to have won s individually for</p>",
    "a": "A. Chemistry in 1954, Peace Prize in 1962",
    "b": "B. Peace Prize in 1954, Chemistry in 1962",
    "c": "C. Physics in 1954, Medicine in 1962",
    "d": "D. Medicine in 1954, Physics in 1962",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Free market is",
    "a": "A. a condition in the international market where nations do not impose customs duty or other taxes on import of goods",
    "b": "B. market where the price of a commodity is determined by free play of the forces of supply and demand",
    "c": "C. ports that are exempted from payment of customs duty on articles of commerce, primarily to encourage tourism",
    "d": "D. None of the above",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "East Timor, which became the 191st member of the UN, is in </p>",
    "a": "A. Asia",
    "b": "B. Africa",
    "c": "C. Europe",
    "d": "D. South America",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Free surface of a liquid behaves like a sheet and tends to e smallest possible area due to the</p>",
    "a": "A. force of adhesion",
    "b": "B. force of friction",
    "c": "C. centrifugal force",
    "d": "D. force of cohesion",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Gopal Krishna Gokhale",
    "a": "A. started as a maths teacher and rose to the position of the principal of Ferguson College, Pune",
    "b": "B. founded the servants of India Society",
    "c": "C. served as President of the Indian National Congress in 1905",
    "d": "D. All of the above",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "GNLF stands for",
    "a": "A. Gorkha National Liberation Front",
    "b": "B. Gross National Liberation Form",
    "c": "C. Both option A and B",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Excessive secretion from the pituitary gland in the children results in",
    "a": "A. increased height",
    "b": "B. retarded growth",
    "c": "C. weakening of bones",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
},{
    "qtext": "Fa-Hien was",
    "a": "A. the first Buddhist pilgrim of China to visit India during the reign of Chandragupta Vikramaditya",
    "b": "B. the discoverer of Puerto Rico and Jamaica",
    "c": "C. the first Buddhist pilgrim of India to visit China",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Basic General Knowledge",
    "section": "(General Awareness)"
}]
