{
  "data": [
    {
      "qtext": "The Centre for Cellular and Molecular Biology is situated at",
      "a": "A. Patna",
      "b": "B. Jaipur",
      "c": "C. Hyderabad",
      "d": "D. New Delhi",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Where is the Railway Staff College located?",
      "a": "A. Pune",
      "b": "B. Allahabad",
      "c": "C. Vadodara",
      "d": "D. Delhi",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The famous Dilwara Temples are situated in",
      "a": "A. Uttar Pradesh",
      "b": "B. Rajasthan",
      "c": "C. Maharashtra",
      "d": "D. Madhya Pradesh",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Wadia Institute of Himalayan Geology is located at",
      "a": "A. Delhi",
      "b": "B. Shimla",
      "c": "C. Dehradun",
      "d": "D. Kulu",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Bijapur is known for its",
      "a": "A. severe drought condition",
      "b": "B. Gol Gumbaz",
      "c": "C. heavy rainfall",
      "d": "D. statue of Gomateswara",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The headquarters of the National Power Training institute is located in",
      "a": "A. Pune",
      "b": "B. Bhopal",
      "c": "C. Faridabad",
      "d": "D. Lucknow",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The Dr. Babasaheb Ambedkar Marathwada University is at which of the following places?",
      "a": "A. Aurangabad",
      "b": "B. Nanded",
      "c": "C. Parbhani",
      "d": "D. Nagpur",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The Indian Institute of Science is located at",
      "a": "A. Kerala",
      "b": "B. Madras",
      "c": "C. Bangalore",
      "d": "D. New Delhi",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'Bagh', a village in Gwalior is famous for",
      "a": "A. Sculptures",
      "b": "B. Architecture",
      "c": "C. Cave Painting",
      "d": "D. All of the above",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which city is known as 'Electronic City of India'?",
      "a": "A. Mumbai",
      "b": "B. Hyderabad",
      "c": "C. Guragon",
      "d": "D. Bangalore",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Indian School of Mines is located in",
      "a": "A. Dhanbad",
      "b": "B. Asansol",
      "c": "C. Tatanagar",
      "d": "D. Rourkela",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following place is famous for its gigantic rock-cut statue of Buddha?",
      "a": "A. Bamiyan",
      "b": "B. Borobudur",
      "c": "C. Anuradhapuram",
      "d": "D. Angor Vat",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Siachen is a",
      "a": "A. desert frontier zone between India and Pakistan",
      "b": "B. frontier zone between China and India",
      "c": "C. frontier zone between India and Myanmar",
      "d": "D. glacier frontier zone between India and Pakistan",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Golden Temple is situated in",
      "a": "A. New Delhi",
      "b": "B. Agra",
      "c": "C. Amritsar",
      "d": "D. Mumbai",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Where is the headquarters of Oil and Natural Gas Commission?",
      "a": "A. Dehradun",
      "b": "B. Vadodara",
      "c": "C. Digboi",
      "d": "D. Mumbai",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'Vijay Stambha' is situated in",
      "a": "A. Jaipur",
      "b": "B. Agra",
      "c": "C. Delhi",
      "d": "D. Chittor",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The 'Char Minar' is in",
      "a": "A. Ahmedabad",
      "b": "B. Hyderabad",
      "c": "C. Delhi",
      "d": "D. Sikri",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Where is the National Institute of Virology situated?",
      "a": "A. Pune",
      "b": "B. Delhi",
      "c": "C. Kolkata",
      "d": "D. Madras",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The 'satellite freight city' is being developed near which of the following cities?",
      "a": "A. New Delhi",
      "b": "B. Orissa",
      "c": "C. Gurgaon",
      "d": "D. Kolkata",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Central Arid Zone Research Institute is located in",
      "a": "A. Bihar",
      "b": "B. Gujarat",
      "c": "C. Rajasthan",
      "d": "D. Madhya Pradesh",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "National Institute of Nutrition is located in which of the following place?",
      "a": "A. Bangalore",
      "b": "B. Kerala",
      "c": "C. Gandhinagar",
      "d": "D. Hyderabad",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "National Institute of Aeronautical Engineering is located at",
      "a": "A. Dehradun",
      "b": "B. Lucknow",
      "c": "C. Bangalore",
      "d": "D. Delhi",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The world famous 'Khajuraho' sculptures are located in",
      "a": "A. Gujarat",
      "b": "B. Madhya Pradesh",
      "c": "C. Orissa",
      "d": "D. Maharashtra",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'Kandla' is situated on the Gulf of Kachh is well known for which of the following?",
      "a": "A. Export Processing Zone",
      "b": "B. Centre for Marine Food products",
      "c": "C. Cutting and Polishing of diamonds",
      "d": "D. Ship breaking industry",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "National Police Academy is located at",
      "a": "A. Bangalore",
      "b": "B. Hyderabad",
      "c": "C. Abu Road",
      "d": "D. Dehradun",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "National Archives is located at?",
      "a": "A. Calcutta",
      "b": "B. Dehradun",
      "c": "C. Bombay",
      "d": "D. New Delhi",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which is known as 'Garden City of India'?",
      "a": "A. Trivandram",
      "b": "B. Imphal",
      "c": "C. Simla",
      "d": "D. Bangalore",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The Central Rice Research institute is located at",
      "a": "A. Rajamundry",
      "b": "B. Madra",
      "c": "C. Cuttack",
      "d": "D. Cochin",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Where is the 'National Remote Sensing Agency' situated?",
      "a": "A. Shadnagar",
      "b": "B. Bangalore",
      "c": "C. Chennai",
      "d": "D. Dehradun",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Badrinath is situated on the bank of river",
      "a": "A. Ganga",
      "b": "B. Yamuna",
      "c": "C. Alaknanda",
      "d": "D. Saraswathi",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Indian Cancer Research institute is located at",
      "a": "A. New Delhi",
      "b": "B. Calcutta",
      "c": "C. Chennai",
      "d": "D. Mumbai",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Central Drug Research Institute is located at",
      "a": "A. Trissur",
      "b": "B. Nagpur",
      "c": "C. Mysore",
      "d": "D. Lucknow",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Ajanta-Ellora caves are situated near",
      "a": "A. Ajmer",
      "b": "B. Jaipur",
      "c": "C. Patna",
      "d": "D. Aurangabad",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "National School of Mines is located in ?",
      "a": "A. Dhanbad",
      "b": "B. Kavalpur",
      "c": "C. Udaipur",
      "d": "D. Hyderabad",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Sun Temple is situated at?",
      "a": "A. Konark",
      "b": "B. Bangalore",
      "c": "C. Haridwar",
      "d": "D. Kerala",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The 'Golconda Fort' is in which state?",
      "a": "A. Telangana",
      "b": "B. Uttar Pradesh",
      "c": "C. Bihar",
      "d": "D. Karnataka",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Under Mother Teresa's guidance, the Missionaries of Charit built near Asansol, a lep er  colony is called",
      "a": "A. Peace City",
      "b": "B. Sahara",
      "c": "C. Shanti Nagar",
      "d": "D. SOS",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'Kanchipuram' is in which of the following states?",
      "a": "A. Andhra Pradesh",
      "b": "B. Orissa",
      "c": "C. Kerala",
      "d": "D. Tamil Nadu",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The famous Meenakshi temple is located in",
      "a": "A. Bihar",
      "b": "B. Madurai",
      "c": "C. Madras",
      "d": "D. Trichy",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'Tin Bhiga' lease by India to Bangladesh, was a part of",
      "a": "A. West Bengal",
      "b": "B. Assam",
      "c": "C. Meghalaya",
      "d": "D. Tripura",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Vikram Sarabhai Space Centre is located at",
      "a": "A. Pune",
      "b": "B. Ahmedabad",
      "c": "C. Sriharikota",
      "d": "D. Thiruvananthapuram",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'Mandi House' is a",
      "a": "A. the office of the P.M.",
      "b": "B. the office of Director General of Doordarshan",
      "c": "C. the office of NFDC",
      "d": "D. the Doordarshan C.P.C",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The National Institute of Community Development is located at",
      "a": "A. Chennai",
      "b": "B. Pant Nagar",
      "c": "C. Hyderabad",
      "d": "D. Bangalore",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The famous Rock Garden is located in which city?",
      "a": "A. Jaipur",
      "b": "B. Lucknow",
      "c": "C. Simla",
      "d": "D. Chandigarh",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Sanchi Stupa is located near",
      "a": "A. Gaya",
      "b": "B. Bhopal",
      "c": "C. Varanasi",
      "d": "D. Bijapur",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "National Science Centre is located at",
      "a": "A. Bangalore",
      "b": "B. Bombay",
      "c": "C. Kolkata",
      "d": "D. Delhi",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Central Road Research Institute is in",
      "a": "A. Delhi",
      "b": "B. Bangalore",
      "c": "C. Roorkee",
      "d": "D. Hyderabad",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The world famous Ajanta caves are situated in",
      "a": "A. Orissa",
      "b": "B. Andhra Pradesh",
      "c": "C. Kerala",
      "d": "D. Maharashtra",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Where is Chitrakut situated?",
      "a": "A. Maharashtra",
      "b": "B. Uttar Pradesh",
      "c": "C. Bihar",
      "d": "D. Madhya Pradesh",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which city is called 'White City' of Rajasthan?",
      "a": "A. Bihar",
      "b": "B. Jaipur",
      "c": "C. Udaipur",
      "d": "D. Jodhpur",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The first Indian University was opened in 1857 was in",
      "a": "A. Chennai",
      "b": "B. Bihar",
      "c": "C. Mumbai",
      "d": "D. Kolkata",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The largest dry rock in India is situated at",
      "a": "A. Mumbai",
      "b": "B. Cochin",
      "c": "C. Marmugao",
      "d": "D. Kolkata",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The largest Indian State by area is",
      "a": "A. Rajasthan",
      "b": "B. Maharashtra",
      "c": "C. Uttar Pradesh",
      "d": "D. Madhya Pradesh",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which is the oldest monuments?",
      "a": "A. Qutub Minar",
      "b": "B. Ajanta Caves",
      "c": "C. Khajurah",
      "d": "D. Taj Mahal",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Ms. Harita Kaur has the distinction of being the first Indian Women",
      "a": "A. pilot to fly an aircraft solo",
      "b": "B. ambassador to a foreign country",
      "c": "C. to be inducted into Indian Navy",
      "d": "D. doctor to create first test tube baby",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The largest and the oldest museum of India is located in the state/union territory of",
      "a": "A. New Delhi",
      "b": "B. West Bengal",
      "c": "C. Andhra Pradesh",
      "d": "D. Uttar Pradesh",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The first Indian Satellite launched from Soviet Cosmodrome is?",
      "a": "A. Bhaskara",
      "b": "B. Bharat",
      "c": "C. Rohini",
      "d": "D. Aryabhatta",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The first nuclear reactor in India is",
      "a": "A. Dhurva",
      "b": "B. Harsha",
      "c": "C. Vipula",
      "d": "D. Apsara",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The first person of Indian origin to be appointed as a judge in U.S. is",
      "a": "A. P.A.Sangma",
      "b": "B. Basava Rajeswari",
      "c": "C. R.C.Bharadwaj",
      "d": "D. Ridhi Desai",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Largest Mint in India is located at",
      "a": "A. Nasik",
      "b": "B. Kolkata",
      "c": "C. Hyderabad",
      "d": "D. Mumbai",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "India's first 'Ladies Special' Suburban train was started by which of the Indian Railway Zone?",
      "a": "A. Southern",
      "b": "B. Northern",
      "c": "C. Western",
      "d": "D. Eastern",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The first electric train of India 'Deccan Queen' was run between",
      "a": "A. Howrah and Delhi",
      "b": "B. Bombay and Surat",
      "c": "C. Kalyan and Pune",
      "d": "D. New Delhi and Madras",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Who was the first Indian to go into space?",
      "a": "A. Ravi Malhotra",
      "b": "B. Satish Dawan",
      "c": "C. Kalpana Chawla",
      "d": "D. Rakesh Sharma",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The first 'Financial Service Park' for industry being set up at",
      "a": "A. Guragaon",
      "b": "B. Surat",
      "c": "C. Bangalore",
      "d": "D. Pune",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'Apsara' is the name of India's first",
      "a": "A. Railway Locomotive",
      "b": "B. Helicopter",
      "c": "C. Nuclear Reactor",
      "d": "D. Ground Battle Tank",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Famous Places in India",
      "section": "(General Awareness)"
    }
  ]
}
