{
"data":[{
    "qtext": "<p>Who is the father of Geometry?</p>",
    "a": "A. Aristotle",
    "b": "B. Euclid",
    "c": "C. Pythagoras",
    "d": "D. Kepler",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is common between Kutty, Shankar, Laxman and Sudhir Dar?</p>",
    "a": "A. Film Direction",
    "b": "B. Drawing Cartoons",
    "c": "C. Instrumental Music",
    "d": "D. Classical Dance",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was known as Iron man of India?</p>",
    "a": "A. Govind Ballabh Pant",
    "b": "B. Jawaharlal Nehru",
    "c": "C. Subhash Chandra Bose",
    "d": "D. Sardar Vallabhbhai Patel",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The Indian to beat the computers in mathematical wizardry is</p>",
    "a": "A. Ramanujam",
    "b": "B. Rina Panigrahi",
    "c": "C. Raja Ramanna",
    "d": "D. Shakunthala Devi",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Jude Felix is a famous Indian player in which of the fields?</p>",
    "a": "A. Volleyball",
    "b": "B. Tennis",
    "c": "C. Football",
    "d": "D. Hockey",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who among the following was an eminent painter?</p>",
    "a": "A. Sarada Ukil",
    "b": "B. Uday Shanker",
    "c": "C. V. Shantaram",
    "d": "D. Meherally",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Professor Amartya Sen is famous in which of the fields?</p>",
    "a": "A. Biochemistry",
    "b": "B. Electronics",
    "c": "C. Economics",
    "d": "D. Geology",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following was Satyajit Ray associated with?</p>",
    "a": "A. Classical music",
    "b": "B. Commercial art",
    "c": "C. Film Direction",
    "d": "D. Classical dance",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Dr. Joon Lew of korea, the recipient of international Gandhi Award is known for his service in the?</p>",
    "a": "A. Eradication of leprosy",
    "b": "B. Campaigning against AIDS",
    "c": "C. Against Drugs",
    "d": "D. Against child labour",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Amjad Ali Khan is associated with which of the following musical instruments?</p>",
    "a": "A. Sarod",
    "b": "B. Veena",
    "c": "C. Violin",
    "d": "D. Sitar",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Guru Gopi Krishna was a maestro of which of the following dance forma?</p>",
    "a": "A. Kuchipudi",
    "b": "B. Kathak",
    "c": "C. Manipuri",
    "d": "D. Bahratanatyam",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ms. Bachendri Pal had undertaken a unique expedition for focusing attention on which of these?</p>",
    "a": "A. One Nation one Family",
    "b": "B. The Girl Child",
    "c": "C. National Integration",
    "d": "D. Sprit of Adventure",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following fields A. Nageshwara Rao is associated with?</p>",
    "a": "A. Sports",
    "b": "B. Literature",
    "c": "C. Motion Pictures",
    "d": "D. Politics",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Jamini Roy was a famous?</p>",
    "a": "A. Producer",
    "b": "B. Painter",
    "c": "C. Dancer",
    "d": "D. Actor",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>In which field 'Aachan Maharaj' has distinguished himself?</p>",
    "a": "A. Painting",
    "b": "B. Drama",
    "c": "C. Dance",
    "d": "D. Vocal Music",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The name of Pierre Cardin is associated with which of the following fields?</p>",
    "a": "A. Painting",
    "b": "B. Films",
    "c": "C. Pop Music",
    "d": "D. Fashion Designing",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is well known collector of artefacts and curios?</p>",
    "a": "A. Wadeyar",
    "b": "B. Salar Jung",
    "c": "C. Rabindranath Tagore",
    "d": "D. Motilal Nehru",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ms. Vijaya Mehta has earned distinction in which of the field?</p>",
    "a": "A. Theatre",
    "b": "B. Film Direction",
    "c": "C. Classical Dance",
    "d": "D. Journalism",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Dr. M. S. Swaminathan has distinguished himself in which of the following fields?</p>",
    "a": "A. Agriculture",
    "b": "B. Medicine",
    "c": "C. Astrophysics",
    "d": "D. Physics",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Satyen Bose has shown his excellence in which of the following fields?</p>",
    "a": "A. Stage Acting",
    "b": "B. Drawing and Painting",
    "c": "C. Classical Dance",
    "d": "D. Motion Picture",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Charles Correa has distinguished himself in which of the following fields?</p>",
    "a": "A. Painting",
    "b": "B. Ballet",
    "c": "C. Architecture",
    "d": "D. Western Music",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who declared that his ultimate aim was to wipe 'every tear from every eye'?</p>",
    "a": "A. Rajendra Prasad",
    "b": "B. Sardar Patel",
    "c": "C. Jawaharlal Nehru",
    "d": "D. Mahatma Gandhi",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ashok Pandit is known for his outstanding performance in which field?</p>",
    "a": "A. Wrestling",
    "b": "B. Kabaddi",
    "c": "C. Shooting",
    "d": "D. Swimming",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who among the following is a social activist campaigning against child labour?</p>",
    "a": "A. Baba Amte",
    "b": "B. Shabana Amzi",
    "c": "C. Mira Nair",
    "d": "D. Swami Agnivesh",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Pandit K. G. Ginde, was well known for his contribution in the field of?</p>",
    "a": "A. Music",
    "b": "B. Sanskrit",
    "c": "C. Dance",
    "d": "D. Ayurveda",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who fits with this description 'Indian Cotton merchant, Banker, Congressman, a close associate of Mahatma Gandhi'?</p>",
    "a": "A. M. R. Jayakar",
    "b": "B. V. S. Sastri",
    "c": "C. G. D. Birla",
    "d": "D. Jamanlal Bajaj",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Pandit Jasraj has established his reputation in which of the following fields?</p>",
    "a": "A. Music",
    "b": "B. Literature",
    "c": "C. Sanskrit",
    "d": "D. Dance",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ustad Nisar hussain Khan earned distinction in which of the following fields?</p>",
    "a": "A. Vocal Music",
    "b": "B. Instrumental music",
    "c": "C. Acting",
    "d": "D. Classical dance",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>R. K. Laxman is a renowned</p>",
    "a": "A. Dance master",
    "b": "B. Writer",
    "c": "C. Cartoonist",
    "d": "D. Journalist",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Dr. Amiya Chakravarthy is known for his</p>",
    "a": "A. work in the Chipko movement",
    "b": "B. composing music for Ray's films",
    "c": "C. being literary Secretary to R. N. Tagore",
    "d": "D. patenting a living organism",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The first woman in space was</p>",
    "a": "A. Valentina Tereshkova",
    "b": "B. Sally Ride",
    "c": "C. Naidia Comenci",
    "d": "D. Tamara Press",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Mr. Sham Lal has done commendable work in the field of?</p>",
    "a": "A. Journalism",
    "b": "B. Politics",
    "c": "C. Socail Service",
    "d": "D. Trade Unionism",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ali Akbar plays which of the following musical instruments?</p>",
    "a": "A. Flute",
    "b": "B. Tabla",
    "c": "C. Sitar",
    "d": "D. Sarod",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Professor Malcolm Adiseshaih had earned worldwide distinction in which of the fields?</p>",
    "a": "A. Literature",
    "b": "B. Defence",
    "c": "C. Economics",
    "d": "D. Medicine",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Samantha Fox is associated with</p>",
    "a": "A. Politics",
    "b": "B. Pop music",
    "c": "C. Journalism",
    "d": "D. Sports",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Greta Garbo is associated with</p>",
    "a": "A. Classical dance",
    "b": "B. Literature",
    "c": "C. Journalism",
    "d": "D. Acting",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is the Flying Sikh of India?</p>",
    "a": "A. Mohinder Singh",
    "b": "B. Joginder Singh",
    "c": "C. Ajit Pal Singh",
    "d": "D. Milkha singh",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ben kingsley is associated with which of the following fields?</p>",
    "a": "A. Politics",
    "b": "B. Social Service",
    "c": "C. Sports",
    "d": "D. Motion Pictures",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>In which of the following dance forms 'Guru Kelucharan Mohapatra' is associated with?</p>",
    "a": "A. Odissi",
    "b": "B. Bharathanatiyam",
    "c": "C. Kathak",
    "d": "D. Kathakali",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Bismillah Khan was associated with?</p>",
    "a": "A. Sarod",
    "b": "B. Shehnai",
    "c": "C. Flute",
    "d": "D. Tabla",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who among the following is not a dramatist?</p>",
    "a": "A. Girish R. Karnad",
    "b": "B. Badal Sircar",
    "c": "C. Jayanta Mahapatra",
    "d": "D. Vijay Tendulkar",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who headed the committee on 'computerisation' in Indian Banks(1988)?</p>",
    "a": "A. C. Rangarajan",
    "b": "B. R.N. Malhotra",
    "c": "C. S. Venkitramanan",
    "d": "D. M.Narasimhan",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is the famous Sarod player?</p>",
    "a": "A. Hari Prasad",
    "b": "B. Zakir Hussain",
    "c": "C. Ram Narain",
    "d": "D. Amjad Ali Khan",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Sanjay Dutt, a noted film actor was held under</p>",
    "a": "A. TADA",
    "b": "B. Narcotics Act",
    "c": "C. Act 302",
    "d": "D. Anti - Defection Act",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Shovna Narayan is a reputed personality in which of the following fields?</p>",
    "a": "A. Classical dance",
    "b": "B. Literature",
    "c": "C. Journalism",
    "d": "D. Classical music",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Hari Prasad Chaurasia is a renowned player of</p>",
    "a": "A. Sitar",
    "b": "B. Flute",
    "c": "C. Sarod",
    "d": "D. Tabla",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Graham Green was associated with which of the fields?</p>",
    "a": "A. Science",
    "b": "B. Music",
    "c": "C. Painting",
    "d": "D. Literature",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Dr. V. Kurien is famous in the field of ?</p>",
    "a": "A. Atomic Power",
    "b": "B. poultry farms",
    "c": "C. Dairy development",
    "d": "D. Economic Reforms",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following pairs of artists and their areas of specialization is not correct?</p>",
    "a": "A. Pt. Ravi Shankar - Sitar",
    "b": "B. M. S. Subbulakshmi - Dance",
    "c": "C. Hari Prasad Chaurasia - Flute",
    "d": "D. Ustad Zakir Hussain Khan - Tabla",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Miss Universe 1994, Ms. Sushmita Sen hails from which of the following cities?</p>",
    "a": "A. Mumbai",
    "b": "B. Chandigarh",
    "c": "C. New Delhi",
    "d": "D. Bangalore",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is Tania Sachdev?</p>",
    "a": "A. Chess player",
    "b": "B. Cricketer",
    "c": "C. Actress",
    "d": "D. Dancer",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Limba Ram is associated in which fields?</p>",
    "a": "A. Sports",
    "b": "B. Politics",
    "c": "C. Social Service",
    "d": "D. Motion Picture",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ms. Meera Sahib Fathima Beevi is distinguished as the first lady</p>",
    "a": "A. Prime minister of Bangladesh",
    "b": "B. Judge of Supreme Court",
    "c": "C. Judge of the High court",
    "d": "D. Governor of a state",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is the creator of the Rock Garden in Chandigarh?</p>",
    "a": "A. Pupal Jayakar",
    "b": "B. Le Corbousier",
    "c": "C. Glen",
    "d": "D. Nek Chand",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Hitendra Desai was famous in the which field?</p>",
    "a": "A. Social Service",
    "b": "B. Journalism",
    "c": "C. Politics",
    "d": "D. Literature",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Naina Devi, was associated with field of?</p>",
    "a": "A. Social Service",
    "b": "B. Stage acting",
    "c": "C. Classical dance",
    "d": "D. Vocal music",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is known as 'Trimurthy of Carnatic Music'?</p>",
    "a": "A. Muthuswami Dikshitar",
    "b": "B. Purandardasa",
    "c": "C. Swami Thirunal",
    "d": "D. None of these",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Gangubai hangal is the name associated with</p>",
    "a": "A. Literature",
    "b": "B. Music",
    "c": "C. Journalism",
    "d": "D. Environment",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is known as the 'Lady with the Lamp'?</p>",
    "a": "A. Florence Nightingale",
    "b": "B. Sarojini Naidu",
    "c": "C. Indira Gandhi",
    "d": "D. Joan of Arc",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Girilal Jain was a noted figure in which of the following fields?</p>",
    "a": "A. Social Service",
    "b": "B. Journalism",
    "c": "C. Literature",
    "d": "D. Politics",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is Larry Pressler?</p>",
    "a": "A. Politician",
    "b": "B. Painter",
    "c": "C. Actor",
    "d": "D. Tennis player",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Pandit Vishwa Mohan Bhatt, who has won the prestigious 'Grammy Awards' is an exponent in which of the following musical instruments?</p>",
    "a": "A. Guitar",
    "b": "B. Violin",
    "c": "C. sarod",
    "d": "D. Tabla",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Raja Ravi Verma, was famous in which of the fields?</p>",
    "a": "A. Painting",
    "b": "B. Politics",
    "c": "C. Dance",
    "d": "D. Music",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is known as 'Desert Fox'?</p>",
    "a": "A. Bismarck",
    "b": "B. Eisenhower",
    "c": "C. Gen. Rommel",
    "d": "D. Walter Scott",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The title of 'sparrow' given to</p>",
    "a": "A. Napoleon",
    "b": "B. Major General Rajinder Singh",
    "c": "C. T. T. Krishnamachari",
    "d": "D. Sardar Patel",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who headed the first scientific group to leave for Antarctica in 1982?</p>",
    "a": "A. Dr. D.R. Sengupta",
    "b": "B. Dr. S.Z. Kasim",
    "c": "C. Dr. V. K. Raina",
    "d": "D. Dr. H. K. Gupta",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which among the famous danseuses is not an exponent of the Odissi dance style?</p>",
    "a": "A. Sanjukta Panigrahi",
    "b": "B. Madhavi Mudgal",
    "c": "C. Sonal Man Singh",
    "d": "D. Yamini Krishnamurthy",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Michael Jackson is a distinguished person in the field of?</p>",
    "a": "A. Pop Music",
    "b": "B. Jounalism",
    "c": "C. Sports",
    "d": "D. Acting",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ms Kim Campbell is the first woman Prime Minister of</p>",
    "a": "A. Portugal",
    "b": "B. Canada",
    "c": "C. Switzerland",
    "d": "D. Congo",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The first Indian to swim across English channel was</p>",
    "a": "A. V. Merchant",
    "b": "B. P. K. Banerji",
    "c": "C. Mihir Sen",
    "d": "D. Arati Saha",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is known as 'Indian Bismarck'?</p>",
    "a": "A. Kamaraj",
    "b": "B. Sardar Vallabhbhai Patel",
    "c": "C. Nehru",
    "d": "D. Rajaji",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Famous Personalities",
    "section": "(General Awareness)"
}]
}
