{
  "data": [
    {
      "qtext": "Brass gets discoloured in air because of the presence of which of the following gases in air?",
      "a": "A. Oxygen",
      "b": "B. Hydrogen sulphide",
      "c": "C. Carbon dioxide",
      "d": "D. Nitrogen",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is a non metal that remains liquid at room temperature?",
      "a": "A. Phosphorous",
      "b": "B. Bromine",
      "c": "C. Chlorine",
      "d": "D. Helium",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Chlorophyll is a naturally occurring chelate compound in which central metal is",
      "a": "A. copper",
      "b": "B. magnesium",
      "c": "C. iron",
      "d": "D. calcium",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is used in pencils?",
      "a": "A. Graphite",
      "b": "B. Silicon",
      "c": "C. Charcoal",
      "d": "D. Phosphorous",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following metals forms an amalgam with other metals?",
      "a": "A. Tin",
      "b": "B. Mercury",
      "c": "C. Lead",
      "d": "D. Zinc",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Chemical formula for water is",
      "a": "A. NaAlO2",
      "b": "B. H2O",
      "c": "C. Al2O3",
      "d": "D. CaSiO3",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The gas usually filled in the electric bulb is",
      "a": "A. nitrogen",
      "b": "B. hydrogen",
      "c": "C. carbon dioxide",
      "d": "D. oxygen",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Washing soda is the common name for",
      "a": "A. Sodium carbonate",
      "b": "B. Calcium bicarbonate",
      "c": "C. Sodium bicarbonate",
      "d": "D. Calcium carbonate",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Quartz crystals normally used in quartz clocks etc. is chemically",
      "a": "A. silicon dioxide",
      "b": "B. germanium oxide",
      "c": "C. a mixture of germanium oxide and silicon dioxide",
      "d": "D. sodium silicate",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the gas is not known as green house gas?",
      "a": "A. Methane",
      "b": "B. Nitrous oxide",
      "c": "C. Carbon dioxide",
      "d": "D. Hydrogen",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Bromine is a",
      "a": "A. black solid",
      "b": "B. red liquid",
      "c": "C. colourless gas",
      "d": "D. highly inflammable gas",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The hardest substance available on earth is",
      "a": "A. Gold",
      "b": "B. Iron",
      "c": "C. Diamond",
      "d": "D. Platinum",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The variety of coal in which the deposit contains recognisable traces of the original plant material is",
      "a": "A. bitumen",
      "b": "B. anthracite",
      "c": "C. lignite",
      "d": "D. peat",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Tetraethyl lead is used as",
      "a": "A. pain killer",
      "b": "B. fire extinguisher",
      "c": "C. mosquito repellent",
      "d": "D. petrol additive",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is used as a lubricant?",
      "a": "A. Graphite",
      "b": "B. Silica",
      "c": "C. Iron Oxide",
      "d": "D. Diamond",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The inert gas which is substituted for nitrogen in the air used by deep sea divers for breathing, is",
      "a": "A. Argon",
      "b": "B. Xenon",
      "c": "C. Helium",
      "d": "D. Krypton",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The gases used in different types of welding would include",
      "a": "A. oxygen and hydrogen",
      "b": "B. oxygen, hydrogen, acetylene and nitrogen",
      "c": "C. oxygen, acetylene and argon",
      "d": "D. oxygen and acetylene",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The property of a substance to absorb moisture from the air on exposure is called",
      "a": "A. osmosis",
      "b": "B. deliquescence",
      "c": "C. efflorescence",
      "d": "D. desiccation",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In which of the following activities silicon carbide is used?",
      "a": "A. Making cement and glass",
      "b": "B. Disinfecting water of ponds",
      "c": "C. cutting very hard substances",
      "d": "D. Making casts for statues",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The average salinity of sea water is",
      "a": "A. 3%",
      "b": "B. 3.5%",
      "c": "C. 2.5%",
      "d": "D. 2%",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "When an iron nail gets rusted, iron oxide is formed",
      "a": "A. without any change in the weight of the nail",
      "b": "B. with decrease in the weight of the nail",
      "c": "C. with increase in the weight of the nail",
      "d": "D. without any change in colour or weight of the nail",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Galvanised iron sheets have a coating of",
      "a": "A. lead",
      "b": "B. chromium",
      "c": "C. zinc",
      "d": "D. tin",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Among the various allotropes of carbon,",
      "a": "A. coke  is the hardest, graphite is the softest",
      "b": "B. diamond is the hardest, coke is the softest",
      "c": "C. diamond is the hardest, graphite is the softest",
      "d": "D. diamond is the hardest, lamp black is the softest",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The group of metals Fe, Co, Ni may best called as",
      "a": "A. transition metals",
      "b": "B. main group metals",
      "c": "C. alkali metals",
      "d": "D. rare metals",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Heavy water is",
      "a": "A. deuterium oxide",
      "b": "B. PH7",
      "c": "C. rain water",
      "d": "D. tritium oxide",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The chemical (ethyl mercaptan) added to the otherwise odourless LPG cooking gas for imparting a detectable smell to the gas is a compound of",
      "a": "A. bromine",
      "b": "B. fluorine",
      "c": "C. chlorine",
      "d": "D. sulphur",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The element common to all acids is",
      "a": "A. hydrogen",
      "b": "B. carbon",
      "c": "C. sulphur",
      "d": "D. oxygen",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Non stick cooking utensils are coated with",
      "a": "A. Teflon",
      "b": "B. PVC",
      "c": "C. black paint",
      "d": "D. polystyrene",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Monazite is an ore of",
      "a": "A. titanium",
      "b": "B. zirconium",
      "c": "C. iron",
      "d": "D. thorium",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Carbon, diamond and graphite are together called",
      "a": "A. allotropes",
      "b": "B. isomers",
      "c": "C. isomorphs",
      "d": "D. isotopes",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Potassium nitrate is used in",
      "a": "A. medicine",
      "b": "B. fertiliser",
      "c": "C. salt",
      "d": "D. glass",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Permanent hardness of water may be removed by the addition of",
      "a": "A. sodium carbonate",
      "b": "B. alum",
      "c": "C. potassium permanganate",
      "d": "D. lime",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Soda water contains",
      "a": "A. carbonic acid",
      "b": "B. sulphuric acid",
      "c": "C. carbon dioxide",
      "d": "D. nitrous acid",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The most important ore of aluminium is",
      "a": "A. galena",
      "b": "B. calamine",
      "c": "C. calcite",
      "d": "D. bauxite",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Most soluble in water is",
      "a": "A. camphor",
      "b": "B. sulphur",
      "c": "C. common salt",
      "d": "D. sugar",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following was to be discovered first in the chromospheres of the sun?",
      "a": "A. Krypton",
      "b": "B. Xenon",
      "c": "C. Neon",
      "d": "D. Helium",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is in liquid form at room temperature?",
      "a": "A. Lithium",
      "b": "B. Sodium",
      "c": "C. Francium",
      "d": "D. Cerium",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Sodium metal is kept under",
      "a": "A. petrol",
      "b": "B. alcohol",
      "c": "C. water",
      "d": "D. kerosene",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following are the ingredients of gun metal?",
      "a": "A. Iron, Zinc, Titanium",
      "b": "B. Iron, tin",
      "c": "C. Iron, Brass, Tin",
      "d": "D. Copper, Tin",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "From which mineral is radium obtained?",
      "a": "A. Rutile",
      "b": "B. Haematite",
      "c": "C. Limestone",
      "d": "D. Pitchblende",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is laughing gas?",
      "a": "A. Nitrous Oxide",
      "b": "B. Carbon monoxide",
      "c": "C. Sulphur dioxide",
      "d": "D. Hydrogen peroxide",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Actinides are the elements with atomic numbers from",
      "a": "A. 97 to 104",
      "b": "B. 101 to 115",
      "c": "C. 89 to 103",
      "d": "D. 36 from 43",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The two elements that are frequently used for making transistors are",
      "a": "A. boron and aluminium",
      "b": "B. silicon and germanium",
      "c": "C. iridium and tungsten",
      "d": "D. niobium and columbium",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The filament of an electric bulb is made of",
      "a": "A. tungsten",
      "b": "B. nichrome",
      "c": "C. graphite",
      "d": "D. iron",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Diamond is an allotropic form of",
      "a": "A. germanium",
      "b": "B. carbon",
      "c": "C. silicon",
      "d": "D. sulphur",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In fireworks, the green flame is produced because of",
      "a": "A. sodium",
      "b": "B. barium",
      "c": "C. mercury",
      "d": "D. potassium",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Permanent hardness of water can be removed by adding",
      "a": "A. chlorine",
      "b": "B. washing soda",
      "c": "C. potassium permanganate",
      "d": "D. bleaching powder",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Marsh gas is",
      "a": "A. nitrogen",
      "b": "B. ethane",
      "c": "C. methane",
      "d": "D. hydrogen",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "LPG consists of mainly",
      "a": "A. methane, ethane and hexane",
      "b": "B. ethane, hexane and nonane",
      "c": "C. methane, hexane and nonane",
      "d": "D. methane, butane and propane",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Air is a/an",
      "a": "A. compound",
      "b": "B. element",
      "c": "C. electrolyte",
      "d": "D. mixture",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Production of chlorofluorocarbons (CFC) gas which is proposed to be banned in  India, is used in which of the following domestic products?",
      "a": "A. Television",
      "b": "B. Refrigerator",
      "c": "C. Tube light",
      "d": "D. Cooking gas",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Balloons are filled with",
      "a": "A. nitrogen",
      "b": "B. helium",
      "c": "C. oxygen",
      "d": "D. argon",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following does not contain a coinage metal?",
      "a": "A. Silver and Gold",
      "b": "B. Zinc and Gold",
      "c": "C. Copper and Silver",
      "d": "D. Copper and Gold",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which metal pollute the air of a big city?",
      "a": "A. Copper",
      "b": "B. Chromium",
      "c": "C. Lead",
      "d": "D. Cadmium",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Bell metal is an alloy of",
      "a": "A. nickel and copper",
      "b": "B. zinc and copper",
      "c": "C. brass and nickel",
      "d": "D. tin and copper",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Water is a good solvent of ionic salts because",
      "a": "A. it has a high specific heat",
      "b": "B. it has no colour",
      "c": "C. it has a high dipole moment",
      "d": "D. it has a high boiling point",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is not an isotope of hydrogen?",
      "a": "A. Tritium",
      "b": "B. Deuterium",
      "c": "C. Protium",
      "d": "D. Yttrium",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The main constituents of pearls are",
      "a": "A. calcium oxide and ammonium chloride",
      "b": "B. calcium carbonate and magnesium carbonate",
      "c": "C. aragonite and conchiolin",
      "d": "D. ammonium sulphate and sodium carbonate",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Amalgams are",
      "a": "A. highly coloured alloys",
      "b": "B. alloys which contain mercury as one of the contents",
      "c": "C. alloys which have great resistance to abrasion",
      "d": "D. alloys which contain carbon",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is the lightest metal?",
      "a": "A. Mercury",
      "b": "B. Lithium",
      "c": "C. Lead",
      "d": "D. Silver",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following metals remain in liquid for under normal conditions?",
      "a": "A. Radium",
      "b": "B. Zinc",
      "c": "C. Uranium",
      "d": "D. Mercury",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Potassium Permanganate is used for purifying drinking water, because",
      "a": "A. it is a sterilising agent",
      "b": "B. it dissolves the impurities of water",
      "c": "C. it is a reducing agent",
      "d": "D. it is an oxidising agent",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is an element?",
      "a": "A. Ruby",
      "b": "B. Sapphire",
      "c": "C. Emerald",
      "d": "D. Diamond",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the unit for measuring the amplitude of a sound?",
      "a": "A. Decibel",
      "b": "B. Coulomb",
      "c": "C. Hum",
      "d": "D. Cycles",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Reading of a barometer going down is an indication of",
      "a": "A. snow",
      "b": "B. storm",
      "c": "C. intense heat",
      "d": "D. rainfall",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Decibel is the unit for",
      "a": "A. speed of light",
      "b": "B. radio wave frequency",
      "c": "C. intensity of sound",
      "d": "D. intensity of heat",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "One fathom is equal to",
      "a": "A. 6 feet",
      "b": "B. 6 meters",
      "c": "C. 60 feet",
      "d": "D. 100 cm",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Fathom is the unit of",
      "a": "A. sound",
      "b": "B. depth",
      "c": "C. frequency",
      "d": "D. distance",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Light year is a measurement of",
      "a": "A. speed of aeroplanes",
      "b": "B. speed of light",
      "c": "C. Stellar distances",
      "d": "D. speed of rockets",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Very small time intervals are accurately measure by",
      "a": "A. White dwarfs",
      "b": "B. Quartz clocks",
      "c": "C. Atomic clocks",
      "d": "D. Pulsars",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "One kilometre is equal to how many miles?",
      "a": "A. 0.84",
      "b": "B. 0.5",
      "c": "C. 1.6",
      "d": "D. 0.62",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "kilohertz is a unit which measures",
      "a": "A. power used by a current of one ampere",
      "b": "B. electromagnetic radio wave frequencies",
      "c": "C. voltage",
      "d": "D. electric resistance",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "One horse power is equal to",
      "a": "A. 746 watts",
      "b": "B. 748 watts",
      "c": "C. 756 watts",
      "d": "D. 736 watts",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'Bar' is the unit of",
      "a": "A. temperature",
      "b": "B. heat",
      "c": "C. atmospheric pressure",
      "d": "D. current",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "One Joule is equal to",
      "a": "A. 105 ergs",
      "b": "B. 103 ergs",
      "c": "C. 107 ergs",
      "d": "D. 1011 ergs",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Kilowatt is a unit to measure",
      "a": "A. work",
      "b": "B. power",
      "c": "C. electricity",
      "d": "D. current",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Electric current is measure by",
      "a": "A. commutator",
      "b": "B. anemometer",
      "c": "C. ammeter",
      "d": "D. voltmeter",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "A chronometer measures",
      "a": "A. colour contrast",
      "b": "B. sound waves",
      "c": "C. time",
      "d": "D. water waves",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Nautical mile is a unit of distance used in",
      "a": "A. navigation",
      "b": "B. road mile",
      "c": "C. astronomy",
      "d": "D. measuring the boundaries of a nation",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Knot is a unit of speed of which of the following?",
      "a": "A. Aeroplane",
      "b": "B. Light waves",
      "c": "C. Ship",
      "d": "D. Sound waves",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is used as a moderator in nuclear reactor?",
      "a": "A. Thorium",
      "b": "B. Graphite",
      "c": "C. Radium",
      "d": "D. Ordinary water",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which among the following is a positively charged particle emitted by a radioactive element?",
      "a": "A. Beta ray",
      "b": "B. Alpha ray",
      "c": "C. Cathode ray",
      "d": "D. Gamma ray",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Atoms are composed of",
      "a": "A. electrons and protons",
      "b": "B. electrons only",
      "c": "C. protons only",
      "d": "D. electrons and nuclei",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In an atomic explosion, enormous energy is released which is due to",
      "a": "A. conversion of chemical energy into heat energy",
      "b": "B. conversion of mechanical energy into nuclear energy",
      "c": "C. conversion of mass into energy",
      "d": "D. conversion of neutrons into protons",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Isotopes are separated by",
      "a": "A. crystallisation",
      "b": "B. sublimation",
      "c": "C. distillation",
      "d": "D. filtration",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The wavelength of X-rays is of the order of",
      "a": "A. 10 micron",
      "b": "B. 1 angstrom",
      "c": "C. 1 cm",
      "d": "D. 1 m",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Mesons are found in",
      "a": "A. Laser beam",
      "b": "B. X-rays",
      "c": "C. Gamma rays",
      "d": "D. Cosmic rays",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which radioactive pollutant has recently drawn to public, due to its occurrence in the building material?",
      "a": "A. Thorium",
      "b": "B. Radium",
      "c": "C. Plutonium",
      "d": "D. Radan",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following shows the masses of the three elementary particles in decreasing order?",
      "a": "A. Leptons, Baryons, Mesons",
      "b": "B. Mesons, Baryons, Leptons",
      "c": "C. Baryons, Mesons, Leptons",
      "d": "D. Leptons, Mesons Baryons",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the wavelength of visible spectrum?",
      "a": "A. 8500 - 9800 angstrom",
      "b": "B. 7800 - 8000 angstrom",
      "c": "C. 3900 - 7600 angstrom",
      "d": "D. 1300 - 3000 angstrom",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following has a least penetrating power?",
      "a": "A. All have same penetrating power",
      "b": "B. Beta Particles",
      "c": "C. Alpha particles",
      "d": "D. Gamma rays",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The isotope of uranium capable of sustaining chain reaction is",
      "a": "A. U-235",
      "b": "B. U-245",
      "c": "C. U-239",
      "d": "D. U-238",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The age of most ancient geological formations is estimated by",
      "a": "A. Ra - Si method",
      "b": "B. Potassium - argon method",
      "c": "C. C14 method",
      "d": "D. Uranium - lead method",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Who suggested that most of the mass of the atom is located in the nucleus?",
      "a": "A. Thompson",
      "b": "B. Bohr",
      "c": "C. Rutherford",
      "d": "D. Einstein",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The dark lines in the solar spectrum are due to",
      "a": "A. absorption of corresponding wavelengths by the outer layers of the sun",
      "b": "B. destructive interference between waves of certain definite wavelengths",
      "c": "C. absorption of corresponding wavelengths by the prism used in the photograph",
      "d": "D. absence of corresponding wavelengths from the light emitted by the core of the sun",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In an atomic nucleus, neutrons and protons are held together by",
      "a": "A. gravitational forces",
      "b": "B. exchange forces",
      "c": "C. coulombic forces",
      "d": "D. magnetic forces",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'No two electrons in an atom can have the same set of four quantum numbers' is",
      "a": "A. Newton's law",
      "b": "B. Bohr's law",
      "c": "C. Aufbau principle",
      "d": "D. Pauli's exclusion principle",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "According to Avogadro's Hypothesis, the smallest particle of an element or a compound, that can exist independently, is called ____ .",
      "a": "A. a molecule",
      "b": "B. a cation",
      "c": "C. an anion",
      "d": "D. an atom",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Atoms of an element differ from those of all other elements in",
      "a": "A. atomic number and electronic configuration",
      "b": "B. number of neutrons and number of valence electrons",
      "c": "C. atomic number and number of valence electrons",
      "d": "D. number of neutrons and electronic configuration",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Nuclear fission is caused by the impact of",
      "a": "A. neutron",
      "b": "B. proton",
      "c": "C. deuteron",
      "d": "D. electron",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following rays are more penetrating?",
      "a": "A. Beta rays",
      "b": "B. Alpha rays",
      "c": "C. Gamma rays",
      "d": "D. X-rays",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "How many colours the sunlight spectrum has?",
      "a": "A. Three",
      "b": "B. Seven",
      "c": "C. Four",
      "d": "D. Five",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which is/are the important raw material(s) required in cement industry?",
      "a": "A. Gypsum and Clay",
      "b": "B. Clay",
      "c": "C. Limestone and Clay",
      "d": "D. Limestone",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which type of fire extinguisher is used for petroleum fire?",
      "a": "A. Powder type",
      "b": "B. Liquid type",
      "c": "C. Soda acid type",
      "d": "D. Foam type",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is commonly called a 'polyamide'?",
      "a": "A. Terylene",
      "b": "B. Nylon",
      "c": "C. Rayon",
      "d": "D. Orlon",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Epoxy resins are used as",
      "a": "A. detergents",
      "b": "B. insecticides",
      "c": "C. adhesives",
      "d": "D. moth repellents",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Detergents used for cleaning clothes and utensils contain?",
      "a": "A. bicarbonates",
      "b": "B. bismuthates",
      "c": "C. sulphonates",
      "d": "D. nitrates",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is used for removing air bubbles from glass during its manufacture?",
      "a": "A. Arsenous oxide",
      "b": "B. Potassium carbonate",
      "c": "C. Soda ash",
      "d": "D. Feldspar",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is a protein?",
      "a": "A. Natural rubber",
      "b": "B. Starch",
      "c": "C. Cellulose",
      "d": "D. None of these",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Wood is the main raw material for the manufacture of",
      "a": "A. paint",
      "b": "B. paper",
      "c": "C. ink",
      "d": "D. gun powder",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Rayon is chemically",
      "a": "A. cellulose",
      "b": "B. pectin",
      "c": "C. glucose",
      "d": "D. amylase",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Optic fibres are mainly used for which of the following?",
      "a": "A. Musical instruments",
      "b": "B. Food industry",
      "c": "C. Weaving",
      "d": "D. Communication",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The major ingredient of leather is",
      "a": "A. collagen",
      "b": "B. carbohydrate",
      "c": "C. polymer",
      "d": "D. nucleic acid",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What are the soaps?",
      "a": "A. Salts of silicates",
      "b": "B. Mixture of glycerol and alcohols",
      "c": "C. Sodium or potassium salts of heavier fatty acids",
      "d": "D. Esters of heavy fatty acids",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "How does common salt help in separating soap from the solution after saponification?",
      "a": "A. By decreasing density of Soap",
      "b": "B. By decreasing solubility of Soap",
      "c": "C. By increasing density of Soap",
      "d": "D. By increasing solubility of Soap",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In vulcanisation, natural rubber is heated with",
      "a": "A. Carbon",
      "b": "B. Silicon",
      "c": "C. Sulphur",
      "d": "D. Phosphorous",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Deep blue colour is imparted to glass by the presence of",
      "a": "A. cupric oxide",
      "b": "B. nickel oxide",
      "c": "C. cobalt oxide",
      "d": "D. iron oxide",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Glass is made of the mixture of",
      "a": "A. quartz and mica",
      "b": "B. sand and silicates",
      "c": "C. salt and quartz",
      "d": "D. sand and salt",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The vast resources of unutilised natural gas can be used in the production of",
      "a": "A. graphite",
      "b": "B. Synthetic petroleum",
      "c": "C. fertilisers",
      "d": "D. carbide",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Paper is manufactured by",
      "a": "A. Wood and resin",
      "b": "B. Wood, sodium and bleaching powder",
      "c": "C. Wood, calcium, hydrogen sulphite and resin",
      "d": "D. Wood and bleaching powder",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Gypsum is added to cement clinker to",
      "a": "A. increase the tensile strength of cement",
      "b": "B. decrease the rate of setting of cement",
      "c": "C. facilitate the formation of colloidal gel",
      "d": "D. bind the particles of calcium silicate",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Soap is a mixture of sodium or potassium salts of",
      "a": "A. dicarboxylic acids",
      "b": "B. monocarboxylic acids",
      "c": "C. glycerol",
      "d": "D. tricarboxylic acids",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The type of glass used in making lenses and prisms is",
      "a": "A. jena glass",
      "b": "B. soft glass",
      "c": "C. pyrex glass",
      "d": "D. flint glass",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which one of the following is the petroleum wax?",
      "a": "A. Paraffin wax",
      "b": "B. Jonoba wax",
      "c": "C. Carnauba wax",
      "d": "D. Bees wax",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "General Science",
      "section": "(General Awareness)"
    }
  ]
}
