{
  "data": [
    {
      "qtext": " When was the Nobel Prize for literature instituted?",
      "a": "(A) 1969",
      "b": "(B) 1956",
      "c": "(C) 1972",
      "d": "(D) 1975",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who was the first Indian to receive a Nobel Prize?",
      "a": "(A) Mother Teresa",
      "b": "(B) Hargobind Tagore",
      "c": "(C) CV Raman",
      "d": "(D) Rabindranath Tagore",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The Nobel prize for Economics was instituted in 1967, but was first awarded in",
      "a": "(A) 1970",
      "b": "(B) 1988",
      "c": "(C) 1967",
      "d": "(D) 1969",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who was the first Indian lady actress to receive the Padma Shri Award?",
      "a": "(A) Madhubala",
      "b": "(B) Meena Kumari",
      "c": "(C) Nargis Dutt",
      "d": "(D) Smita Patil",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which of the following is India's highest honour in the field of literature?",
      "a": "(A) Kalidas Samman",
      "b": "(B) Saraswathi Samman",
      "c": "(C) Vyas Samman",
      "d": "(D) Jnanpith Award",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who was the first Indian to receive the Magaysay Award?",
      "a": "(A) TN Seshan",
      "b": "(B) Kiran Bedi",
      "c": "(C) Indira Gandhi",
      "d": "(D) Vinoba Bhave",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which one of the following awards was instituted by the KK Birla Foundation?",
      "a": "(A) Saraswati Samman",
      "b": "(B) Kabir Award",
      "c": "(C) Jnanpith Award",
      "d": "(D) Kalidas Samman",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who among the following has received both Bharat Ratna and Nishan -e -Pakistan?",
      "a": "(A) Ayub Khan",
      "b": "(B) Moraji Desai",
      "c": "(C) Mahatma Gandhi",
      "d": "(D) Maulana Abul Kalam Azad",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Ramon Magaysay Award is named after the former president of",
      "a": "(A) Phillipines",
      "b": "(B) Thailand",
      "c": "(C) Indonesia",
      "d": "(D) None of the above",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who among the following got the Bharat Ratna award before becoming the president of India?",
      "a": "(A) W Giri",
      "b": "(B) DR Zakir Hussian",
      "c": "(C) Dr. Rajendra Prasad",
      "d": "(D) R Venkataraman",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Meghanath Saha award is given for outstanding contribution in which of the following fields?",
      "a": "(A) Social Science",
      "b": "(B) Journalism",
      "c": "(C) Science",
      "d": "(D) Literature",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Meghanath Saha award is given for outstanding contribution in which of the following fields?",
      "a": "(A) Social Science",
      "b": "(B) Journalism",
      "c": "(C) Science",
      "d": "(D) Literature",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " From which one of the following did india buy the Brank anti missile defence systems?",
      "a": "(A) Israel",
      "b": "(B) USA",
      "c": "(C) France",
      "d": "(D) Russia",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who among the following is not a Data Saheb Phalke awardee?",
      "a": "(A) Mrinal Sen",
      "b": "(B) Adoor Gopalakrishnan",
      "c": "(C) JP Dutta",
      "d": "(D) Shyam Benegal",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which of the following awards was instituted by the Indian National Congress in its Centenary Year?",
      "a": "(A) Gandhi Peace Prize",
      "b": "(B) Nehru Award",
      "c": "(C) Indira Gandhi award",
      "d": "(D) Mahatma Gandhi Award",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The Oscar Award was won 36 times by",
      "a": "(A) Alfred Hitchcock",
      "b": "(B) Walt Disney",
      "c": "(C) Kurosawa",
      "d": "(D) Charlie Chapin",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Goldman Awards are given for outstanding contribution in which of the following fields?",
      "a": "(A) protectionofenvironment",
      "b": "(B) population control",
      "c": "(C) conservation of energy",
      "d": "(D) population of science",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which State Government of India has instituted the Lqbal samman award?",
      "a": "(A) AP",
      "b": "(B) UP",
      "c": "(C) HP",
      "d": "(D) MP",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Shirin Ebadi, who won the nobel peace prize in 2003, is from",
      "a": "(A) Iran",
      "b": "(B) Iraq",
      "c": "(C) Libia",
      "d": "(D) Nigeria",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which among the following Indian artists is the winner of the Oscar Award?",
      "a": "(A) Shyam Benegal",
      "b": "(B) Dilip Kumar",
      "c": "(C) Bhanu Athaiya",
      "d": "(D) Rohini Hattangadi",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which one of the following is a medium range surface to air missile ?",
      "a": "(A) Nag",
      "b": "(B) Trishul",
      "c": "(C) Prithvi",
      "d": "(D) Akash",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Manav Seva Award has been instituted in the memory of",
      "a": "(A) Rajiv Gandhi",
      "b": "(B) Dr.Rajendra Prasad",
      "c": "(C) Indira Gandhi",
      "d": "(D) Acharya Vinoba Bhave",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " India's highest award given for exceptional work in art, literature and recognition of public service of the highest order is",
      "a": "(A) Kalinga Award",
      "b": "(B) Param Vir Chakra",
      "c": "(C) Jnanpith Award",
      "d": "(D) Bharat Ratna",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " To encourage increase in the quality, quantity and availability o food in the world, the world food prizes is founded by",
      "a": "(A) WHO",
      "b": "(B) Prof MS Swaminathan",
      "c": "(C) Prof Norman Borlaug",
      "d": "(D) UNDP",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The Chameli Devi Award is given to an outstanding woman is a",
      "a": "(A) journalist",
      "b": "(B) lawyer",
      "c": "(C) Vocalist",
      "d": "(D) scientist",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who was awarded the highest honour in Indian Cinema Dada Sahib Phalke Award 2012 ?",
      "a": "(A) Devika Rani",
      "b": "(B) Pran Krishan Sikand",
      "c": "(C) Soumitra Chatterjee",
      "d": "(D) K. Balachander",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Jnanpith Award is given for excellence in the field of:",
      "a": "(A) Films",
      "b": "(B) Literature",
      "c": "(C) Music",
      "d": "(D) Sports ",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": "  Recently Tan Twan Eng, the Malaysian author was declared as the winner of Walter Scott Prize 2013 for his English fiction novel ___?",
      "a": "(A) The Streets",
      "b": "(B) The Strangers Child",
      "c": "(C) The Garden of Evening Mists",
      "d": "(D) Bring Up the Bodies",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Professor Ramdarash Mishra conferred with the Vyas Samman for the year___?",
      "a": "(A) 2013",
      "b": "(B) 2012",
      "c": "(C) 2011",
      "d": "(D) 2010",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": "  Gershwin Prize given in which among the following field?",
      "a": "(A) Art",
      "b": "(B) Literature",
      "c": "(C) Science",
      "d": "(D) Music",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which among the following organization is awarded with 2012 Nobel Peace Prize?",
      "a": "(A) OECD",
      "b": "(B) UNEP",
      "c": "(C) European union",
      "d": "(D) NATO",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which film has bagged the Best Feature Film award at the third SAARC Film Festival in Colombo?",
      "a": "(A) Vicky Donor",
      "b": "(B) Argo",
      "c": "(C) Barfi",
      "d": "(D) Paan Singh Tomar",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " By defeating which of the following team, India clinched the ICC Champions Trophy 2013?",
      "a": "(A) Sri Lanka",
      "b": "(B) New Zealand",
      "c": "(C) West indies",
      "d": "(D) England",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " B. C. Roy Award is given in the field of",
      "a": "(A) Music",
      "b": "(B) Journalism",
      "c": "(C) Medicine",
      "d": "(D) Environment",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Gandhi Peace Prize for the year 2000 was awarded to the former President of South Africa along with",
      "a": "(A) Sathish Dawan",
      "b": "(B) C. Subramanian",
      "c": "(C) Grameen Bank of Bangladesh",
      "d": "(D) World Healt Organisation",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who has been awarded the first lifetime Achievement Award for his/her contribution in the field of Cinema?",
      "a": "(A) Ashok Kumar",
      "b": "(B) Hou Hsio-hsein",
      "c": "(C) Akiro Burosova",
      "d": "(D) Bernardo Burtolucci",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The prestigious Ramon Magsaysay Award was conferred was conferred upon Ms. Kiran Bedi for her excellent contribution to which of the following fields?",
      "a": "(A) Literature",
      "b": "(B) Community Welfare",
      "c": "(C) Government Service",
      "d": "(D) Journalism",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which of the following societies has instituted an award for an outstanding parliamentarian?",
      "a": "(A) Jamanlal Bajaj Foundation",
      "b": "(B) Institute of Constitutional and Parliamentary Studies",
      "c": "(C) G. B. Pant Memorial Society",
      "d": "(D) R. D. Birla samara Kosh",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which is the highest gallantry award in India?",
      "a": "(A) Param Vishishtat Seva Medal",
      "b": "(B) Param Vir Chakra",
      "c": "(C) Kirti Chakra",
      "d": "(D) Vir Chakra",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who is the first Asian Winner of Nobel Prize?",
      "a": "(A) C. V. Raman",
      "b": "(B) Rajiv Gandhi",
      "c": "(C) Rabindranath Tagore",
      "d": "(D) Mother Teresa",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The first Indian to receive Noble Prize in Literature was",
      "a": "(A) Mother Teresa",
      "b": "(B) C. V. Raman",
      "c": "(C) Rabindranath Tagore",
      "d": "(D) Sarojini Naidu",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The first recipient of Rajiv Gandhi's 'Khel Ratna' award is",
      "a": "(A) Vishwanathan Anand",
      "b": "(B) Leander Peas",
      "c": "(C) Kapil Dev",
      "d": "(D) Limba Ram",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Pulitzer prize is awarded for outstanding work in the field of",
      "a": "(A) Science and Technology",
      "b": "(B) Environmental Studies",
      "c": "(C) Literature and Journalism",
      "d": "(D) International Understanding",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The Arjuna Awards were instituted in the year",
      "a": "(A) 1965",
      "b": "(B) 1961",
      "c": "(C) 1963",
      "d": "(D) 1957",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who among the following is the recipient of the first Dayawati Modi Award for art, culture and education?",
      "a": "(A) Dharmavir Bharti",
      "b": "(B) Amitabh Bachchaan",
      "c": "(C) B. V. Karanth",
      "d": "(D) Ashok Vajpeyi",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The Nobel Prize was first awarded in",
      "a": "(A) 1976",
      "b": "(B) 1958",
      "c": "(C) 1901",
      "d": "(D) 1972",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who among the following own the Nobel prize for literature?",
      "a": "(A) Linus Pauling",
      "b": "(B) Samuel Beckett",
      "c": "(C) Philip Noel - Baker",
      "d": "(D) Ralph Bunche",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The 'Cannes Award' is given for excellence in which field?",
      "a": "(A) Films",
      "b": "(B) Journalism",
      "c": "(C) Literature",
      "d": "(D) Economics",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The journalist who refused to accept 'Padma Bhushan' was?",
      "a": "(A) Shekaran Nair",
      "b": "(B) Khushwant Singh",
      "c": "(C) Ratan Thiyam",
      "d": "(D) Arun Shourie",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The Nobel peace prize is awarded in which city?",
      "a": "(A) Oslo",
      "b": "(B) Stockholm",
      "c": "(C) Brussels",
      "d": "(D) Geneva",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who among the following is not a recipient of the Bharatiya Jnanpith Award?",
      "a": "(A) Ashaparna Devi",
      "b": "(B) M. F. Hussain",
      "c": "(C) Raghupathi Sahai",
      "d": "(D) V. K. Gokak",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who among the following is not a recipient of 'Dada Saheb Phalke' Award?",
      "a": "(A) Ramanand Sagar",
      "b": "(B) Raj Kapoor",
      "c": "(C) V. Shantaram",
      "d": "(D) Ashok Kumar",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which state Government of India has instituted the Samman Award?",
      "a": "(A) Uttar Pradesh",
      "b": "(B) Himachal Pradesh",
      "c": "(C) Madhya Pradesh",
      "d": "(D) Andhra Pradesh",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The highest civilian award of India 'Bharat Ratna' has been awarded to only two foreigners so far. One of them is Nelson Mandela. The other is",
      "a": "(A) Abdul Ghaffar khan",
      "b": "(B) Mikhail Gorbachev",
      "c": "(C) Marshal Tito",
      "d": "(D) Abdul Wali Khan",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The Shanti Swarup Bhatnagar Award is given by which of the following organisations?",
      "a": "(A) Council for Scientific and industrial research",
      "b": "(B) Indian Council for Agricultural Research",
      "c": "(C) Indian National Science Academy",
      "d": "(D) ISRO",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which of the following awards was conferred upon Smt. Aruna Asaf Ali for her role in the welfare of adult and women?",
      "a": "(A) Tagore Literacy Award",
      "b": "(B) UNSECO Literacy Award",
      "c": "(C) Moorti Devi Award",
      "d": "(D) Kalinga Prize",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " On whose name is the highest award for services to the development of cinema given?",
      "a": "(A) Raj Kapoor",
      "b": "(B) Dada Saheb",
      "c": "(C) Meena Kumari",
      "d": "(D) Amitabh Bachchan",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which of the following famous financial journals of international repute confers 'Finance minister of the year' Award?",
      "a": "(A) Dalal Street",
      "b": "(B) Business Standard",
      "c": "(C) Euromoney",
      "d": "(D) Money Matters",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " On whom did the U. S. President George W. Bush bestow, in 2002, the U.S.'s highest award for life time achievement in the field of scientific research?",
      "a": "(A) Arun Netravalli",
      "b": "(B) Dr.Hargoving Kohrana",
      "c": "(C) Subramania Chandrasekar",
      "d": "(D) Professor C. Radhakrishna Rao",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The only Indian to win the Nobel prize in physics is",
      "a": "(A) Dr. J.C. Bose",
      "b": "(B) Dr. C. V. Raman",
      "c": "(C) Dr. Vickram Sarabhai",
      "d": "(D) Dr. H. J. Bhabha",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who among the following is a winner of the Indira Gandhi Award for National integration?",
      "a": "(A) Aruna Asaf Ali",
      "b": "(B) Ashok Kumar",
      "c": "(C) Sundarlal Bahuguna",
      "d": "(D) M. G. K. Menon",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The first black American to win the Nobel Prize for literature is",
      "a": "(A) Aurthe Ashe",
      "b": "(B) Martin Luther King",
      "c": "(C) Toni Morrison",
      "d": "(D) Nelson Mandela",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who among the following got the 'Bharat Ratna' award, before becoming the President of India?",
      "a": "(A) R. Venkatramanan",
      "b": "(B) Dr. Zakir Hussain",
      "c": "(C) V. V. Giri",
      "d": "(D) Dr. Rajendra Prasad",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Manav Seva Award has been instituted in the memory of",
      "a": "(A) Rajiv Gandhi",
      "b": "(B) Dr. Rajendra Prasad",
      "c": "(C) Indira Gandhi",
      "d": "(D) Acharya",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which of the following films has won 9 Oscar Awards in 1987?",
      "a": "(A) The World Safari",
      "b": "(B) The Last Emperor",
      "c": "(C) Rain Man",
      "d": "(D) Amadeus",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which of the following awards was conferred on Mrs. Kiran Bedi?",
      "a": "(A) Golden Globe",
      "b": "(B) Rani Lakshmi",
      "c": "(C) Magsaysay",
      "d": "(D) Saraswati",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " 'Global 500' awards are given for the outstanding achievement in which of the following fields?",
      "a": "(A) Campaign against AIDS",
      "b": "(B) Population control",
      "c": "(C) Protection of environment",
      "d": "(D) Elimination of illiteracy",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who was the only foreigner who was awarded with Padma Vibhusan Award 2015 ?",
      "a": "(A) Jean-Claude Carriere",
      "b": "(B) George L. Hart",
      "c": "(C) Karim AI Hussaini Aga Khan",
      "d": "(D) Jacques Balmont",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which of the following two Indian won the 57th edition Grammy Awards 2015 ?",
      "a": "(A) Ricky Kej & O.P Jaisha",
      "b": "(B) Ricky kej & Neela Vaswani",
      "c": "(C) Neela Vaswani & Anouska Sharma",
      "d": "(D) Rickey kej & Wouter Kellerman",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who has been selected for the Jnanpith award for 2014 ?",
      "a": "(A) Atal Bihari Vajpayee",
      "b": "(B) Asha Bhosle",
      "c": "(C) Bhalchandra Nemade",
      "d": "(D) Kailash Satyarthi",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who among the following has been selected for Sardar Vallabhbhai Patel Vishwa Pratibha Award for his contribution to society as a Gujarati in March 2015 ?",
      "a": "(A) Kishwar Desai",
      "b": "(B) Khusvant Singh",
      "c": "(C) Lord Meghnad Desai",
      "d": "(D) None of these",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which among the following is the highest of civil awards and honor given by Pakistan ?",
      "a": "(A) Nishan-e-Pakistan",
      "b": "(B) Hi –Hu - Pakistan",
      "c": "(C) Sitara-e-Pakistan",
      "d": "(D) Nishan-e-Pakistan",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who received the Deutsche prize for pricing models 2015 ?",
      "a": "(A) Robert Margo",
      "b": "(B) Jean Tirole",
      "c": "(C) Stephen Ross",
      "d": "(D) Raghuram Rajan",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which one of the following has been awarded with the 2015 ‘European Car of the Year’?",
      "a": "(A) Mercedes",
      "b": "(B) BMW",
      "c": "(C) Ford Mondeo",
      "d": "(D) Volkswagen Passat",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who has been selected for the prestigious Saraswati Samman for 2014 ?",
      "a": "(A) Zakir Hussain",
      "b": "(B) APJ abdul kalam",
      "c": "(C) Atal Bihari Vajpayee",
      "d": "(D) M. Veerappa Moily",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " ___________Tourism won the silver prize of Golden Gate award at the Internationale Tourismus-Borse Berlin (ITB-Berlin) 2015, Germany ?",
      "a": "(A) Rajasthan",
      "b": "(B) Gujarat",
      "c": "(C) Madhya Pradesh",
      "d": "(D) Kerala",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who amongst the following has been chosen for US Presidential Award in March 2015 ?",
      "a": "(A) Murty S Kambhampati",
      "b": "(B) M .k Shinha",
      "c": "(C) Rahual Richard",
      "d": "(D) Nitin Hasika",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who wins of the 2015 Time magazine 100 reader’s poll?",
      "a": "(A) Lady Gaga",
      "b": "(B) Narendra Modi",
      "c": "(C) Xi Jinping",
      "d": "(D) Vladimir Putin",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " An Indian-origin schoolboy (15 year old) Pratap Singh was recently awarded the Institute of Physics Prize for conducting an experiment that verified an effect of ?",
      "a": "(A) Albert Einstein's theory of special relativity",
      "b": "(B) Raman effect",
      "c": "(C) Both A & B",
      "d": "(D) None of these",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who received Hevesy Medal Award 2015 for the development of nanomedicine products?",
      "a": "(A) Dr. Kattesh V.Katti",
      "b": "(B) Dr. Nilhan Samaranayake",
      "c": "(C) Dr. Fredric Brandt",
      "d": "(D) Dr. K.L. Ramakumar",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who is the co-creator of element 117 who was awarded Hevesy Medal Award2015 ?",
      "a": "(A) Susanta Lahiri",
      "b": "(B) Bappi Lahiri",
      "c": "(C) Arwind Lahiri",
      "d": "(D) Tarun Lahiri",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who has been selected for the Polly Umrigar Award for the 2013-14 season?",
      "a": "(A) Bhuvneshwar Kumar",
      "b": "(B) Virat Kohli",
      "c": "(C) Stuart Binny",
      "d": "(D) Ravindra Jadeja",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " With reference to the Jnanipath Award, which of the following statement(s) is/are correct? <br/> It is given for literary work in any language listed in the 8th schedule of the Indian Constitution.<br/>It is given for lifetime contribution to Indian Literature.",
      "a": "(A) Only 1",
      "b": "(B) Only 2",
      "c": "(C) Both 1 & 2",
      "d": "(D) Neither 1 nor 2",
      "correct": "C",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which Organization has been chosen for the Indira Gandhi Prize for Peace, Disarmament and Development 2014?",
      "a": "(A) ISRO",
      "b": "(B) Suzlon",
      "c": "(C) Coal India",
      "d": "(D) ONGC",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who among the following leaders was lauded with Japan's top National Award called 'The Grand Cordon Of the Order of the Paulownia Flowers' in 2014?",
      "a": "(A) Narendra Modi",
      "b": "(B) Manmohan Singh",
      "c": "(C) Sonia Gandhi",
      "d": "(D) Pranab Mukherji",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who was the winner of the Earth Heroes Award 2014?",
      "a": "(A) Erach Bharucha",
      "b": "(B) D.V. Girish",
      "c": "(C) Nirmal Kulkarni",
      "d": "(D) J.J.Dutta",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which actor won the Global Diversity award 2014?",
      "a": "(A) Amitabh Bachchan",
      "b": "(B) ShahRukh Khan",
      "c": "(C) Amir Khan",
      "d": "(D) Salman Khan",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who is the winner of the Sveriges Riskbank Prize in Economic Sciences for 2014, which is in memory of Alfred Nobel?",
      "a": "(A) Robert J.Shiller",
      "b": "(B) Llyod S. Shapley",
      "c": "(C) Thomas J. Sargent",
      "d": "(D) Jean Tirole",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Which of the following lyricist won the Kishore Kumar Award for 2012-13?",
      "a": "(A) Sameer",
      "b": "(B) Gulzaar",
      "c": "(C) Javed Akhtar",
      "d": "(D) Anjaan",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who received the Dadabhai Naoroji Award for Culture by the UK Government?",
      "a": "(A) Madhav Sharma",
      "b": "(B) Asha Khemka",
      "c": "(C) Patricia Hewitt",
      "d": "(D) Lynda Bellingham",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The “l international journalism award, given by the “Golden Pen of Freedom Award” is presented by ?",
      "a": "(A) World Association of Newspapers",
      "b": "(B) UNESCO",
      "c": "(C) Times Group",
      "d": "(D) United Nations",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " The Sant Kabir award is presented for exemplary contribution in which field?",
      "a": "(A) Hindustani Music",
      "b": "(B) Handicrafts and Handlooms",
      "c": "(C) Culture and Heritage",
      "d": "(D) Literature",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " For which of his creation Indian sand artist Sudarsan Pattnaik won the People’s Choice prize at the World Cup of Sand Sculpting-2014 in US.",
      "a": "(A) Save Water, Save the Future",
      "b": "(B) Save Tree, Enrich Green",
      "c": "(C) Save Water, Save the Life",
      "d": "(D) Save Tree, Save the Future",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Who was chosen for the honour ' Legion of France'?",
      "a": "(A) Ranbeer Kapoor",
      "b": "(B) Shah Rukh Khan",
      "c": "(C) Amir Khan",
      "d": "(D) Salman Khan",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Identify the winner of Pen Pinter Prize 2014?",
      "a": "(A) Arundathi Roy",
      "b": "(B) Salman Rushdie",
      "c": "(C) J K Rowling",
      "d": "(D) Ronald Clipp",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Gro Harlem Brundtland, the first recipient of Tang Prize in sustainable development, was a former Prime Minister of ?",
      "a": "(A) Norway",
      "b": "(B) Brazil",
      "c": "(C) Netherland",
      "d": "(D) Chile",
      "correct": "A",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Identify the award given for exemplary work in the field of ' Sustainable Development' ?",
      "a": "(A) Turing Prize",
      "b": "(B) Pen Pinter Award",
      "c": "(C) Donald P. Eckman Award",
      "d": "(D) Tang Prize",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Eminent writer Kedarnath Singh, chosen for the prestigious Jnanpith award, 2013 writes in which language?",
      "a": "(A) Panjabi",
      "b": "(B) Gujarati",
      "c": "(C) Urdu",
      "d": "(D) Hindi",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Identify the personality selected for the prestigious Moortidevi award, 2013?",
      "a": "(A) S L Byrappa",
      "b": "(B) Gopalkrishna Ayyer",
      "c": "(C) U R Anantha Murthy",
      "d": "(D) C Radhakrishnan",
      "correct": "D",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },
    {
      "qtext": " Sanjaya Rajaram a noted Indian scientists received the prestigious World Food Prize, 2014 for his contribution to developing high-yield varieties of ____?",
      "a": "(A) Soyabean",
      "b": "(B) Wheat",
      "c": "(C) Barley",
      "d": "(D) Rice",
      "correct": "B",
      "img": "",
      "topic": "Honours and Awards",
      "section": "(General Awareness)"
    },{
    "qtext": "B. C. Roy Award is given in the field of",
    "a": "A. Music",
    "b": "B. Journalism",
    "c": "C. Medicine",
    "d": "D. Environment",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "In which year was Pulitzer Prize established?",
    "a": "A. 1917",
    "b": "B. 1918",
    "c": "C. 1922",
    "d": "D. 1928",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Gandhi Peace Prize for the year 2000 was awarded to the former President of South Africa along with",
    "a": "A. Sathish Dawan",
    "b": "B. C. Subramanian",
    "c": "C. Grameen Bank of Bangladesh",
    "d": "D. World Healt Organisation",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The prestigious Ramon Magsaysay Award was conferred was conferred upon Ms. Kiran Bedi for her excellent contribution to which of the following fields?",
    "a": "A. Literature",
    "b": "B. Community Welfare",
    "c": "C. Government Service",
    "d": "D. Journalism",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following societies has instituted an award for an outstanding parliamentarian?",
    "a": "A. Jamanlal Bajaj Foundation",
    "b": "B. Institute of Constitutional and Parliamentary Studies",
    "c": "C. G. B. Pant Memorial Society",
    "d": "D. R. D. Birla samara Kosh",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Which is the highest gallantry award in India?",
    "a": "A. Param Vishishtat Seva Medal",
    "b": "B. Param Vir Chakra",
    "c": "C. Kirti Chakra",
    "d": "D. Vir Chakra",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Which state gives Mewar Award?",
    "a": "A. Haryana",
    "b": "B. Delhi",
    "c": "C. Punjab",
    "d": "D. Rajasthan",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Who is the first Asian Winner of Nobel Prize?",
    "a": "A. C. V. Raman",
    "b": "B. Rajiv Gandhi",
    "c": "C. Rabindranath Tagore",
    "d": "D. Mother Teresa",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The first Indian to receive Noble Prize in Literature was",
    "a": "A. Mother Teresa",
    "b": "B. C. V. Raman",
    "c": "C. Rabindranath Tagore",
    "d": "D. Sarojini Naidu",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The first recipient of Rajiv Gandhi's 'Khel Ratna' award is",
    "a": "A. Vishwanathan Anand",
    "b": "B. Leander Peas",
    "c": "C. Kapil Dev",
    "d": "D. Limba Ram",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Pulitzer prize is awarded for outstanding work in the field of",
    "a": "A. Science and Technology",
    "b": "B. Environmental Studies",
    "c": "C. Literature and Journalism",
    "d": "D. International Understanding",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Saraswathi Samman is given annually for outstanding contribution to",
    "a": "A. classical music",
    "b": "B. education",
    "c": "C. literature",
    "d": "D. fine arts",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Who among the following has received a Nobel Prize in literature 1953?",
    "a": "A. Pablo Neruda",
    "b": "B. Derek Walcott",
    "c": "C. Ernest Hemingway",
    "d": "D. Winston Churchill",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The Arjuna Awards were instituted in the year",
    "a": "A. 1965",
    "b": "B. 1961",
    "c": "C. 1963",
    "d": "D. 1957",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The first Indira Gandhi Award for International Justice and Harmony has been given to",
    "a": "A. Larry Pressler",
    "b": "B. Amnesty International",
    "c": "C. Hussain Ibrahim Zaki",
    "d": "D. Yasser Arafat",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "'Ashoka Chakra' is awarded for",
    "a": "A. acts of gallantry in the presence of enemy",
    "b": "B. gallantry by children",
    "c": "C. outstanding contribution to literature",
    "d": "D. the most conspicuous bravery or self sacrifice on land, air or sea but not in the presence of the enemy",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Who among the following is the recipient of the first Dayawati Modi Award for art, culture and education?",
    "a": "A. Dharmavir Bharti",
    "b": "B. Amitabh Bachchaan",
    "c": "C. B. V. Karanth",
    "d": "D. Ashok Vajpeyi",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The Nobel Prize was first awarded in",
    "a": "A. 1976",
    "b": "B. 1958",
    "c": "C. 1901",
    "d": "D. 1972",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Who among the following own the Nobel prize for literature?",
    "a": "A. Linus Pauling",
    "b": "B. Samuel Beckett",
    "c": "C. Philip Noel - Baker",
    "d": "D. Ralph Bunche",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The 'Cannes Award' is given for excellence in which field?",
    "a": "A. Films",
    "b": "B. Journalism",
    "c": "C. Literature",
    "d": "D. Economics",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The journalist who refused to accept 'Padma Bhushan' was?",
    "a": "A. Shekaran Nair",
    "b": "B. Khushwant Singh",
    "c": "C. Ratan Thiyam",
    "d": "D. Arun Shourie",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The Nobel peace prize is awarded in which city?",
    "a": "A. Oslo",
    "b": "B. Stockholm",
    "c": "C. Brussels",
    "d": "D. Geneva",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Arjuna Award is given for",
    "a": "A. Exceptional service in emergency",
    "b": "B. Bravery on battlefield",
    "c": "C. Outstanding performance in sports",
    "d": "D. Exceptional service in slum dwellers",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Who among the following is not a recipient of the Bharatiya Jnanpith Award?",
    "a": "A. Ashaparna Devi",
    "b": "B. M. F. Hussain",
    "c": "C. Raghupathi Sahai",
    "d": "D. V. K. Gokak",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The UNSECO's  'Prix Jules Verne' prize has been given to which of the following serials of Doordarshan?",
    "a": "A. The World This Week",
    "b": "B. Surabhi",
    "c": "C. Eye Witness",
    "d": "D. Turning Point",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Who among the following is not a recipient of 'Dada Saheb Phalke' Award?",
    "a": "A. Ramanand Sagar",
    "b": "B. Raj Kapoor",
    "c": "C. V. Shantaram",
    "d": "D. Ashok Kumar",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Which state Government of India has instituted the Samman Award?",
    "a": "A. Uttar Pradesh",
    "b": "B. Himachal Pradesh",
    "c": "C. Madhya Pradesh",
    "d": "D. Andhra Pradesh",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Sharad Joshi Samman is awarded for",
    "a": "A. Cartoon",
    "b": "B. Satire and essay",
    "c": "C. Trade Union Activity",
    "d": "D. Social Service",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "In 1901, Nobel Prize was not given for",
    "a": "A. Chemistry",
    "b": "B. Physics",
    "c": "C. Economics",
    "d": "D. Peace",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The highest civilian award of India 'Bharat Ratna' has been awarded to only two foreigners so far. One of them is Nelson Mandela. The other is",
    "a": "A. Abdul Ghaffar khan",
    "b": "B. Mikhail Gorbachev",
    "c": "C. Marshal Tito",
    "d": "D. Abdul Wali Khan",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The first recipient of Nehru Award was",
    "a": "A. Martin Luther King",
    "b": "B. Khan Abdul Ghaffar Khan",
    "c": "C. Mother Teresa",
    "d": "D. U Thant",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Shanthi Swaroop Bhatnagar awards are given for",
    "a": "A. exploring new dimensions in creative writing in Indian languages",
    "b": "B. outstanding contribution to science",
    "c": "C. creating mass awareness on environmental issues",
    "d": "D. excellence in film direction",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The Shanti Swarup Bhatnagar Award is given by which of the following organisations?",
    "a": "A. Council for Scientific and industrial research",
    "b": "B. Indian Council for Agricultural Research",
    "c": "C. Indian National Science Academy",
    "d": "D. ISRO",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following awards was conferred upon Smt. Aruna Asaf Ali for her role in the welfare of adult and women?",
    "a": "A. Tagore Literacy Award",
    "b": "B. UNSECO Literacy Award",
    "c": "C. Moorti Devi Award",
    "d": "D. Kalinga Prize",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "On whose name is the highest award for services to the development of cinema given?",
    "a": "A. Raj Kapoor",
    "b": "B. Dada Saheb",
    "c": "C. Meena Kumari",
    "d": "D. Amitabh Bachchan",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following famous financial journals of international repute confers 'Finance minister of the year' Award?",
    "a": "A. Dalal Street",
    "b": "B. Business Standard",
    "c": "C. Euromoney",
    "d": "D. Money Matters",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Tansen Samman has been instituted by the Government of?",
    "a": "A. Gujarat",
    "b": "B. Maharashtra",
    "c": "C. Uttar Pradesh",
    "d": "D. Madhya Pradesh",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "On whom did the U. S. President George W. Bush bestow, in 2002, the U.S.'s highest award for life time achievement in the field of scientific research?",
    "a": "A. Arun Netravalli",
    "b": "B. Dr.Hargoving Kohrana",
    "c": "C. Subramania Chandrasekar",
    "d": "D. Professor C. Radhakrishna Rao",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The only Indian to win the Nobel prize in physics is",
    "a": "A. Dr. J.C. Bose",
    "b": "B. Dr. C. V. Raman",
    "c": "C. Dr. Vickram Sarabhai",
    "d": "D. Dr. H. J. Bhabha",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Who among the following is a winner of the Indira Gandhi Award for National integration?",
    "a": "A. Aruna Asaf Ali",
    "b": "B. Ashok Kumar",
    "c": "C. Sundarlal Bahuguna",
    "d": "D. M. G. K. Menon",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "The first black American to win the Nobel Prize for literature is",
    "a": "A. Aurthe Ashe",
    "b": "B. Martin Luther King",
    "c": "C. Toni Morrison",
    "d": "D. Nelson Mandela",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Who among the following got the 'Bharat Ratna' award, before becoming the President of India?",
    "a": "A. R. Venkatramanan",
    "b": "B. Dr. Zakir Hussain",
    "c": "C. V. V. Giri",
    "d": "D. Dr. Rajendra Prasad",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Manav Seva Award has been instituted in the memory of",
    "a": "A. Rajiv Gandhi",
    "b": "B. Dr. Rajendra Prasad",
    "c": "C. Indira Gandhi",
    "d": "D. Acharya",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Kalinga Award was instituted by",
    "a": "A. UNESCO for exceptional contribution of efforts to popularise science",
    "b": "B. Indian Military.",
    "c": "C. Jnanpith, a cultural literacy society for encouraging creative writing in modern languages",
    "d": "D. Indian Adult Education Association for outstanding contribution of adult literacy in India",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following films has won 9 Oscar Awards in 1987?",
    "a": "A. The World Safari",
    "b": "B. The Last Emperor",
    "c": "C. Rain Man",
    "d": "D. Amadeus",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following awards was conferred on Mrs. Kiran Bedi?",
    "a": "A. Golden Globe",
    "b": "B. Rani Lakshmi",
    "c": "C. Magsaysay",
    "d": "D. Saraswati",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "Who was awarded the first Rajiv Gandhi National Sadhavana Award?",
    "a": "A. Archarya Tulsi",
    "b": "B. Dr. J. Rengaswamy",
    "c": "C. J. R. D Tata",
    "d": "D. Mother Teresa",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "'Global 500' awards are given for the outstanding achievement in which of the following fields?",
    "a": "A. Campaign against AIDS",
    "b": "B. Population control",
    "c": "C. Protection of environment",
    "d": "D. Elimination of illiteracy",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
},{
    "qtext": "To whom was 'Bharat Ratna' awarded in 1999?",
    "a": "A. Lata Mangeshkar",
    "b": "B. Amartya Sen",
    "c": "C. M. S. Subbulakshmi",
    "d": "D. Atal Behari Vajpayee",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Honours and Awards",
    "section": "(General Awareness)"
}
  ]
}