{"data":[
  {
    "qtext": "Sattriya is a classical dance form of which State?",
    "a": "a. Manipur",
    "b": "b. Uttar Pradesh",
    "c": "c. Assam",
    "d": "d. Andhra Pradesh",
    "correct": "c",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "___________ is classical dance form of Uttar Pradesh.",
    "a": "a. Kathakali",
    "b": "b. Kathak",
    "c": "c. Kuchipudi",
    "d": "d. Mohiniattam",
    "correct": "b",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which classical dance form is famous in Tamil Nadu?",
    "a": "a. Kuchipudi",
    "b": "b. Mohiniattam",
    "c": "c. Bharatanatyam",
    "d": "d. Kathakali",
    "correct": "c",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which of the following is not a folk dance of Uttar Pradesh?",
    "a": "a. Quawwalis",
    "b": "b. Chhau",
    "c": "c. Birhas",
    "d": "d. Charkulas",
    "correct": "b",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which is the folk dance of Andhra Pradesh?",
    "a": "a. Kolattam",
    "b": "b. Karakattam",
    "c": "c. Lavani",
    "d": "d. Saturi",
    "correct": "a",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which devotional saint was cobbler by profession?",
    "a": "a. Tulsidas",
    "b": "b. Raidas",
    "c": "c. Surdas",
    "d": "d. None of the above",
    "correct": "b",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which Indian Academy is promoting dance, drama and music?",
    "a": "a. Sahitya Academy",
    "b": "b. National School of Drama",
    "c": "c. Lalit Kala Academy",
    "d": "d. Sangeet Academy",
    "correct": "d",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "In which year National Anthem was first sung?",
    "a": "a. 1911",
    "b": "b. 1912",
    "c": "c. 1913",
    "d": "d. 1914",
    "correct": "a",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Madhubani painting is famous in which of the following state?",
    "a": "a. Uttar Pradesh",
    "b": "b. Kerala",
    "c": "c. Bihar",
    "d": "d. Tamil Naidu",
    "correct": "c",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "The word ‘Sathyameva Jayate’ is taken from __________",
    "a": "a. Yajur Veda",
    "b": "b. Mundaka Upanishad",
    "c": "c. Atharva Veda",
    "d": "d. Sam Veda",
    "correct": "b",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "The famous song ‘Saare Jaha se Achha’ is composed by ___________",
    "a": "a. Ravindra Nath Tagore",
    "b": "b. Bankim Chandra Chattopadhya",
    "c": "c. Mohammad Iqbal",
    "d": "d. None of the above",
    "correct": "c",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Boat race is part of which of the following festival?",
    "a": "a. Pongal",
    "b": "b. Onam",
    "c": "c. Bihu",
    "d": "d. Navratri",
    "correct": "b",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Who had introduced Police system in India?",
    "a": "a. Lord Wellesley",
    "b": "b. Lord Minto",
    "c": "c. Lord Hastings",
    "d": "d. Lord Cornwallis",
    "correct": "d",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which of the following Raga is sung early in the morning?",
    "a": "a. Todi",
    "b": "b. Darbari",
    "c": "c. Malhar",
    "d": "d. Bhopali",
    "correct": "a",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "__________ is the traditional form of Rangoli practised in the state of Uttarakhand.",
    "a": "a. Aripana",
    "b": "b. Aipan",
    "c": "c. Alpana",
    "d": "d. Kolam",
    "correct": "b",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Aripana, an art form of Rangoli is practised in which state?",
    "a": "a. Tamil Nadu",
    "b": "b. Kerala",
    "c": "c. Bihar",
    "d": "d. Uttar Pradesh",
    "correct": "c",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which ofRangoli is made with the help of coarse rice flour?",
    "a": "a. Aripana",
    "b": "b. Kolam",
    "c": "c. Alpana",
    "d": "d. None of the above",
    "correct": "b",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which of the raga is not composed by Tansen?",
    "a": "a. Deepak Raga",
    "b": "b. Bhairav Raga",
    "c": "c. Darbari Todi",
    "d": "d. Malhar Raga",
    "correct": "a",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which form of Hindustani Classical music Pandit Bhimsen Joshi is famous for?",
    "a": "a. Thumri",
    "b": "b. Dhrupad",
    "c": "c. Tarana",
    "d": "d. Khayal",
    "correct": "d",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Badaam Halwa is a popular __________ dish",
    "a": "a. Kashmiri",
    "b": "b. Gujarati",
    "c": "c. Mughlai",
    "d": "d. Bengali",
    "correct": "c",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which dish is one of the popular dishes of Kashmir?",
    "a": "a. Aloo Ka Raita",
    "b": "b. Dum Aloo",
    "c": "c. Kesar Chawal",
    "d": "d. Murgh Achaari",
    "correct": "b",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "The rock cut temples of Mahabalipuram and the temples of Kanchipuram are the achievements of the ________ rulers.",
    "a": "a. Pallava",
    "b": "b. Chola",
    "c": "c. Hoyasala",
    "d": "d. Vijayanagar",
    "correct": "a",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which of the following is not a Char Dham?",
    "a": "a. Puri",
    "b": "b. Dwarka",
    "c": "c. Mansarovar",
    "d": "d. Rameswaram",
    "correct": "c",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Kumbh Mela is held in every ___ years",
    "a": "a. 12",
    "b": "b. 10",
    "c": "c. 9",
    "d": "d. 6",
    "correct": "a",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which of the musical instruments are of Indo-Islamic origin?",
    "a": "a. Sitar, Table and Shehnai",
    "b": "b. Sitar, Tabla and Sarangi",
    "c": "c. Sitar, Sarangi and Shehnai",
    "d": "d. Sarangi, Tabla and Shehnai",
    "correct": "b",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which imaginary place is used in R.K. Narayan’s stories?",
    "a": "a. Malguri",
    "b": "b. Nalgudi",
    "c": "c. Nalguri",
    "d": "d. Malgudi",
    "correct": "d",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which novel Rabindra Nath Tagore won the Noble Prize for?",
    "a": "a. Rajashi",
    "b": "b. Rupanjali",
    "c": "c. Gitanjali",
    "d": "d. Meghadutam",
    "correct": "c",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Who has written famous novel ‘Devdas’?",
    "a": "a. Saratchandra Chattopadhyay",
    "b": "b. Rabindranath Tagore",
    "c": "c. Samudra Gupta",
    "d": "d. Bankim Chandra Chattopadhyay",
    "correct": "a",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "‘Panchatantra’ is originally written by _____________.",
    "a": "a. Kalidas",
    "b": "b. Vishnu Sharma",
    "c": "c. Tulsi Das",
    "d": "d. None of the above",
    "correct": "b",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "Which Veda Sanskrit literature has begun from?",
    "a": "a. Yajur Veda",
    "b": "b. Atharva Veda",
    "c": "c. Sam Veda",
    "d": "d. Rig Veda",
    "correct": "d",
    "img": "",
    "topic": "Indian Culture",
    "section": "(General Awareness)"
  },
  {
    "qtext": "The ratio of width of our National flag to its length is",
    "a": "A. 3:5",
    "b": "B. 2:3",
    "c": "C. 2:4",
    "d": "D. 3:4",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "Rabindranath Tagore's 'Jana Gana Mana' has been adopted as India's National Anthem. How many stanzas of the said song were adopted?",
    "a": "A. Only the first stanza",
    "b": "B. The whole song",
    "c": "C. Third and Fourth stanza",
    "d": "D. First and Second stanza",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "'Natya - Shastra' the main source of India's classical dances was written by",
    "a": "A. Nara Muni",
    "b": "B. Bharat Muni",
    "c": "C. Abhinav Gupt",
    "d": "D. Tandu Muni",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "'Dandia' is a popular dance of",
    "a": "A. Punjab",
    "b": "B. Gujarat",
    "c": "C. Tamil Nadu",
    "d": "D. Maharashtra",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "The words 'Satyameva Jayate' inscribed below the base plate of the emblem of India are taken from",
    "a": "A. Rigveda",
    "b": "B. Satpath Brahmana",
    "c": "C. Mundak Upanishad",
    "d": "D. Ramayana",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "Mohiniattam dance from developed originally in which state?",
    "a": "A. Tamil Nadu",
    "b": "B. Orissa",
    "c": "C. Kerala",
    "d": "D. Karnataka",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "Which of the following folk dance forms is associated with Gujarat?",
    "a": "A. Nautanki",
    "b": "B. Garba",
    "c": "C. Kathakali",
    "d": "D. Bhangra",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "Which of the following Akademis is responsible for fostering the development of dance, drama and music in India?",
    "a": "A. National School of Drama",
    "b": "B. Sangeet Akademi",
    "c": "C. Sahitya Akademi",
    "d": "D. Lalit Kala Akademi",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "The Rath Yatra at Puri is celebrated in honour of which Hindu deity",
    "a": "A. Ram",
    "b": "B. Jaganath",
    "c": "C. Shiva",
    "d": "D. Vishnu",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "The book of Parsis is",
    "a": "A. Torah",
    "b": "B. Bible",
    "c": "C. Zend Avesta",
    "d": "D. Gita",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "'Kathakali' is a folk dance prevalent in which state?",
    "a": "A. Karnataka",
    "b": "B. Orissa",
    "c": "C. Kerala",
    "d": "D. Manipur",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "Which of the following dances is a solo dance?",
    "a": "A. Ottan Thullal",
    "b": "B. Kuchipudi",
    "c": "C. Yakshagana",
    "d": "D. Odissi",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "The National Anthem was first sung in the year",
    "a": "A. 1911",
    "b": "B. 1913",
    "c": "C. 1936",
    "d": "D. 1935",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "Thillana is a format of",
    "a": "A. Kuchipudi",
    "b": "B. Odissi",
    "c": "C. Baharatanatyam",
    "d": "D. Kathak",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "'Madhubani',  a style of folk paintings, is popular in which of the following states in India?",
    "a": "A. Uttar Pradesh",
    "b": "B. Rajasthan",
    "c": "C. Madhya Pradesh",
    "d": "D. Bihar",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "Kathak is a classical dance of",
    "a": "A. North India",
    "b": "B. Tamilnadu",
    "c": "C. Manipur",
    "d": "D. Kerala",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "The head quarters of Sahitya Akademi is at",
    "a": "A. Mumbai",
    "b": "B. Chennai",
    "c": "C. New Delhi",
    "d": "D. Kolkata",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "The dance encouraged and performance from the temple of Tanjore was",
    "a": "A. Kathakali",
    "b": "B. Odissi",
    "c": "C. Kathak",
    "d": "D. Bharatanatyam",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "The last Mahakumbh of the 20th century was held at",
    "a": "A. Nasik",
    "b": "B. Ujjain",
    "c": "C. Allahabad",
    "d": "D. Haridwar",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "The National Song of India was composed by",
    "a": "A. Rabindranath Tagore",
    "b": "B. Bankim Chandra Chatterji",
    "c": "C. Iqbal",
    "d": "D. Jai Shankar Prasad",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "Who composed the famous song 'Sare Jahan SeAchha'?",
    "a": "A. Jaidev",
    "b": "B. Mohammad Iqbal",
    "c": "C. Bankim Chandra Chattopadhyay",
    "d": "D. Rabindranath Tagore",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "In which of the following festivals are boat races a special feature?",
    "a": "A. Onam",
    "b": "B. Rongali Bihu",
    "c": "C. Navratri",
    "d": "D. Pongal",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "Kalchakra ceremony is associated with which of the following ceremonies?",
    "a": "A. Hinduism",
    "b": "B. Buddhism",
    "c": "C. Jainism",
    "d": "D. Islam",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "#topic",
    "section": "#section"
},{
    "qtext": "Which of the following places is famous for Chikankari work, which is a traditional art of embroidery?",
    "a": "A. Lucknow",
    "b": "B. Hyderabad",
    "c": "C. Jaipur",
    "d": "D. Mysore",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "#topic",
    "section": "#section"
}
]}