{
  "data":[
  {
    "qtext": "Papikonda National Park is in _______.",
    "a": " A. Lakshadweep",
    "b": " B. West Bengal",
    "c": " C. Andhra Pradesh",
    "d": " D. Odisha",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Rajiv Gandhi National Park is in _______.",
    "a": " A. Nagaland",
    "b": " B. Mizoram",
    "c": " C. Andhra Pradesh",
    "d": " D. Andaman and Nicobar Islands",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Sri Venkateswara National Park is situated in which of the following states?",
    "a": " A. Andhra Pradesh",
    "b": " B. Haryana",
    "c": " C. Arunachal Pradesh",
    "d": " D. Andaman and Nicobar Islands",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kasu Brahmananda Reddy National Park is in _______.",
    "a": " A. Jammu and Kashmir",
    "b": " B. Puducherry",
    "c": " C. Telangana",
    "d": " D. Bihar",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Mahavir Harina Vanasthali National Park is situated?",
    "a": " A. Maharashtra",
    "b": " B. Chandigarh",
    "c": " C. Telangana",
    "d": " D. Sikkim",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Mrugavani National Park is situated?",
    "a": " A. Punjab",
    "b": " B. Chhattisgarh",
    "c": " C. Daman and Diu",
    "d": " D. Telangana",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Namdapha National Park is in _______.",
    "a": " A. Delhi",
    "b": " B. Andaman and Nicobar Islands",
    "c": " C. Assam",
    "d": " D. Arunachal Pradesh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mouling National Park is in _______.",
    "a": " A. Chandigarh",
    "b": " B. Manipur",
    "c": " C. Jharkhand",
    "d": " D. Arunachal ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Dibru-Saikhowa National Park is situated?",
    "a": " A. Jammu and Kashmir",
    "b": " B. Tamil Nadu",
    "c": " C. Jharkhand",
    "d": " D. ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kaziranga National Park is in _______.",
    "a": " A. Puducherry",
    "b": " B. Arunachal Pradesh",
    "c": " C. Chandigarh",
    "d": " D. Assam",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Manas National Park is situated?",
    "a": " A. Dadra and Nagar Haveli",
    "b": " B. Andaman and Nicobar Islands",
    "c": " C. Manipur",
    "d": " D. ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Nameri National Park is situated in which of the following states?",
    "a": " A. Goa",
    "b": " B. Rajasthan",
    "c": " C. Sikkim",
    "d": " D. ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Rajiv Gandhi Orang National Park is situated?",
    "a": " A. Daman and Diu",
    "b": " B. Mizoram",
    "c": " C. Jharkhand",
    "d": " D. Assam",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Valmiki National Park is situated in which of the following states?",
    "a": " A. Nagaland",
    "b": " B. Telangana",
    "c": " C. Jharkhand",
    "d": " D. Bihar",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Indravati National Park is in _______.",
    "a": " A. Karnataka",
    "b": " B. Nagaland",
    "c": " C. Chhattisgarh",
    "d": " D. Rajasthan",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kanger Valley National Park is situated in which of the following states?",
    "a": " A. Lakshadweep",
    "b": " B. ",
    "c": " C. Jharkhand",
    "d": " D. Maharashtra",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Guru Ghasi Das (Sanjay) National Park is in _______.",
    "a": " A. Uttarakhand",
    "b": " B. Rajasthan",
    "c": " C. Andhra Pradesh",
    "d": " D. Chhattisgarh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bhagwan Mahavir (Mollem) National Park is situated in which of the following states?",
    "a": " A. Uttarakhand",
    "b": " B. Meghalaya",
    "c": " C. ",
    "d": " D. Chhattisgarh",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Blackbuck National Park is situated?",
    "a": " A. West Bengal",
    "b": " B. Rajasthan",
    "c": " C. Karnataka",
    "d": " D.  Velavadar Gujarat",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Gir Forest National Park is situated?",
    "a": " A. Gujarat",
    "b": " B. Jammu and Kashmir",
    "c": " C. Chhattisgarh",
    "d": " D. Arunachal Pradesh",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Marine National Park is situated in which of the following states?",
    "a": " A. Andhra Pradesh",
    "b": " B. Meghalaya",
    "c": " C.  Gulf of Kutch Gujarat",
    "d": " D. Maharashtra",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Vansda National Park is in _______.",
    "a": " A. Arunachal Pradesh",
    "b": " B. Jharkhand",
    "c": " C. Daman and Diu",
    "d": " D. Gujarat",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kalesar National Park is in _______.",
    "a": " A. Telangana",
    "b": " B. Tripura",
    "c": " C. Jammu and Kashmir",
    "d": " D. Haryana",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Sultanpur National Park is in _______.",
    "a": " A. Goa",
    "b": " B. Jharkhand",
    "c": " C. Karnataka",
    "d": " D. Haryana",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Pin Valley National Park is situated?",
    "a": " A. Assam",
    "b": " B. Himachal ",
    "c": " C. Uttar Pradesh",
    "d": " D. Kerala",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Great Himalayan National Park is in _______.",
    "a": " A. Tamil Nadu",
    "b": " B. Assam",
    "c": " C. Nagaland",
    "d": " D. Himachal Pradesh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Inderkilla  National Park is situated?",
    "a": " A. Nagaland",
    "b": " B. Himachal ",
    "c": " C. Mizoram",
    "d": " D. Madhya Pradesh",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Khirganga  National Park is in _______.",
    "a": " A. Dadra and Nagar Haveli",
    "b": " B. Himachal Pradesh",
    "c": " C. Himachal ",
    "d": " D. Mizoram",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Simbalbara  National Park is situated?",
    "a": " A. Jharkhand",
    "b": " B. Gujarat",
    "c": " C. Telangana",
    "d": " D. Himachal Pradesh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Dachigam National Park is in _______.",
    "a": " A. Rajasthan",
    "b": " B. Jammu and ",
    "c": " C. Andhra Pradesh",
    "d": " D. Odisha",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Hemis National Park is situated in which of the following states?",
    "a": " A. Uttar Pradesh",
    "b": " B. Telangana",
    "c": " C. Sikkim",
    "d": " D. Jammu and ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kishtwar National Park is situated in which of the following states?",
    "a": " A. Punjab",
    "b": " B. Mizoram",
    "c": " C. Jammu and ",
    "d": " D. West Bengal",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Salim Ali National Park is in _______.",
    "a": " A. Kerala",
    "b": " B. Nagaland",
    "c": " C. Chhattisgarh",
    "d": " D. Jammu and Kashmir",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Betla National Park is in _______.",
    "a": " A. Sikkim",
    "b": " B. Jammu and Kashmir",
    "c": " C. Odisha",
    "d": " D. Jharkhand",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bandipur National Park is in _______.",
    "a": " A. Uttarakhand",
    "b": " B. Delhi",
    "c": " C. Kerala",
    "d": " D. Karnataka",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bannerghatta National Park is in _______.",
    "a": " A. Karnataka",
    "b": " B. Himachal Pradesh",
    "c": " C. Madhya Pradesh",
    "d": " D. Sikkim",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kudremukh National Park is situated in which of the following states?",
    "a": " A. Arunachal Pradesh",
    "b": " B. Nagaland",
    "c": " C. Delhi",
    "d": " D. Karnataka",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Nagarhole (Rajiv Gandhi) National Park is situated in which of the following states?",
    "a": " A. Tamil Nadu",
    "b": " B. Karnataka",
    "c": " C. Rajasthan",
    "d": " D. Madhya Pradesh",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Anshi national park is situated?",
    "a": " A. Delhi",
    "b": " B. Uttar Pradesh",
    "c": " C. Chhattisgarh",
    "d": " D. Karnataka",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Eravikulam National Park is situated in which of the following states?",
    "a": " A. Uttar Pradesh",
    "b": " B. Uttarakhand",
    "c": " C. Puducherry",
    "d": " D. ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mathikettan Shola National Park is in _______.",
    "a": " A. Daman and Diu",
    "b": " B. Gujarat",
    "c": " C. Kerala",
    "d": " D. West Bengal",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Periyar National Park is situated in which of the following states?",
    "a": " A. Uttar Pradesh",
    "b": " B. Jammu and Kashmir",
    "c": " C. Andaman and Nicobar Islands",
    "d": " D. ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Silent Valley National Park is situated?",
    "a": " A. Dadra and Nagar Haveli",
    "b": " B. Bihar",
    "c": " C. Himachal Pradesh",
    "d": " D. Kerala",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Anamudi Shola National Park is in _______.",
    "a": " A. Tripura",
    "b": " B. Telangana",
    "c": " C. Madhya Pradesh",
    "d": " D. Kerala",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Pambadum Shola National Park is situated?",
    "a": " A. Sikkim",
    "b": " B. Kerala",
    "c": " C. Goa",
    "d": " D. Uttar Pradesh",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bandhavgarh National Park is situated in which of the following states?",
    "a": " A. Dadra and Nagar Haveli",
    "b": " B. Madhya Pradesh",
    "c": " C. Tamil Nadu",
    "d": " D. Chhattisgarh",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Kanha National Park is situated?",
    "a": " A. Jammu and Kashmir",
    "b": " B. Jharkhand",
    "c": " C. Sikkim",
    "d": " D. Madhya ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Madhav National Park is situated?",
    "a": " A. Madhya Pradesh",
    "b": " B. Gujarat",
    "c": " C. Karnataka",
    "d": " D. Mizoram",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mandla Plant Fossils National Park is in _______.",
    "a": " A. West Bengal",
    "b": " B. Karnataka",
    "c": " C. Madhya Pradesh",
    "d": " D. Andhra Pradesh",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Panna National Park is situated?",
    "a": " A. Andaman and Nicobar Islands",
    "b": " B. Madhya Pradesh",
    "c": " C. Arunachal Pradesh",
    "d": " D. Andhra Pradesh",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Pench (Priyadarshini) National Park is situated?",
    "a": " A. Madhya Pradesh",
    "b": " B. Punjab",
    "c": " C. Nagaland",
    "d": " D. Kerala",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Sanjay National Park is in _______.",
    "a": " A. Chandigarh",
    "b": " B. Daman and Diu",
    "c": " C. Arunachal Pradesh",
    "d": " D. Madhya Pradesh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Satpura National Park is situated?",
    "a": " A. Uttarakhand",
    "b": " B. Chandigarh",
    "c": " C. Kerala",
    "d": " D. Madhya Pradesh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Van Vihar National Park is in _______.",
    "a": " A. Mizoram",
    "b": " B. Madhya Pradesh",
    "c": " C. Kerala",
    "d": " D. Andaman and Nicobar Islands",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Chandoli National Park is situated?",
    "a": " A. Jammu and Kashmir",
    "b": " B. Maharashtra",
    "c": " C. Telangana",
    "d": " D. Andhra Pradesh",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Gugamal National Park is in _______.",
    "a": " A. Karnataka",
    "b": " B. Uttar Pradesh",
    "c": " C. Himachal Pradesh",
    "d": " D. Maharashtra",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Navegaon National Park is situated in which of the following states?",
    "a": " A. Goa",
    "b": " B. Andhra Pradesh",
    "c": " C. Nagaland",
    "d": " D. Maharashtra",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Sanjay Gandhi  (Borivilli) National Park is situated in which of the following states?",
    "a": " A. Lakshadweep",
    "b": " B. Karnataka",
    "c": " C. Uttarakhand",
    "d": " D. Maharashtra",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Tadoba National Park is situated?",
    "a": " A. Gujarat",
    "b": " B. Uttarakhand",
    "c": " C. Kerala",
    "d": " D. Maharashtra",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Pench National Park is situated in which of the following states?",
    "a": " A. West Bengal",
    "b": " B. Andhra Pradesh",
    "c": " C. Delhi",
    "d": " D. Maharashtra",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Keibul Lamjao National Park is situated?",
    "a": " A. Tamil Nadu",
    "b": " B. Karnataka",
    "c": " C. Jammu and Kashmir",
    "d": " D. ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Balphakram National Park is situated?",
    "a": " A. Maharashtra",
    "b": " B. Dadra and Nagar Haveli",
    "c": " C. Daman and Diu",
    "d": " D. ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Nokrek National Park is situated?",
    "a": " A. Goa",
    "b": " B. Meghalaya",
    "c": " C. Bihar",
    "d": " D. Delhi",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Murlen National Park is situated?",
    "a": " A. Tripura",
    "b": " B. Himachal Pradesh",
    "c": " C. Chhattisgarh",
    "d": " D. ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Phawngpui Blue Mountain National Park is in _______.",
    "a": " A. Nagaland",
    "b": " B. Jharkhand",
    "c": " C. West Bengal",
    "d": " D. ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Intanki  National Park is situated?",
    "a": " A. Maharashtra",
    "b": " B. Chandigarh",
    "c": " C. Nagaland",
    "d": " D. Karnataka",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bhitarkanika National Park is in _______.",
    "a": " A. Jammu and Kashmir",
    "b": " B. ",
    "c": " C. Madhya Pradesh",
    "d": " D. Goa",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Simlipal National Park is situated in which of the following states?",
    "a": " A. Madhya Pradesh",
    "b": " B. Daman and Diu",
    "c": " C. Maharashtra",
    "d": " D. Odisha",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Sariska National Park is situated in which of the following states?",
    "a": " A. Goa",
    "b": " B. Dadra and Nagar Haveli",
    "c": " C. Chandigarh",
    "d": " D. Rajasthan",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Ranthambore National Park is in _______.",
    "a": " A. Jharkhand",
    "b": " B. Andaman and Nicobar Islands",
    "c": " C. ",
    "d": " D. Delhi",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Mukundra Hills (Darrah) National Park is situated?",
    "a": " A. Andhra Pradesh",
    "b": " B. Mizoram",
    "c": " C. Punjab",
    "d": " D. Rajasthan",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Desert National Park is situated in which of the following states?",
    "a": " A. Lakshadweep",
    "b": " B. ",
    "c": " C. Maharashtra",
    "d": " D. Sikkim",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Keoladeo Ghana National Park is situated?",
    "a": " A. Daman and Diu",
    "b": " B. Bihar",
    "c": " C. Telangana",
    "d": " D. Rajasthan",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Khangchendzonga National Park is situated?",
    "a": " A. Himachal Pradesh",
    "b": " B. Assam",
    "c": " C. Uttar Pradesh",
    "d": " D. ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mudumalai National Park is situated in which of the following states?",
    "a": " A. Uttar Pradesh",
    "b": " B. Tamil Nadu",
    "c": " C. Uttarakhand",
    "d": " D. Nagaland",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Mukurthi National Park is situated?",
    "a": " A. Himachal Pradesh",
    "b": " B. Delhi",
    "c": " C. Tamil Nadu",
    "d": " D. Bihar",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Indira Gandhi (Annamalai) National Park is in _______.",
    "a": " A. Andhra Pradesh",
    "b": " B. Kerala",
    "c": " C. Tamil Nadu",
    "d": " D. Dadra and Nagar Haveli",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Guindy National Park is situated in which of the following states?",
    "a": " A. Puducherry",
    "b": " B. Uttar Pradesh",
    "c": " C. Dadra and Nagar Haveli",
    "d": " D. Tamil Nadu",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Gulf of Mannar Marine National Park is in _______.",
    "a": " A. Maharashtra",
    "b": " B. West Bengal",
    "c": " C. Tamil Nadu",
    "d": " D. Dadra and Nagar Haveli",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bison( Rajbari )  National Park is situated in which of the following states?",
    "a": " A. Dadra and Nagar Haveli",
    "b": " B. Haryana",
    "c": " C. Tripura",
    "d": " D. Karnataka",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Clouded Leopard  National Park is in _______.",
    "a": " A. Rajasthan",
    "b": " B. Nagaland",
    "c": " C. Tripura",
    "d": " D. Chandigarh",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Dudhwa National Park is situated in which of the following states?",
    "a": " A. Manipur",
    "b": " B. Telangana",
    "c": " C. Andhra Pradesh",
    "d": " D. Uttar ",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Gangotri National Park is situated in which of the following states?",
    "a": " A. Bihar",
    "b": " B. Haryana",
    "c": " C. Uttarakhand",
    "d": " D. Arunachal Pradesh",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Govind Pashu Vihar is situated in which of the following states?",
    "a": " A. Telangana",
    "b": " B. Gujarat",
    "c": " C. Assam",
    "d": " D. Uttarakhand",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Jim Corbett National Park is situated?",
    "a": " A. Tamil Nadu",
    "b": " B. Assam",
    "c": " C. Uttarakhand",
    "d": " D. Kerala",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Nanda Devi National Park is situated?",
    "a": " A. Haryana",
    "b": " B. Chhattisgarh",
    "c": " C. Uttarakhand",
    "d": " D. Puducherry",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Rajaji National Park is situated in which of the following states?",
    "a": " A. West Bengal",
    "b": " B. Punjab",
    "c": " C. Mizoram",
    "d": " D. Uttarakhand",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Valley of Flowers National Park is situated?",
    "a": " A. Uttarakhand",
    "b": " B. Maharashtra",
    "c": " C. Dadra and Nagar Haveli",
    "d": " D. Bihar",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Gorumara National Park is situated in which of the following states?",
    "a": " A. West Bengal",
    "b": " B. Tamil Nadu",
    "c": " C. Daman and Diu",
    "d": " D. Goa",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Buxa National Park is in _______.",
    "a": " A. Tamil Nadu",
    "b": " B. West Bengal",
    "c": " C. Bihar",
    "d": " D. Puducherry",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Neora Valley National Park is situated?",
    "a": " A. Andaman and Nicobar Islands",
    "b": " B. Tamil Nadu",
    "c": " C. West Bengal",
    "d": " D. Delhi",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Singalila National Park is situated in which of the following states?",
    "a": " A. Gujarat",
    "b": " B. Arunachal Pradesh",
    "c": " C. Karnataka",
    "d": " D. West Bengal",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Jaldapara National Park is situated in which of the following states?",
    "a": " A. Uttar Pradesh",
    "b": " B. Haryana",
    "c": " C. West Bengal",
    "d": " D. Assam",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Sundarbans National Park is in _______.",
    "a": " A. Tamil Nadu",
    "b": " B. Dadra and Nagar Haveli",
    "c": " C. Lakshadweep",
    "d": " D. West Bengal",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mahatama Gandhi Marine (Wandoor) National Park is situated in which of the following states?",
    "a": " A. Haryana",
    "b": " B. Arunachal Pradesh",
    "c": " C. Andaman and Nicobar Islands",
    "d": " D. Odisha",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Middle Button Island National Park is situated?",
    "a": " A. Maharashtra",
    "b": " B. Punjab",
    "c": " C. Puducherry",
    "d": " D. Andaman and Nicobar Islands",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mount Harriett National Park is in _______.",
    "a": " A. Daman and Diu",
    "b": " B. Chandigarh",
    "c": " C. Rajasthan",
    "d": " D. Andaman and Nicobar Islands",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states North Button Island National Park is situated?",
    "a": " A. Andaman and Nicobar Islands",
    "b": " B. Maharashtra",
    "c": " C. Chandigarh",
    "d": " D. Meghalaya",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Rani Jhansi Marine National Park is in _______.",
    "a": " A. Andaman and Nicobar Islands",
    "b": " B. Daman and Diu",
    "c": " C. Odisha",
    "d": " D. Gujarat",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Saddle Peak National Park is situated?",
    "a": " A. Jharkhand",
    "b": " B. Andaman and Nicobar Islands",
    "c": " C. Gujarat",
    "d": " D. Nagaland",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states South Button Island National Park is situated?",
    "a": " A. Maharashtra",
    "b": " B. Jharkhand",
    "c": " C. Andaman and Nicobar Islands",
    "d": " D. Chandigarh",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Campbell Bay National Park is situated in which of the following states?",
    "a": " A. Punjab",
    "b": " B. Rajasthan",
    "c": " C. Assam",
    "d": " D. Andaman and Nicobar Islands",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Galathea Bay National Park is situated?",
    "a": " A. Andaman and Nicobar",
    "b": " B. Tripura",
    "c": " C. Odisha",
    "d": " D. Jharkhand",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  }
]}
