{"data":[
  {
    "qtext": "Papikonda National Park is in _______.",
    "a": " A. Tripura",
    "b": " B. Chandigarh",
    "c": " C. Andaman and Nicobar Islands",
    "d": " D. Andhra Pradesh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Rajiv Gandhi National Park is in _______.",
    "a": " A. Andhra Pradesh",
    "b": " B. Karnataka",
    "c": " C. Tripura",
    "d": " D. Bihar",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Sri Venkateswara National Park is situated in which of the following states?",
    "a": " A. Dadra and Nagar Haveli",
    "b": " B. Nagaland",
    "c": " C. Andhra Pradesh",
    "d": " D. Tamil Nadu",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kasu Brahmananda Reddy National Park is situated in which of the following states?",
    "a": " A. Delhi",
    "b": " B. Haryana",
    "c": " C. Nagaland",
    "d": " D. Telangana",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mahavir Harina Vanasthali National Park is situated in which of the following states?",
    "a": " A. Jharkhand",
    "b": " B. Mizoram",
    "c": " C. Delhi",
    "d": " D. Telangana",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mrugavani National Park is in _______.",
    "a": " A. Mizoram",
    "b": " B. Punjab",
    "c": " C. Telangana",
    "d": " D. Jammu and Kashmir",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Namdapha National Park is in _______.",
    "a": " A. Himachal Pradesh",
    "b": " B. Haryana",
    "c": " C. Arunachal Pradesh",
    "d": " D. Chhattisgarh",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mouling National Park is situated in which of the following states?",
    "a": " A. Tripura",
    "b": " B. Arunachal ",
    "c": " C. Sikkim",
    "d": " D. Puducherry",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Dibru-Saikhowa National Park is in _______.",
    "a": " A. Sikkim",
    "b": " B. Daman and Diu",
    "c": " C. Assam",
    "d": " D. Uttar Pradesh",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kaziranga National Park is in _______.",
    "a": " A. Mizoram",
    "b": " B. Tripura",
    "c": " C. Haryana",
    "d": " D. Assam",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Manas National Park is in _______.",
    "a": " A. Sikkim",
    "b": " B. Puducherry",
    "c": " C. Arunachal Pradesh",
    "d": " D. Assam",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Nameri National Park is situated in which of the following states?",
    "a": " A. Puducherry",
    "b": " B. Assam",
    "c": " C. Gujarat",
    "d": " D. Kerala",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Rajiv Gandhi Orang National Park is situated?",
    "a": " A. Madhya Pradesh",
    "b": " B. Daman and Diu",
    "c": " C. Jammu and Kashmir",
    "d": " D. Assam",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Valmiki National Park is situated in which of the following states?",
    "a": " A. Jharkhand",
    "b": " B. Manipur",
    "c": " C. Puducherry",
    "d": " D. Bihar",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Indravati National Park is in _______.",
    "a": " A. Chhattisgarh",
    "b": " B. Telangana",
    "c": " C. Daman and Diu",
    "d": " D. Puducherry",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kanger Valley National Park is in _______.",
    "a": " A. Kerala",
    "b": " B. Andaman and Nicobar Islands",
    "c": " C. West Bengal",
    "d": " D. Chhattisgarh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Guru Ghasi Das (Sanjay) National Park is situated in which of the following states?",
    "a": " A. Tripura",
    "b": " B. Chhattisgarh",
    "c": " C. Telangana",
    "d": " D. Uttarakhand",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bhagwan Mahavir (Mollem) National Park is in _______.",
    "a": " A. Goa",
    "b": " B. Madhya Pradesh",
    "c": " C. Punjab",
    "d": " D. Uttar Pradesh",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Blackbuck National Park is situated?",
    "a": " A. Sikkim",
    "b": " B. Gujarat",
    "c": " C. Chhattisgarh",
    "d": " D. Puducherry",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Gir Forest National Park is in _______.",
    "a": " A. Chhattisgarh",
    "b": " B. Assam",
    "c": " C. Puducherry",
    "d": " D. Gujarat",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Marine National Park is situated in which of the following states?",
    "a": " A. Gulf of Kutch Gujarat",
    "b": " B. Dadra and Nagar Haveli",
    "c": " C. Assam",
    "d": " D. Arunachal Pradesh",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Vansda National Park is situated?",
    "a": " A. Andhra Pradesh",
    "b": " B. Lakshadweep",
    "c": " C. Uttarakhand",
    "d": " D. Gujarat",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kalesar National Park is in _______.",
    "a": " A. Haryana",
    "b": " B. Assam",
    "c": " C. Lakshadweep",
    "d": " D. Rajasthan",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Sultanpur National Park is situated in which of the following states?",
    "a": " A. Andhra Pradesh",
    "b": " B. Tamil Nadu",
    "c": " C. Jharkhand",
    "d": " D. Haryana",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Pin Valley National Park is situated in which of the following states?",
    "a": " A. Delhi",
    "b": " B. Himachal ",
    "c": " C. Jharkhand",
    "d": " D. Assam",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Great Himalayan National Park is in _______.",
    "a": " A. Himachal Pradesh",
    "b": " B. Chandigarh",
    "c": " C. Lakshadweep",
    "d": " D. Andhra Pradesh",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Inderkilla  National Park is situated?",
    "a": " A. Assam",
    "b": " B. Himachal Pradesh",
    "c": " C. Himachal ",
    "d": " D. Arunachal Pradesh",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Khirganga  National Park is in _______.",
    "a": " A. Madhya Pradesh",
    "b": " B. Tripura",
    "c": " C. Himachal ",
    "d": " D. Delhi",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Simbalbara  National Park is situated?",
    "a": " A. Karnataka",
    "b": " B. Tamil Nadu",
    "c": " C. Andhra Pradesh",
    "d": " D. Himachal Pradesh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Dachigam National Park is situated?",
    "a": " A. Jammu and Kashmir",
    "b": " B. Bihar",
    "c": " C. Karnataka",
    "d": " D. Meghalaya",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Hemis National Park is situated?",
    "a": " A. Maharashtra",
    "b": " B. Madhya Pradesh",
    "c": " C. Arunachal Pradesh",
    "d": " D. Jammu and Kashmir",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kishtwar National Park is in _______.",
    "a": " A. Uttarakhand",
    "b": " B. Punjab",
    "c": " C. Manipur",
    "d": " D. Jammu and Kashmir",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Salim Ali National Park is situated in which of the following states?",
    "a": " A. Kerala",
    "b": " B. Meghalaya",
    "c": " C. Jammu and Kashmir",
    "d": " D. Delhi",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Betla National Park is situated in which of the following states?",
    "a": " A. Karnataka",
    "b": " B. Tamil Nadu",
    "c": " C. Jharkhand",
    "d": " D. Uttar Pradesh",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bandipur National Park is situated in which of the following states?",
    "a": " A. Delhi",
    "b": " B. Punjab",
    "c": " C. Karnataka",
    "d": " D. Uttarakhand",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bannerghatta National Park is situated in which of the following states?",
    "a": " A. Jammu and Kashmir",
    "b": " B. Daman and Diu",
    "c": " C. Manipur",
    "d": " D. Karnataka",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kudremukh National Park is situated in which of the following states?",
    "a": " A. Sikkim",
    "b": " B. Punjab",
    "c": " C. Karnataka",
    "d": " D. Lakshadweep",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Nagarhole (Rajiv Gandhi) National Park is situated?",
    "a": " A. Chhattisgarh",
    "b": " B. Himachal Pradesh",
    "c": " C. Kerala",
    "d": " D. Karnataka",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Anshi national park is situated?",
    "a": " A. Karnataka",
    "b": " B. Sikkim",
    "c": " C. West Bengal",
    "d": " D. Uttarakhand",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Eravikulam National Park is in _______.",
    "a": " A. Tamil Nadu",
    "b": " B. Daman and Diu",
    "c": " C. Sikkim",
    "d": " D. Kerala",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mathikettan Shola National Park is in _______.",
    "a": " A. Kerala",
    "b": " B. Delhi",
    "c": " C. Haryana",
    "d": " D. Jharkhand",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Periyar National Park is situated?",
    "a": " A. Tamil Nadu",
    "b": " B. Daman and Diu",
    "c": " C. Telangana",
    "d": " D. Kerala",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Silent Valley National Park is situated in which of the following states?",
    "a": " A. Kerala",
    "b": " B. Goa",
    "c": " C. Haryana",
    "d": " D. Uttar Pradesh",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Anamudi Shola National Park is situated?",
    "a": " A. Arunachal Pradesh",
    "b": " B. Kerala",
    "c": " C. Puducherry",
    "d": " D. Chandigarh",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Pambadum Shola National Park is in _______.",
    "a": " A. Kerala",
    "b": " B. Tamil Nadu",
    "c": " C. Mizoram",
    "d": " D. Uttar Pradesh",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bandhavgarh National Park is situated in which of the following states?",
    "a": " A. Puducherry",
    "b": " B. Andhra Pradesh",
    "c": " C. Lakshadweep",
    "d": " D. Madhya Pradesh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Kanha National Park is situated in which of the following states?",
    "a": " A. Telangana",
    "b": " B. Lakshadweep",
    "c": " C. Puducherry",
    "d": " D. Madhya Pradesh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Madhav National Park is situated?",
    "a": " A. Delhi",
    "b": " B. Uttar Pradesh",
    "c": " C. Madhya Pradesh",
    "d": " D. West Bengal",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mandla Plant Fossils National Park is situated in which of the following states?",
    "a": " A. Odisha",
    "b": " B. Rajasthan",
    "c": " C. Uttarakhand",
    "d": " D. Madhya Pradesh",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Panna National Park is in _______.",
    "a": " A. Karnataka",
    "b": " B. Manipur",
    "c": " C. Madhya Pradesh",
    "d": " D. Goa",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Pench (Priyadarshini) National Park is situated?",
    "a": " A. Andaman and Nicobar Islands",
    "b": " B. Madhya Pradesh",
    "c": " C. Maharashtra",
    "d": " D. Sikkim",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Sanjay National Park is situated in which of the following states?",
    "a": " A. Madhya Pradesh",
    "b": " B. Gujarat",
    "c": " C. Bihar",
    "d": " D. Jharkhand",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Satpura National Park is situated in which of the following states?",
    "a": " A. Puducherry",
    "b": " B. Tamil Nadu",
    "c": " C. Madhya Pradesh",
    "d": " D. Odisha",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Van Vihar National Park is in _______.",
    "a": " A. Uttarakhand",
    "b": " B. Madhya Pradesh",
    "c": " C. Punjab",
    "d": " D. Arunachal Pradesh",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Chandoli National Park is in _______.",
    "a": " A. Jharkhand",
    "b": " B. Tripura",
    "c": " C. Maharashtra",
    "d": " D. Lakshadweep",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Gugamal National Park is situated?",
    "a": " A. Chandigarh",
    "b": " B. Daman and Diu",
    "c": " C. Andaman and Nicobar Islands",
    "d": " D. Maharashtra",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Navegaon National Park is in _______.",
    "a": " A. Maharashtra",
    "b": " B. Tripura",
    "c": " C. Gujarat",
    "d": " D. Delhi",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Sanjay Gandhi  (Borivilli) National Park is in _______.",
    "a": " A. Himachal Pradesh",
    "b": " B. Gujarat",
    "c": " C. Manipur",
    "d": " D. Maharashtra",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Tadoba National Park is situated in which of the following states?",
    "a": " A. Haryana",
    "b": " B. Maharashtra",
    "c": " C. Mizoram",
    "d": " D. Punjab",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Pench National Park is situated in which of the following states?",
    "a": " A. Maharashtra",
    "b": " B. Gujarat",
    "c": " C. Chhattisgarh",
    "d": " D. Dadra and Nagar Haveli",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Keibul Lamjao National Park is situated?",
    "a": " A. Chhattisgarh",
    "b": " B. Rajasthan",
    "c": " C. Manipur",
    "d": " D. Lakshadweep",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Balphakram National Park is situated in which of the following states?",
    "a": " A. Puducherry",
    "b": " B. Haryana",
    "c": " C. Rajasthan",
    "d": " D. Meghalaya",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Nokrek National Park is situated in which of the following states?",
    "a": " A. Meghalaya",
    "b": " B. Punjab",
    "c": " C. Daman and Diu",
    "d": " D. Puducherry",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Murlen National Park is in _______.",
    "a": " A. Mizoram",
    "b": " B. Jharkhand",
    "c": " C. Himachal Pradesh",
    "d": " D. Manipur",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Phawngpui Blue Mountain National Park is situated in which of the following states?",
    "a": " A. Madhya Pradesh",
    "b": " B. Uttarakhand",
    "c": " C. Manipur",
    "d": " D. Mizoram",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Intanki  National Park is in _______.",
    "a": " A. West Bengal",
    "b": " B. Maharashtra",
    "c": " C. Nagaland",
    "d": " D. Haryana",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bhitarkanika National Park is situated in which of the following states?",
    "a": " A. Daman and Diu",
    "b": " B. Kerala",
    "c": " C. Chandigarh",
    "d": " D. Odisha",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Simlipal National Park is situated in which of the following states?",
    "a": " A. Nagaland",
    "b": " B. Odisha",
    "c": " C. Punjab",
    "d": " D. Delhi",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Sariska National Park is situated?",
    "a": " A. Daman and Diu",
    "b": " B. Haryana",
    "c": " C. Rajasthan",
    "d": " D. Goa",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Ranthambore National Park is situated in which of the following states?",
    "a": " A. Delhi",
    "b": " B. Rajasthan",
    "c": " C. Tripura",
    "d": " D. Meghalaya",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mukundra Hills (Darrah) National Park is in _______.",
    "a": " A. West Bengal",
    "b": " B. Tamil Nadu",
    "c": " C. Haryana",
    "d": " D. Rajasthan",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Desert National Park is in _______.",
    "a": " A. Daman and Diu",
    "b": " B. Rajasthan",
    "c": " C. Nagaland",
    "d": " D. Uttar Pradesh",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Keoladeo Ghana National Park is situated in which of the following states?",
    "a": " A. Bihar",
    "b": " B. West Bengal",
    "c": " C. Delhi",
    "d": " D. Rajasthan",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Khangchendzonga National Park is situated?",
    "a": " A. Tamil Nadu",
    "b": " B. Karnataka",
    "c": " C. Arunachal Pradesh",
    "d": " D. Sikkim",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mudumalai National Park is situated in which of the following states?",
    "a": " A. Jharkhand",
    "b": " B. Kerala",
    "c": " C. Uttar Pradesh",
    "d": " D. Tamil Nadu",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Mukurthi National Park is situated?",
    "a": " A. Tripura",
    "b": " B. Madhya Pradesh",
    "c": " C. Bihar",
    "d": " D. Tamil Nadu",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Indira Gandhi (Annamalai) National Park is situated?",
    "a": " A. West Bengal",
    "b": " B. Gujarat",
    "c": " C. Chhattisgarh",
    "d": " D. Tamil Nadu",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Guindy National Park is situated in which of the following states?",
    "a": " A. Tripura",
    "b": " B. Nagaland",
    "c": " C. Mizoram",
    "d": " D. Tamil Nadu",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Gulf of Mannar Marine National Park is in _______.",
    "a": " A. Goa",
    "b": " B. Tamil Nadu",
    "c": " C. Andhra Pradesh",
    "d": " D. Bihar",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Bison( Rajbari )  National Park is situated in which of the following states?",
    "a": " A. Telangana",
    "b": " B. Bihar",
    "c": " C. Tripura",
    "d": " D. Karnataka",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Clouded Leopard  National Park is in _______.",
    "a": " A. Andaman and Nicobar Islands",
    "b": " B. Mizoram",
    "c": " C. Tripura",
    "d": " D. Odisha",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Dudhwa National Park is situated?",
    "a": " A. Punjab",
    "b": " B. Uttar Pradesh",
    "c": " C. Lakshadweep",
    "d": " D. Tripura",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Gangotri National Park is situated?",
    "a": " A. Rajasthan",
    "b": " B. Chhattisgarh",
    "c": " C. Delhi",
    "d": " D. Uttarakhand",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Govind Pashu Vihar is in _______.",
    "a": " A. Meghalaya",
    "b": " B. Uttarakhand",
    "c": " C. Lakshadweep",
    "d": " D. Jharkhand",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Jim Corbett National Park is situated?",
    "a": " A. Daman and Diu",
    "b": " B. Chandigarh",
    "c": " C. Sikkim",
    "d": " D. Uttarakhand",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Nanda Devi National Park is situated in which of the following states?",
    "a": " A. Manipur",
    "b": " B. Chandigarh",
    "c": " C. Uttarakhand",
    "d": " D. Goa",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Rajaji National Park is in _______.",
    "a": " A. Dadra and Nagar Haveli",
    "b": " B. Odisha",
    "c": " C. Daman and Diu",
    "d": " D. Uttarakhand",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Valley of Flowers National Park is in _______.",
    "a": " A. Delhi",
    "b": " B. Uttarakhand",
    "c": " C. Rajasthan",
    "d": " D. Jharkhand",
    "correct": "2",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Gorumara National Park is in _______.",
    "a": " A. Telangana",
    "b": " B. Daman and Diu",
    "c": " C. Karnataka",
    "d": " D. West Bengal",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Buxa National Park is in _______.",
    "a": " A. West Bengal",
    "b": " B. Puducherry",
    "c": " C. Kerala",
    "d": " D. Tamil Nadu",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Neora Valley National Park is situated?",
    "a": " A. West Bengal",
    "b": " B. Andhra Pradesh",
    "c": " C. Delhi",
    "d": " D. Andaman and Nicobar Islands",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Singalila National Park is situated?",
    "a": " A. Chhattisgarh",
    "b": " B. Uttarakhand",
    "c": " C. Jharkhand",
    "d": " D. West Bengal",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Jaldapara National Park is in _______.",
    "a": " A. Telangana",
    "b": " B. Rajasthan",
    "c": " C. Gujarat",
    "d": " D. West Bengal",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Sundarbans National Park is situated in which of the following states?",
    "a": " A. Uttarakhand",
    "b": " B. Gujarat",
    "c": " C. Meghalaya",
    "d": " D. West Bengal",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Mahatama Gandhi Marine (Wandoor) National Park is situated?",
    "a": " A. Andhra Pradesh",
    "b": " B. West Bengal",
    "c": " C. Andaman and Nicobar Islands",
    "d": " D. Uttarakhand",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Middle Button Island National Park is situated in which of the following states?",
    "a": " A. Punjab",
    "b": " B. Nagaland",
    "c": " C. Andaman and Nicobar Islands",
    "d": " D. Goa",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Mount Harriett National Park is in _______.",
    "a": " A. Punjab",
    "b": " B. Mizoram",
    "c": " C. Lakshadweep",
    "d": " D. Andaman and Nicobar Islands",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "North Button Island National Park is situated in which of the following states?",
    "a": " A. Punjab",
    "b": " B. Dadra and Nagar Haveli",
    "c": " C. Andaman and Nicobar Islands",
    "d": " D. Assam",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Rani Jhansi Marine National Park is in _______.",
    "a": " A. Nagaland",
    "b": " B. Jammu and Kashmir",
    "c": " C. Andaman and Nicobar Islands",
    "d": " D. Sikkim",
    "correct": "3",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Saddle Peak National Park is situated in which of the following states?",
    "a": " A. Andaman and Nicobar Islands",
    "b": " B. Sikkim",
    "c": " C. Karnataka",
    "d": " D. Puducherry",
    "correct": "1",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states South Button Island National Park is situated?",
    "a": " A. Rajasthan",
    "b": " B. Mizoram",
    "c": " C. Uttar Pradesh",
    "d": " D. Andaman and Nicobar Islands",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In which of the following states Campbell Bay National Park is situated?",
    "a": " A. Uttar Pradesh",
    "b": " B. Sikkim",
    "c": " C. Manipur",
    "d": " D. Andaman and Nicobar Islands",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Galathea Bay National Park is in _______.",
    "a": " A. Tripura",
    "b": " B. Gujarat",
    "c": " C. Karnataka",
    "d": " D. Andaman and Nicobar",
    "correct": "4",
    "img": "",
    "topic": "National Parks",
    "section": "(General Intelligence & Reasoning)"
  }
]}[{"qtext":"Papikonda National Park is in _______.","a":" A. Tripura","b":" B. Chandigarh","c":" C. Andaman and Nicobar Islands","d":" D. Andhra Pradesh","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Rajiv Gandhi National Park is in _______.","a":" A. Andhra Pradesh","b":" B. Karnataka","c":" C. Tripura","d":" D. Bihar","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Sri Venkateswara National Park is situated in which of the following states?","a":" A. Dadra and Nagar Haveli","b":" B. Nagaland","c":" C. Andhra Pradesh","d":" D. Tamil Nadu","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Kasu Brahmananda Reddy National Park is situated in which of the following states?","a":" A. Delhi","b":" B. Haryana","c":" C. Nagaland","d":" D. Telangana","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Mahavir Harina Vanasthali National Park is situated in which of the following states?","a":" A. Jharkhand","b":" B. Mizoram","c":" C. Delhi","d":" D. Telangana","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Mrugavani National Park is in _______.","a":" A. Mizoram","b":" B. Punjab","c":" C. Telangana","d":" D. Jammu and Kashmir","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Namdapha National Park is in _______.","a":" A. Himachal Pradesh","b":" B. Haryana","c":" C. Arunachal Pradesh","d":" D. Chhattisgarh","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Mouling National Park is situated in which of the following states?","a":" A. Tripura","b":" B. Arunachal ","c":" C. Sikkim","d":" D. Puducherry","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Dibru-Saikhowa National Park is in _______.","a":" A. Sikkim","b":" B. Daman and Diu","c":" C. Assam","d":" D. Uttar Pradesh","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Kaziranga National Park is in _______.","a":" A. Mizoram","b":" B. Tripura","c":" C. Haryana","d":" D. Assam","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Manas National Park is in _______.","a":" A. Sikkim","b":" B. Puducherry","c":" C. Arunachal Pradesh","d":" D. Assam","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Nameri National Park is situated in which of the following states?","a":" A. Puducherry","b":" B. Assam","c":" C. Gujarat","d":" D. Kerala","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Rajiv Gandhi Orang National Park is situated?","a":" A. Madhya Pradesh","b":" B. Daman and Diu","c":" C. Jammu and Kashmir","d":" D. Assam","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Valmiki National Park is situated in which of the following states?","a":" A. Jharkhand","b":" B. Manipur","c":" C. Puducherry","d":" D. Bihar","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Indravati National Park is in _______.","a":" A. Chhattisgarh","b":" B. Telangana","c":" C. Daman and Diu","d":" D. Puducherry","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Kanger Valley National Park is in _______.","a":" A. Kerala","b":" B. Andaman and Nicobar Islands","c":" C. West Bengal","d":" D. Chhattisgarh","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Guru Ghasi Das (Sanjay) National Park is situated in which of the following states?","a":" A. Tripura","b":" B. Chhattisgarh","c":" C. Telangana","d":" D. Uttarakhand","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Bhagwan Mahavir (Mollem) National Park is in _______.","a":" A. Goa","b":" B. Madhya Pradesh","c":" C. Punjab","d":" D. Uttar Pradesh","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Blackbuck National Park is situated?","a":" A. Sikkim","b":" B. Gujarat","c":" C. Chhattisgarh","d":" D. Puducherry","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Gir Forest National Park is in _______.","a":" A. Chhattisgarh","b":" B. Assam","c":" C. Puducherry","d":" D. Gujarat","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Marine National Park is situated in which of the following states?","a":" A. Gulf of Kutch Gujarat","b":" B. Dadra and Nagar Haveli","c":" C. Assam","d":" D. Arunachal Pradesh","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Vansda National Park is situated?","a":" A. Andhra Pradesh","b":" B. Lakshadweep","c":" C. Uttarakhand","d":" D. Gujarat","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Kalesar National Park is in _______.","a":" A. Haryana","b":" B. Assam","c":" C. Lakshadweep","d":" D. Rajasthan","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Sultanpur National Park is situated in which of the following states?","a":" A. Andhra Pradesh","b":" B. Tamil Nadu","c":" C. Jharkhand","d":" D. Haryana","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Pin Valley National Park is situated in which of the following states?","a":" A. Delhi","b":" B. Himachal ","c":" C. Jharkhand","d":" D. Assam","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Great Himalayan National Park is in _______.","a":" A. Himachal Pradesh","b":" B. Chandigarh","c":" C. Lakshadweep","d":" D. Andhra Pradesh","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Inderkilla  National Park is situated?","a":" A. Assam","b":" B. Himachal Pradesh","c":" C. Himachal ","d":" D. Arunachal Pradesh","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Khirganga  National Park is in _______.","a":" A. Madhya Pradesh","b":" B. Tripura","c":" C. Himachal ","d":" D. Delhi","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Simbalbara  National Park is situated?","a":" A. Karnataka","b":" B. Tamil Nadu","c":" C. Andhra Pradesh","d":" D. Himachal Pradesh","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Dachigam National Park is situated?","a":" A. Jammu and Kashmir","b":" B. Bihar","c":" C. Karnataka","d":" D. Meghalaya","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Hemis National Park is situated?","a":" A. Maharashtra","b":" B. Madhya Pradesh","c":" C. Arunachal Pradesh","d":" D. Jammu and Kashmir","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Kishtwar National Park is in _______.","a":" A. Uttarakhand","b":" B. Punjab","c":" C. Manipur","d":" D. Jammu and Kashmir","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Salim Ali National Park is situated in which of the following states?","a":" A. Kerala","b":" B. Meghalaya","c":" C. Jammu and Kashmir","d":" D. Delhi","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Betla National Park is situated in which of the following states?","a":" A. Karnataka","b":" B. Tamil Nadu","c":" C. Jharkhand","d":" D. Uttar Pradesh","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Bandipur National Park is situated in which of the following states?","a":" A. Delhi","b":" B. Punjab","c":" C. Karnataka","d":" D. Uttarakhand","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Bannerghatta National Park is situated in which of the following states?","a":" A. Jammu and Kashmir","b":" B. Daman and Diu","c":" C. Manipur","d":" D. Karnataka","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Kudremukh National Park is situated in which of the following states?","a":" A. Sikkim","b":" B. Punjab","c":" C. Karnataka","d":" D. Lakshadweep","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Nagarhole (Rajiv Gandhi) National Park is situated?","a":" A. Chhattisgarh","b":" B. Himachal Pradesh","c":" C. Kerala","d":" D. Karnataka","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Anshi national park is situated?","a":" A. Karnataka","b":" B. Sikkim","c":" C. West Bengal","d":" D. Uttarakhand","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Eravikulam National Park is in _______.","a":" A. Tamil Nadu","b":" B. Daman and Diu","c":" C. Sikkim","d":" D. Kerala","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Mathikettan Shola National Park is in _______.","a":" A. Kerala","b":" B. Delhi","c":" C. Haryana","d":" D. Jharkhand","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Periyar National Park is situated?","a":" A. Tamil Nadu","b":" B. Daman and Diu","c":" C. Telangana","d":" D. Kerala","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Silent Valley National Park is situated in which of the following states?","a":" A. Kerala","b":" B. Goa","c":" C. Haryana","d":" D. Uttar Pradesh","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Anamudi Shola National Park is situated?","a":" A. Arunachal Pradesh","b":" B. Kerala","c":" C. Puducherry","d":" D. Chandigarh","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Pambadum Shola National Park is in _______.","a":" A. Kerala","b":" B. Tamil Nadu","c":" C. Mizoram","d":" D. Uttar Pradesh","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Bandhavgarh National Park is situated in which of the following states?","a":" A. Puducherry","b":" B. Andhra Pradesh","c":" C. Lakshadweep","d":" D. Madhya Pradesh","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Kanha National Park is situated in which of the following states?","a":" A. Telangana","b":" B. Lakshadweep","c":" C. Puducherry","d":" D. Madhya Pradesh","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Madhav National Park is situated?","a":" A. Delhi","b":" B. Uttar Pradesh","c":" C. Madhya Pradesh","d":" D. West Bengal","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Mandla Plant Fossils National Park is situated in which of the following states?","a":" A. Odisha","b":" B. Rajasthan","c":" C. Uttarakhand","d":" D. Madhya Pradesh","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Panna National Park is in _______.","a":" A. Karnataka","b":" B. Manipur","c":" C. Madhya Pradesh","d":" D. Goa","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Pench (Priyadarshini) National Park is situated?","a":" A. Andaman and Nicobar Islands","b":" B. Madhya Pradesh","c":" C. Maharashtra","d":" D. Sikkim","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Sanjay National Park is situated in which of the following states?","a":" A. Madhya Pradesh","b":" B. Gujarat","c":" C. Bihar","d":" D. Jharkhand","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Satpura National Park is situated in which of the following states?","a":" A. Puducherry","b":" B. Tamil Nadu","c":" C. Madhya Pradesh","d":" D. Odisha","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Van Vihar National Park is in _______.","a":" A. Uttarakhand","b":" B. Madhya Pradesh","c":" C. Punjab","d":" D. Arunachal Pradesh","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Chandoli National Park is in _______.","a":" A. Jharkhand","b":" B. Tripura","c":" C. Maharashtra","d":" D. Lakshadweep","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Gugamal National Park is situated?","a":" A. Chandigarh","b":" B. Daman and Diu","c":" C. Andaman and Nicobar Islands","d":" D. Maharashtra","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Navegaon National Park is in _______.","a":" A. Maharashtra","b":" B. Tripura","c":" C. Gujarat","d":" D. Delhi","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Sanjay Gandhi  (Borivilli) National Park is in _______.","a":" A. Himachal Pradesh","b":" B. Gujarat","c":" C. Manipur","d":" D. Maharashtra","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Tadoba National Park is situated in which of the following states?","a":" A. Haryana","b":" B. Maharashtra","c":" C. Mizoram","d":" D. Punjab","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Pench National Park is situated in which of the following states?","a":" A. Maharashtra","b":" B. Gujarat","c":" C. Chhattisgarh","d":" D. Dadra and Nagar Haveli","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Keibul Lamjao National Park is situated?","a":" A. Chhattisgarh","b":" B. Rajasthan","c":" C. Manipur","d":" D. Lakshadweep","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Balphakram National Park is situated in which of the following states?","a":" A. Puducherry","b":" B. Haryana","c":" C. Rajasthan","d":" D. Meghalaya","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Nokrek National Park is situated in which of the following states?","a":" A. Meghalaya","b":" B. Punjab","c":" C. Daman and Diu","d":" D. Puducherry","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Murlen National Park is in _______.","a":" A. Mizoram","b":" B. Jharkhand","c":" C. Himachal Pradesh","d":" D. Manipur","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Phawngpui Blue Mountain National Park is situated in which of the following states?","a":" A. Madhya Pradesh","b":" B. Uttarakhand","c":" C. Manipur","d":" D. Mizoram","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Intanki  National Park is in _______.","a":" A. West Bengal","b":" B. Maharashtra","c":" C. Nagaland","d":" D. Haryana","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Bhitarkanika National Park is situated in which of the following states?","a":" A. Daman and Diu","b":" B. Kerala","c":" C. Chandigarh","d":" D. Odisha","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Simlipal National Park is situated in which of the following states?","a":" A. Nagaland","b":" B. Odisha","c":" C. Punjab","d":" D. Delhi","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Sariska National Park is situated?","a":" A. Daman and Diu","b":" B. Haryana","c":" C. Rajasthan","d":" D. Goa","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Ranthambore National Park is situated in which of the following states?","a":" A. Delhi","b":" B. Rajasthan","c":" C. Tripura","d":" D. Meghalaya","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Mukundra Hills (Darrah) National Park is in _______.","a":" A. West Bengal","b":" B. Tamil Nadu","c":" C. Haryana","d":" D. Rajasthan","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Desert National Park is in _______.","a":" A. Daman and Diu","b":" B. Rajasthan","c":" C. Nagaland","d":" D. Uttar Pradesh","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Keoladeo Ghana National Park is situated in which of the following states?","a":" A. Bihar","b":" B. West Bengal","c":" C. Delhi","d":" D. Rajasthan","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Khangchendzonga National Park is situated?","a":" A. Tamil Nadu","b":" B. Karnataka","c":" C. Arunachal Pradesh","d":" D. Sikkim","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Mudumalai National Park is situated in which of the following states?","a":" A. Jharkhand","b":" B. Kerala","c":" C. Uttar Pradesh","d":" D. Tamil Nadu","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Mukurthi National Park is situated?","a":" A. Tripura","b":" B. Madhya Pradesh","c":" C. Bihar","d":" D. Tamil Nadu","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Indira Gandhi (Annamalai) National Park is situated?","a":" A. West Bengal","b":" B. Gujarat","c":" C. Chhattisgarh","d":" D. Tamil Nadu","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Guindy National Park is situated in which of the following states?","a":" A. Tripura","b":" B. Nagaland","c":" C. Mizoram","d":" D. Tamil Nadu","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Gulf of Mannar Marine National Park is in _______.","a":" A. Goa","b":" B. Tamil Nadu","c":" C. Andhra Pradesh","d":" D. Bihar","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Bison( Rajbari )  National Park is situated in which of the following states?","a":" A. Telangana","b":" B. Bihar","c":" C. Tripura","d":" D. Karnataka","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Clouded Leopard  National Park is in _______.","a":" A. Andaman and Nicobar Islands","b":" B. Mizoram","c":" C. Tripura","d":" D. Odisha","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Dudhwa National Park is situated?","a":" A. Punjab","b":" B. Uttar Pradesh","c":" C. Lakshadweep","d":" D. Tripura","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Gangotri National Park is situated?","a":" A. Rajasthan","b":" B. Chhattisgarh","c":" C. Delhi","d":" D. Uttarakhand","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Govind Pashu Vihar is in _______.","a":" A. Meghalaya","b":" B. Uttarakhand","c":" C. Lakshadweep","d":" D. Jharkhand","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Jim Corbett National Park is situated?","a":" A. Daman and Diu","b":" B. Chandigarh","c":" C. Sikkim","d":" D. Uttarakhand","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Nanda Devi National Park is situated in which of the following states?","a":" A. Manipur","b":" B. Chandigarh","c":" C. Uttarakhand","d":" D. Goa","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Rajaji National Park is in _______.","a":" A. Dadra and Nagar Haveli","b":" B. Odisha","c":" C. Daman and Diu","d":" D. Uttarakhand","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Valley of Flowers National Park is in _______.","a":" A. Delhi","b":" B. Uttarakhand","c":" C. Rajasthan","d":" D. Jharkhand","correct":"2","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Gorumara National Park is in _______.","a":" A. Telangana","b":" B. Daman and Diu","c":" C. Karnataka","d":" D. West Bengal","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Buxa National Park is in _______.","a":" A. West Bengal","b":" B. Puducherry","c":" C. Kerala","d":" D. Tamil Nadu","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Neora Valley National Park is situated?","a":" A. West Bengal","b":" B. Andhra Pradesh","c":" C. Delhi","d":" D. Andaman and Nicobar Islands","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Singalila National Park is situated?","a":" A. Chhattisgarh","b":" B. Uttarakhand","c":" C. Jharkhand","d":" D. West Bengal","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Jaldapara National Park is in _______.","a":" A. Telangana","b":" B. Rajasthan","c":" C. Gujarat","d":" D. West Bengal","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Sundarbans National Park is situated in which of the following states?","a":" A. Uttarakhand","b":" B. Gujarat","c":" C. Meghalaya","d":" D. West Bengal","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Mahatama Gandhi Marine (Wandoor) National Park is situated?","a":" A. Andhra Pradesh","b":" B. West Bengal","c":" C. Andaman and Nicobar Islands","d":" D. Uttarakhand","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Middle Button Island National Park is situated in which of the following states?","a":" A. Punjab","b":" B. Nagaland","c":" C. Andaman and Nicobar Islands","d":" D. Goa","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Mount Harriett National Park is in _______.","a":" A. Punjab","b":" B. Mizoram","c":" C. Lakshadweep","d":" D. Andaman and Nicobar Islands","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"North Button Island National Park is situated in which of the following states?","a":" A. Punjab","b":" B. Dadra and Nagar Haveli","c":" C. Andaman and Nicobar Islands","d":" D. Assam","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Rani Jhansi Marine National Park is in _______.","a":" A. Nagaland","b":" B. Jammu and Kashmir","c":" C. Andaman and Nicobar Islands","d":" D. Sikkim","correct":"3","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Saddle Peak National Park is situated in which of the following states?","a":" A. Andaman and Nicobar Islands","b":" B. Sikkim","c":" C. Karnataka","d":" D. Puducherry","correct":"1","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states South Button Island National Park is situated?","a":" A. Rajasthan","b":" B. Mizoram","c":" C. Uttar Pradesh","d":" D. Andaman and Nicobar Islands","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"In which of the following states Campbell Bay National Park is situated?","a":" A. Uttar Pradesh","b":" B. Sikkim","c":" C. Manipur","d":" D. Andaman and Nicobar Islands","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"},{"qtext":"Galathea Bay National Park is in _______.","a":" A. Tripura","b":" B. Gujarat","c":" C. Karnataka","d":" D. Andaman and Nicobar","correct":"4","img":"","topic":"National Parks","section":"(General Intelligence & Reasoning)"}]
