{
  "data":[
    {
        "qtext": "  National game of Canada is:",
        "a": "(1) Ice Hockey ",
        "b": "(2) Rugby ",
        "c": "(3) Baseball ",
        "d": "(4) Bull fighting",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Which taste belongs to Rahul Dravid :",
        "a": "(1) Mr. Reliable ",
        "b": "(2) The Wall ",
        "c": "(3) Jammy ",
        "d": "(4) All of these",
        "correct": "4",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Roger Federer is belongs to which country:",
        "a": "(1) Spain ",
        "b": "(2) England ",
        "c": "(3) Switzerland ",
        "d": "(4) Sweden",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Which is not included in Grand Slam?",
        "a": "(1) Wimbeldon ",
        "b": "(2) French Open ",
        "c": "(3) US Open ",
        "d": "(4) Italian Open",
        "correct": "4",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Bishop Term is associated with:",
        "a": "(1) Wimbeldon ",
        "b": "(2) French Open ",
        "c": "(3) Chess ",
        "d": "(4) Italian",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Ashes term is associated with:",
        "a": "(1) Wimbeldon ",
        "b": "(2) Chess ",
        "c": "(3) Cricket ",
        "d": "(4) French Open",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Polo started in India in which state?",
        "a": "(1) Rajasthan ",
        "b": "(2) Manipur ",
        "c": "(3) Maharashtra ",
        "d": "(4) Kerela",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Who is Known as the Magician of Hockey:",
        "a": "(1) Balbeer Singh ",
        "b": "(2) Sayeed Ahmed ",
        "c": "(3) Harpreet Singh ",
        "d": "(4) Major Dhyanchand",
        "correct": "4",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Skating is played in",
        "a": "(1) Ring ",
        "b": "(2) Rellodrum ",
        "c": "(3) Arena ",
        "d": "(4) Rink",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  How many square on a Chase board:",
        "a": "(1) 32 ",
        "b": "(2) 48 ",
        "c": "(3) 54 ",
        "d": "(4) 64",
        "correct": "4",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Green Park stadium is situated in:",
        "a": "(1) Lucknow ",
        "b": "(2) Kanpur ",
        "c": "(3) Mumbai ",
        "d": "(4) Delhi",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Firozshah Kotla stadium is at:",
        "a": "(1) Lucknow ",
        "b": "(2) Delhi ",
        "c": "(3) Mumbai ",
        "d": "(4) Jaipur",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  How many players are in Volleyball, Baseball, Baketball respectively:",
        "a": "(1) 6, 9, 5 ",
        "b": "(2) 9, 5, 6 ",
        "c": "(3) 5, 9, 6 ",
        "d": "(4) 7, 4, 3",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Which Cricketer is known as Hollywood?",
        "a": "(1) Jacque Kallis ",
        "b": "(2) Moh. Sami ",
        "c": "(3) Shane Warne ",
        "d": "(4) Sachin Tendulkar",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Maria Sherapora belonge to which country?",
        "a": "(1) Spain ",
        "b": "(2) Belgin ",
        "c": "(3) Russia ",
        "d": "(4) USA",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Length of the Marathon?",
        "a": "(1) 40.195 Km ",
        "b": "(2) 41.195 Km ",
        "c": "(3) 42.195 Km ",
        "d": "(4) 43.195 Km",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Wankhade stadium is situated at:",
        "a": "(1) Banglore ",
        "b": "(2) Chennai ",
        "c": "(3) Mumbai ",
        "d": "(4) Delhi",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Sawai Man Singh stadium is at :",
        "a": "(1) Banglore ",
        "b": "(2) Jaipur ",
        "c": "(3) Mumbai ",
        "d": "(4) Delhi",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  National game of Scotland?",
        "a": "(1) Ice Hockey ",
        "b": "(2) Rugby ",
        "c": "(3) Baseball ",
        "d": "(4) Bull fighting",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Ryder Cup is associated with?",
        "a": "(1) Polo ",
        "b": "(2) Golf ",
        "c": "(3) L.T. ",
        "d": "(4) T.T.",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Clay, Court and Hard Court is associated with :",
        "a": "(1) Polo ",
        "b": "(2) L.T.(Long Tennis)",
        "c": "(3) Goy ",
        "d": "(4) T.T.",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Double Fault word is associated with:",
        "a": "(1) Cricket ",
        "b": "(2) Football ",
        "c": "(3) Hockey ",
        "d": "(4) Tennis",
        "correct": "4",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Googly is associated with:",
        "a": "(1) Hockey ",
        "b": "(2) Football ",
        "c": "(3) Cricket ",
        "d": "(4) Tennis",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Which sport doesnt use the word Hattrick:",
        "a": "(1) Cricket ",
        "b": "(2) Football ",
        "c": "(3) Hockey ",
        "d": "(4) L.T.",
        "correct": "4",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  National game of USA:",
        "a": "(1) Ice Hockey ",
        "b": "(2) Rugby ",
        "c": "(3) Baseball ",
        "d": "(4) Bull fighting",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Pot, Canon & Que are related to which Sports?",
        "a": "(1) Snooker ",
        "b": "(2) Billiards ",
        "c": "(3) Golf ",
        "d": "(4) Bridge",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Third Eye is related with which sport?",
        "a": "(1) Cricket ",
        "b": "(2) Archery ",
        "c": "(3) Billiards ",
        "d": "(4) Hockey",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  “My Best Game of Chess” book belongs to which chess Player?",
        "a": "(1) Vishwanath Anand ",
        "b": "(2) Garry Casparov",
        "c": "(3) Anatoli Capov ",
        "d": "(4) Bobby Fisher",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Who has written Cricket My Style?",
        "a": "(1) Kapildev ",
        "b": "(2) Sunil Gawaskar ",
        "c": "(3) Sandeep Patil ",
        "d": "(4) Vivian Richards",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  The amount awarded in Arjuna Award?",
        "a": "(1) Rs. 75000 ",
        "b": "(2) Rs. 150000 ",
        "c": "(3) Rs. 250000 ",
        "d": "(4) Rs. 300000",
        "correct": "4",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  In which year first National Games held?",
        "a": "(1) 1925 ",
        "b": "(2) 1930 ",
        "c": "(3) 1935 ",
        "d": "(4) 1940",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  With Which game Ian Thorpe associated?",
        "a": "(1) Badminton ",
        "b": "(2) Chess ",
        "c": "(3) Swimming ",
        "d": "(4) Squash",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Boxer Mohhammad Alis daughter Laila Ali is associated with which game :",
        "a": "(1) Chess ",
        "b": "(2) Swimming ",
        "c": "(3) Boxing ",
        "d": "(4) Tennis",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  T, Put & Keddy are related to which sport?",
        "a": "(1) Golf ",
        "b": "(2) Polo ",
        "c": "(3) Bridge ",
        "d": "(4) Squash",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  In which sport word Silly point",
        "a": "(1) Cricket ",
        "b": "(2) Hockey ",
        "c": "(3) Football ",
        "d": "(4) Volleyball",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Who is the writer of Bradman Best?",
        "a": "(1) Rolland Perry ",
        "b": "(2) Don Bradman ",
        "c": "(3) J.K. Rowhing ",
        "d": "(4) Tony Greg",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Whos famous books is White Lightning?",
        "a": "(1) Brett Lee ",
        "b": "(2) Allen Donald ",
        "c": "(3) Glen Mcgrath ",
        "d": "(4)Damian Fleming",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  The award given for best coaching in sports is :",
        "a": "(1) Arjuna Award ",
        "b": "(2) Eklavya Award",
        "c": "(3) Dronacharya Award ",
        "d": "(4) C.K. Naidu Award",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  What does Rings on Olympic Flag Signifies?",
        "a": "(1) 5 Continents ",
        "b": "(2) 5 Oceans ",
        "c": "(3) 5 Countries ",
        "d": "(4) 5 Sports",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  With which game David Beckham is associated?",
        "a": "(1) Cricket ",
        "b": "(2) Hockey ",
        "c": "(3) Football ",
        "d": "(4) Tennis",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  With which game Michael Jordan is associated?",
        "a": "(1) Baseball ",
        "b": "(2) Volleyball ",
        "c": "(3) Handball ",
        "d": "(4) Basketball",
        "correct": "4",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Breast stroke is related to which sport?",
        "a": "(1) Basketball ",
        "b": "(2) Tennis ",
        "c": "(3) Swimming ",
        "d": "(4) Volleyball",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Goal is the autobiography of which Indian Hockey Player?",
        "a": "(1) Major Dhyanchand ",
        "b": "(2) Roop Singh",
        "c": "(3) K.D. Singh ",
        "d": "(4) Ram Jaypal Singh",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Who is the writer of Idols?",
        "a": "(1) Kapildev ",
        "b": "(2) Sunil Gawaskar",
        "c": "(3) Ajeet Wadekar ",
        "d": "(4) Farooq Engineer",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Who has written My life beautiful game?",
        "a": "(1) Vishwanath Anand ",
        "b": "(2) Michal Platini",
        "c": "(3) Jinedin Jidane ",
        "d": "(4) A.D. Nausimento (Pele)",
        "correct": "4",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  The amount given under the Dronacharya Award is :",
        "a": "(1) Rs. 75000 ",
        "b": "(2) Rs. 150000 ",
        "c": "(3) Rs. 300000 ",
        "d": "(4) Rs. 500000",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  What is the Idol statement of Olympic games in Latin Language?",
        "a": "(1) Citius, Altius, Fortius ",
        "b": "(2) Faster, Higher, Stronger",
        "c": "(3) Ever Onward ",
        "d": "(4) Forever Higher",
        "correct": "1",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  With which game Anju B. George associated?",
        "a": "(1) High Jump ",
        "b": "(2) Long Jump ",
        "c": "(3) Shortput ",
        "d": "(4) Kabbaddi",
        "correct": "2",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  Pankaj Advani is associated with which game.",
        "a": "(1) Golf ",
        "b": "(2) Snooker ",
        "c": "(3) Billiards ",
        "d": "(4) Bridge",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
        "qtext": "  First individual (Indian) Olympic Gold Medal won by",
        "a": "(1) Major Rajyaverdan Singh ",
        "b": "(2) Sushil Kumar",
        "c": "(3) Abhinav Bindra ",
        "d": "(4) Vijendra Kumar",
        "correct": "3",
        "img": "",
        "topic": "Sports",
        "section": "(General Awareness)"
    },
    {
    "qtext": "<p>Former Australian captain Mark Taylor has had several nicknames over his playing career. Which of the following was NOT one of them?</p>",
    "a": "A. Tubby",
    "b": "B. Stodge",
    "c": "C. Helium Bat",
    "d": "D. Stumpy",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which was the 1st non Test playing country to beat India in an international match?</p>",
    "a": "A. Canada",
    "b": "B. Sri Lanka",
    "c": "C. Zimbabwe",
    "d": "D. East Africa",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Track and field star Carl Lewis won how many gold medals at the 1984 Olympic games?</p>",
    "a": "A. Two",
    "b": "B. Three",
    "c": "C. Four",
    "d": "D. Eight",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which county did Ravi Shastri play for?</p>",
    "a": "A. Glamorgan",
    "b": "B. Leicestershire",
    "c": "C. Gloucestershire",
    "d": "D. Lancashire",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was the first Indian to win the World Amateur Billiards title?</p>",
    "a": "A. Geet Sethi",
    "b": "B. Wilson Jones",
    "c": "C. Michael Ferreira",
    "d": "D. Manoj Kothari",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is the first Indian woman to win an Asian Games gold in 400m run?</p>",
    "a": "A. M.L.Valsamma",
    "b": "B. P.T.Usha",
    "c": "C. Kamaljit Sandhu",
    "d": "D. K.Malleshwari",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which two counties did Kapil Dev play?</p>",
    "a": "A. Northamptonshire & Worcestershire",
    "b": "B. Northamptonshire & Warwickshire",
    "c": "C. Nottinghamshire & Worcestershire",
    "d": "D. Nottinghamshire & Warwickshire",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>When was Amateur Athletics Federation of India established?</p>",
    "a": "A. 1936",
    "b": "B. 1946",
    "c": "C. 1956",
    "d": "D. 1966",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who did Stone Cold Steve Austin wrestle at the 1998 edition of \"Over the Edge\"?</p>",
    "a": "A. Cactus Jack",
    "b": "B. Mankind",
    "c": "C. Dude Love",
    "d": "D. Mick Foley",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ricky Ponting is also known as what?</p>",
    "a": "A. The Rickster",
    "b": "B. Ponts",
    "c": "C. Ponter",
    "d": "D. Punter",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How long are professional Golf Tour players allotted per shot?</p>",
    "a": "A. 45 seconds",
    "b": "B. 25 seconds",
    "c": "C. 1 minute",
    "d": "D. 2 minutes",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which NBA player scored 8 points in the final 7 seconds of a game to lead his team to victory?</p>",
    "a": "A. Baron Davis",
    "b": "B. Kevin Garnett",
    "c": "C. Stephon Maurbury",
    "d": "D. Reggie Miller",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>In the match between India and Pakistan at Jaipur on 02-10-1983, Which new rule was introduced?</p>",
    "a": "A. Limit of overs was reduced to 50 overs",
    "b": "B. The rule of field restriction was taken.",
    "c": "C. Over throw runs were batsman's score",
    "d": "D. No-balls & wides were debited to bowlers analysis",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The first hang gliders to be flown were flown in...?</p>",
    "a": "A. 1600s",
    "b": "B. 1700s",
    "c": "C. 1800s",
    "d": "D. 1900s",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which two counties did Anil Kumble play for?</p>",
    "a": "A. Nottinghamshire & Lancashire",
    "b": "B. Nottinghamshire & Leicestershire",
    "c": "C. Northamptonshire & Leicestershire",
    "d": "D. Northamptonshire & Lancashire",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The nickname of Glenn McGrath is what?</p>",
    "a": "A. Ooh Ahh",
    "b": "B. Penguin",
    "c": "C. Big Bird",
    "d": "D. Pigeon",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Mark Waugh is commonly called what?</p>",
    "a": "A. Afganistan",
    "b": "B. Junior",
    "c": "C. Tugga",
    "d": "D. Julio",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>India won its first Olympic hockey gold in...?</p>",
    "a": "A. 1928",
    "b": "B. 1932",
    "c": "C. 1936",
    "d": "D. 1948",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many times did Geet Sethi win the lBSF World Billiards title?</p>",
    "a": "A. 2",
    "b": "B. 3",
    "c": "C. 4",
    "d": "D. 5",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>In which year did Milkha Singh win the first National title in the 400 m race?</p>",
    "a": "A. 1955",
    "b": "B. 1956",
    "c": "C. 1957",
    "d": "D. 1970",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who won the 1993 \"King of the Ring\"?</p>",
    "a": "A. Owen Hart",
    "b": "B. Bret Hart",
    "c": "C. Edge",
    "d": "D. Mabel",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What NHL goaltender has the most career wins?</p>",
    "a": "A. Grant Fuhr",
    "b": "B. Patrick Roy",
    "c": "C. Chris Osgood",
    "d": "D. Mike Vernon",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What Major League Baseball player holds the record for all-time career high batting average?</p>",
    "a": "A. Ty Cobb",
    "b": "B. Larry Walker",
    "c": "C. Jeff Bagwell",
    "d": "D. Frank Thomas",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who among the following is NOT associated with billiards in India?</p>",
    "a": "A. Subash Agrawal",
    "b": "B. Ashok Shandilya",
    "c": "C. Manoj Kothari",
    "d": "D. Mihir Sen",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which player has scored the most runs in a single Test innings?</p>",
    "a": "A. Graham Gooch",
    "b": "B. Matthew Hayden",
    "c": "C. Brian Lara",
    "d": "D. Agarkar",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was the 1st ODI captain for India?</p>",
    "a": "A. Ajit Wadekar",
    "b": "B. Bishen Singh Bedi",
    "c": "C. Nawab Pataudi",
    "d": "D. Vinoo Mankad",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Where did India play its 1st one day international match?</p>",
    "a": "A. Lords",
    "b": "B. Headingley",
    "c": "C. Taunton",
    "d": "D. The Oval",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>India reached the final of the Davis Cup for the first time in...?</p>",
    "a": "A. 1964",
    "b": "B. 1966",
    "c": "C. 1970",
    "d": "D. 1974",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The Asian Games were held in Delhi for the first time in...?</p>",
    "a": "A. 1951",
    "b": "B. 1963",
    "c": "C. 1971",
    "d": "D. 1982",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What Australian player was known as 'Fruitfly' amongst the rest of the team?</p>",
    "a": "A. Geoff Lawson",
    "b": "B. Merv Hughes",
    "c": "C. Mike Veletta",
    "d": "D. Mike Whitney",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which county did Mohammad Azharuddin play for?</p>",
    "a": "A. Yorkshire",
    "b": "B. Hampshire",
    "c": "C. Lancashire",
    "d": "D. Derbyshire",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The first hand glider was designed by...?</p>",
    "a": "A. Leonardo DaVinci",
    "b": "B. The Wright brothers",
    "c": "C. Francis Rogallo",
    "d": "D. Galileo",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which county did Sunil Gavaskar play for?</p>",
    "a": "A. Somerset",
    "b": "B. Worcestershire",
    "c": "C. Warwickshire",
    "d": "D. Glamorgan",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The 'Dronacharya Award' is given to...?</p>",
    "a": "A. Sportsmen",
    "b": "B. Coaches",
    "c": "C. Umpires",
    "d": "D. Sports Editors",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>In which Indian state did the game of Polo originate?</p>",
    "a": "A. Meghalaya",
    "b": "B. Rajasthan",
    "c": "C. Manipur",
    "d": "D. West Bengal",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What do African-American football players Ernie Davis, Archie Griffin, and Tony Dorsett have in common?</p>",
    "a": "A. They all played for Pittsburgh",
    "b": "B. They all won the Heisman Trophy",
    "c": "C. They all led to Super Bowl titles",
    "d": "D. They dont have any similarity",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which cricketer died on the field in Bangladesh while playing for Abahani Club?</p>",
    "a": "A. Subhash Gupte",
    "b": "B. M.L.Jaisimha",
    "c": "C. Lala Amarnath",
    "d": "D. Raman Lamba",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following is a Manipuri version of Hockey?</p>",
    "a": "A. Khong Kangjei",
    "b": "B. Hiyang Tanaba",
    "c": "C. Yubi Lakpi",
    "d": "D. None of above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which county did Javagal Srinath sign for in 2003?</p>",
    "a": "A. Surrey",
    "b": "B. Durham",
    "c": "C. Sussex",
    "d": "D. Essex",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which county did Sachin Tendulkar play for?</p>",
    "a": "A. Nottinghamshire",
    "b": "B. Yorkshire",
    "c": "C. Lancashire",
    "d": "D. Leicestershire",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who did Shawn Michaels beat to win his first Intercontinental Title?</p>",
    "a": "A. Bret Hart",
    "b": "B. Marty Jannetty",
    "c": "C. British Bulldog",
    "d": "D. Tito Santana",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Where did the 1st ODI match was played in India?</p>",
    "a": "A. New Delhi",
    "b": "B. Ahmedabad",
    "c": "C. Kolkata",
    "d": "D. Mumbai",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who had a torrid time with Lancashire in 2000?</p>",
    "a": "A. Sachin Tendulkar",
    "b": "B. Nayan Mongia",
    "c": "C. Javagal Srinath",
    "d": "D. Saurav Ganguly",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the name of the person that controls a football match?</p>",
    "a": "A. A referee",
    "b": "B. An umpire",
    "c": "C. A spectator",
    "d": "D. A goalkeeper",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Former Australian captain Allan Border was sometimes known as \"Captain Grumpy\". What was his other nickname?</p>",
    "a": "A. Abe",
    "b": "B. Captain Junior",
    "c": "C. AB",
    "d": "D. Groucho",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The Indian football team made its first appearance at Olympics in...?</p>",
    "a": "A. 1936",
    "b": "B. 1948",
    "c": "C. 1952",
    "d": "D. 1956",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was the first captain of Indian Test team?</p>",
    "a": "A. Vijay Hazare",
    "b": "B. C K Nayudu",
    "c": "C. Lala Amarnath",
    "d": "D. Vijay Merchant",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Fenway Park is the home field of what Major League Baseball team?</p>",
    "a": "A. New York Yankees",
    "b": "B. Chicago White Sox",
    "c": "C. Montreal Expos",
    "d": "D. Boston Red Sox",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Pravin Amre and Vinod Kambli played for which province in South Africa?</p>",
    "a": "A. Border",
    "b": "B. Boland",
    "c": "C. Griqualand West",
    "d": "D. Gauteng",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which football hero was nicknamed \"The Sundance Kid\"?</p>",
    "a": "A. Jim Kiick",
    "b": "B. Troy Aikman",
    "c": "C. Brett Favre",
    "d": "D. Joe Montana",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which country won the Cricket World Cup in 1999?</p>",
    "a": "A. Australia",
    "b": "B. South Africa",
    "c": "C. Pakistan",
    "d": "D. England",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who did The Rock beat to win his first WWE Title?</p>",
    "a": "A. Triple H",
    "b": "B. Stone Cold Steve Austin",
    "c": "C. Mankind",
    "d": "D. Bret Hart",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The name Kunjarani Devi is associated with...?</p>",
    "a": "A. Weight Lifting",
    "b": "B. Target shooting",
    "c": "C. Athletics",
    "d": "D. Swimming",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>In what year was the first international cricket match held?</p>",
    "a": "A. 1892 between England and India",
    "b": "B. 1869 between England and Australia",
    "c": "C. 1883 between Australia and Wales",
    "d": "D. 1844 between Canada and the USA",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many gold medals have been won by India in the Olympics so far?</p>",
    "a": "A. 4",
    "b": "B. 8",
    "c": "C. 9",
    "d": "D. 10",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who did The Rock wrestle in the main event at the 1999 edition of \"Wrestlemania\"?</p>",
    "a": "A. Stone Cold Steve Austin",
    "b": "B. Triple H",
    "c": "C. Mankind",
    "d": "D. Undertaker",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which English county did batting sensation Virender Sehwag join in the 2003 season?</p>",
    "a": "A. Lancashire",
    "b": "B. Leicestershire",
    "c": "C. Yorkshire",
    "d": "D. Middlesex",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who has scored the most Test hundreds ever?</p>",
    "a": "A. Steve Waugh",
    "b": "B. Sachin Tendulkar",
    "c": "C. Shane Warne",
    "d": "D. Sunil Gavaskar",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>When was the first cricket Test match played?</p>",
    "a": "A. 1873",
    "b": "B. 1877",
    "c": "C. 1870",
    "d": "D. 1788",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which track and field star overcame childhood polio to become one of the greatest athletes of her time?</p>",
    "a": "A. Wilma Rudolph",
    "b": "B. Gail Devers",
    "c": "C. Florence Griffith Joyner",
    "d": "D. Jackie Robinson",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who beat Duke in the Great Alaskan Shootout Finals in 1998?</p>",
    "a": "A. Syracuse",
    "b": "B. University of Cincinnati",
    "c": "C. Notre Dame",
    "d": "D. UCLA",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>'Dizzy' is the nickname of what Australian player?</p>",
    "a": "A. Adam Gilchrist",
    "b": "B. Jason Gillespie",
    "c": "C. Glenn McGrath",
    "d": "D. Brett Lee",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who is the highest wicket taker in Test cricket?</p>",
    "a": "A. Shane Warne",
    "b": "B. Brian Lara",
    "c": "C. Courtney Walsh",
    "d": "D. Muttiah Muralitharan",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which country, which made its debut in the Norwich Union League in 2003, signed Rahul Dravid as their overseas player?</p>",
    "a": "A. Holland",
    "b": "B. Ireland",
    "c": "C. Wales",
    "d": "D. Scotland",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which county signed Yuvraj Singh to play for them in 2003?</p>",
    "a": "A. Nottinghamshire",
    "b": "B. Lancashire",
    "c": "C. Hampshire",
    "d": "D. Yorkshire",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which county did the outspoken Spin great Bishen Singh Bedi play for?</p>",
    "a": "A. Essex",
    "b": "B. Surrey",
    "c": "C. Northamptonshire",
    "d": "D. Sussex",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was the first Indian to win an individual medal in Olympics?</p>",
    "a": "A. Milkha Singh",
    "b": "B. P.T.Usha",
    "c": "C. Karnam Malleshwari",
    "d": "D. K.D.Jadhav",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which county did speedster Javagal Srinath play for in 1995?</p>",
    "a": "A. Kent",
    "b": "B. Glamorgan",
    "c": "C. Gloucestershire",
    "d": "D. Leicestershire",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Stripped of his heavyweight title in 1967 for refusing induction into the U.S. military, Muhammad Ali regained the heavyweight championship on October 30, 1974, in Kinshasa, Zaire with an eighth-round knockout of which prizefighter?</p>",
    "a": "A. George Foreman",
    "b": "B. Joe Frazier",
    "c": "C. Leon Spinks",
    "d": "D. Sputnik",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Undertaker wrestled Yokozuna at the 1994 \"Royal Rumble\". This was a Casket Match. Undertaker wrestled in another Casket Match at the 1998 \"Royal Rumble\". Who did he wrestle?</p>",
    "a": "A. Yokozuna",
    "b": "B. Shawn Michaels",
    "c": "C. Mabel",
    "d": "D. Triple H",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>With which sport is the 'Choudhury Trophy' associated?</p>",
    "a": "A. Golf",
    "b": "B. Circumnavigation of the earth by car",
    "c": "C. Formula One racing",
    "d": "D. Buggy-Jumping",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The nickname of wicketkeeping great Rod Marsh was what?</p>",
    "a": "A. Billabong",
    "b": "B. Swampy",
    "c": "C. Bacchus",
    "d": "D. Lagoon",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was the 1st president of BCCI ( Board of Control for Cricket in India )?</p>",
    "a": "A. R.E. Grant Govan",
    "b": "B. Dr. Maharajkumar Sir Vijaya Ananda",
    "c": "C. Sikandar Hyat Khan",
    "d": "D. Anthony S. D'Mello",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many gold medals did P.T.Usha win in the 1986 Seoul Asian Games?</p>",
    "a": "A. 1",
    "b": "B. 2",
    "c": "C. 3",
    "d": "D. 4",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who holds second and third place for most yards rushing in a single season in the NFL?</p>",
    "a": "A. Barry Sanders",
    "b": "B. Jim Brown",
    "c": "C. OJ Simpson",
    "d": "D. Dick Lane",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following countries won the final of the triangular cricket series held in durban in februarry 1997?</p>",
    "a": "A. India",
    "b": "B. New zealand",
    "c": "C. South africa",
    "d": "D. Zimbabwe",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who has scored the most runs in a single First-class innings?</p>",
    "a": "A. Hanif Mohammad",
    "b": "B. Brian Lara",
    "c": "C. Sir Donald Bradman",
    "d": "D. Sachin Tendulkar",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which batsman started his international cricketing career at the age of 16?</p>",
    "a": "A. Suresh Raina",
    "b": "B. Sachin Tendulkar",
    "c": "C. Piyush Chawla",
    "d": "D. Rahul Dravid",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many wickets did Yograj Singh take in his 1st ODI match?</p>",
    "a": "A. 1",
    "b": "B. 2",
    "c": "C. 4",
    "d": "D. 3",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who made his Test debut alongwith Salil Ankola in the same match?</p>",
    "a": "A. Rahul Dravid",
    "b": "B. Sachin Tendulkar",
    "c": "C. Kapil Dev",
    "d": "D. Mohinder Amarnath",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the middle name of Rahul Dravid?</p>",
    "a": "A. Naren",
    "b": "B. Sharad",
    "c": "C. Srivatsav",
    "d": "D. Shyam",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the middle name of Akash Chopra, a Delhi batsman?</p>",
    "a": "A. Mohanlal",
    "b": "B. Shyamlal",
    "c": "C. Amarnath",
    "d": "D. Chotaram",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Where did India play its 1st one day international cricket match?</p>",
    "a": "A. Lords",
    "b": "B. Headingley",
    "c": "C. Taunton",
    "d": "D. The Oval",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>When did Sachin Tendulkar make his Test debut?</p>",
    "a": "A. 1986",
    "b": "B. 1991",
    "c": "C. 1990",
    "d": "D. 1989",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was named India's Cricketer of the Century by Wisden?</p>",
    "a": "A. Anil Kumble",
    "b": "B. Sachin Tendulkar",
    "c": "C. Kapil Dev",
    "d": "D. Sunil Gavaskar",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What were the bowling figures for Irfan Pathan on his ODI debut?The answer is in this form : Overs - Maidens - Runs given - Wickets taken.</p>",
    "a": "A. 10 - 0 - 60 - 6",
    "b": "B. 10 - 0 - 61 - 0",
    "c": "C. 9 - 1 - 38 - 3",
    "d": "D. 5 - 2 - 13 - 4",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What was Sachin Tendulkar's average when he made his first thousand runs in ODIs?</p>",
    "a": "A. 35.83",
    "b": "B. 22.92",
    "c": "C. 43.87",
    "d": "D. 42.86",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Farokh Engineer played his last Test match at his home ground.Where did he play his last Test match?</p>",
    "a": "A. Delhi",
    "b": "B. Calcutta",
    "c": "C. Hyderabad",
    "d": "D. Mumbai",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Syed Kirmani made his ODI debut in 1976 against New Zealand as a wicketkeeper. How many runs did India make in that match?</p>",
    "a": "A. 254 all out",
    "b": "B. 222/9",
    "c": "C. 219/5",
    "d": "D. 154 all out",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many wickets Kapil Dev had taken in Test matches when he retired?</p>",
    "a": "A. 450",
    "b": "B. 430",
    "c": "C. 435",
    "d": "D. 434",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The highest first wicket partnership in Test Match Cricket was between two Indians: one is V.Mankad, who is the other?</p>",
    "a": "A. Subhash Gupte",
    "b": "B. Sunil Gavaskar",
    "c": "C. Pankaj Roy",
    "d": "D. Chetan Chauhan",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the middle name of Deep Dasgupta?</p>",
    "a": "A. Karan",
    "b": "B. Jogan",
    "c": "C. Chandar",
    "d": "D. Biplab",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was named Wisden Cricketer of the Year in 2000?</p>",
    "a": "A. Rahul Dravid",
    "b": "B. Sourav Ganguly",
    "c": "C. Sachin Tendulkar",
    "d": "D. Yuvraj Singh",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the middle name of the world class batsman Sachin Tendulkar?</p>",
    "a": "A. Rohan",
    "b": "B. Ramesh",
    "c": "C. Rahul",
    "d": "D. Ravi",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which Indian batsman made his ODI debut in the same match in which Kapil Dev did?</p>",
    "a": "A. Mohammad Azharuddin",
    "b": "B. Surinder Amarnath",
    "c": "C. Sachin Tendulkar",
    "d": "D. Navjot Sidhu",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Against which team did Rahul Dravid made his ODI debut?</p>",
    "a": "A. Kenya",
    "b": "B. Pakistan",
    "c": "C. Sri Lanka",
    "d": "D. Australia",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the middle name of the Ajith Agarkar, a top class all rounder?</p>",
    "a": "A. Karan",
    "b": "B. Bhalchandra",
    "c": "C. Dalmiya",
    "d": "D. Rohan",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Rahul Dravid also made Test debut along with Sourav Ganguly in the same match.He scored 95 runs. How many fours did he hit in that innings of 95 runs?</p>",
    "a": "A. 6",
    "b": "B. 10",
    "c": "C. 5",
    "d": "D. 7",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Javagal Srinath took no wicket in his last ODI match.What were his bowling figures in that match? [Format : Overs bowled - Maidens - Runs given - Wickets taken]</p>",
    "a": "A. 7 - 0 - 67 - 0",
    "b": "B. 10 - 0 - 87 - 0",
    "c": "C. 10 - 0 - 57 - 0",
    "d": "D. 7 - 0 - 39 - 0",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Where did Yuvraj Singh make his ODI debut?</p>",
    "a": "A. Nairobi, Kenya",
    "b": "B. Mumbai, India",
    "c": "C. London, England",
    "d": "D. Lahore, Pakistan",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many wickets did Zaheer Khan pick up in his ODI debut?</p>",
    "a": "A. 0",
    "b": "B. 3",
    "c": "C. 5",
    "d": "D. 2",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was named as the ICC Emerging Player of the Year 2004?</p>",
    "a": "A. Piyush Chawla",
    "b": "B. Gautam Gambhir",
    "c": "C. Irfan Pathan",
    "d": "D. Suresh Raina",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Vinod Kambli on his Test debut made 28 runs having a strike rate of :</p>",
    "a": "A. 63.58",
    "b": "B. 46.66",
    "c": "C. 12.55",
    "d": "D. 91.07",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which Indian batsman was the first to hit 44 fours in a test match innings?</p>",
    "a": "A. Tendulkar",
    "b": "B. Gavaskar",
    "c": "C. Ganguly",
    "d": "D. Laxman",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Against which team did Virender Sehwag make his one day international debut?</p>",
    "a": "A. New Zealand",
    "b": "B. Sri Lanka",
    "c": "C. Pakistan",
    "d": "D. South Africa",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was the first Indian woman to win a medal in the Olympics?</p>",
    "a": "A. P.T.Usha",
    "b": "B. Karnam Malleshwari",
    "c": "C. Kunjarani Devi",
    "d": "D. Bachendri Pal",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Madan Lal had played 67 ODIs with his highest being 53 not out.How many runs did he make in these 67 ODIs?</p>",
    "a": "A. 399",
    "b": "B. 405",
    "c": "C. 401",
    "d": "D. 411",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ajit Agarkar made his Test debut in 1998 as a bowler. How many wickets did he take in that match including both 1st and 2nd innings?</p>",
    "a": "A. 2",
    "b": "B. 1",
    "c": "C. 5",
    "d": "D. 3",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ajit Agarkar's first match was against Australia on April 1, 1998 at Kochi. Which Australian batsman was dismissed by Agarkar in that match?</p>",
    "a": "A. Ponting",
    "b": "B. Warne",
    "c": "C. Martyn",
    "d": "D. Gilchrist",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which team did Sachin Tendulkar play for in the Ranji Trophy when he made his debut in first class cricket?</p>",
    "a": "A. Karnataka",
    "b": "B. Delhi",
    "c": "C. Mumbai",
    "d": "D. Kerala",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What was Yashpal Sharma's best score in First Class Cricket?</p>",
    "a": "A. 201 not out",
    "b": "B. 200",
    "c": "C. 199",
    "d": "D. 153 not out",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many ODI matches had Farokh Engineer played throughout his career?</p>",
    "a": "A. 5",
    "b": "B. 10",
    "c": "C. 15",
    "d": "D. 9",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the middle name of V.V.S. Laxman?</p>",
    "a": "A. Vangipurapu Venkata Sai",
    "b": "B. Vishwanatha Venkata Sai",
    "c": "C. Vaidyanatha Venkata Sai",
    "d": "D. None of the above",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Where did Mahendra Singh Dhoni make his ODI debut?</p>",
    "a": "A. Chittagong",
    "b": "B. Dhaka",
    "c": "C. Hyderabad",
    "d": "D. Vishakapatnam",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the middle name of Bajji (Harbhajan Singh)?</p>",
    "a": "A. Plaba",
    "b": "B. Plaha",
    "c": "C. Kholi",
    "d": "D. Asrani",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Where did Yashpal Sharma play his last ODI match?</p>",
    "a": "A. Chandigarh",
    "b": "B. Indore",
    "c": "C. Delhi",
    "d": "D. Hyderabad",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many runs did VVS Laxman score in his ODI debut?</p>",
    "a": "A. 100",
    "b": "B. 1",
    "c": "C. 99",
    "d": "D. 0",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Sourav Ganguly made his Test debut in 1996.How many runs did he score in the 1st innings of that match?</p>",
    "a": "A. 132",
    "b": "B. 131",
    "c": "C. 32",
    "d": "D. 99",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was the first Indian batsman to hit a century on Test debut against England at England's home?</p>",
    "a": "A. Sachin Tendulkar",
    "b": "B. Abbas Ali Baig",
    "c": "C. Kapil Dev",
    "d": "D. Wassim Jaffer",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>In which year did Ajay Jadeja make his ODI debut?</p>",
    "a": "A. 1996",
    "b": "B. 1985",
    "c": "C. 1992",
    "d": "D. 1991",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many runs did Sachin Tendulkar was scored in his ODI debut?</p>",
    "a": "A. 140",
    "b": "B. 0",
    "c": "C. 23",
    "d": "D. 1",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following countries won the final of the triangular cricket series held in durban in februarry 1997 ?</p>",
    "a": "A. India",
    "b": "B. New zealand",
    "c": "C. South africa",
    "d": "D. Zimbabwe",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many centuries in Tests did Sunil Gavaskar bag when he retired?</p>",
    "a": "A. 23",
    "b": "B. 45",
    "c": "C. 34",
    "d": "D. 54",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many fours had Yograj Singh hit throughout his Test career?</p>",
    "a": "A. 10",
    "b": "B. 9",
    "c": "C. 4",
    "d": "D. 1",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What was the bowling figures (O-M-R-W ) of Anil Kumble in his ODI debut against Sri Lanka?</p>",
    "a": "A. 1.1-0-27-0",
    "b": "B. 10-7-10-5",
    "c": "C. 10-0-42-1",
    "d": "D. 8.2-2-33-2",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was named as the Wisden Cricketer of the Year 1980?</p>",
    "a": "A. Madan Lal",
    "b": "B. Bishen Singh Bedi",
    "c": "C. Sunil Gavaskar",
    "d": "D. Abbas Ali Baig",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Navjot Singh Sidhu had a marvellous start to his ODI cricketing career.How many sixes did he hit in his innings of 73 runs on debut?</p>",
    "a": "A. 3",
    "b": "B. 6",
    "c": "C. 5",
    "d": "D. 10",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was the man of the match of the 1983 World Cup Final?</p>",
    "a": "A. Kapil Dev",
    "b": "B. Roger Binny",
    "c": "C. Sunil Gavaskar",
    "d": "D. M. Amarnath",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who was the first Indian batsman to have achieved 300 runs in an innings in Tests?</p>",
    "a": "A. Sachin Tendulkar",
    "b": "B. Sourav Ganguly",
    "c": "C. Bishen Singh Bedi",
    "d": "D. Virender Sehwag",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>When did Sourav Ganguly made his ODI debut?</p>",
    "a": "A. 20 March 1993",
    "b": "B. 11 January 1992",
    "c": "C. 1 December 1987",
    "d": "D. 1 June 1998",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the middle name of Parthiv Patel?</p>",
    "a": "A. Rohan",
    "b": "B. Jaichandra",
    "c": "C. Ajay",
    "d": "D. Karan",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the middle name of Sourav Ganguly?</p>",
    "a": "A. Chandidas",
    "b": "B. Mohandas",
    "c": "C. Chandradas",
    "d": "D. Tarwadi",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the middle name of Ashish Nehra?</p>",
    "a": "A. Diwansingh",
    "b": "B. Karansingh",
    "c": "C. Ramsingh",
    "d": "D. Kulwaniram",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many runs did M.Kaif score in his ODI debut?</p>",
    "a": "A. DNB",
    "b": "B. 15",
    "c": "C. 0",
    "d": "D. 99",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Anil Kumble became the first Indian bowler to reach 500 Test wickets in 2006. How did he get his 500th wicket?</p>",
    "a": "A. Run out",
    "b": "B. Bowled",
    "c": "C. LBW",
    "d": "D. Catch out",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Name the Indian Chess player who has broken the World Record by finishing the game in first twelve moves?</p>",
    "a": "A. Vishwanathan Anand",
    "b": "B. Champa Bose",
    "c": "C. Sakunthala Devi",
    "d": "D. Praveen Thipsey",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Yondieki who set up a new world record in 10,000 meters race, belongs to</p>",
    "a": "A. Australia",
    "b": "B. Canada",
    "c": "C. Kenya",
    "d": "D. Mexico",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Jeev Milkha Singh is associated with which sports?</p>",
    "a": "A. Volleyball",
    "b": "B. Golf",
    "c": "C. Athletics",
    "d": "D. Hockey",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Amar Singh Sokhi is remembered for his performance in ?</p>",
    "a": "A. Archery",
    "b": "B. Cycling",
    "c": "C. Swimming",
    "d": "D. Athletics",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many players are there in Kabbadi team?</p>",
    "a": "A. 11",
    "b": "B. 9",
    "c": "C. 5",
    "d": "D. 7",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following is a pair names of the same game?</p>",
    "a": "A. Soccer - Football",
    "b": "B. Golf - Polo",
    "c": "C. Billiards - Carrom",
    "d": "D. Volleyball - Squash",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>'Popping Crease' is associated with which games?</p>",
    "a": "A. Swimming",
    "b": "B. Cricket",
    "c": "C. Water polo",
    "d": "D. Lawn Tennis",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Maradona is a famous player associated with</p>",
    "a": "A. Hockey",
    "b": "B. Football",
    "c": "C. Cricket",
    "d": "D. Golf",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The famous player 'Pele' is associated with which games?</p>",
    "a": "A. Football",
    "b": "B. Hockey",
    "c": "C. volleyball",
    "d": "D. Tennis",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ben Johnson, the well known athlete belongs to which of the following countries?</p>",
    "a": "A. South Africa",
    "b": "B. Canada",
    "c": "C. Germany",
    "d": "D. Cuba",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Limba Ram is known for his outstanding performance in which of the following?</p>",
    "a": "A. Karate",
    "b": "B. Judo",
    "c": "C. Shooting",
    "d": "D. Archery",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>How many players are there in Water Polo team?</p>",
    "a": "A. 4",
    "b": "B. 5",
    "c": "C. 6",
    "d": "D. 7",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Monica Seles is associated with which games?</p>",
    "a": "A. Tennis",
    "b": "B. Volley ball",
    "c": "C. Athletics",
    "d": "D. Badminton",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>In which city the Asian Games first took place?</p>",
    "a": "A. Hong kong",
    "b": "B. Tokyo",
    "c": "C. New delhi",
    "d": "D. Kuala Lampur",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The 13th Asian Games were held in</p>",
    "a": "A. China",
    "b": "B. Bangok",
    "c": "C. Manila",
    "d": "D. Singapore",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>India first won the Olympic Hockey gold at</p>",
    "a": "A. London",
    "b": "B. Rome",
    "c": "C. Berlin",
    "d": "D. Amsterdam",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Sergei Bubhka, an athlete of international repute, belongs to which of the following countries?</p>",
    "a": "A. Ukraine",
    "b": "B. Brazil",
    "c": "C. Russia",
    "d": "D. U.S.A",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Tripping is associates with</p>",
    "a": "A. Snooker",
    "b": "B. Volleyball",
    "c": "C. Football",
    "d": "D. Cricket",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following cups/trophies is associated with football?</p>",
    "a": "A. Davis Cup",
    "b": "B. Champions trophy",
    "c": "C. Santosh Trophy",
    "d": "D. Deodhar Trophy",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Merdeka Cup is associated with</p>",
    "a": "A. Football",
    "b": "B. Tennis",
    "c": "C. Badminton",
    "d": "D. Hockey",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Olympic Games after 4th century A.D. restarted from</p>",
    "a": "A. 1916",
    "b": "B. 1912",
    "c": "C. 1904",
    "d": "D. 1896",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>If you scored a cannon, which game would you be playing?</p>",
    "a": "A. football",
    "b": "B. Billiards",
    "c": "C. Cricket",
    "d": "D. Hockey",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Michael Ferraria is associated with which games/sports?</p>",
    "a": "A. Billiards",
    "b": "B. Karate",
    "c": "C. Hockey",
    "d": "D. Tennis",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The term 'Caddle' is associates with which sports?</p>",
    "a": "A. Golf",
    "b": "B. Billiards",
    "c": "C. Polo",
    "d": "D. Bridge",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The state which declared 1995-1996 as the Hockey year is</p>",
    "a": "A. Punjab",
    "b": "B. Gujarat",
    "c": "C. Tamil Nadu",
    "d": "D. New Delhi",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Wankhede Stadium is situated in (India)</p>",
    "a": "A. Chennai",
    "b": "B. Delhi",
    "c": "C. Chandigarh",
    "d": "D. Mumbai",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The name of Geoff Bycott is associated with which of the following games?</p>",
    "a": "A. Cricket",
    "b": "B. Golf",
    "c": "C. Swimming",
    "d": "D. Boxing",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>What is the length of each stump in the cricket?</p>",
    "a": "A. 35 inches",
    "b": "B. 22 inches",
    "c": "C. 28 inches",
    "d": "D. 33 inches",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who received he Wisden Award for the 'Indian Cricketer of the Century' (20th Century)</p>",
    "a": "A. Kapil Dev",
    "b": "B. Sachin Tendulkar",
    "c": "C. Ajit Wadekar",
    "d": "D. Sunil Gavaskar",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who won the Grand Slam title four times successively?</p>",
    "a": "A. Mortina Navratilova",
    "b": "B. Steffi Graf",
    "c": "C. Jennifer Capriati",
    "d": "D. Monica Seles",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Wimbledon is a place connected with</p>",
    "a": "A. Lawn Tennis",
    "b": "B. Badminton",
    "c": "C. Cricket",
    "d": "D. Table Tennis",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following places is known as 'Mecca of Indian Football'?</p>",
    "a": "A. Kolkata",
    "b": "B. Bombay",
    "c": "C. Haryana",
    "d": "D. Delhi",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The term 'Chukker' is used in</p>",
    "a": "A. Polo",
    "b": "B. Horse racing",
    "c": "C. Wrestling",
    "d": "D. Rifle shooting",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The Reggio Emilia Tournament in which an Indian Won early in 1992 is related to</p>",
    "a": "A. Chess",
    "b": "B. Tennis",
    "c": "C. Golf",
    "d": "D. Shooting",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Levoy Burrell is associated with which sports?</p>",
    "a": "A. Cricket",
    "b": "B. Swimming",
    "c": "C. Athletics",
    "d": "D. Boxing",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who won the maximum number of gold medals in Hiroshima Asian Games?</p>",
    "a": "A. China",
    "b": "B. India",
    "c": "C. South Korea",
    "d": "D. Japan",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Bahadur Singh is famous in which of the following?</p>",
    "a": "A. Athletics",
    "b": "B. Swimming",
    "c": "C. Boxing",
    "d": "D. Weight Lifting",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Kamlesh Mehta was associated with which games/sports?</p>",
    "a": "A. Hockey",
    "b": "B. Golf",
    "c": "C. Table Tennis",
    "d": "D. Chess",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>First Olympic Games were held in</p>",
    "a": "A. 876 BC",
    "b": "B. 798 BC",
    "c": "C. 776 BC",
    "d": "D. 898 BC",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Anita Sood is associated with which of the following games/sports?</p>",
    "a": "A. Table Tennis",
    "b": "B. Badminton",
    "c": "C. Hockey",
    "d": "D. Swimming",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which Indian batsman made three consecutive centuries in his first three Test matches?</p>",
    "a": "A. Vinoo Mankad",
    "b": "B. Mohd. Azaruddin",
    "c": "C. S.M. Gavaskar",
    "d": "D. G.R. Viswanath",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following is correctly matched?</p>",
    "a": "A. Nehru Trophy - Table Tennis",
    "b": "B. B.C. Roy Trophy - Lawn Tennis",
    "c": "C. Holkar Trophy - Bridge",
    "d": "D. Ruia Trophy - Kabbadi",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Geet Sethi has made a mark in</p>",
    "a": "A. Billiards",
    "b": "B. Shooting",
    "c": "C. Chess",
    "d": "D. Golf",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The Rovers Cup is associated with</p>",
    "a": "A. Cricket",
    "b": "B. Mauritius",
    "c": "C. Hockey",
    "d": "D. Football",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Grand Slam in Tennis means a player has to win</p>",
    "a": "A. Australian open, French open, U.S. open and Wimbledon",
    "b": "B. Australian open, U.S. Open and Wimbledon",
    "c": "C. Australian open, French open and Wimbledon",
    "d": "D. French open, Wimbledon",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Misha Grewal is associated with which games/sports?</p>",
    "a": "A. Badminton",
    "b": "B. Chess",
    "c": "C. Football",
    "d": "D. Squash",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The winter Olympics came into being in</p>",
    "a": "A. 1912",
    "b": "B. 1924",
    "c": "C. 1920",
    "d": "D. 1916",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Chris Evert's name is associated with which sports?</p>",
    "a": "A. Tennis",
    "b": "B. Swimming",
    "c": "C. Skating",
    "d": "D. Shooting",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Ali Sher, an Arjuna Award winner, is associated with</p>",
    "a": "A. Golf",
    "b": "B. Football",
    "c": "C. Yatching",
    "d": "D. Hockey",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following games originated from England?</p>",
    "a": "A. Baseball",
    "b": "B. Archery",
    "c": "C. Cricket",
    "d": "D. Hockey",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Jaspal Rana is in which of the following games?</p>",
    "a": "A. Shooting",
    "b": "B. Weight Lifting",
    "c": "C. Swimming",
    "d": "D. Archery",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which Indian Criketer was given the title 'Tiger'?</p>",
    "a": "A. Sunil Gavaskar",
    "b": "B. Rahul Dravid",
    "c": "C. B.S. Bedi",
    "d": "D. Mansur Ali Khan Pataudi",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The Golf player Vijay Singh represents</p>",
    "a": "A. Canada",
    "b": "B. Fiji",
    "c": "C. Sri Lanka",
    "d": "D. India",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The 'Agha Khan Cup' is associated with which game?</p>",
    "a": "A. Badminton",
    "b": "B. Hockey",
    "c": "C. Football",
    "d": "D. Cricket",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Shiny Wilson is associated with which of the following games/sports?</p>",
    "a": "A. Athletics",
    "b": "B. Hockey",
    "c": "C. Swimming",
    "d": "D. Cricket",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Prakash Padukone is associated with which games?</p>",
    "a": "A. Cricket",
    "b": "B. Table Tennis",
    "c": "C. Judo",
    "d": "D. Badminton",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Vishal Uppal and Harsh Mankad won the Doubles of the ITF Men's Futures Tournament in</p>",
    "a": "A. Badminton",
    "b": "B. Tennis",
    "c": "C. Football",
    "d": "D. Volleyball",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who among the following was adjudged the Best Athlete of 14th Asian games held in Busan, South Korea?</p>",
    "a": "A. Kosuke Kitajima",
    "b": "B. Taufik Hidayat",
    "c": "C. Lee Bong - Ju",
    "d": "D. Zaw Min Htwe",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Major R.S. Brar is associated with</p>",
    "a": "A. Boxing",
    "b": "B. Golf",
    "c": "C. Equestrian",
    "d": "D. Tennis",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Crame Trophy Tennis final held in May 2003 was played between</p>",
    "a": "A. Leander Paes and David Rickle",
    "b": "B. John McEnore and David Rickle",
    "c": "C. Boris Becker and John McEnroe",
    "d": "D. Boris Becker and Leander Paes",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following games is not included in the Olympic Games?</p>",
    "a": "A. Skiing",
    "b": "B. Cycling",
    "c": "C. Cricket",
    "d": "D. Archery",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>'Queens berry Rules' is the name given to the rules in</p>",
    "a": "A. Boxing",
    "b": "B. Football",
    "c": "C. Tennis",
    "d": "D. Cricket",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>'Ashes' is the term associates with which sports?</p>",
    "a": "A. Basketball",
    "b": "B. Cricket",
    "c": "C. Hockey",
    "d": "D. Volleyball",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The term 'Butterfly Stroke' is associated with</p>",
    "a": "A. Wrestling",
    "b": "B. Boxing",
    "c": "C. Kabaddi",
    "d": "D. Swimming",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Which of the following was the mascot of the Barcelona Olympic Games?</p>",
    "a": "A. Cobi",
    "b": "B. Doves",
    "c": "C. hodori",
    "d": "D. Panda",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The term 'Tee' is connected with</p>",
    "a": "A. Badminton",
    "b": "B. Golf",
    "c": "C. Bridge",
    "d": "D. Polo",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The name of the Mascot for 1996 Olympics held at Atlanta was</p>",
    "a": "A. Matari",
    "b": "B. APPU",
    "c": "C. WHATZ IT",
    "d": "D. Uncle Sam",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>S. Vijayalakshmi and Nisha Mohita are associated with</p>",
    "a": "A. Badminton",
    "b": "B. Tennis",
    "c": "C. Chess",
    "d": "D. Table Tennis",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>The Olympic museum was opened at which of the following places?</p>",
    "a": "A. Lausanne",
    "b": "B. Istanbul",
    "c": "C. Athens",
    "d": "D. Rome",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Who among the Indian to win the Athletics Gold in 1998 Asian Games?</p>",
    "a": "A. Kapil Dev",
    "b": "B. Jyotirmoyee Sikdar",
    "c": "C. Sunita Rani",
    "d": "D. P.T. Usha",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>India First won the Olympic Hockey Gold at</p>",
    "a": "A. London",
    "b": "B. Amsterdam",
    "c": "C. Berlin",
    "d": "D. Rome",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
},{
    "qtext": "<p>Susi Susanti, held the Grand Slam title in which of the following games</p>",
    "a": "A. Lawn Tennis",
    "b": "B. Tennis",
    "c": "C. Badminton",
    "d": "D. volley ball",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "Sports",
    "section": "(General Awareness)"
}

]}