{
  "data": [
    {
      "qtext": "In which decade was the American Institute of Electrical Engineers (AIEE) founded?",
      "a": "A. 1850s",
      "b": "B. 1880s",
      "c": "C. 1930s",
      "d": "D. 1950s",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is part of a database that holds only one type of information?",
      "a": "A. Report",
      "b": "B. Field",
      "c": "C. Record",
      "d": "D. File",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'OS' computer abbreviation usually means ?",
      "a": "A. Order of Significance",
      "b": "B. Open Software",
      "c": "C. Operating System",
      "d": "D. Optical Sensor",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In which decade with the first transatlantic radio broadcast occur?",
      "a": "A. 1850s",
      "b": "B. 1860s",
      "c": "C. 1870s",
      "d": "D. 1900s",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'.MOV' extension refers usually to what kind of file?",
      "a": "A. Image file",
      "b": "B. Animation/movie file",
      "c": "C. Audio file",
      "d": "D. MS Office document",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In which decade was the SPICE simulator introduced?",
      "a": "A. 1950s",
      "b": "B. 1960s",
      "c": "C. 1970s",
      "d": "D. 1980s",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Most modern TV's draw power even if turned off. The circuit the power is used in does what function?",
      "a": "A. Sound",
      "b": "B. Remote control",
      "c": "C. Color balance",
      "d": "D. High voltage",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which is a type of Electrically-Erasable Programmable Read-Only Memory?",
      "a": "A. Flash",
      "b": "B. Flange",
      "c": "C. Fury",
      "d": "D. FRAM",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The purpose of choke in tube light is ?",
      "a": "A. To decrease the current",
      "b": "B. To increase the current",
      "c": "C. To decrease the voltage momentarily",
      "d": "D. To increase the voltage momentarily",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'.MPG' extension refers usually to what kind of file?",
      "a": "A. WordPerfect Document file",
      "b": "B. MS Office document",
      "c": "C. Animation/movie file",
      "d": "D. Image file",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Who is largely responsible for breaking the German Enigma codes, created a test that provided a foundation for artificial intelligence?",
      "a": "A. Alan Turing",
      "b": "B. Jeff Bezos",
      "c": "C. George Boole",
      "d": "D. Charles Babbage",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Who developed Yahoo?",
      "a": "A. Dennis Ritchie & Ken Thompson",
      "b": "B. David Filo & Jerry Yang",
      "c": "C. Vint Cerf & Robert Kahn",
      "d": "D. Steve Case & Jeff Bezos",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Made from a variety of materials, such as carbon, which inhibits the flow of current...?",
      "a": "A. Choke",
      "b": "B. Inductor",
      "c": "C. Resistor",
      "d": "D. Capacitor",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The most common format for a home video recorder is VHS. VHS stands for...?",
      "a": "A. Video Home System",
      "b": "B. Very high speed",
      "c": "C. Video horizontal standard",
      "d": "D. Voltage house standard",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does VVVF stand for?",
      "a": "A. Variant Voltage Vile Frequency",
      "b": "B. Variable Velocity Variable Fun",
      "c": "C. Very Very Vicious Frequency",
      "d": "D. Variable Voltage Variable Frequency",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What frequency range is the High Frequency band?",
      "a": "A. 100 kHz",
      "b": "B. 1 GHz",
      "c": "C. 30 to 300 MHz",
      "d": "D. 3 to 30 MHz",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The first step to getting output from a laser is to excite an active medium. What is this process called?",
      "a": "A. Pumping",
      "b": "B. Exciting",
      "c": "C. Priming",
      "d": "D. Raising",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the relationship between resistivity r and conductivity s?",
      "a": "A. R = s2",
      "b": "B. R = s",
      "c": "C. R > s",
      "d": "D. R = 1/s",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which motor is NOT suitable for use as a DC machine?",
      "a": "A. Permanent magnet motor",
      "b": "B. Series motor",
      "c": "C. Squirrel cage motor",
      "d": "D. Synchronous motor",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "A given signal's second harmonic is twice the given signal's __________ frequency...?",
      "a": "A. Fourier",
      "b": "B. Foundation",
      "c": "C. Fundamental",
      "d": "D. Field",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In which year was MIDI(Musical Instrument Digital Interface) introduced?",
      "a": "A. 1987",
      "b": "B. 1983",
      "c": "C. 1973",
      "d": "D. 1977",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does the term PLC stand for?",
      "a": "A. Programmable Lift Computer",
      "b": "B. Program List Control",
      "c": "C. Programmable Logic Controller",
      "d": "D. Piezo Lamp Connector",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "When measuring the characteristics of a small-signal amplifier, say for a radio receiver, one might be concerned with its \"Noise...\"?",
      "a": "A. Fundamental",
      "b": "B. Fall",
      "c": "C. Force",
      "d": "D. Figure",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'DB' computer abbreviation usually means ?",
      "a": "A. Database",
      "b": "B. Double Byte",
      "c": "C. Data Block",
      "d": "D. Driver Boot",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'.INI' extension refers usually to what kind of file?",
      "a": "A. Image file",
      "b": "B. System file",
      "c": "C. Hypertext related file",
      "d": "D. Image Color Matching Profile file",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The sampling rate, (how many samples per second are stored) for a CD is...?",
      "a": "A. 48.4 kHz",
      "b": "B. 22,050 Hz",
      "c": "C. 44.1 kHz",
      "d": "D. 48 kHz",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Who created Pretty Good Privacy (PGP)?",
      "a": "A. Phil Zimmermann",
      "b": "B. Tim Berners-Lee",
      "c": "C. Marc Andreessen",
      "d": "D. Ken Thompson",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What do we call a network whose elements may be separated by some distance? It usually involves two or more small networks and dedicated high-speed telephone lines.",
      "a": "A. URL (Universal Resource Locator)",
      "b": "B. LAN (Local Area Network)",
      "c": "C. WAN (Wide Area Network)",
      "d": "D. World Wide Web",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "After the first photons of light are produced, which process is responsible for amplification of the light?",
      "a": "A. Blackbody radiation",
      "b": "B. Stimulated emission",
      "c": "C. Planck's radiation",
      "d": "D. Einstein oscillation",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which is NOT an acceptable method of distributing small power outlets throughout an open plan office area?",
      "a": "A. Power Poles",
      "b": "B. Power Skirting",
      "c": "C. Flush Floor Ducting",
      "d": "D. Extension Cords",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Sometimes computers and cache registers in a foodmart are connected to a UPS system. What does UPS mean?",
      "a": "A. United Parcel Service",
      "b": "B. Uniform Product Support",
      "c": "C. Under Paneling Storage",
      "d": "D. Uninterruptable Power Supply",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Who co-founded Hotmail in 1996 and then sold the company to Microsoft?",
      "a": "A. Shawn Fanning",
      "b": "B. Ada Byron Lovelace",
      "c": "C. Sabeer Bhatia",
      "d": "D. Ray Tomlinson",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'.TMP' extension refers usually to what kind of file?",
      "a": "A. Compressed Archive file",
      "b": "B. Image file",
      "c": "C. Temporary file",
      "d": "D. Audio file",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In the UK, what type of installation requires a fireman's switch?",
      "a": "A. Neon Lighting",
      "b": "B. High Pressure Sodium Lighting",
      "c": "C. Water Features",
      "d": "D. Hotel Rooms",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The electromagnetic coils on the neck of the picture tube or tubes which pull the electron beam from side to side and up and down are called a...?",
      "a": "A. Transformer",
      "b": "B. Yoke",
      "c": "C. Capacitor",
      "d": "D. Diode",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In the United States the television broadcast standard is...?",
      "a": "A. PAL",
      "b": "B. NTSC",
      "c": "C. SECAM",
      "d": "D. RGB",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In a color television set using a picture tube a high voltage is used to accelerate electron beams to light the screen. That voltage is about...?",
      "a": "A. 500 volts",
      "b": "B. 5 thousand volts",
      "c": "C. 25 thousand volts",
      "d": "D. 100 thousand volts",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The transformer that develops the high voltage in a home television is commonly called a...?",
      "a": "A. Tesla coil",
      "b": "B. Flyback",
      "c": "C. Yoke",
      "d": "D. Van de Graaf",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which consists of two plates separated by a dielectric and can store a charge?",
      "a": "A. Inductor",
      "b": "B. Capacitor",
      "c": "C. Transistor",
      "d": "D. Relay",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What do we call a collection of two or more computers that are located within a limited distance of each other and that are connected to each other directly or indirectly?",
      "a": "A. Inernet",
      "b": "B. Interanet",
      "c": "C. Local Area Network",
      "d": "D. Wide Area Network",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'.JPG' extension refers usually to what kind of file?",
      "a": "A. System file",
      "b": "B. Animation/movie file",
      "c": "C. MS Encarta document",
      "d": "D. Image file",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does AM mean?",
      "a": "A. Angelo marconi",
      "b": "B. Anno median",
      "c": "C. Amplitude modulation",
      "d": "D. Amperes",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In what year was the \"@\" chosen for its use in e-mail addresses?",
      "a": "A. 1976",
      "b": "B. 1972",
      "c": "C. 1980",
      "d": "D. 1984",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'.TXT' extension refers usually to what kind of file?",
      "a": "A. Text File",
      "b": "B. Image file",
      "c": "C. Audio file",
      "d": "D. Adobe Acrobat file",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What was the first ARPANET message?",
      "a": "A. \"lo\"",
      "b": "B. \"hello world\"",
      "c": "C. \"mary had a little lamb\"",
      "d": "D. \"cyberspace, the final frontier\"",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The NTSC (National Television Standards Committee) is also used in the country of...?",
      "a": "A. Japan",
      "b": "B. France",
      "c": "C. Germany",
      "d": "D. England",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "\"FET\" is a type of transistor, Its full name is ________ Effect Transistor...?",
      "a": "A. Field",
      "b": "B. Factor",
      "c": "C. Flash",
      "d": "D. Force",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What are three types of lasers?",
      "a": "A. Gas, metal vapor, rock",
      "b": "B. Pointer, diode, CD",
      "c": "C. Diode, inverted, pointer",
      "d": "D. Gas, solid state, diode",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What will a UPS be used for in a building?",
      "a": "A. To provide power to essential equipment",
      "b": "B. To monitor building electricity use",
      "c": "C. To carry messages between departments",
      "d": "D. To control lighting and power systems",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Who built the world's first binary digit computer: Z1...?",
      "a": "A. Konrad Zuse",
      "b": "B. Ken Thompson",
      "c": "C. Alan Turing",
      "d": "D. George Boole",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Compact discs, (according to the original CD specifications) hold how many minutes of music?",
      "a": "A. 74 mins",
      "b": "B. 56 mins",
      "c": "C. 60 mins",
      "d": "D. 90 mins",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Once the active medium is excited, the first photons of light are produced by which physical process?",
      "a": "A. Blackbody radiation",
      "b": "B. Spontaneous emission",
      "c": "C. Synchrotron radiation",
      "d": "D. Planck’s oscillation",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'DTP' computer abbreviation usually means ?",
      "a": "A. Digital Transmission Protocol",
      "b": "B. DeskTop Publishing",
      "c": "C. Data Type Programming",
      "d": "D. Document Type Processing",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The average power (in watts) used by a 20 to 25 inch home color television is...?",
      "a": "A. 70-100",
      "b": "B. 25-50",
      "c": "C. 500-800",
      "d": "D. Over 1000",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does AC and DC stand for in the electrical field?",
      "a": "A. Alternating Current and Direct Current",
      "b": "B. A Rock Band from Australia",
      "c": "C. Average Current and Discharged Capacitor",
      "d": "D. Atlantic City and District of Columbia",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In which decade was the ARRL founded?",
      "a": "A. 1940s",
      "b": "B. 1930s",
      "c": "C. 1920s",
      "d": "D. 1910s",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'CD' computer abbreviation usually means ?",
      "a": "A. Command Description",
      "b": "B. Change Data",
      "c": "C. Copy Density",
      "d": "D. Compact Disc",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'.BAK' extension refers usually to what kind of file?",
      "a": "A. Backup file",
      "b": "B. Audio file",
      "c": "C. Animation/movie file",
      "d": "D. MS Encarta document",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Where is the headquarters of Intel located?",
      "a": "A. Redmond, Washington",
      "b": "B. Tucson, Arizona",
      "c": "C. Santa Clara, California",
      "d": "D. Richmond, Virginia",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Who co-created the UNIX operating system in 1969 with Dennis Ritchie?",
      "a": "A. Bjarne Stroustrup",
      "b": "B. Steve Wozniak",
      "c": "C. Ken Thompson",
      "d": "D. Niklaus Wirth",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Voltage is sometimes referred to as EMF, or Electromotive...?",
      "a": "A. Field",
      "b": "B. Factor",
      "c": "C. Flash",
      "d": "D. Force",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does AM mean?",
      "a": "A. Angelo marconi",
      "b": "B. Anno median",
      "c": "C. Amplitude modulation",
      "d": "D. Amperes",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "'.BAT' extension refers usually to what kind of file?",
      "a": "A. Compressed Archive file",
      "b": "B. System file",
      "c": "C. Audio file",
      "d": "D. Backup file",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the term to ask the computer to put information in order numerically or alphabetically?",
      "a": "A. Crop",
      "b": "B. Report",
      "c": "C. Record",
      "d": "D. Sort",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The input used by an antenna or cable to a TV set uses frequencies called...?",
      "a": "A. IF",
      "b": "B. RF",
      "c": "C. AF",
      "d": "D. SAP",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Larger buildings may be supplied with a medium voltage electricity supply, and will required a substation or mini-sub. What is the main item of equipment contained in these?",
      "a": "A. Transformer",
      "b": "B. Transponder",
      "c": "C. Transducer",
      "d": "D. Converter",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What was the active medium used in the first working laser ever constructed?",
      "a": "A. A diamond block",
      "b": "B. Helium-neon gas",
      "c": "C. A ruby rod",
      "d": "D. Carbon dioxide gas",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does EPROM stand for?",
      "a": "A. Electric Programmable Read Only Memory",
      "b": "B. Erasable Programmable Read Only Memory",
      "c": "C. Evaluable Philotic Random Optic Memory",
      "d": "D. Every Person Requires One Mind",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Blue is what number on the resistor color code?",
      "a": "A. 1",
      "b": "B. 4",
      "c": "C. 2",
      "d": "D. 6",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Changing computer language of 1's and 0's to characters that a person can understand is...",
      "a": "A. Highlight",
      "b": "B. Clip art",
      "c": "C. Decode",
      "d": "D. Execute",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What's a web browser?",
      "a": "A. A kind of spider",
      "b": "B. A computer that stores WWW files",
      "c": "C. A person who likes to look at websites",
      "d": "D. A software program that allows you to access sites on the World Wide Web",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "http://www.indiabix.com - is an example of what?",
      "a": "A. A URL",
      "b": "B. An access code",
      "c": "C. A directory",
      "d": "D. A server",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "How many bits is a byte?",
      "a": "A. 4",
      "b": "B. 8",
      "c": "C. 16",
      "d": "D. 32",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "How do you subscribe to an Internet mailing list?",
      "a": "A. Contact your Internet service provider",
      "b": "B. Send e-mail to the list manager",
      "c": "C. Telephone the mailing list webmaster",
      "d": "D. Send a letter to the list",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Computers calculate numbers in what mode?",
      "a": "A. Decimal",
      "b": "B. Octal",
      "c": "C. Binary",
      "d": "D. None of the above",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is an FET?",
      "a": "A. Farad Effect Transformer",
      "b": "B. Field Effect Transformer",
      "c": "C. Field Effect Transistor",
      "d": "D. French Energy Transfer",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The speed of your net access is defined in terms of...",
      "a": "A. RAM",
      "b": "B. MHz",
      "c": "C. Kbps",
      "d": "D. Megabytes",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "How many diodes are in a full wave bridge rectifier?",
      "a": "A. 8",
      "b": "B. 2",
      "c": "C. 4",
      "d": "D. 3",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The \"desktop\" of a computer refers to:",
      "a": "A. The visible screen",
      "b": "B. The area around the monitor",
      "c": "C. The top of the mouse pad",
      "d": "D. The inside of a folder",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of these is a search engine?",
      "a": "A. FTP",
      "b": "B. Google",
      "c": "C. Archie",
      "d": "D. ARPANET",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The letters, \"DOS\" stand for...",
      "a": "A. Data Out System",
      "b": "B. Disk Out System",
      "c": "C. Disk Operating System",
      "d": "D. Data Operating System",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does CPU stand for?",
      "a": "A. Cute People United",
      "b": "B. Commonwealth Press Union",
      "c": "C. Computer Parts of USA",
      "d": "D. Central Processing Unit",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of these is a valid e-mail address?",
      "a": "A. professor.at.learnthenet",
      "b": "B. www.learnthenet.com",
      "c": "C. professor@learnthenet.com",
      "d": "D. professor@learnthenet",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which device can be used to store charge?",
      "a": "A. Transistor",
      "b": "B. Diode",
      "c": "C. Capacitor",
      "d": "D. Resistor",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Modem stands for...",
      "a": "A. Modulator Demodulater",
      "b": "B. Monetary Devaluation Exchange Mechanism",
      "c": "C. Memory Demagnetization",
      "d": "D. Monetary Demarkation",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the difference between the Internet and an intranet?",
      "a": "A. One is public, the other is private",
      "b": "B. One is safer than the other",
      "c": "C. One can be monitored, the other can't",
      "d": "D. None of the above",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In a Digital circuit, what is 1 'AND' 1?",
      "a": "A. 0",
      "b": "B. 1",
      "c": "C. 2",
      "d": "D. 4",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Your computer has gradually slowed down. What's the most likely cause?",
      "a": "A. Overheating",
      "b": "B. Your processor chip is just getting old",
      "c": "C. Adware/spyware is infecting your PC",
      "d": "D. You dropped a sandwich in your computer",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In which decade was the transistor invented?",
      "a": "A. 1940s",
      "b": "B. 1950s",
      "c": "C. 1960s",
      "d": "D. 1980s",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "A JPG is...",
      "a": "A. A Jumper Programmed Graphic",
      "b": "B. A format for an image file",
      "c": "C. A type of hard disk",
      "d": "D. A unit of measure for memory",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "A dual-layer DVD is valued because it:",
      "a": "A. Can hold more data",
      "b": "B. Contains a backup of the data stored",
      "c": "C. Uses a second layer to offer a speed increase",
      "d": "D. Creates alternative sound tracks",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "To select text by shading as you drag the mouse arrow over the text is known as...",
      "a": "A. Clip art",
      "b": "B. To highlight",
      "c": "C. To fetch",
      "d": "D. To decode",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Another word for 'Graphics for a word processor'?",
      "a": "A. Peripheral",
      "b": "B. Clip art",
      "c": "C. Highlight",
      "d": "D. Execute",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What Designates where the next action occurs?",
      "a": "A. Decode",
      "b": "B. Highlight",
      "c": "C. Select",
      "d": "D. Mother board",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which was an early mainframe computer?",
      "a": "A. ENIAC",
      "b": "B. UNIC",
      "c": "C. BRAINIA",
      "d": "D. FUNTRIA",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Experts say the healthiest way to view a computer monitor is by...",
      "a": "A. Placing it 18 to 30 inches away from your eyes",
      "b": "B. Viewing from a darkened room",
      "c": "C. Adjusting the screen for maximum contrast",
      "d": "D. Using special glasses that filter out UV rays",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Name the terminals of a BJT.",
      "a": "A. Drain, Gate, Source",
      "b": "B. Positive, Negative, Neutral",
      "c": "C. Anode, Cathode, Triode",
      "d": "D. Emitter, Base, Collector",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What do you call a computer on a network that requests files from another computer?",
      "a": "A. A client",
      "b": "B. A host",
      "c": "C. A router",
      "d": "D. A web server",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In which decade were the first successful diode and triode vacuum tubes invented?",
      "a": "A. 1800s",
      "b": "B. 1880s",
      "c": "C. 1890s",
      "d": "D. 1900s",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "RAM stands for...",
      "a": "A. Random Access Memory",
      "b": "B. Really Annoying Machine",
      "c": "C. Read A Manual",
      "d": "D. Real Absolute Memory",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Hardware devices that are not part of the main computer system and are often added later to the system.",
      "a": "A. Peripheral",
      "b": "B. Clip art",
      "c": "C. Highlight",
      "d": "D. Execute",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "On which of the following sites can you set up your email account:",
      "a": "A. Www.linux.org",
      "b": "B. Www.gre.org",
      "c": "C. Www.syvum.com",
      "d": "D. Www.hotmail.com",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The main computer that stores the files that can be sent to computers that are networked together is...",
      "a": "A. Clip art",
      "b": "B. Mother board",
      "c": "C. Peripheral",
      "d": "D. File server",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "How can you catch a computer virus?",
      "a": "A. Sending e-mail messages",
      "b": "B. Using a laptop during the winter",
      "c": "C. Opening e-mail attachments",
      "d": "D. Shopping online",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In which decade was the first solid state integrated circuit demonstrated?",
      "a": "A. 1950s",
      "b": "B. 1960s",
      "c": "C. 1970s",
      "d": "D. 1980s",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "A DV camcorder is...",
      "a": "A. Capable of creating video in HDTV",
      "b": "B. Used to create digital video",
      "c": "C. Limited to the Direct Video format",
      "d": "D. A Denon Video brand product",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What are the 2 terminals of a diode called?",
      "a": "A. Pentode and Triode",
      "b": "B. Gate and Drain",
      "c": "C. Drain and Source",
      "d": "D. Anode and Cathode",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "A coating of dust on a computer's main circuit boards has this probable consequence",
      "a": "A. Overheating",
      "b": "B. Short circuits",
      "c": "C. Slower hard disk",
      "d": "D. None",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "How many terminals does a BJT have?",
      "a": "A. 1",
      "b": "B. 5",
      "c": "C. 4",
      "d": "D. 3",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Google (www.google.com) is a...",
      "a": "A. Search Engine",
      "b": "B. Number in Math",
      "c": "C. Directory of images",
      "d": "D. Chat service on the web",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is a BJT?",
      "a": "A. Bit Junction Transfer",
      "b": "B. Bi-polar Junction Transistor",
      "c": "C. Bell Jar Transformer",
      "d": "D. Back Junction Transformer",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which is not an internet protocol?",
      "a": "A. HTTP",
      "b": "B. FTP",
      "c": "C. STP",
      "d": "D. IP",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is not a valid domain name?",
      "a": "A. Www.yahoo.com",
      "b": "B. Www.yahoo.co.uk",
      "c": "C. Www.fr.yahoo",
      "d": "D. Www.yahoo.fr",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "AOL stands for...",
      "a": "A. Arranged Outer Line",
      "b": "B. America Over LAN",
      "c": "C. Audio Over LAN",
      "d": "D. America Online",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What are the three main search expressions, or operators, recognized by Boolean logic?",
      "a": "A. FROM, TO, WHOM",
      "b": "B. AND, OR, NOT",
      "c": "C. SEARCH, KEYWORD, TEXT",
      "d": "D. AND, OR, BUT",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Another name for a computer chip is ...",
      "a": "A. Execute",
      "b": "B. Micro chip",
      "c": "C. Microprocessor",
      "d": "D. Select",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "\"www\" stands for...",
      "a": "A. World Wide Web",
      "b": "B. World Wide Wares",
      "c": "C. World Wide Wait",
      "d": "D. World Wide War",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of these is not a computer?",
      "a": "A. Aptiva",
      "b": "B. Macintosh",
      "c": "C. Acorn",
      "d": "D. Paseo",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is not a programming language?",
      "a": "A. Basic",
      "b": "B. Java",
      "c": "C. Turing",
      "d": "D. C#",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is not a method of accessing the web?",
      "a": "A. ISDN",
      "b": "B. Modem",
      "c": "C. CPU",
      "d": "D. DSL",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The \"home page\" of a web site is...",
      "a": "A. The largest page",
      "b": "B. The last page",
      "c": "C. The first page",
      "d": "D. The most colorful page",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "ROM stands for...",
      "a": "A. Royal Ontario Museum",
      "b": "B. Read Only Memory",
      "c": "C. Read on Monday",
      "d": "D. Real Obsolute Memory",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "HTML is used to...",
      "a": "A. Plot complicated graphs",
      "b": "B. Author webpages",
      "c": "C. Translate one language into another",
      "d": "D. Solve equations",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In which decade was the telegraph invented?",
      "a": "A. 1810s",
      "b": "B. 1840s",
      "c": "C. 1870s",
      "d": "D. 1890s",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Another word for the CPU is...",
      "a": "A. Execute",
      "b": "B. Microprocessor",
      "c": "C. Micro chip",
      "d": "D. Decode",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What would you use for immediate, real-time communication with a friend?",
      "a": "A. Instant Messenging",
      "b": "B. E-Mail",
      "c": "C. Usenet",
      "d": "D. A mailing list",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What kind of data can you send by e-mail?",
      "a": "A. Audio",
      "b": "B. Pictures",
      "c": "C. Video",
      "d": "D. All of the above",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "When discussing technology, a hot spot is...",
      "a": "A. A small overheated area on a CPU",
      "b": "B. A place served by public wireless access",
      "c": "C. Jargon for an X-rated Web site",
      "d": "D. A faulty area in the programming code",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In which decade was the Internet first implemented?",
      "a": "A. 1940s",
      "b": "B. 1950s",
      "c": "C. 1960s",
      "d": "D. 1980s",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In which decade was the telephone invented?",
      "a": "A. 1850s",
      "b": "B. 1860s",
      "c": "C. 1870s",
      "d": "D. 1880s",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Main circuit board in a computer is...",
      "a": "A. Decoder",
      "b": "B. Highlight",
      "c": "C. Select",
      "d": "D. Mother board",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Name the terminals of an FET.",
      "a": "A. Drain, Gate, Source",
      "b": "B. Positive, Negative, Neutral",
      "c": "C. Anode, Cathode, Triode",
      "d": "D. Emitter, Base, Collector",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Where are the contents of your computer's hard drive indexed?",
      "a": "A. Yahoo!",
      "b": "B. Google",
      "c": "C. MSN",
      "d": "D. None of the above",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "ISP stands for...",
      "a": "A. Internet Survey Period",
      "b": "B. Integrated Service Provider",
      "c": "C. Internet Security Protocol",
      "d": "D. Internet Service Provider",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Internet Explorer is a...",
      "a": "A. Any person browsing the net",
      "b": "B. Web Browser",
      "c": "C. Graphing Package",
      "d": "D. News Reader",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Lately you hear a clatter from your computer, especially when you load a program or call up information. What's going on?",
      "a": "A. It's infested with reindeer",
      "b": "B. Your hard disk may be headed for failure",
      "c": "C. A loose wire is hitting the cooling fan",
      "d": "D. A loud metallic clatter is normal",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The \"http\" you type at the beginning of any site's address stands for...",
      "a": "A. HTML Transfer Technology Process",
      "b": "B. Hyperspace Terms and Tech Protocol",
      "c": "C. Hyperspace Techniques & Tech Progress",
      "d": "D. Hyper Text Transfer Protocol",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which company created the most used networking software in the 1980's",
      "a": "A. Microsoft",
      "b": "B. Sun",
      "c": "C. IBM",
      "d": "D. Novell",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following operating systems is produced by IBM?",
      "a": "A. OS-2",
      "b": "B. Windows",
      "c": "C. DOS",
      "d": "D. UNIX",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is NOT a type of expansion slot or bus design used in Advanced-Technology class systems?",
      "a": "A. PCMCIA",
      "b": "B. ISA",
      "c": "C. PROM",
      "d": "D. EISA",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is a GPU?",
      "a": "A. Grouped Processing Unit",
      "b": "B. Graphics Processing Unit",
      "c": "C. Graphical Performance Utility",
      "d": "D. Graphical Portable Unit",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does DOCSIS stand for?",
      "a": "A. Data Over Cable Service Interface Specification",
      "b": "B. Data Over Cable Security Internet Std",
      "c": "C. Data Over Cable Secure International Stds",
      "d": "D. Data Over Cable Service Internet Standard",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which one of the following is a search engine?",
      "a": "A. Macromedia Flash",
      "b": "B. Google",
      "c": "C. Netscape",
      "d": "D. Librarians’ Index to the Internet",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which is the best search tool for finding Web sites that have been handpicked and recommended by someone else?",
      "a": "A. Subject directories",
      "b": "B. Search engines",
      "c": "C. Meta-search engines",
      "d": "D. Discussion groups",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is LCP?",
      "a": "A. Local Connection Protocol",
      "b": "B. Lost Connection Problem",
      "c": "C. Link Control Protocol",
      "d": "D. Laggy Connection Problem",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is VCM?",
      "a": "A. Virtual Connection Manager",
      "b": "B. Virtual Channel Memory",
      "c": "C. Voice Controlled Modem",
      "d": "D. Voice Communications Module",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does the abbreviation \"http\" stand for?",
      "a": "A. Hypertext Transfer Protocol",
      "b": "B. High Task Termination Procedure",
      "c": "C. Harvard Teletext Proof",
      "d": "D. Hindustan Times Technical Proffesionals",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "ARPANET, the precursor to the Internet, was developed by:",
      "a": "A. FAA",
      "b": "B. Department of Defence",
      "c": "C. NATO",
      "d": "D. UART",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is a spider?",
      "a": "A. A computer virus",
      "b": "B. A program that catalogs Web sites",
      "c": "C. A hacker who breaks into computer systems",
      "d": "D. An application for viewing Web sites",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following is not a part of the Internet?",
      "a": "A. World Wide Web",
      "b": "B. Email",
      "c": "C. CD-ROM",
      "d": "D. HTTP",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The abbreviation URL stands for:",
      "a": "A. User Regulation Law",
      "b": "B. Unknown RAM Load",
      "c": "C. Uniform Resource Locator",
      "d": "D. Ultimate RAM Locator",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the Websites code for the country Mongolia?",
      "a": "A. MN",
      "b": "B. ML",
      "c": "C. MG",
      "d": "D. MO",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What was the clock speed of the original IBM PC?",
      "a": "A. Less than 5 MHz",
      "b": "B. 10 MHz",
      "c": "C. 8 MHz",
      "d": "D. Just over 16 MHz",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is NAT?",
      "a": "A. Network Address Translation",
      "b": "B. Network Administration Tool",
      "c": "C. Novell Address Transfer",
      "d": "D. Newly Added Technology",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is not always necessary for accessing the Web?",
      "a": "A. A Web browser",
      "b": "B. A connection to an Internet Access Provider",
      "c": "C. A computer",
      "d": "D. A modem",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "On what date was the debut of the first IBM Personal Computer?",
      "a": "A. August 12, 1981",
      "b": "B. January 21 1979",
      "c": "C. August 21, 1980",
      "d": "D. January 12, 1982",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "A computer virus that actively attacks an anti-virus program or programs in an effort to prevent detection is...",
      "a": "A. Worm",
      "b": "B. Retrovirus",
      "c": "C. Trojan",
      "d": "D. Ghost virus",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the Websites code for the country Spain?",
      "a": "A. SI",
      "b": "B. SP",
      "c": "C. ES",
      "d": "D. SN",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The first web server was built in:",
      "a": "A. 1990 in Geneva, Switzerland",
      "b": "B. 1985 in Berkeley, California",
      "c": "C. 1988 in Cambridge, Massachusetts",
      "d": "D. 1947 in Berningham, UK",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In what year did the Symantec Corporation first release Norton Antivirus?",
      "a": "A. 1990",
      "b": "B. 1995",
      "c": "C. 1988",
      "d": "D. 1997",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The IBM PC-XT was the first to include a hard drive. What was the capacity of this disk?",
      "a": "A. 20 MB",
      "b": "B. 1.44 MB",
      "c": "C. 10 MB",
      "d": "D. 750 KB",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the Websites code for the country Colombia?",
      "a": "A. CO",
      "b": "B. CM",
      "c": "C. CL",
      "d": "D. CB",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of the following word processors came first?",
      "a": "A. WordPerfect",
      "b": "B. Lotus Notes",
      "c": "C. MS Word",
      "d": "D. WordStar",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The invention of the transistor, or semiconductor, was one of the most important developments leading to the personal computer revolution. What company invented the transistor in 1947?",
      "a": "A. International Business Machines",
      "b": "B. MITS",
      "c": "C. Xerox",
      "d": "D. Bell Laboratories",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is TTL?",
      "a": "A. Technical Talk Language",
      "b": "B. Transparent Transfer Layer",
      "c": "C. Time To Live",
      "d": "D. True Technology Lives",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the Websites code for the country Bulgaria?",
      "a": "A. BU",
      "b": "B. BR",
      "c": "C. BL",
      "d": "D. BG",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does PPTP stand for?",
      "a": "A. Point to Point Transmission Protocol",
      "b": "B. Point to Point Transfer Protocol",
      "c": "C. Point to Point Tunneling Protocol",
      "d": "D. Point to Point Traffic Protocol",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "According to CNN, how much did Internet traffic increase between 1994 and 1996?",
      "a": "A. Two times",
      "b": "B. Five times",
      "c": "C. Ten times",
      "d": "D. Twenty-five times",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "In 1983, which person was the first to offer a definition of the term 'computer virus'?",
      "a": "A. McAfee",
      "b": "B. Smith",
      "c": "C. Cohen",
      "d": "D. Norton",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the World Wide Web?",
      "a": "A. A computer game",
      "b": "B. A software program",
      "c": "C. The part of the Internet that enables information-sharing via interconnected pages",
      "d": "D. Another name for the Internet",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the Websites code for the country United Kingdom?",
      "a": "A. GB",
      "b": "B. UK",
      "c": "C. EN",
      "d": "D. EG",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is a MAC?",
      "a": "A. A Computer made by Apple",
      "b": "B. Memory Address Corruption",
      "c": "C. Mediocre Apple Computer",
      "d": "D. Media Access Control",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "This virus activated every Friday the 13th, affects both .EXE and .COM files and deletes any programs run on that day. What is the name of that virus?",
      "a": "A. Chernobyl",
      "b": "B. Jerusalem",
      "c": "C. Melissa",
      "d": "D. I Love You",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "A program that neither replicates or copies itself, but does damage or compromises the security of the computer. Which 'Computer Virus' it is?",
      "a": "A. Joke Program",
      "b": "B. Worm",
      "c": "C. Trojan",
      "d": "D. Hoax",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is the Websites code for the country New Zealand?",
      "a": "A. NZ",
      "b": "B. NW",
      "c": "C. NE",
      "d": "D. ZL",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which Intel chip was the first to support a 32-bit bus architecture?",
      "a": "A. 486SI",
      "b": "B. Pentium",
      "c": "C. 286",
      "d": "D. 386DX",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does ECP stand for?",
      "a": "A. Extended Capabilities Port",
      "b": "B. Extra Compatible Part",
      "c": "C. Extended Connection Port",
      "d": "D. External Cordless Peripheral",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The first graphical browser for the WWW was named:",
      "a": "A. Netscape",
      "b": "B. Veronica",
      "c": "C. Mosaic",
      "d": "D. Explorer",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is RISC?",
      "a": "A. Remodeled Interface System Computer",
      "b": "B. Remote Intranet Secured Connection",
      "c": "C. Runtime Instruction Set Compiler",
      "d": "D. Reduced Instruction Set Computer",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does ICMP stand for?",
      "a": "A. Internet Connection Modem Protocol",
      "b": "B. Intranet Control Message Program",
      "c": "C. Internal Conflict Management Program",
      "d": "D. Internet Control Message Protocol",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is FMD?",
      "a": "A. FastEthernet Measuring Device",
      "b": "B. Flashing Media Diode",
      "c": "C. Fluorescent Multi-Layer Disc",
      "d": "D. Flash Media Driver",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "Which of these is a documented hoax virus?",
      "a": "A. McDonalds screensaver",
      "b": "B. Alien.worm",
      "c": "C. Merry Xmas",
      "d": "D. Adolph",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What does SSL stand for?",
      "a": "A. Secure Socket Layer",
      "b": "B. System Socket Layer",
      "c": "C. Superuser System Login",
      "d": "D. Secure System Login",
      "e": "",
      "correct": "A",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is a URL?",
      "a": "A. A computer software program",
      "b": "B. A type of UFO",
      "c": "C. The address of a document or \"page\" on the World Wide Web",
      "d": "D. An acronym for Uniform Resources Learning",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The Central Processing Unit is an embeded chip that acts as the 'brains' of a computer. What Intel chip was used in the Altair (the first real personal computer)?",
      "a": "A. 6502",
      "b": "B. 8080",
      "c": "C. 6400",
      "d": "D. 8286",
      "e": "",
      "correct": "B",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "What is a NIC?",
      "a": "A. Netware Intranet Controller",
      "b": "B. No Internet Connection",
      "c": "C. Network Interface Card",
      "d": "D. Network Interference Control",
      "e": "",
      "correct": "C",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },
    {
      "qtext": "The Internet was developed in the...",
      "a": "A. Early 1990s",
      "b": "B. Late 1980s",
      "c": "C. Early 1970s",
      "d": "D. Late 1960s",
      "e": "",
      "correct": "D",
      "img": "",
      "topic": "Technology",
      "section": "(General Awareness)"
    },{
"qtext":"What is the size of  Floppy Diskette which is used normally?",
"a":"A. 3.5",
"b":"B. 5.5",
"c":"C. 5.3",
"d":"D. 2",
"correct":"1",
"img":"",
"topic":"Technology",
"section":"(General Awareness)"
},
{
"qtext":"A compact disc (CD) is a data storage system of the type",
"a":" A. Magnetic",
"b":" B. Optical",
"c":" C. Electrical",
"d":" D. Electromechanical",
"correct":"2",
"img":"",
"topic":"Technology",
"section":"(General Awareness)"
}



  ]
}
