{
  "data": [
    {
    "qtext": "Which of the following is not associated with the UNO?",
    "a": "A. ILO",
    "b": "B. WHO",
    "c": "C. ASEAN",
    "d": "D. All of the above",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The chairmanship/presidency of the UN Security Council rotates among the Council Members",
    "a": "A. every 6 months",
    "b": "B. every 3 months",
    "c": "C. every year",
    "d": "D. every month",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following is not a chief organ of the United Nations Organisations?",
    "a": "A. International Labour Organisation",
    "b": "B. Security Council",
    "c": "C. International Court of Justice",
    "d": "D. General Assembly",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Permanent Secretariat to coordinate the implementation of SAARC programme is located at",
    "a": "A. Dhaka",
    "b": "B. New Delhi",
    "c": "C. Colombo",
    "d": "D. Kathmandu",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The Indian delegation to the first World Conference on Human Rights was led by",
    "a": "A. Dr. Manmohan Singh",
    "b": "B. Farooq Abdullah",
    "c": "C. Dinesh singh",
    "d": "D. Alam Khan",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The year 1995 is the Golden Jubilee year of which of the following international organisations?",
    "a": "A. UNO",
    "b": "B. NAM",
    "c": "C. GATT (now WTO)",
    "d": "D. ASEAN",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The United Nations Conference on Trade and Development (UNCTAD) is located at which of the following places?",
    "a": "A. Geneva",
    "b": "B. Rome",
    "c": "C. Paris",
    "d": "D. Vienna",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Amnesty International is an organisation associated with which of the following fields?",
    "a": "A. Protection of Cruelty to animals",
    "b": "B. Environment protection",
    "c": "C. Protection of human rights",
    "d": "D. Protection of historic monuments",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The Halifax summit was that of",
    "a": "A. G-7 countries",
    "b": "B. Leaders of the NAM",
    "c": "C. countries in favour of a common currency for Europe",
    "d": "D. Palestinian and Israeli leaders",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The office of the UN General Assembly is in",
    "a": "A. Vienna",
    "b": "B. New York",
    "c": "C. Paris",
    "d": "D. Zurich",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which is principal organ of the United Nations that as virtually accomplished its object?",
    "a": "A. The Security Council",
    "b": "B. The General Assembly",
    "c": "C. The International Court of Justice",
    "d": "D. The Trusteeship Council",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The headquarters of the UNESCO is at",
    "a": "A. Rome",
    "b": "B. Geneva",
    "c": "C. New York",
    "d": "D. Paris",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which UN body deals with population problem?",
    "a": "A. UNFPA",
    "b": "B. UNDP",
    "c": "C. UNICEF",
    "d": "D. UNESCO",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Besides UK, USA, Germany and Japan the G-7 countries includes",
    "a": "A. Canada, France and Russia",
    "b": "B. Canada, Italy and Netherlands",
    "c": "C. France, Netherlands and Russia",
    "d": "D. Canada, France and Italy",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The headquarters of World Intellectual Property Organisation (WIPO) is located in",
    "a": "A. Paris",
    "b": "B. Madrid",
    "c": "C. New York",
    "d": "D. Geneva",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "SAARC is observing a decade(1991-2000) of which of the following?",
    "a": "A. Girl child",
    "b": "B. Literacy",
    "c": "C. Health services to rural poor",
    "d": "D. Shelter for all",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The headquarters of Food and Agriculture Organisation is in",
    "a": "A. Washington",
    "b": "B. Paris",
    "c": "C. Madrid",
    "d": "D. Rome",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following countries is not a member of Group 15 developing countries?",
    "a": "A. Mexico",
    "b": "B. Malaysia",
    "c": "C. Brazil",
    "d": "D. Bolivia",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which one of the following is not related to disarmament?",
    "a": "A. SALT",
    "b": "B. NPT",
    "c": "C. CTBT",
    "d": "D. NATO",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following describe correctly the Group of Seven Countries (G-7)?",
    "a": "A. They are developing countries",
    "b": "B. They are industrialised countries",
    "c": "C. They are holding Atomic Bomb technology",
    "d": "D. They are countries who can launch their own satellites",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following is used as the logo of the World Wide Fund for Nature (WWF)?",
    "a": "A. Deer",
    "b": "B. Panda",
    "c": "C. Camel",
    "d": "D. Lion",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following countries is not a member of the G-8 group?",
    "a": "A. Germany",
    "b": "B. France",
    "c": "C. Italy",
    "d": "D. Spain",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Pakistan which rejoined the Commonwealth, had pulled itself out of it in the year",
    "a": "A. 1978",
    "b": "B. 1975",
    "c": "C. 1972",
    "d": "D. 1982",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following countries is not a member of SAARC?",
    "a": "A. Nepal",
    "b": "B. Bangladesh",
    "c": "C. Afghanistan",
    "d": "D. Myanmar",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The main aim of SAARC is",
    "a": "A. Regional Cooperation",
    "b": "B. Internal affairs",
    "c": "C. Non-alignity",
    "d": "D. Peaceful Coexistence",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The International Human Rights Convention adopted by the United Nations in 1990 relates to",
    "a": "A. disabled",
    "b": "B. stateless persons",
    "c": "C. migrant workers",
    "d": "D. children",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Who was the first Indian to be President of UN General Assembly?",
    "a": "A. Mrs. Vijay Lakshmi Pandit",
    "b": "B. Ramesh Bhandari",
    "c": "C. Natwar Singh",
    "d": "D. Krishna Menon",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "How many former republics of USSR have become members of the Commonwealth of Independent States?",
    "a": "A. 11",
    "b": "B. 10",
    "c": "C. 12",
    "d": "D. 9",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The five permanent members of UN security council are",
    "a": "A. Japan, West Germany, USSR, UK and USA",
    "b": "B. Canada, China, France, USSR and USA",
    "c": "C. Germany, China, USSR, UK and USA",
    "d": "D. China, France, USSR, UK and USA",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "When was the South Asian Association for Regional Co-operation (SAARC) formed?",
    "a": "A. 1985",
    "b": "B. 1982",
    "c": "C. 1986",
    "d": "D. 1987",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following is the headquarters of World Trade Organisation (WTO)?",
    "a": "A. New York",
    "b": "B. Geneva",
    "c": "C. Madrid",
    "d": "D. Paris",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The international township built near Pondicherry in India in coloration with UNESCO is called",
    "a": "A. Elbaville",
    "b": "B. Auroville",
    "c": "C. Gayaville",
    "d": "D. Broadway",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following is a cultural organisation?",
    "a": "A. UNESCO",
    "b": "B. ILO",
    "c": "C. WHO",
    "d": "D. FAO",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The non-permanent members of the Security Council of the UN elected by the General Assembly for two years term at present include (2-year term which begins on the January 1, 2011)",
    "a": "A. Japan, India, Hungary, Venezuela",
    "b": "B. Morocco, Cape, Verde, Belgium, Russia",
    "c": "C. Zimbabwe, Venezuela, India, France",
    "d": "D. Colombia, Germany, India, Portugal, South Africa",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following countries is not a member of G-15?",
    "a": "A. Jamaica",
    "b": "B. Indonesia",
    "c": "C. Colombia",
    "d": "D. Peru",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The Economic and Social Commission for Asia and Pacific (ESCAP) is located at",
    "a": "A. Manila",
    "b": "B. Singapore",
    "c": "C. Kuala lumpur",
    "d": "D. Bangkok",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Vietnam joined the U.N.O in the year",
    "a": "A. 1977",
    "b": "B. 1970",
    "c": "C. 1976",
    "d": "D. 1974",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The International Court of Justice is located at",
    "a": "A. Geneva",
    "b": "B. Hague",
    "c": "C. Amsterdam",
    "d": "D. Vienna",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following international organisations has started the scheme 'Partnership for Peace' for a group of nations?",
    "a": "A. Organisation of Petroleum Exporting Countries (OPEC)",
    "b": "B. Economic and Social Commission for Asia and Pacific (ESCAP)",
    "c": "C. North Atlantic Treaty Organisation (NATO)",
    "d": "D. Organisations of African Unity (OAU)",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following pairs of country and the purpose for which U.N. Peace Keeping Force is maintained is correctly is correctly matched?",
    "a": "A. Cyprus - to maintain peace between the two dominant ethnic groups in the country",
    "b": "B. Mozambique - To supervise a referendum",
    "c": "C. El Salvador - to deliver humanitarian aid",
    "d": "D. Lebanon - For supervising a 1992 accord",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following is Human Rights Organisation?",
    "a": "A. The French community",
    "b": "B. The Organisation of African Unity",
    "c": "C. The Arab League",
    "d": "D. Amnesty International",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The headquarters of International Atomic Energy Agency is located in",
    "a": "A. Vienna",
    "b": "B. London",
    "c": "C. Geneva",
    "d": "D. Washington",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The head quarters of the International Red Cross is situated in",
    "a": "A. Vienna",
    "b": "B. Paris",
    "c": "C. Hague",
    "d": "D. Geneva",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which was the first country to withdraw from CENTO?",
    "a": "A. Iraq",
    "b": "B. Afghanistan",
    "c": "C. Turkey",
    "d": "D. U.K.",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "First Indian to make a speech in Hindi before the UN General Assembly is",
    "a": "A. Moraji Desai",
    "b": "B. A.B. Vajpayee",
    "c": "C. Lal Bahadur Shastri",
    "d": "D. Lal Krishna Advani",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "When was SAARC founded?",
    "a": "A. 1982",
    "b": "B. 1984",
    "c": "C. 1985",
    "d": "D. 1983",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following is not a member of G-15?",
    "a": "A. Pakistan",
    "b": "B. Malaysia",
    "c": "C. Indonesia",
    "d": "D. India",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Amnesty International has its headquarters at",
    "a": "A. Berlin",
    "b": "B. New York",
    "c": "C. Washington",
    "d": "D. London",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Headquarters of the World Health Organisation is located at",
    "a": "A. Geneva",
    "b": "B. Washington DC",
    "c": "C. New York",
    "d": "D. Rome",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The working language(s) of the UNESCO is/are",
    "a": "A. French only",
    "b": "B. English only",
    "c": "C. English and French",
    "d": "D. English, French and Russian",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The number of principal organs of UNO is",
    "a": "A. 3",
    "b": "B. 4",
    "c": "C. 5",
    "d": "D. 6",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "G-7 includes",
    "a": "A. South Africa",
    "b": "B. Australia",
    "c": "C. India",
    "d": "D. Italy",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "INTERPOL means",
    "a": "A. International Political Conference",
    "b": "B. International Criminal Police Organisation",
    "c": "C. None of these",
    "d": "D. International Association of Police Officers",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The headquarters of U.N. is located in",
    "a": "A. Rome",
    "b": "B. Geneva",
    "c": "C. New York",
    "d": "D. Washington D.C.",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The SAARC movement was launched for",
    "a": "A. political alliances",
    "b": "B. regional cooperation",
    "c": "C. cultural exchanges",
    "d": "D. military strategy",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The headquarters of UNHCR is located at",
    "a": "A. New York",
    "b": "B. Rome",
    "c": "C. Geneva",
    "d": "D. London",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following is a military alliance?",
    "a": "A. NATO",
    "b": "B. NAFTA",
    "c": "C. EEC",
    "d": "D. ASEAN",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The headquarters of International Labour Organisation is at",
    "a": "A. Paris",
    "b": "B. New York",
    "c": "C. Hague",
    "d": "D. Geneva",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The UNO was founded at",
    "a": "A. Moscow",
    "b": "B. London",
    "c": "C. Paris",
    "d": "D. San Francisco",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The first General Secretary of UNO was",
    "a": "A. Dag Hamarskjoeld",
    "b": "B. U Thant",
    "c": "C. Trygve Lie",
    "d": "D. Kurt Waldheim",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The NAM summit which demanded expansion of the United Nations Security council had met at",
    "a": "A. Tehran",
    "b": "B. Cairo",
    "c": "C. Harare",
    "d": "D. Jakarta",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following countries is not a member of a SAARC",
    "a": "A. Sri Lanka",
    "b": "B. Myanmar",
    "c": "C. Maldives",
    "d": "D. Bhutan",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Where was the first ever security Council Summit meeting held in early 1992?",
    "a": "A. New York",
    "b": "B. Paris",
    "c": "C. Geneva",
    "d": "D. London",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following country is not a member of G-7?",
    "a": "A. Japan",
    "b": "B. Russia",
    "c": "C. France",
    "d": "D. Italy",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which of the following is not an agency of U.N.?",
    "a": "A. World Health Organisation",
    "b": "B. Food and Agricultural Organisation",
    "c": "C. International Committee of the Red Cross",
    "d": "D. International Monetary Fund",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "G-15 is a group of",
    "a": "A. developing countries",
    "b": "B. non-aligned countries",
    "c": "C. developed countries",
    "d": "D. companies",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The Indian Red Cross Society was established in the year",
    "a": "A. 1932",
    "b": "B. 1920",
    "c": "C. 1945",
    "d": "D. 1890",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "SAARC was founded in",
    "a": "A. New Delhi",
    "b": "B. Geneva",
    "c": "C. Dhaka",
    "d": "D. Thimpu",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which organ of United Nations has ceased to be operational?",
    "a": "A. Trusteeship Council",
    "b": "B. Secretariat",
    "c": "C. International Court of Justice",
    "d": "D. Economic and Social Council",
    "e": "",
    "correct": "A",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The member countries of NAFTA are",
    "a": "A. USA and Canada",
    "b": "B. USA, Canada and Mexico",
    "c": "C. Canada and Mexico",
    "d": "D. USA and Mexico",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "India was elected as a President of General Assembly of the United Nations in 1953. Who occupied this office on behalf of India?",
    "a": "A. S. Radha Krishnan",
    "b": "B. Gopalswamy Iyyengar",
    "c": "C. V.K. Krishna Menon",
    "d": "D. Vijayalakshmi Pandit",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "United Nations adapted a Charter of Economic Rights in the year",
    "a": "A. 1969",
    "b": "B. 1974",
    "c": "C. 1956",
    "d": "D. 1964",
    "e": "",
    "correct": "B",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "Which organ of the United Nations has ceased to be operational?",
    "a": "A. Economic and Social Council",
    "b": "B. International Court of Justice",
    "c": "C. Trusteeship Council",
    "d": "D. Secretariat",
    "e": "",
    "correct": "C",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
},{
    "qtext": "The United Nations is considered as a universal organisation. Which organ of rhe united nations fully represents the fact?",
    "a": "A. The Economic and Social Council",
    "b": "B. The Security Council",
    "c": "C. The Secretariat",
    "d": "D. The General Assembly",
    "e": "",
    "correct": "D",
    "img": "",
    "topic": "World Organizations",
    "section": "(General Awareness)"
}
  ]
}
