{
  "data": [
  {
    "qtext": "Look at this series: 2, 4, 6, 8, 10, ...What number should come next?",
    "a": "(A) 11",
    "b": "(B) 12",
    "c": "(C) 13",
    "d": "(D) 14",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 58, 52, 46, 40, 34, . . . What number should come next?",
    "a": "(A) 26",
    "b": "(B) 28",
    "c": "(C) 30",
    "d": "(D) 32",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 40, 40, 47, 47, 54, . . . What number should come next?",
    "a": "(A) 40",
    "b": "(B) 44",
    "c": "(C) 54",
    "d": "(D) 61",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 544, 509, 474, 439, . . . What number should come next?",
    "a": "(A) 404",
    "b": "(B) 414",
    "c": "(C) 420",
    "d": "(D) 445",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 201, 202, 204, 207, . . . What number should come next?",
    "a": "(A) 205",
    "b": "(B) 208",
    "c": "(C) 210",
    "d": "(D) 211",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 8, 22, 8, 28, 8, . . . What number should come next?",
    "a": "(A) 9",
    "b": "(B) 29",
    "c": "(C) 32",
    "d": "(D) 34",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 80, 10, 70, 15, 60, . . . What number should come next?",
    "a": "(A) 20",
    "b": "(B) 25",
    "c": "(C) 30",
    "d": "(D) 50",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 36, 34, 30, 28, 24, . . . What number should come next?",
    "a": "(A) 20",
    "b": "(B) 22",
    "c": "(C) 23",
    "d": "(D) 26",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 22, 21, 23, 22, 24, 23,...What number should come next?",
    "a": "(A) 22",
    "b": "(B) 24",
    "c": "(C) 25",
    "d": "(D) 26",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 3, 4, 7, 8, 11, 12, . . . What number should come next?",
    "a": "(A) 7",
    "b": "(B) 10",
    "c": "(C) 14",
    "d": "(D) 15",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 31, 29, 24, 22, 17, . . . What number should come next?",
    "a": "(A) 15",
    "b": "(B) 14",
    "c": "(C) 13",
    "d": "(D) 12",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 21, 9, 21, 11, 21, 13,...What number should come next?",
    "a": "(A) 14",
    "b": "(B) 15",
    "c": "(C) 21",
    "d": "(D) 23",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 53, 53, 40, 40, 27, 27,...What number should come next?",
    "a": "(A) 12",
    "b": "(B) 14",
    "c": "(C) 27",
    "d": "(D) 53",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 2, 6, 18, 54, ...What number should come next?",
    "a": "(A) 108",
    "b": "(B) 148",
    "c": "(C) 162",
    "d": "(D) 216",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 1,000, 200, 40, . . . What number should come next?",
    "a": "(A) 8",
    "b": "(B) 10",
    "c": "(C) 15",
    "d": "(D) 20",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 7, 10, 8, 11, 9, 12, . . . What number should come next?",
    "a": "(A) 7",
    "b": "(B) 10",
    "c": "(C) 12",
    "d": "(D) 13",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 14, 28, 20, 40, 32, 64,...What number should come next?",
    "a": "(A) 52",
    "b": "(B) 56",
    "c": "(C) 96",
    "d": "(D) 128",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 1.5, 2.3, 3.1, 3.9, . . . What number should come next?",
    "a": "(A) 4.2",
    "b": "(B) 4.4",
    "c": "(C) 4.7",
    "d": "(D) 5.1",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 5.2, 4.8, 4.4, 4, . . . What number should come next?",
    "a": "(A) 3",
    "b": "(B) 3.3",
    "c": "(C) 3.5",
    "d": "(D) 3.6",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "20.Look at this series: 2, 1, 1/2, 1/4,...What number should come next?",
    "a": "(A)1/3",
    "b": "(B)1/8",
    "c": "(C)2/8",
    "d": "(D)1/16",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "84 78 72 66 60 54 48",
    "a": "(A) 44 34",
    "b": "(B) 42 36",
    "c": "(C) 42 32",
    "d": "(D) 40 34",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3 8 13 18 23 28 33",
    "a": "(A) 39 44",
    "b": "(B) 38 44",
    "c": "(C) 38 43",
    "d": "(D) 37 42",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "20 20 17 17 14 14 11",
    "a": "(A) 8 8",
    "b": "(B) 11 11",
    "c": "(C) 11 14",
    "d": "(D) 11 8",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "18 21 25 18 29 33 18",
    "a": "(A) 43 18",
    "b": "(B) 41 44",
    "c": "(C) 37 18",
    "d": "(D) 37 41",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "9 11 33 13 15 33 17",
    "a": "(A) 19 33",
    "b": "(B) 33 35",
    "c": "(C) 33 19",
    "d": "(D) 15 33",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2 8 14 20 26 32 38",
    "a": "(A) 2 46",
    "b": "(B) 44 50",
    "c": "(C) 42 48",
    "d": "(D) 40 42",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "28 25 5 21 18 5 14",
    "a": "(A) 11 5",
    "b": "(B) 10 7",
    "c": "(C) 11 8",
    "d": "(D) 5 10",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "9 12 11 14 13 16 15",
    "a": "(A) 14 13",
    "b": "(B) 18 21",
    "c": "(C) 14 17",
    "d": "(D) 18 17",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "75 65 85 55 45 85 35",
    "a": "(A) 25 15",
    "b": "(B) 25 85",
    "c": "(C) 35 25",
    "d": "(D) 85 35",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1 10 7 20 13 30 19",
    "a": "(A) 26 40",
    "b": "(B) 29 36",
    "c": "(C) 40 25",
    "d": "(D) 25 31",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "10 20 25 35 40 50 55",
    "a": "(A) 70 65",
    "b": "(B) 60 70",
    "c": "(C) 60 75",
    "d": "(D) 65 70",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "40 40 31 31 22 22 13",
    "a": "(A) 13 4",
    "b": "(B) 13 5",
    "c": "(C) 4 13",
    "d": "(D) 9 4",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "17 17 34 20 20 31 23",
    "a": "(A) 26 23",
    "b": "(B) 34 20",
    "c": "(C) 23 33",
    "d": "(D) 23 28",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2 3 4 5 6 4 8",
    "a": "(A) 9 10",
    "b": "(B) 4 8",
    "c": "(C) 10 4",
    "d": "(D) 9 4",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "61 57 50 61 43 36 61",
    "a": "(A) 29 61",
    "b": "(B) 27 20",
    "c": "(C) 31 61",
    "d": "(D) 29 22",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "9 16 23 30 37 44 51",
    "a": "(A) 59 66",
    "b": "(B) 56 62",
    "c": "(C) 58 66",
    "d": "(D) 58 65",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8 22 12 16 22 20 24",
    "a": "(A) 28 32",
    "b": "(B) 28 22",
    "c": "(C) 22 28",
    "d": "(D) 32 36",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "6 20 8 14 10 8 12",
    "a": "(A) 14 10",
    "b": "(B) 2 18",
    "c": "(C) 4 12",
    "d": "(D) 2 14",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "11 16 21 26 31 36 41",
    "a": "(A) 47 52",
    "b": "(B) 46 52",
    "c": "(C) 45 49",
    "d": "(D) 46 51",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8 11 21 15 18 21 22",
    "a": "(A) 25 18",
    "b": "(B) 25 21",
    "c": "(C) 25 29",
    "d": "(D) 24 21",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "44 41 38 35 32 29 26",
    "a": "(A) 24 21",
    "b": "(B) 22 19",
    "c": "(C) 23 19",
    "d": "(D) 23 20",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "6 10 14 18 22 26 30",
    "a": "(A) 36 40",
    "b": "(B) 33 37",
    "c": "(C) 38 42",
    "d": "(D) 34 38",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "34 30 26 22 18 14 10",
    "a": "(A) 8 6",
    "b": "(B) 6 4",
    "c": "(C) 14 18",
    "d": "(D) 6 2",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2 44 4 41 6 38 8",
    "a": "(A) 10 12",
    "b": "(B) 35 32",
    "c": "(C) 34 9",
    "d": "(D) 35 10",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "32 29 26 23 20 17 14",
    "a": "(A) 11 8",
    "b": "(B) 12 8",
    "c": "(C) 11 7",
    "d": "(D) 32 29",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "14 14 26 26 38 38 50",
    "a": "(A) 60 72",
    "b": "(B) 50 62",
    "c": "(C) 50 72",
    "d": "(D) 62 62",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8 12 9 13 10 14 11",
    "a": "(A) 14 11",
    "b": "(B) 15 12",
    "c": "(C) 8 15",
    "d": "(D) 15 19",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "4 7 26 10 13 20 16",
    "a": "(A) 14 4",
    "b": "(B) 14 17",
    "c": "(C) 18 14",
    "d": "(D) 19 13",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3 8 10 15 17 22 24",
    "a": "(A) 26 28",
    "b": "(B) 29 34",
    "c": "(C) 29 31",
    "d": "(D) 26 31",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "17 14 14 11 11 8 8",
    "a": "(A) 8 5",
    "b": "(B) 5 2",
    "c": "(C) 8 2",
    "d": "(D) 5 5",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "13 29 15 26 17 23 19",
    "a": "(A) 21 23",
    "b": "(B) 20 21",
    "c": "(C) 20 17",
    "d": "(D) 25 27",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "16 26 56 36 46 68 56",
    "a": "(A) 80 66",
    "b": "(B) 64 82",
    "c": "(C) 66 80",
    "d": "(D) 78 68",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "7 9 66 12 14 66 17",
    "a": "(A) 19 66",
    "b": "(B) 66 19",
    "c": "(C) 19 22",
    "d": "(D) 20 66",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3 5 35 10 12 35 17",
    "a": "(A) 22 35",
    "b": "(B) 35 19",
    "c": "(C) 19 35",
    "d": "(D) 19 24",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "36 31 29 24 22 17 15",
    "a": "(A) 13 11",
    "b": "(B) 10 5",
    "c": "(C) 13 8",
    "d": "(D) 10 8",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "42 40 38 35 33 31 28",
    "a": "(A) 25 22",
    "b": "(B) 26 23",
    "c": "(C) 26 24",
    "d": "(D) 25 23",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "11 14 14 17 17 20 20",
    "a": "(A) 23 23",
    "b": "(B) 23 26",
    "c": "(C) 21 24",
    "d": "(D) 24 24",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "17 32 19 29 21 26 23",
    "a": "(A) 25 25",
    "b": "(B) 20 22",
    "c": "(C) 23 25",
    "d": "(D) 25 22",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "10 34 12 31 14 28 16",
    "a": "(A) 25 18",
    "b": "(B) 30 13",
    "c": "(C) 19 26",
    "d": "(D) 18 20",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "32 31 32 29 32 27 32",
    "a": "(A) 25 32",
    "b": "(B) 31 32",
    "c": "(C) 29 32",
    "d": "(D) 25 30",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 8, 43, 11, 41, __, 39, 17,...What number should fill in the blank?",
    "a": "(A) 8",
    "b": "(B) 14",
    "c": "(C) 43",
    "d": "(D) 44",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 15, __, 27, 27, 39, 39,...What number should fill the blank?",
    "a": "(A) 51",
    "b": "(B) 39",
    "c": "(C) 23",
    "d": "(D) 15",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 83, 73, 93, 63, __, 93, 43, . . .What number should fill the blank?",
    "a": "(A) 33",
    "b": "(B) 53",
    "c": "(C) 73",
    "d": "(D) 93",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 4, 7, 25, 10, __, 20, 16, 19,...What number should fill the blank?",
    "a": "(A) 13",
    "b": "(B) 15",
    "c": "(C) 20",
    "d": "(D) 28",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 72, 76, 73, 77, 74, __, 75,...What number should fill the blank?",
    "a": "(A) 70",
    "b": "(B) 71",
    "c": "(C) 75",
    "d": "(D) 78",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 70, 71, 76, __, 81, 86, 70, 91,...What number should fill the blank?",
    "a": "(A) 70",
    "b": "(B) 71",
    "c": "(C) 80",
    "d": "(D) 96",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 664, 332, 340, 170, __, 89,...What number should fill the blank?",
    "a": "(A) 85",
    "b": "(B) 97",
    "c": "(C) 109",
    "d": "(D) 178",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 0.15, 0.3, __, 1.2, 2.4, . . .What number should fill the blank?",
    "a": "(A) 4.8",
    "b": "(B) 0.006",
    "c": "(C) 0.6",
    "d": "(D) 0.9",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: 1/9, 1/3, 1, 9,....What number should fill the blank?",
    "a": "(A)2/3",
    "b": "(B) 3",
    "c": "(C) 6",
    "d": "(D) 27",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: U32, V29, __, X23, Y20, . . .What number should fill the blank?",
    "a": "(A) W26",
    "b": "(B) W17",
    "c": "(C) Z17",
    "d": "(D) Z26",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: J14, L16, __, P20, R22, . . .What number should fill the blank?",
    "a": "(A) S24",
    "b": "(B) N18",
    "c": "(C) M18",
    "d": "(D) T24",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: F2, __, D8, C16, B32, . . .What number should fill the blank?",
    "a": "(A) A16",
    "b": "(B) G4",
    "c": "(C) E4",
    "d": "(D) E3",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: V, VIII, XI, XIV, __, XX,...What number should fill the blank?",
    "a": "(A) IX",
    "b": "(B) XXIII",
    "c": "(C) XV",
    "d": "(D) XVII",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: XXIV, XX, __, XII, VIII, . . .What number should fill the blank?",
    "a": "(A) XXII",
    "b": "(B) XIII",
    "c": "(C) XVI",
    "d": "(D) IV",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Look at this series: VI, 10, V, 11, __, 12, III,...What number should fill the blank?",
    "a": "(A) II",
    "b": "(B) IV",
    "c": "(C) IX",
    "d": "(D) 14",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 1, (1/2), (1/4)",
    "a": "(A)(1/3)",
    "b": "(B)(1/8)",
    "c": "(C)(2/8)",
    "d": "(D)(1/16)",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "7, 10, 8, 11, 9, 12",
    "a": "(A)7",
    "b": "(B)10",
    "c": "(C)12",
    "d": "(D)13",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "36, 34, 30, 28, 24",
    "a": "(A)20",
    "b": "(B)22",
    "c": "(C)23",
    "d": "(D)26",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "22, 21, 23, 22, 24, 23",
    "a": "(A)22",
    "b": "(B)24",
    "c": "(C)25",
    "d": "(D)26",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "53, 53, 40, 40, 27, 27",
    "a": "(A)12",
    "b": "(B)14",
    "c": "(C)27",
    "d": "(D)53",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "21, 9, 21, 11, 21, 13, 21",
    "a": "(A)14",
    "b": "(B)15",
    "c": "(C)21",
    "d": "(D)23",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "58, 52, 46, 40, 34",
    "a": "(A)26",
    "b": "(B)28",
    "c": "(C)30",
    "d": "(D)32",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3, 4, 7, 8, 11, 12",
    "a": "(A)7",
    "b": "(B)10",
    "c": "(C)14",
    "d": "(D)15",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8, 22, 8, 28, 8",
    "a": "(A)9",
    "b": "(B)29",
    "c": "(C)32",
    "d": "(D)34",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "31, 29, 24, 22, 17",
    "a": "(A)15",
    "b": "(B)14",
    "c": "(C)13",
    "d": "(D)12",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1.5, 2.3, 3.1, 3.9",
    "a": "(A)4.2",
    "b": "(B)4.4",
    "c": "(C)4.7",
    "d": "(D)5.1",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "14, 28, 20, 40, 32, 64",
    "a": "(A)52",
    "b": "(B)56",
    "c": "(C)96",
    "d": "(D)128",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 4, 6, 8, 10",
    "a": "(A)11",
    "b": "(B)12",
    "c": "(C)13",
    "d": "(D)14",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "201, 202, 204, 207",
    "a": "(A)205",
    "b": "(B)208",
    "c": "(C)210",
    "d": "(D)211",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "544, 509, 474, 439",
    "a": "(A)404",
    "b": "(B)414",
    "c": "(C)420",
    "d": "(D)445",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "80, 10, 70, 15, 60",
    "a": "(A)20",
    "b": "(B)25",
    "c": "(C)30",
    "d": "(D)50",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 6, 18, 54",
    "a": "(A)108",
    "b": "(B)148",
    "c": "(C)162",
    "d": "(D)216",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "5.2, 4.8, 4.4, 4",
    "a": "(A)3",
    "b": "(B)3.3",
    "c": "(C)3.5",
    "d": "(D)3.6",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8, 6, 9, 23, 87 ",
    "a": "(A)128",
    "b": "(B)226",
    "c": "(C)324",
    "d": "(D)429",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "F2, __, D8, C16, B32",
    "a": "(A)A16",
    "b": "(B)G4",
    "c": "(C)E4",
    "d": "(D)E3",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "664, 332, 340, 170, ____, 89",
    "a": "(A)85",
    "b": "(B)97",
    "c": "(C)109",
    "d": "(D)178",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "V, VIII, XI, XIV, __, XX",
    "a": "(A)IX",
    "b": "(B)XXIII",
    "c": "(C)XV",
    "d": "(D)XVII",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "70, 71, 76, __, 81, 86, 70, 91",
    "a": "(A)70",
    "b": "(B)71",
    "c": "(C)80",
    "d": "(D)96",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8, 43, 11, 41, __, 39, 17",
    "a": "(A)8",
    "b": "(B)14",
    "c": "(C)43",
    "d": "(D)44",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "VI, 10, V, 11, __, 12, III",
    "a": "(A)II",
    "b": "(B)IV",
    "c": "(C)IX",
    "d": "(D)14",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "(1/9), (1/3), 1, ____ , 9",
    "a": "(A)(2/3)",
    "b": "(B)3",
    "c": "(C)6",
    "d": "(D)27",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "83, 73, 93, 63, __, 93, 43",
    "a": "(A)33",
    "b": "(B)53",
    "c": "(C)73",
    "d": "(D)93",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "15, __, 27, 27, 39, 39",
    "a": "(A)51",
    "b": "(B)39",
    "c": "(C)23",
    "d": "(D)15",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "72, 76, 73, 77, 74, __, 75",
    "a": "(A)70",
    "b": "(B)71",
    "c": "(C)75",
    "d": "(D)78",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "J14, L16, __, P20, R22",
    "a": "(A)S24",
    "b": "(B)N18",
    "c": "(C)M18",
    "d": "(D)T24",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "4, 7, 25, 10, __, 20, 16, 19",
    "a": "(A)13",
    "b": "(B)15",
    "c": "(C)20",
    "d": "(D)28",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "XXIV, XX, __, XII, VIII",
    "a": "(A)XXII",
    "b": "(B)XIII",
    "c": "(C)XVI",
    "d": "(D)IV",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "0.15, 0.3, ____, 1.2, 2.4",
    "a": "(A)4.8",
    "b": "(B)0.006",
    "c": "(C)0.6",
    "d": "(D)0.9",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "U32, V29, __, X23, Y20",
    "a": "(A)W26",
    "b": "(B)W17",
    "c": "(C)Z17",
    "d": "(D)Z26",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n1, 9, 25, 49, ?, 121.",
    "a": "(A)100",
    "b": "(B)91",
    "c": "(C)64",
    "d": "(D)81",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n4, 7, 12, 19, 28, ?",
    "a": "(A)49",
    "b": "(B)36",
    "c": "(C)30",
    "d": "(D)39",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n6, 11, 21, 36, 56, ?",
    "a": "(A)91",
    "b": "(B)51",
    "c": "(C)81",
    "d": "(D)42",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n10, 100, 200, 310, ?",
    "a": "(A)430",
    "b": "(B)420",
    "c": "(C)410",
    "d": "(D)400",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n8, 28, 116, 584, ?",
    "a": "(A)1752",
    "b": "(B)3504",
    "c": "(C)3508",
    "d": "(D)3502",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n3, 7, 23, 95, ?",
    "a": "(A)62",
    "b": "(B)128",
    "c": "(C)479",
    "d": "(D)575",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n7, 26, 63, 124, 215, 342, ?",
    "a": "(A)391",
    "b": "(B)511",
    "c": "(C)481",
    "d": "(D)421",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n165, 195, 255, 285, 345, ?",
    "a": "(A)390",
    "b": "(B)420",
    "c": "(C)435",
    "d": "(D)375",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n34, 45, 56, 67,?",
    "a": "(A)78",
    "b": "(B)73",
    "c": "(C)82",
    "d": "(D)84",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n3, 2, 7, 6, 11, ?",
    "a": "(A)8",
    "b": "(B)10",
    "c": "(C)4",
    "d": "(D)2",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In the following number series a wrong number is given. Find out the wrong number.\n150, 450, 750, 1060,1350,1650,1950",
    "a": "(A)1060",
    "b": "(B)1950",
    "c": "(C)450",
    "d": "(D)1350",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n5690, 5121, 4552, 3983, 3414, 2845, ?",
    "a": "(A)750",
    "b": "(B)2276",
    "c": "(C)2516",
    "d": "(D)2356",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n6, 13, 28, 59, ?, 249.",
    "a": "(A)2456",
    "b": "(B)124",
    "c": "(C)122",
    "d": "(D)120",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n4, 8, 10, 14, 16, 20, ?",
    "a": "(A)118",
    "b": "(B)22",
    "c": "(C)21",
    "d": "(D)20",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n9, 17, 33, 65, ?",
    "a": "(A)16",
    "b": "(B)117",
    "c": "(C)119",
    "d": "(D)129",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n2, 3, 6, 15, ?, 123",
    "a": "(A)47",
    "b": "(B)42",
    "c": "(C)45",
    "d": "(D)50",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In the following number series a wrong number is given. Find out the wrong number.\n1, 3, 10, 21, 64, 129, 356, 777",
    "a": "(A)129",
    "b": "(B)21",
    "c": "(C)10",
    "d": "(D)356",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n9, 27, 31, 155, 161, 1127, ?",
    "a": "(A)316",
    "b": "(B)1135",
    "c": "(C)1288",
    "d": "(D)2254",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n2, 7, 27, 107, 427, ?",
    "a": "(A)1262",
    "b": "(B)1707",
    "c": "(C)4027",
    "d": "(D)4207",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\nSunday, Monday, Wednesday, Saturday, Wednesday, Monday, ?,?",
    "a": "(A)Sunday, Sunday",
    "b": "(B)Sunday, Monday",
    "c": "(C)Sunday, Wednesday",
    "d": "(D)Sunday, Saturday",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n2816, ? , 176, 44, 11.",
    "a": "(A)704",
    "b": "(B)1408",
    "c": "(C)352",
    "d": "(D)2640",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n113, 225, 449, ? , 1793",
    "a": "(A)897",
    "b": "(B)789",
    "c": "(C)987",
    "d": "(D)978",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\nPRODUCTIVITY, RODUCTIVIT, ODUCTIVI, ?",
    "a": "(A)DUCTIV",
    "b": "(B)DUCTLY",
    "c": "(C)UCTIV",
    "d": "(D)DUCTI",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n6, 24, 60,120, 210, ?",
    "a": "(A)336",
    "b": "(B)366",
    "c": "(C)330",
    "d": "(D)660",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "6, 11, 31, 121, 601, ?",
    "a": "(A)3600",
    "b": "(B)3621",
    "c": "(C)3601",
    "d": "(D)3611",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "7, 11, 19, 35, 67, ?",
    "a": "(A)99",
    "b": "(B)131",
    "c": "(C)137",
    "d": "(D)124",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8, 22, 64, 190, 568, ?",
    "a": "(A)1702",
    "b": "(B)7767",
    "c": "(C)6992",
    "d": "(D)6913",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "5760,2880,960, 240, 48, ?",
    "a": "(A)6",
    "b": "(B)8",
    "c": "(C)12",
    "d": "(D)16",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "0, 6, 24, 60, 120, 210, ?",
    "a": "(A)336 ",
    "b": "(B)349",
    "c": "(C)312",
    "d": "(D)337",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "11, 14, 19, 22, 27, 30, ?",
    "a": "(A)39",
    "b": "(B)34",
    "c": "(C)36",
    "d": "(D)35",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "6, 12, 21, ? , 48",
    "a": "(A)33",
    "b": "(B)39",
    "c": "(C)36",
    "d": "(D)31",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "18, 22, 30, ? ,78, 142",
    "a": "(A) 44",
    "b": "(B) 35",
    "c": "(C) 46",
    "d": "(D) 48",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "73205, 6655, 605, 55, ?",
    "a": "(A)9",
    "b": "(B)5",
    "c": "(C)13",
    "d": "(D)11",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "25, 100, ?, 1600, 6400",
    "a": "(A)400",
    "b": "(B)300",
    "c": "(C)360",
    "d": "(D)420",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "125, ?, 343, 512, 729, 1000",
    "a": "(A)216",
    "b": "(B)215",
    "c": "(C)256",
    "d": "(D)225",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1 , 9 , 125 , 343 , ? , 1331",
    "a": "(A)730",
    "b": "(B)729",
    "c": "(C)512",
    "d": "(D)772",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "121, 144, 169, ?, 225",
    "a": "(A)180",
    "b": "(B)172",
    "c": "(C)186",
    "d": "(D)196",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "?, 2116, 2209, 2304, 2401, 2500",
    "a": "(A)2124",
    "b": "(B)1972",
    "c": "(C)1521",
    "d": "(D)2025",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1, 4, 9, 16, 25, ? ",
    "a": "(A) 35 ",
    "b": "(B) 36 ",
    "c": "(C) 48 ",
    "d": "(D) 49",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "20, 19, 17, ?, 10, 5 ",
    "a": "(A) 12 ",
    "b": "(B) 13 ",
    "c": "(C) 14 ",
    "d": "(D) 15",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 3, 5, 7, 11, ?, 17",
    "a": "(A) 12 ",
    "b": "(B) 13 ",
    "c": "(C) 14 ",
    "d": "(D) 15",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "6, 11, 21, 36, 56, ? ",
    "a": "(A) 42 ",
    "b": "(B) 51 ",
    "c": "(C) 81 ",
    "d": "(D) 91",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1, 6, 13, 22, 33, ? ",
    "a": "(A) 44 ",
    "b": "(B) 45 ",
    "c": "(C) 46 ",
    "d": "(D) 47",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3, 9, 27, 81, ? ",
    "a": "(A) 324 ",
    "b": "(B) 243 ",
    "c": "(C) 210 ",
    "d": "(D) 162",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1, 9, 17, 33, 49, 73, ? ",
    "a": "(A) 97 ",
    "b": "(B) 98 ",
    "c": "(C) 99 ",
    "d": "(D) 100",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 5, 9, ?, 20, 27 ",
    "a": "(A) 14 ",
    "b": "(B) 16 ",
    "c": "(C) 18 ",
    "d": "(D) 24",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "5, 9, 17, 29, 45, ?",
    "a": "(A) 60 ",
    "b": "(B) 65 ",
    "c": "(C) 68 ",
    "d": "(D) 70",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3, 7, 15, 31, 63, ?",
    "a": "(A) 92 ",
    "b": "(B) 115 ",
    "c": "(C) 127 ",
    "d": "(D) 131",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1, 6, 15, ?, 45, 66, 91 ",
    "a": "(A) 25 ",
    "b": "(B) 26 ",
    "c": "(C) 27 ",
    "d": "(D) 28",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1, 2, 3, 5, 8, ? ",
    "a": "(A) 9 ",
    "b": "(B) 11 ",
    "c": "(C) 13 ",
    "d": "(D) 15",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "0.5, 1.5, 4.5, 13.5, ? ",
    "a": "(A) 45.5 ",
    "b": "(B) 39.5 ",
    "c": "(C) 30.5 ",
    "d": "(D) 40.5",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "121, 225, 361, (,) ",
    "a": "(A) 441 ",
    "b": "(B) 484 ",
    "c": "(C) 529 ",
    "d": "(D) 729",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "0, 2, 8, 14, ?, 34",
    "a": "(A) 24 ",
    "b": "(B) 22 ",
    "c": "(C) 20 ",
    "d": "(D) 18",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "19, 2, 38, 3, 114, 4, ? ",
    "a": "(A) 228 ",
    "b": "(B) 256 ",
    "c": "(C) 352 ",
    "d": "(D) 456",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1, 2, 3, 6, 9, 18, ?, 54",
    "a": "(A) 18 ",
    "b": "(B) 27 ",
    "c": "(C) 36 ",
    "d": "(D) 81",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "4, 5, 9, 18, 34, ?",
    "a": "(A) 43 ",
    "b": "(B) 49 ",
    "c": "(C) 50 ",
    "d": "(D) 59",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3, 6, 18, 72, ? ",
    "a": "(A) 144 ",
    "b": "(B) 216 ",
    "c": "(C) 288 ",
    "d": "(D) 360",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "66, 36, 18, ?",
    "a": "(A) 3 ",
    "b": "(B) 6 ",
    "c": "(C) 8 ",
    "d": "(D) 9",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "21, 25, 33, 49, 81, ?",
    "a": "(A) 145 ",
    "b": "(B) 129 ",
    "c": "(C) 113 ",
    "d": "(D) 97",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "12, 32, 72, 152, ?",
    "a": "(A) 312 ",
    "b": "(B) 325 ",
    "c": "(C) 515 ",
    "d": "(D) 613",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3, 6, 5, 20, 7, 42, 9, ?",
    "a": "(A) 54 ",
    "b": "(B) 60 ",
    "c": "(C) 66 ",
    "d": "(D) 72",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1, 3, 4, 8, 15, 27, ?",
    "a": "(A) 37 ",
    "b": "(B) 44 ",
    "c": "(C) 50 ",
    "d": "(D) 55",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 15, 41, 80, ?",
    "a": "(A) 111 ",
    "b": "(B)120 ",
    "c": "(C) 121 ",
    "d": "(D) 132",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8, 10, 14, 18, ?, 34, 50, 66",
    "a": "(A) 24 ",
    "b": "(B) 25 ",
    "c": "(C) 26 ",
    "d": "(D) 27",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1,2, 6,24, ?",
    "a": "(A) 60 ",
    "b": "(B) 95 ",
    "c": "(C) 120 ",
    "d": "(D) 150",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 3, 8, 63, ?",
    "a": "(A) 1038 ",
    "b": "(B) 1998 ",
    "c": "(C) 3008 ",
    "d": "(D) 3968",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "95, 115.5, 138, ?, 189",
    "a": "(A) 154.5 ",
    "b": "(B) 162.5 ",
    "c": "(C) 164.5 ",
    "d": "(D) 166.5",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "4, 10, ?, 82, 244, 730",
    "a": "(A) 24 ",
    "b": "(B) 28 ",
    "c": "(C) 77 ",
    "d": "(D) 218",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "4, 32, 128, ?",
    "a": "(A) 128 ",
    "b": "(B) 144 ",
    "c": "(C) 192 ",
    "d": "(D) 256",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 5, 9, 19, 37, ?",
    "a": "(A) 76 ",
    "b": "(B) 75 ",
    "c": "(C) 74 ",
    "d": "(D) 72",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "24, 60, 120, 210, ?",
    "a": "(A) 300 ",
    "b": "(B) 336 ",
    "c": "(C) 420 ",
    "d": "(D) 525",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "165, 195, 255, 285, 345, ?",
    "a": "(A) 375 ",
    "b": "(B) 420 ",
    "c": "(C) 435 ",
    "d": "(D) 390",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "5, 17, 37, 65, ?, 145",
    "a": "(A) 95 ",
    "b": "(B) 97 ",
    "c": "(C) 99 ",
    "d": "(D) 101",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "9, 11, 20, 31, ?, 82",
    "a": "(A) 41 ",
    "b": "(B) 51 ",
    "c": "(C) 60 ",
    "d": "(D) 71",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "5, 16, 49, 104, ?",
    "a": "(A) 115 ",
    "b": "(B) 148 ",
    "c": "(C) 170 ",
    "d": "(D) 181",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "34, 18, 10, 6, 4, ?",
    "a": "(A) 0 ",
    "b": "(B) 1 ",
    "c": "(C) 2 ",
    "d": "(D) 3",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "462, 420, 380, ?, 306",
    "a": "(A) 322 ",
    "b": "(B) 332 ",
    "c": "(C) 342 ",
    "d": "(D) 352",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3, 8, 22, 63, 185, ?",
    "a": "(A) 550 ",
    "b": "(B) 310 ",
    "c": "(C) 295 ",
    "d": "(D) 285 ",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1, 2, 5, 12, 27, 58, 121, ? ",
    "a": "(A) 246 ",
    "b": "(B) 247 ",
    "c": "(C) 248 ",
    "d": "(D) 249",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "0.5, 0.55, 0.65, 0.8, ?",
    "a": "(A) 0.9 ",
    "b": "(B) 0.82 ",
    "c": "(C) 1 ",
    "d": "(D) 0.95",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3, 8, 13, 24, 41, ? ",
    "a": "(A) 70 ",
    "b": "(B) 75 ",
    "c": "(C) 80 ",
    "d": "(D) 85",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "97, 86, 73, 58, 45, ?",
    "a": "(A) 34 ",
    "b": "(B) 54 ",
    "c": "(C) 55 ",
    "d": "(D) 56",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "17, 19, 23, 29, ?, 37 ",
    "a": "(A) 31 ",
    "b": "(B) 33 ",
    "c": "(C) 35 ",
    "d": "(D) 36",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "5, 6, 9, 15, ?, 40 ",
    "a": "(A) 21 ",
    "b": "(B) 25 ",
    "c": "(C) 27 ",
    "d": "(D) 33",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3, 12, 27, 48, 75, 108, ? ",
    "a": "(A) 147 ",
    "b": "(B) 162 ",
    "c": "(C) 183 ",
    "d": "(D) 192",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "134, 245, 356, 467, ? ",
    "a": "(A) 579 ",
    "b": "(B) 578 ",
    "c": "(C) 568 ",
    "d": "(D) 478",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "6, 13, 28, ? ",
    "a": "(A) 56 ",
    "b": "(B) 57 ",
    "c": "(C) 58 ",
    "d": "(D) 59",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "563, 647, 479, 815, ?",
    "a": "(A) 672 ",
    "b": "(B) 386 ",
    "c": "(C) 279 ",
    "d": "(D) 143",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "11, 12, 17, 18, 23, 24, ? ",
    "a": "(A) 12 ",
    "b": "(B) 29 ",
    "c": "(C) 30 ",
    "d": "(D) 35",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "225, 336, 447, ?, 669, 7710 ",
    "a": "(A) 114 ",
    "b": "(B)338 ",
    "c": "(C) 558 ",
    "d": "(D) 991",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "840, 168, 42, 14, 7, ? ",
    "a": "(A) 1 ",
    "b": "(B) 7 ",
    "c": "(C)9 ",
    "d": "(D) 12",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "5, 6, 7, 8, 10, 11, 14, ? ",
    "a": "(A) 15 ",
    "b": "(B) 16 ",
    "c": "(C) 17 ",
    "d": "(D) 18",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "0, 2, 3, 5, 8, 10, 15, 17, 24, 26, ?",
    "a": "(A) 35 ",
    "b": "(B) 32 ",
    "c": "(C) 30 ",
    "d": "(D) 28",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "0, 4, 6, 3, 7, 9, 6, ?, 12 ",
    "a": "(A) 8 ",
    "b": "(B) 10 ",
    "c": "(C) 11 ",
    "d": "(D) 14",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1, 1, 3, 9, 6, 36, 10, 100, ?, 225 ",
    "a": "(A) 15 ",
    "b": "(B) 16 ",
    "c": "(C) 20 ",
    "d": "(D) 22",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 1, 2, 4, 4, 5, 6, 7, 8, 8, 10, 11, ? ",
    "a": "(A) 9 ",
    "b": "(B) 10 ",
    "c": "(C) 11 ",
    "d": "(D) 12",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "4, 23, 60, 121, ?",
    "a": "(A) 212 ",
    "b": "(B) 221 ",
    "c": "(C) 241 ",
    "d": "(D) 242",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1, 4, 2, 8, 6, 24, 22, 88, ? ",
    "a": "(A) 86 ",
    "b": "(B) 90 ",
    "c": "(C) 154 ",
    "d": "(D) 352",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "13, 32, 24, 43, 35, ?, 46, 65, 57, 76 ",
    "a": "(A) 45 ",
    "b": "(B) 52 ",
    "c": "(C) 54 ",
    "d": "(D) 55",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3, 4, 7, 7, 13, 13, 21, 22, 31, 44, ?",
    "a": "(A) 42 ",
    "b": "(B) 43 ",
    "c": "(C) 51 ",
    "d": "(D) 52",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 6, 12, 20, 30, 42, 56, ?",
    "a": "(A) 60 ",
    "b": "(B) 64 ",
    "c": "(C) 70 ",
    "d": "(D) 72",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8, 9, 8, 7, 10, 9, 6, 11, 10, ?, 12",
    "a": "(A) 5 ",
    "b": "(B) 7 ",
    "c": "(C) 8 ",
    "d": "(D) 11",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "90, 180, 12, 50, 100, 200, ?, 3, 50, 4, 25, 2, 6, 30, 3",
    "a": "(A) 150 ",
    "b": "(B) 175 ",
    "c": "(C) 225 ",
    "d": "(D) 250",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "11, 10, ?, 100, 1001, 1000, 10001",
    "a": "(A) 101 ",
    "b": "(B) 110 ",
    "c": "(C) 111 ",
    "d": "(D) None of these",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "123456147, 12345614, 2345614, 234561, ?",
    "a": "(A) 3456 ",
    "b": "(B) 2345 ",
    "c": "(C) 23456 ",
    "d": "(D) 34561",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "4/9, 9/20, ?, 39/86",
    "a": "(A) 17/40 ",
    "b": "(B) 19/42 ",
    "c": "(C) 20/45 ",
    "d": "(D) 29/53",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2/√5, 3/5, 4/5√5, 5/25, ?",
    "a": "(A) 6/5√5 ",
    "b": "(B) 6/25√5 ",
    "c": "(C) 6/125 ",
    "d": "(D) 7/25",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "(2, 3), (3, 5), (5, 7), (7, 11), (11, 13), (? ?)",
    "a": "(A) (13, 15) ",
    "b": "(B) (15, 16) ",
    "c": "(C) (13, 17) ",
    "d": "(D) (13, 19)",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In the series 10, 17, 24, 31, 38, , which of the following will be a number of the series ?",
    "a": "(A) 48 ",
    "b": "(B) 346 ",
    "c": "(C) 574 ",
    "d": "(D) 1003",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Which of the following will not be a number of the series 1, 8, 27, 64, 125, , ?",
    "a": "(A) 256 ",
    "b": "(B) 512 ",
    "c": "(C) 729 ",
    "d": "(D) 1000 ",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In the series 3, 9, 15 what will be the 21st term ?",
    "a": "(A) 117 ",
    "b": "(B) 121 ",
    "c": "(C) 123 ",
    "d": "(D) 129",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In the series 2, 6, 18, 54...What will be the 8th term ?",
    "a": "(A) 4370 ",
    "b": "(B) 4374 ",
    "c": "(C) 7443 ",
    "d": "(D) 7434",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Which term of the series 5, 8, 11, 14, , is 320 ?",
    "a": "(A) 104th ",
    "b": "(B) 105th ",
    "c": "(C) 106th ",
    "d": "(D) 64th",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "Which term of the series 5, 10, ,20, 40, , is 1280 ?",
    "a": "(A) 10th ",
    "b": "(B) 9th ",
    "c": "(C) 8th ",
    "d": "(D) None of these",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  }
]
}
