[
  {
    "qtext": "The owner of Star TV is",
    "a": "(A)Rupert Murdoch",
    "b": "(B)Tata Group",
    "c": "(C)Richard Attenborough",
    "d": "(D)George Lucas",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "What is the purpose of SAARC?",
    "a": "(A)To promote the welfare of the people of South Asia",
    "b": "(B)To improve the environment of security in the region",
    "c": "(C)To accelerate economic growth and cultural development",
    "d": "(D)All of the above",
    "correct": "D",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "What is the literacy rate of Punjab?",
    "a": "(A)63.615 per cent",
    "b": "(B)61.03 per cent",
    "c": "(C)69.95 per cent",
    "d": "(D)65.07 per cent",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Dr. V. Kurien is famous in the field of ?",
    "a": "(A)Atomic Power",
    "b": "(B)poultry farms",
    "c": "(C)Dairy development",
    "d": "(D)Economic Reforms",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The rainfall in the peninsular interior averages about",
    "a": "(A)650 mm a year",
    "b": "(B)750 mm a year",
    "c": "(C)850 mm a year",
    "d": "(D)550 mm a year",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "When was the first Lionel trains manufactured?",
    "a": "(A)1920",
    "b": "(B)1890",
    "c": "(C)1901",
    "d": "(D)1944",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "There were widespread risings against the British in the 1820s. Which one of the following did not revolt in the 1820s?",
    "a": "(A)Santhals",
    "b": "(B)Ahoms",
    "c": "(C)Pagal Panthis",
    "d": "(D)Ramosi",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Profit made when an asset is sold more than the price at which it was bought is called",
    "a": "(A)capital",
    "b": "(B)capital-gain",
    "c": "(C)capitalism",
    "d": "(D)None of the above",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The refineries are Mathura, Digboi and Panipat are set up by",
    "a": "(A)Indian Oil Corporation Ltd.",
    "b": "(B)Hindustan Petroleum Corporation Ltd.",
    "c": "(C)Bharat Petroleum Corporation Ltd.",
    "d": "(D)Crude Distillation unit of Madras Refineries Ltd.",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The most important ore of aluminium is",
    "a": "(A)bauxite",
    "b": "(B)magnetite",
    "c": "(C)haematite",
    "d": "(D)monazite",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The method of concentrating the ore which makes use of the difference in density between ore and impurities is called",
    "a": "(A)liquation",
    "b": "(B)leaching",
    "c": "(C)levigation",
    "d": "(D)magnetic separation",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "To which of the following country Olympic Airways belong?",
    "a": "(A)France",
    "b": "(B)Greece",
    "c": "(C)Hong Kong",
    "d": "(D)Indonesia",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The United Nations Conference on Trade and Development (UNCTAD) is located at which of the following places?",
    "a": "(A)Geneva",
    "b": "(B)Rome",
    "c": "(C)Paris",
    "d": "(D)Vienna",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The group of minerals chemically containing hydrocarbons is",
    "a": "(A)silicate group",
    "b": "(B)organic group",
    "c": "(C)oxide group",
    "d": "(D)hydride group",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The soil found in areas of heavy rainfall and high humidity, where there is good growth of vegetation is",
    "a": "(A)peat and marshy soil",
    "b": "(B)saline and alkaline soil",
    "c": "(C)black soil",
    "d": "(D)alluvial soil",
    "correct": "A",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Karoline Mikkelsen was the first woman to",
    "a": "(A)reach North Pole",
    "b": "(B)reach South Pole",
    "c": "(C)climb Mt. Everest",
    "d": "(D)set foot on the moon",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "Point A is at a lower electrical potential than point B. An electron between them on the line joining them will",
    "a": "(A)move towards A",
    "b": "(B)move towards B",
    "c": "(C)move at right angles to the line joining A and B",
    "d": "(D)remain at rest",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The absorption of ink by blotting paper involves",
    "a": "(A)viscosity of ink",
    "b": "(B)capillary action phenomenon",
    "c": "(C)diffusion of ink through the blotting",
    "d": "(D)siphon action",
    "correct": "B",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "G-15 is an economic grouping of",
    "a": "(A)First World Nations",
    "b": "(B)Second World Nations",
    "c": "(C)Third World Nations",
    "d": "(D)Fourth World Nations",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  },
  {
    "qtext": "The vast resources of unutilised natural gas can be used in the production of",
    "a": "(A)graphite",
    "b": "(B)Synthetic petroleum",
    "c": "(C)fertilisers",
    "d": "(D)carbide",
    "correct": "C",
    "img": "",
    "topic": "",
    "section": "General Awarness"
  }
]
