[{
    "qtext": "2, 1, (1/2), (1/4)",
    "a": "(A)(1/3)",
    "b": "(B)(1/8)",
    "c": "(C)(2/8)",
    "d": "(D)(1/16)",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "7, 10, 8, 11, 9, 12",
    "a": "(A)7",
    "b": "(B)10",
    "c": "(C)12",
    "d": "(D)13",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "36, 34, 30, 28, 24",
    "a": "(A)20",
    "b": "(B)22",
    "c": "(C)23",
    "d": "(D)26",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "22, 21, 23, 22, 24, 23",
    "a": "(A)22",
    "b": "(B)24",
    "c": "(C)25",
    "d": "(D)26",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "53, 53, 40, 40, 27, 27",
    "a": "(A)12",
    "b": "(B)14",
    "c": "(C)27",
    "d": "(D)53",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "21, 9, 21, 11, 21, 13, 21",
    "a": "(A)14",
    "b": "(B)15",
    "c": "(C)21",
    "d": "(D)23",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "58, 52, 46, 40, 34",
    "a": "(A)26",
    "b": "(B)28",
    "c": "(C)30",
    "d": "(D)32",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "3, 4, 7, 8, 11, 12",
    "a": "(A)7",
    "b": "(B)10",
    "c": "(C)14",
    "d": "(D)15",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8, 22, 8, 28, 8",
    "a": "(A)9",
    "b": "(B)29",
    "c": "(C)32",
    "d": "(D)34",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "31, 29, 24, 22, 17",
    "a": "(A)15",
    "b": "(B)14",
    "c": "(C)13",
    "d": "(D)12",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1.5, 2.3, 3.1, 3.9",
    "a": "(A)4.2",
    "b": "(B)4.4",
    "c": "(C)4.7",
    "d": "(D)5.1",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "14, 28, 20, 40, 32, 64",
    "a": "(A)52",
    "b": "(B)56",
    "c": "(C)96",
    "d": "(D)128",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 4, 6, 8, 10",
    "a": "(A)11",
    "b": "(B)12",
    "c": "(C)13",
    "d": "(D)14",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "201, 202, 204, 207",
    "a": "(A)205",
    "b": "(B)208",
    "c": "(C)210",
    "d": "(D)211",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "544, 509, 474, 439",
    "a": "(A)404",
    "b": "(B)414",
    "c": "(C)420",
    "d": "(D)445",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "80, 10, 70, 15, 60",
    "a": "(A)20",
    "b": "(B)25",
    "c": "(C)30",
    "d": "(D)50",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "2, 6, 18, 54",
    "a": "(A)108",
    "b": "(B)148",
    "c": "(C)162",
    "d": "(D)216",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "5.2, 4.8, 4.4, 4",
    "a": "(A)3",
    "b": "(B)3.3",
    "c": "(C)3.5",
    "d": "(D)3.6",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8, 6, 9, 23, 87 ",
    "a": "(A)128",
    "b": "(B)226",
    "c": "(C)324",
    "d": "(D)429",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "F2, __, D8, C16, B32",
    "a": "(A)A16",
    "b": "(B)G4",
    "c": "(C)E4",
    "d": "(D)E3",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "664, 332, 340, 170, ____, 89",
    "a": "(A)85",
    "b": "(B)97",
    "c": "(C)109",
    "d": "(D)178",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "V, VIII, XI, XIV, __, XX",
    "a": "(A)IX",
    "b": "(B)XXIII",
    "c": "(C)XV",
    "d": "(D)XVII",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "70, 71, 76, __, 81, 86, 70, 91",
    "a": "(A)70",
    "b": "(B)71",
    "c": "(C)80",
    "d": "(D)96",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8, 43, 11, 41, __, 39, 17",
    "a": "(A)8",
    "b": "(B)14",
    "c": "(C)43",
    "d": "(D)44",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "VI, 10, V, 11, __, 12, III",
    "a": "(A)II",
    "b": "(B)IV",
    "c": "(C)IX",
    "d": "(D)14",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "(1/9), (1/3), 1, ____ , 9",
    "a": "(A)(2/3)",
    "b": "(B)3",
    "c": "(C)6",
    "d": "(D)27",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "83, 73, 93, 63, __, 93, 43",
    "a": "(A)33",
    "b": "(B)53",
    "c": "(C)73",
    "d": "(D)93",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "15, __, 27, 27, 39, 39",
    "a": "(A)51",
    "b": "(B)39",
    "c": "(C)23",
    "d": "(D)15",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "72, 76, 73, 77, 74, __, 75",
    "a": "(A)70",
    "b": "(B)71",
    "c": "(C)75",
    "d": "(D)78",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "J14, L16, __, P20, R22",
    "a": "(A)S24",
    "b": "(B)N18",
    "c": "(C)M18",
    "d": "(D)T24",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "4, 7, 25, 10, __, 20, 16, 19",
    "a": "(A)13",
    "b": "(B)15",
    "c": "(C)20",
    "d": "(D)28",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "XXIV, XX, __, XII, VIII",
    "a": "(A)XXII",
    "b": "(B)XIII",
    "c": "(C)XVI",
    "d": "(D)IV",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "0.15, 0.3, ____, 1.2, 2.4",
    "a": "(A)4.8",
    "b": "(B)0.006",
    "c": "(C)0.6",
    "d": "(D)0.9",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "U32, V29, __, X23, Y20",
    "a": "(A)W26",
    "b": "(B)W17",
    "c": "(C)Z17",
    "d": "(D)Z26",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n1, 9, 25, 49, ?, 121.",
    "a": "(A)100",
    "b": "(B)91",
    "c": "(C)64",
    "d": "(D)81",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n4, 7, 12, 19, 28, ?",
    "a": "(A)49",
    "b": "(B)36",
    "c": "(C)30",
    "d": "(D)39",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n6, 11, 21, 36, 56, ?",
    "a": "(A)91",
    "b": "(B)51",
    "c": "(C)81",
    "d": "(D)42",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n10, 100, 200, 310, ?",
    "a": "(A)430",
    "b": "(B)420",
    "c": "(C)410",
    "d": "(D)400",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n8, 28, 116, 584, ?",
    "a": "(A)1752",
    "b": "(B)3504",
    "c": "(C)3508",
    "d": "(D)3502",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n3, 7, 23, 95, ?",
    "a": "(A)62",
    "b": "(B)128",
    "c": "(C)479",
    "d": "(D)575",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n7, 26, 63, 124, 215, 342, ?",
    "a": "(A)391",
    "b": "(B)511",
    "c": "(C)481",
    "d": "(D)421",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n165, 195, 255, 285, 345, ?",
    "a": "(A)390",
    "b": "(B)420",
    "c": "(C)435",
    "d": "(D)375",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n34, 45, 56, 67,?",
    "a": "(A)78",
    "b": "(B)73",
    "c": "(C)82",
    "d": "(D)84",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n3, 2, 7, 6, 11, ?",
    "a": "(A)8",
    "b": "(B)10",
    "c": "(C)4",
    "d": "(D)2",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In the following number series a wrong number is given. Find out the wrong number.\n150, 450, 750, 1060,1350,1650,1950",
    "a": "(A)1060",
    "b": "(B)1950",
    "c": "(C)450",
    "d": "(D)1350",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n5690, 5121, 4552, 3983, 3414, 2845, ?",
    "a": "(A)750",
    "b": "(B)2276",
    "c": "(C)2516",
    "d": "(D)2356",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n6, 13, 28, 59, ?, 249.",
    "a": "(A)2456",
    "b": "(B)124",
    "c": "(C)122",
    "d": "(D)120",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n4, 8, 10, 14, 16, 20, ?",
    "a": "(A)118",
    "b": "(B)22",
    "c": "(C)21",
    "d": "(D)20",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n9, 17, 33, 65, ?",
    "a": "(A)16",
    "b": "(B)117",
    "c": "(C)119",
    "d": "(D)129",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n2, 3, 6, 15, ?, 123",
    "a": "(A)47",
    "b": "(B)42",
    "c": "(C)45",
    "d": "(D)50",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "In the following number series a wrong number is given. Find out the wrong number.\n1, 3, 10, 21, 64, 129, 356, 777",
    "a": "(A)129",
    "b": "(B)21",
    "c": "(C)10",
    "d": "(D)356",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n9, 27, 31, 155, 161, 1127, ?",
    "a": "(A)316",
    "b": "(B)1135",
    "c": "(C)1288",
    "d": "(D)2254",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n2, 7, 27, 107, 427, ?",
    "a": "(A)1262",
    "b": "(B)1707",
    "c": "(C)4027",
    "d": "(D)4207",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\nSunday, Monday, Wednesday, Saturday, Wednesday, Monday, ?,?",
    "a": "(A)Sunday, Sunday",
    "b": "(B)Sunday, Monday",
    "c": "(C)Sunday, Wednesday",
    "d": "(D)Sunday, Saturday",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n2816, ? , 176, 44, 11.",
    "a": "(A)704",
    "b": "(B)1408",
    "c": "(C)352",
    "d": "(D)2640",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n113, 225, 449, ? , 1793",
    "a": "(A)897",
    "b": "(B)789",
    "c": "(C)987",
    "d": "(D)978",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\nPRODUCTIVITY, RODUCTIVIT, ODUCTIVI, ?",
    "a": "(A)DUCTIV",
    "b": "(B)DUCTLY",
    "c": "(C)UCTIV",
    "d": "(D)DUCTI",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "What will come at the place of question mark ?\n6, 24, 60,120, 210, ?",
    "a": "(A)336",
    "b": "(B)366",
    "c": "(C)330",
    "d": "(D)660",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "6, 11, 31, 121, 601, ?",
    "a": "(A)3600",
    "b": "(B)3621",
    "c": "(C)3601",
    "d": "(D)3611",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "7, 11, 19, 35, 67, ?",
    "a": "(A)99",
    "b": "(B)131",
    "c": "(C)137",
    "d": "(D)124",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "8, 22, 64, 190, 568, ?",
    "a": "(A)1702",
    "b": "(B)7767",
    "c": "(C)6992",
    "d": "(D)6913",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "5760,2880,960, 240, 48, ?",
    "a": "(A)6",
    "b": "(B)8",
    "c": "(C)12",
    "d": "(D)16",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "0, 6, 24, 60, 120, 210, ?",
    "a": "(A)336 ",
    "b": "(B)349",
    "c": "(C)312",
    "d": "(D)337",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "11, 14, 19, 22, 27, 30, ?",
    "a": "(A)39",
    "b": "(B)34",
    "c": "(C)36",
    "d": "(D)35",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "6, 12, 21, ? , 48",
    "a": "(A)33",
    "b": "(B)39",
    "c": "(C)36",
    "d": "(D)31",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "18, 22, 30, ? ,78, 142",
    "a": "(A) 44",
    "b": "(B) 35",
    "c": "(C) 46",
    "d": "(D) 48",
    "correct": "C",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "73205, 6655, 605, 55, ?",
    "a": "(A)9",
    "b": "(B)5",
    "c": "(C)13",
    "d": "(D)11",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "25, 100, ?, 1600, 6400",
    "a": "(A)400",
    "b": "(B)300",
    "c": "(C)360",
    "d": "(D)420",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "125, ?, 343, 512, 729, 1000",
    "a": "(A)216",
    "b": "(B)215",
    "c": "(C)256",
    "d": "(D)225",
    "correct": "A",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "1 , 9 , 125 , 343 , ? , 1331",
    "a": "(A)730",
    "b": "(B)729",
    "c": "(C)512",
    "d": "(D)772",
    "correct": "B",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "121, 144, 169, ?, 225",
    "a": "(A)180",
    "b": "(B)172",
    "c": "(C)186",
    "d": "(D)196",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  },
  {
    "qtext": "?, 2116, 2209, 2304, 2401, 2500",
    "a": "(A)2124",
    "b": "(B)1972",
    "c": "(C)1521",
    "d": "(D)2025",
    "correct": "D",
    "img": "",
    "topic": "Number Series",
    "section": "(General Intelligence & Reasoning)"
  }]
