{
  "data":[
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)We discussed about the problem so thoroughly",
        "b": "(B)on the eve of the examination",
        "c": "(C)that I found it very easy to work it out.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)An Indian ship",
        "b": "(B)laden with merchandise",
        "c": "(C)got drowned in the Pacific Ocean.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I could not put up in a hotel",
        "b": "(B)because the boarding and lodging charges",
        "c": "(C)were exorbitant.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The Indian radio",
        "b": "(B)which was previously controlled by the British rulers",
        "c": "(C)is free now from the narrow vested interests.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)If I had known",
        "b": "(B)this yesterday",
        "c": "(C)I will have helped him.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)A lot of travel delay is caused",
        "b": "(B)due to the inefficiency and lack of good management",
        "c": "(C)on behalf of the railways.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)One of the members",
        "b": "(B)expressed doubt if",
        "c": "(C)the Minister was an atheist.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I have got",
        "b": "(B)my M.Sc. degree",
        "c": "(C)in 1988.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Having received your letter",
        "b": "(B)this morning, we are writing",
        "c": "(C)to thank you for the same.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)If you lend him a book",
        "b": "(B)he will lend it to some one else",
        "c": "(C)and never you will get it back.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)According to the Bible",
        "b": "(B)it is meek and humble",
        "c": "(C)who shall inherit the earth.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Do the roses in your garden smell",
        "b": "(B)more sweetly",
        "c": "(C)than those in ours?",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Block of Residential flats",
        "b": "(B)are coming up",
        "c": "(C)near our house.",
        "d": "(D)No error",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)You can get",
        "b": "(B)all the information that you want",
        "c": "(C)in this book.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The students were",
        "b": "(B)awaiting for",
        "c": "(C)the arrival of the chief guest.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Sixty miles",
        "b": "(B)are",
        "c": "(C)a good distance.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)They have been",
        "b": "(B)very close friends",
        "c": "(C)until they quarrelled.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)When the dentist came in",
        "b": "(B)my tooth was stopped aching",
        "c": "(C)out of fear that I might lose my tooth.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)It is the duty of every citizen to do his utmost",
        "b": "(B)to defend the hardly-won",
        "c": "(C)freedom of the country.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)No sooner did I open the door",
        "b": "(B)when the rain, heavy and stormy, rushed in",
        "c": "(C)making us shiver from head to foot",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)If a man diligently seeks to come into the contact",
        "b": "(B)with the best that has been thought and said in this world",
        "c": "(C)he will become simple and unselfish.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)You must",
        "b": "(B)remember me",
        "c": "(C)to post this letter.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I shall certainly",
        "b": "(B)write you",
        "c": "(C)when I shall reach NewDelhi.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)On the busy Ring Road",
        "b": "(B)we witnessed a collusion",
        "c": "(C)between a truck and an auto.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Mr.Praful Patel",
        "b": "(B)is not attending his office",
        "c": "(C)for the last one month.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He couldn't but help",
        "b": "(B)shedding tears at the plight of the villagers",
        "c": "(C)rendered homeless by a devastating cyclone.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He will certainly help you",
        "b": "(B)if you will ask him",
        "c": "(C)in a pleasant manner.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The brand propositon now therefore had to be that Keokarpin Antiseptic Cream is more effective",
        "b": "(B)because it penetrates deepdown (beinglight and non-sticky) and works from within",
        "c": "(C)(because of its ayurvedic ingredients) to keep skin blemish, free and helps cope with cuts nicks, burns and nappy rash.",
        "d": "(D)No error",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Will you please buy",
        "b": "(B)some jaggery for me",
        "c": "(C)if you go to the market?",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Most of the members at the meeting felt",
        "b": "(B)that the group appointed for investigating the case",
        "c": "(C)were not competent to do the job efficiently.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)In these days of inflation",
        "b": "(B)a ten rupee's note will not buy you",
        "c": "(C)even an ordinary meal.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He persisted",
        "b": "(B)to do it",
        "c": "(C)in spite of my advice",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The long-awaited moment at last came,",
        "b": "(B)and we set out for the station",
        "c": "(C)as merry a band of children as I have ever seen before or since.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Our conception of",
        "b": "(B)what should a science of mental life be",
        "c": "(C)has changed considerably since James' time.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He is not coming tomorrow",
        "b": "(B)as he is having a pain in the chest",
        "c": "(C)and has to see a doctor.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Many times the news has been published",
        "b": "(B)in the papers that the end of the world will be certain",
        "c": "(C)if a nuclear war breaks out.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The reason Ram",
        "b": "(B)is absent from his duty",
        "c": "(C)is because he is unwell.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Azharuddin is one of the finest batsmen",
        "b": "(B)that India have produced",
        "c": "(C)over the decades.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The thief broke in the",
        "b": "(B)house at the",
        "c": "(C)dead of night",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)May I",
        "b": "(B)know who you want",
        "c": "(C)to see please",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He said that he",
        "b": "(B)will mind if",
        "c": "(C)I refused his offer.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Arun's parents died when he was young and",
        "b": "(B)he looked after his aunt",
        "c": "(C)who had no children.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Though child marriage",
        "b": "(B)has been banned.",
        "c": "(C)the custom still prevailed among some groups in India.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)My papa is",
        "b": "(B)in bad mood",
        "c": "(C)today",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The warden",
        "b": "(B)forbade the student",
        "c": "(C)from leaving the hostel.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)In spite of several reminders,",
        "b": "(B)he did not so far send",
        "c": "(C)any reply to me, letters.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)As much as I admire him for his sterling qualities.",
        "b": "(B)I cannot excuse him for",
        "c": "(C)being unfair to his friends.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Please try to understand",
        "b": "(B)that the dispute on this issue is between my brother and myself,",
        "c": "(C)and concerns nobody else.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)All the furnitures have been",
        "b": "(B)sent to the new house",
        "c": "(C)located in a village.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)It does not matter how you do it;",
        "b": "(B)what I want is that",
        "c": "(C)you should finish the work within a month.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Though senior in age,",
        "b": "(B)his father is junior than",
        "c": "(C)my father in service.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)While walking slowly in the park",
        "b": "(B)on a quiet summer afternoon",
        "c": "(C)a mad dog suddenly attacked him from behind",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Everyone visiting the house asked the young girl",
        "b": "(B)how could she kill the wolf",
        "c": "(C)single handed and without a weapon.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Many health-conscious people",
        "b": "(B)prefer margarine",
        "c": "(C)than butter.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The retiring principal asked his old pupils",
        "b": "(B)to take the interest in the school",
        "c": "(C)after he has retired.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)At present juncture",
        "b": "(B)however, the supercomputer",
        "c": "(C)would be a costly toy.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The crews were on board,",
        "b": "(B)and they soon busied themselves",
        "c": "(C)in preparing to meet the storm.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Troy was taken by Greeks",
        "b": "(B)this formed the basis of a story",
        "c": "(C)which has become famous.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I am much pleased",
        "b": "(B)to know that",
        "c": "(C)you have topped the list.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He has not been attending",
        "b": "(B)English classes",
        "c": "(C)since one month",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)It is time",
        "b": "(B)we should accept all our people as equals",
        "c": "(C)and as partners in the task of building a strong and united nation.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Twice twelve",
        "b": "(B)makes",
        "c": "(C)twenty-four",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Regretfully, profits earned by your company",
        "b": "(B)fell by 20 per cent last year",
        "c": "(C)despite higher sales.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)In a report issued by Indian Statistical Institute,",
        "b": "(B)the Iron and Steel Industry is investing more than any other",
        "c": "(C)Indian industry in fighting pollution.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He is going everyday",
        "b": "(B)for a morning walk",
        "c": "(C)with his friends and neighbours",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)My father goes",
        "b": "(B)to the office",
        "c": "(C)five day week.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)If she will be promoted",
        "b": "(B)she will get",
        "c": "(C)a higher salary.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)If I were him,",
        "b": "(B)I would have taught",
        "c": "(C)those cheats a lesson.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Looking back, I find that among the many impressions ofthe people of India,",
        "b": "(B)absorbed while I lived among them,",
        "c": "(C)are their reverence for great men and women.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)If you work hard,",
        "b": "(B)you will get good grades",
        "c": "(C)in examinations.",
        "d": "(D)No error",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He managed to make sense of the book",
        "b": "(B)even though it was the first time",
        "c": "(C)he read anything on the subject.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)She reluctantly said that",
        "b": "(B)if nobody else was doing it",
        "c": "(C)she will do it.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I fail to understand",
        "b": "(B)why he replied in negative",
        "c": "(C)when the proposal was in his favour.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I have",
        "b": "(B)an appointment",
        "c": "(C)on the 9th September on five o'clock",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)They",
        "b": "(B)enjoyed thoroughly",
        "c": "(C)at the party.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The method suggested in the lecture",
        "b": "(B)enables a student to learn more quickly",
        "c": "(C)and to have remembered for a longer period of time.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)My friend asked me",
        "b": "(B)if I can lend him my Parker pen",
        "c": "(C)for a few days.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The test will not need",
        "b": "(B)more than one and half hour",
        "c": "(C)to finish.",
        "d": "(D)No error",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The school is",
        "b": "(B)within hundred yards",
        "c": "(C)from the church.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)His father died of cholera",
        "b": "(B)but his mother also,",
        "c": "(C)though very weak, is out of danger.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The police broke upon the robbers",
        "b": "(B)when they were in the lonely place",
        "c": "(C)to divide their booty.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Since it was his first election campaign, the candidate was confused;",
        "b": "(B)none could clearly understand",
        "c": "(C)either the principles he stood for or the benefits he promised.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Jayesh is getting",
        "b": "(B)fatter because he",
        "c": "(C)does not take exercise at all",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He loved",
        "b": "(B)none but",
        "c": "(C)his neighbour's daughter.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The criminal was",
        "b": "(B)caught, convicted the hung",
        "c": "(C)in a short period of time.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I am thinking of",
        "b": "(B)to go to Agra",
        "c": "(C)for my cousin's marriage.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)In management, as you rise higher,",
        "b": "(B)the problems you face becomemore and more unstructured and you can't just fall back on",
        "c": "(C)the tools you had been",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Neeraj said",
        "b": "(B)that he would rather fail than copying",
        "c": "(C)in the examination",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I had hoped to have met him yesterday",
        "b": "(B)to discuss the matter with him",
        "c": "(C)but he was not in his house, and so I could not meet him.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)You will come",
        "b": "(B)to my party tomorrow,",
        "c": "(C)isn't it?",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I wonder",
        "b": "(B)how am I",
        "c": "(C)to do it",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He is not to blame",
        "b": "(B)for what has happened",
        "c": "(C)for he is in no way connected with it.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Had you not",
        "b": "(B)reached in time",
        "c": "(C)he would have lost allour belongings.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The man told to her",
        "b": "(B)that he had not brought his dog",
        "c": "(C)out for a walk as he was afraid that it would rain.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)If I am you",
        "b": "(B)I would have seen to it",
        "c": "(C)that I won the prize.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)It is unfortunate that",
        "b": "(B)many youngsters get",
        "c": "(C)addicted to gamble.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Kamala's fountain-pen",
        "b": "(B)is as expensive",
        "c": "(C)as Shyama.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)When we consider all the factors, which are many,",
        "b": "(B)the number of school dropouts",
        "c": "(C)are quite disturbing.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)She has never",
        "b": "(B)approve of him",
        "c": "(C)working as a clerk.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)At the station,",
        "b": "(B)I'll hire a coolie",
        "c": "(C)to carry my baggages",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The number of marks carried by each question",
        "b": "(B)are indicated",
        "c": "(C)at the end of the question",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)There is no question",
        "b": "(B)of my failing",
        "c": "(C)in the examination.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)She is",
        "b": "(B)no longer popular as she has",
        "c": "(C)a friends",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)It is necessary",
        "b": "(B)that everybody",
        "c": "(C)must have a house.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Students should not take part",
        "b": "(B)in party politics and political demonstrations",
        "c": "(C)as they interfere in serious study",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)To facilitate exports and improve sales in the domestic market",
        "b": "(B)some of the improvised fabrics and garments fabricated out from them",
        "c": "(C)are displayed in the main pavilion.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Both of you two",
        "b": "(B)can come with me",
        "c": "(C)to the play tonight",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)No sooner did the sun rise",
        "b": "(B)when we took a hasty breakfast",
        "c": "(C)and resumed the journey.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The charges in this hospital",
        "b": "(B)are less than",
        "c": "(C)the hospital near my house.",
        "d": "(D)No error",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The brakes and steering failed",
        "b": "(B)and the bus ran down the hill",
        "c": "(C)without anyone being able control it.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The tall three girls",
        "b": "(B)had left",
        "c": "(C)the day before.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)When he was asked what is wrong with him.",
        "b": "(B)he said that he was not well.",
        "c": "(C)and asked for leave of absence for one day.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Wherever they go",
        "b": "(B)Indians easily adapt to",
        "c": "(C)local circumstances.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Remember that you are part of",
        "b": "(B)the team and your success depends on the support",
        "c": "(C)you are able to give and get from your other team members.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)It is an established fact that the transcendental American poets and philosophers.",
        "b": "(B)who lived in the latter half of the nineteenth century.",
        "c": "(C)were more influenced by Indian philosophy, in particular by Upanishadic Philosophy.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)That house",
        "b": "(B)is costing me",
        "c": "(C)ten thousand rupees",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Firstly you should",
        "b": "(B)think over the meaning of the words",
        "c": "(C)and then use them.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)It is true",
        "b": "(B)that God helps those",
        "c": "(C)who helps themselves.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Happily, zoos were",
        "b": "(B)unwilling to cooperate",
        "c": "(C)in a scheme that was potentially harmful to animal welfare",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Neither he",
        "b": "(B)nor his father is interested",
        "c": "(C)in joining the party.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)With little patience",
        "b": "(B)you will be able to",
        "c": "(C)cross this hurdle",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)She was told",
        "b": "(B)to give the award to whosoever",
        "c": "(C)she thought has done the most for the downtrodden.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)At the end of the year",
        "b": "(B)every student who had done adequate work",
        "c": "(C)was automatically promoted.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The reason why",
        "b": "(B)he was rejected",
        "c": "(C)was because he was too young.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Since we are friends",
        "b": "(B)there should be no secret",
        "c": "(C)between you and I.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Since the attachment of airconditioned sleeping cars to all important trains,",
        "b": "(B)travelling became very pleasant,",
        "c": "(C)especially during the summer season.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)If I will have the time",
        "b": "(B)I shall try and make it",
        "c": "(C)to the zoo this afternoon.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)We are four brothers and sisters living in this house",
        "b": "(B)but neither of us is",
        "c": "(C)satisfied with it.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)A leading textile manufacturer, one of the fastest growing in the industry.",
        "b": "(B)is looking for a marketing manager",
        "c": "(C)to look up the marketing network of the company",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Not one of the hundreds",
        "b": "(B)of striking workers.",
        "c": "(C)were allowed to go near the factory.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The single biggest gainer in this process",
        "b": "(B)was ITC's Gold Flake Kings sales are estimated",
        "c": "(C)to have moved up from 50 million to 200 million sticks per month during 1987 and last year.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)They left",
        "b": "(B)their luggages",
        "c": "(C)at the railway station.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Salim and Antony are such good friends",
        "b": "(B)that one won't go to the pictures.",
        "c": "(C)without his coming too.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)She is",
        "b": "(B)five years",
        "c": "(C)senior than me.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The President had hardly spoken",
        "b": "(B)a few words",
        "c": "(C)when the microphone stopped functioning.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Locke's treatises on government toleration and education",
        "b": "(B)show a mind fully awake in",
        "c": "(C)the possibilities of social reconstruction.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)You will get",
        "b": "(B)all the information",
        "c": "(C)if you read this booklet carefully.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)None of the students attending your class",
        "b": "(B)answered your questions",
        "c": "(C)did they?",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)An animal",
        "b": "(B)can be just as unhappy in a vast area",
        "c": "(C)or in a small one",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He is working in",
        "b": "(B)a bank in New Delhi",
        "c": "(C)for the past several months.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The scientist must follow",
        "b": "(B)his hunches and his data",
        "c": "(C)wherever it may lead.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Each one of the boys",
        "b": "(B)have paid",
        "c": "(C)the tuition-fee.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)A large scale exchange of nuclear weapons",
        "b": "(B)will produce unprecedented amounts of radiation",
        "c": "(C)that can penetrate into the biological tissue.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Had I",
        "b": "(B)known it earlier",
        "c": "(C)I would contact you.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He asked me",
        "b": "(B)why did I call",
        "c": "(C)him a rogue.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Were you",
        "b": "(B)given a choice",
        "c": "(C)or you had to do it?",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The person which was",
        "b": "(B)recommended for the position",
        "c": "(C)did not fulfil the prescribed qualifications.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)What does Professor Dhavan",
        "b": "(B)spend so many hours",
        "c": "(C)in the laboratory?",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The presumption that the average investor does not understand",
        "b": "(B)or take interest in the affairs of the company",
        "c": "(C)is not correct.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Shanghai is",
        "b": "(B)bigger than any city",
        "c": "(C)of the world",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Sheela has scored a first class",
        "b": "(B)in her final exams,",
        "c": "(C)isn't it?",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)At the moment the house",
        "b": "(B)was burgled the family",
        "c": "(C)attended a night party in the neighbourhood.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Scarcely had",
        "b": "(B)I arrived than",
        "c": "(C)the train left.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Though he stoutly persisted in denying his involvement in the case,",
        "b": "(B)the facts made it very clear",
        "c": "(C)that he had hand in the cruel murder of his wife.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)One of my favourite actor",
        "b": "(B)is acting",
        "c": "(C)in this play also.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Emphasis on equality of life ensures",
        "b": "(B)for the health and happiness",
        "c": "(C)of every individual.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)There was very heavy rain last night,",
        "b": "(B)and the rivers have overflown their banks",
        "c": "(C)causing severe hardship to the people living by them.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Every motorist knows",
        "b": "(B)road signs---whether symbols or colour codes--- have an immediacy",
        "c": "(C)that neither the spoken nor the written word can match.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Supposing if",
        "b": "(B)there is no bus.",
        "c": "(C)how will you get there?",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Because of the emergency help",
        "b": "(B)that the patient received",
        "c": "(C)he would have died",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He was in such hurry",
        "b": "(B)that he didn't",
        "c": "(C)wait for me",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Will you be",
        "b": "(B)at Board meeting",
        "c": "(C)on next Wednesday?",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Do you know",
        "b": "(B)to play",
        "c": "(C)the guitar?",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Few scientists changed",
        "b": "(B)people's ideas as much as",
        "c": "(C)Darwin with his Theory of Evolution.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The course provide",
        "b": "(B)not only theoretical inputs",
        "c": "(C)but also practical training",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)After the humiliating exposure",
        "b": "(B)he hanged his head",
        "c": "(C)in shame.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The eminent speaker's speech",
        "b": "(B)was broadcasted over",
        "c": "(C)all the major radio-stations.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The meeting adjourned abruptly",
        "b": "(B)by the Chairman after",
        "c": "(C)about three hours of deliberation.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The company has put up an advertisement",
        "b": "(B)in newspapers",
        "c": "(C)all over the country.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Will you lend me",
        "b": "(B)little money",
        "c": "(C)to tide over this crisis.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He gave them no money",
        "b": "(B)nor did help them",
        "c": "(C)in any way.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The Sharmas",
        "b": "(B)are living in this colony",
        "c": "(C)for the last eight years.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)My wife has got",
        "b": "(B)a new job",
        "c": "(C)a month ago.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The ability to plan,",
        "b": "(B)organise and coordinate work is all fundamental",
        "c": "(C)to working within deadline.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)A group of friends",
        "b": "(B)want to visit",
        "c": "(C)the new plant as early as possible.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)After leaving his office",
        "b": "(B)he went directly",
        "c": "(C)to a restaurant.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He was in a hurry",
        "b": "(B)because he had an appointment",
        "c": "(C)with the company's director.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)A body of volunteers",
        "b": "(B)have been organised",
        "c": "(C)to spread the message of the saint.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)When I get a cold",
        "b": "(B)it takes me weeks",
        "c": "(C)to shake it off.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Another reason for pharmaceutical companies beefing up their",
        "b": "(B)OTC (Over the Country) divisions is that prescription drugs with proven safety records which have been reached",
        "c": "(C)the end of the their patent protection periodare",
        "d": "(D)allowed to be sold without a prescription. No error",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)There is still",
        "b": "(B)little tea",
        "c": "(C)left in the cup.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He says that",
        "b": "(B)his car does",
        "c": "(C)eight kilometers in a litre",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)After opening the door",
        "b": "(B)we entered into the room",
        "c": "(C)next to the kitchen",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Can I lend",
        "b": "(B)your pencil",
        "c": "(C)for a minute, please?",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Last month we celebrated",
        "b": "(B)the wedding of our sister for whom",
        "c": "(C)we have been looking for a suitable alliance for three years.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)In an English paper",
        "b": "(B)examiners should give as much weightage to language",
        "c": "(C)as they give to contents.",
        "d": "(D)No error",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I am hearing",
        "b": "(B)a lot about",
        "c": "(C)the problem of AIDS these days.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Unless you stop to make noise at once",
        "b": "(B)I will have no option but to",
        "c": "(C)bring the matter to the attention of the police.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He is generally",
        "b": "(B)more hungry",
        "c": "(C)than she is .",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Since India has gained Independence",
        "b": "(B)49 years ago.",
        "c": "(C)much progress has been made in almost every field.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He ensured his bank manager",
        "b": "(B)that he would soon",
        "c": "(C)repay the loan.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)A free press is not a privilege",
        "b": "(B)but the organic necessity",
        "c": "(C)in a free society.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He explained the matter",
        "b": "(B)at great length",
        "c": "(C)but I was not the wiser",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He will end up his work",
        "b": "(B)in the city",
        "c": "(C)by the end of the year.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Even though the shirt is rather expensive",
        "b": "(B)but I wish to",
        "c": "(C)purchase it with my own money.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He enquired me",
        "b": "(B)why I had not seen him the previous day",
        "c": "(C)as I had promised to do.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I was there",
        "b": "(B)many a time",
        "c": "(C)in the past.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)All the four sons",
        "b": "(B)of the old man",
        "c": "(C)quarrelled between themselves.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He wanted to work all night",
        "b": "(B)but we saw that he was completely worn out",
        "c": "(C)and so we persuaded him to stop.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Mr.Smith was accused for murder",
        "b": "(B)but the court found him not guilty",
        "c": "(C)and acquitted him.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)She sang",
        "b": "(B)very well",
        "c": "(C)isn't it?",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I am sure that all my monthly expenses",
        "b": "(B)would exceed the income",
        "c": "(C)If I do not economic",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Whenever you go to a temple",
        "b": "(B)you must put off",
        "c": "(C)your shoes at the entrance.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Having read a number of stories",
        "b": "(B)about space travel",
        "c": "(C)his dream now is about to visit the moon",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The party chief made it a point to state that",
        "b": "(B)the Prime Minister and the Union Home Minister should also come.",
        "c": "(C)and they see what his party men had seen.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)It is easy to see that",
        "b": "(B)a lawyer's demeanour in court",
        "c": "(C)may be prejudicial against the interests of his client.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He is wiring",
        "b": "(B)for the",
        "c": "(C)last four hours",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)She walked in",
        "b": "(B)the room where the murder",
        "c": "(C)had taken place.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Were he",
        "b": "(B)to see you,",
        "c": "(C)he would have been surprised.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I could not convince them",
        "b": "(B)because they persisted to suggest",
        "c": "(C)that I was lying.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)If you listen with",
        "b": "(B)the question carefully",
        "c": "(C)you will be able to answer them easily",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)It is difficult",
        "b": "(B)for anyone",
        "c": "(C)to past time thus.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)The customer handed over",
        "b": "(B)a hundred-rupees note",
        "c": "(C)to the shopkeeper.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)Myself and Gopal",
        "b": "(B)will take care of",
        "c": "(C)the function on sunday.",
        "d": "(D)No error.",
        "correct": "A",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)It is the newspaper",
        "b": "(B)that exposes us to the widest range",
        "c": "(C)of human experiences and behaviour.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)A small baby breathes about",
        "b": "(B)45 times per minute while",
        "c": "(C)a child of about six years breathes about 25 times per minute.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)I have read",
        "b": "(B)too many books",
        "c": "(C)by R . K . Narayan.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He was sure",
        "b": "(B)that he should",
        "c": "(C)win the Prize.",
        "d": "(D)No error.",
        "correct": "B",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He is",
        "b": "(B)too intelligent",
        "c": "(C)to make a mistake.",
        "d": "(D)No error.",
        "correct": "D",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    },
    {
        "qtext": "Find out whether there is any grammatical error in part of the sentence, if ANY.",
        "a": "(A)He fell from a running train",
        "b": "(B)and would have died",
        "c": "(C)if the villagers did not get him admitted in the nearby hospital immediately.",
        "d": "(D)No error.",
        "correct": "C",
        "img": "",
        "topic": "Spotting Errors",
        "section": "(English)"
    }
]
}
